<?php

namespace OpenCompany\Integrations\IncidentIo;

use Illuminate\Support\Facades\Http;
use OpenCompany\IntegrationCore\Contracts\ConfigurableIntegration;
use OpenCompany\IntegrationCore\Contracts\CredentialResolver;
use OpenCompany\IntegrationCore\Contracts\HasIntegrationCapabilities;
use OpenCompany\IntegrationCore\Contracts\Tool;
use OpenCompany\IntegrationCore\Contracts\ToolProvider;

/**
 * Tool catalog and configuration metadata for incident.io.
 *
 * Exposes the official incident.io OpenAPI operation set as endpoint-specific
 * agent tools and resolves account-specific API keys in multi-account hosts.
 */
class IncidentIoToolProvider implements ToolProvider, ConfigurableIntegration, HasIntegrationCapabilities
{
    /** @return array<string, mixed> */ public function integrationCapabilities(): array { return ['auth'=>['strategy'=>'api_token','legacy_auth_type'=>'api_token','credential_mode'=>'secret','setup_flows'=>['manual_secret'],'requires_browser_for_setup'=>false,'refreshable'=>false,'token_keys'=>[],'notes'=>['Send an incident.io API key using the Bearer authorization scheme.']],'host_availability'=>['web'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret'],'cli'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret','runtime_mode'=>'normal']],'runtime_requirements'=>[],'compatibility'=>['web_setup_supported'=>true,'web_runtime_supported'=>true,'cli_setup_supported'=>true,'cli_runtime_supported'=>true]]; }
    public function appName(): string { return 'incident-io'; } public function appMeta(): array { return ['label'=>'incident.io','description'=>'Incidents, actions, follow-ups, escalations, alerts, catalog, schedules, statuses, webhooks, and workflows','icon'=>'ph:warning-circle','logo'=>'ph:warning-circle']; }
    public function integrationMeta(): array { return ['name'=>'incident.io','description'=>'Manage incident.io incidents, actions, follow-ups, severities, custom fields, escalations, alerts, catalog resources, schedules, statuses, webhooks, workflows, and API keys.','icon'=>'ph:warning-circle','logo'=>'ph:warning-circle','category'=>'productivity','badge'=>'verified','docs_url'=>'https://api.incident.io/v1/openapiV3.json']; }
    public function configSchema(): array { return [['key'=>'api_key','type'=>'secret','label'=>'API Key','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','placeholder'=>'https://api.incident.io','default'=>'https://api.incident.io']]; }
    /** @param  array<string, mixed>  $config  Credential and endpoint settings. @return array{success: bool, message?: string, error?: string} */ public function testConnection(array $config): array { $apiKey=(string)($config['api_key']??''); $baseUrl=rtrim((string)($config['url']??'https://api.incident.io'),'/'); if($apiKey==='')return ['success'=>false,'error'=>'incident.io API key is required.']; try{$response=Http::withHeaders(['Authorization'=>'Bearer '.$apiKey,'Accept'=>'application/json','Content-Type'=>'application/json'])->timeout(10)->get($baseUrl.'/v1/identity'); if(!$response->successful())return ['success'=>false,'error'=>'incident.io API returned HTTP '.$response->status().'.']; return ['success'=>true,'message'=>'Connected to incident.io at '.$baseUrl.'.'];}catch(\Throwable $e){return ['success'=>false,'error'=>$e->getMessage()];} }
    public function validationRules(): array { return ['api_key'=>'required|string','url'=>'nullable|url']; } public function credentialFields(): array { return [['key'=>'api_key','type'=>'secret','label'=>'API Key','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','required'=>false,'default'=>'https://api.incident.io']]; }
    public function tools(): array { return [
  'incident_io_actions_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoActionsV1List',
  'type' => 'read',
  'name' => 'List Actions V1',
  'description' => 'List Actions V1 Official incident.io endpoint: GET /v1/actions List all actions for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_actions_v1_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoActionsV1Show',
  'type' => 'read',
  'name' => 'Show Actions V1',
  'description' => 'Show Actions V1 Official incident.io endpoint: GET /v1/actions/{id} Get a single incident action.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_api_keys_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoApiKeysV1List',
  'type' => 'read',
  'name' => 'List API Keys V1',
  'description' => 'List API Keys V1 Official incident.io endpoint: GET /v1/api_keys List API keys visible to the calling API key, with pagination. An API key with account-level `api_keys_manage` access will see all keys, while a key with the `api_keys_manage`',
  'icon' => 'ph:warning-circle',
),
  'incident_io_api_keys_v1_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoApiKeysV1Create',
  'type' => 'write',
  'name' => 'Create API Keys V1',
  'description' => 'Create API Keys V1 Official incident.io endpoint: POST /v1/api_keys Create a new API key. The calling API key can only assign roles whose scopes are a subset of its own. The `api_keys_manage` role cannot be assigned via the API. An organiza',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_api_keys_v1_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoApiKeysV1Show',
  'type' => 'read',
  'name' => 'Show API Keys V1',
  'description' => 'Show API Keys V1 Official incident.io endpoint: GET /v1/api_keys/{id} Show details of a specific API key, including its roles, team assignments and when its token was last issued. This endpoint requires a valid API key with the `api_keys_ma',
  'icon' => 'ph:warning-circle',
),
  'incident_io_api_keys_v1_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoApiKeysV1Update',
  'type' => 'write',
  'name' => 'Update API Keys V1',
  'description' => 'Update API Keys V1 Official incident.io endpoint: PUT /v1/api_keys/{id} Update an existing API key\'s name, roles, or team assignments. All fields must be provided (PUT semantics). The calling API key can only assign roles whose scopes are a',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_api_keys_v1_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoApiKeysV1Delete',
  'type' => 'write',
  'name' => 'Delete API Keys V1',
  'description' => 'Delete API Keys V1 Official incident.io endpoint: DELETE /v1/api_keys/{id} Delete an existing API key. The calling API key does not need to hold the scopes of the key being deleted, but a team-scoped key can only delete keys belonging to it',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_api_keys_v1_rotate' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoApiKeysV1Rotate',
  'type' => 'write',
  'name' => 'Rotate API Keys V1',
  'description' => 'Rotate API Keys V1 Official incident.io endpoint: POST /v1/api_keys/{id}/actions/rotate Rotate the access token for an API key. This generates a new bearer token and optionally keeps the old token valid for a configurable grace period (up t',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_custom_field_options_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldOptionsV1List',
  'type' => 'read',
  'name' => 'List Custom Field Options V1',
  'description' => 'List Custom Field Options V1 Official incident.io endpoint: GET /v1/custom_field_options Show custom field options for a custom field',
  'icon' => 'ph:warning-circle',
),
  'incident_io_custom_field_options_v1_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldOptionsV1Create',
  'type' => 'write',
  'name' => 'Create Custom Field Options V1',
  'description' => 'Create Custom Field Options V1 Official incident.io endpoint: POST /v1/custom_field_options Create a custom field option. If the sort key is not supplied, it\'ll default to 1000, so the option appears near the end of the list.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_custom_field_options_v1_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldOptionsV1Show',
  'type' => 'read',
  'name' => 'Show Custom Field Options V1',
  'description' => 'Show Custom Field Options V1 Official incident.io endpoint: GET /v1/custom_field_options/{id} Get a single custom field option',
  'icon' => 'ph:warning-circle',
),
  'incident_io_custom_field_options_v1_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldOptionsV1Update',
  'type' => 'write',
  'name' => 'Update Custom Field Options V1',
  'description' => 'Update Custom Field Options V1 Official incident.io endpoint: PUT /v1/custom_field_options/{id} Update a custom field option',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_custom_field_options_v1_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldOptionsV1Delete',
  'type' => 'write',
  'name' => 'Delete Custom Field Options V1',
  'description' => 'Delete Custom Field Options V1 Official incident.io endpoint: DELETE /v1/custom_field_options/{id} Delete a custom field option',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_custom_fields_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldsV1List',
  'type' => 'read',
  'name' => 'List Custom Fields V1',
  'description' => 'List Custom Fields V1 Official incident.io endpoint: GET /v1/custom_fields List all custom fields for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_custom_fields_v1_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldsV1Create',
  'type' => 'write',
  'name' => 'Create Custom Fields V1',
  'description' => 'Create Custom Fields V1 Official incident.io endpoint: POST /v1/custom_fields Create a new custom field',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_custom_fields_v1_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldsV1Show',
  'type' => 'read',
  'name' => 'Show Custom Fields V1',
  'description' => 'Show Custom Fields V1 Official incident.io endpoint: GET /v1/custom_fields/{id} Get a single custom field.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_custom_fields_v1_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldsV1Update',
  'type' => 'write',
  'name' => 'Update Custom Fields V1',
  'description' => 'Update Custom Fields V1 Official incident.io endpoint: PUT /v1/custom_fields/{id} Update the details of a custom field',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_custom_fields_v1_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldsV1Delete',
  'type' => 'write',
  'name' => 'Delete Custom Fields V1',
  'description' => 'Delete Custom Fields V1 Official incident.io endpoint: DELETE /v1/custom_fields/{id} Delete a custom field',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_utilities_v1_identity' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoUtilitiesV1Identity',
  'type' => 'read',
  'name' => 'Identity Utilities V1',
  'description' => 'Identity Utilities V1 Official incident.io endpoint: GET /v1/identity Test if your API key is valid, and which roles it has.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_attachments_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentAttachmentsV1List',
  'type' => 'read',
  'name' => 'List Incident Attachments V1',
  'description' => 'List Incident Attachments V1 Official incident.io endpoint: GET /v1/incident_attachments List all incident attachments for a given external resource or incident. You must provide either a specific incident ID or a specific external resource',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_attachments_v1_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentAttachmentsV1Create',
  'type' => 'write',
  'name' => 'Create Incident Attachments V1',
  'description' => 'Create Incident Attachments V1 Official incident.io endpoint: POST /v1/incident_attachments Attaches an external resource to an incident',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_attachments_v1_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentAttachmentsV1Delete',
  'type' => 'write',
  'name' => 'Delete Incident Attachments V1',
  'description' => 'Delete Incident Attachments V1 Official incident.io endpoint: DELETE /v1/incident_attachments/{id} Unattaches an external resource from an incident',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_memberships_v1_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentMembershipsV1Create',
  'type' => 'write',
  'name' => 'Create Incident Memberships V1',
  'description' => 'Create Incident Memberships V1 Official incident.io endpoint: POST /v1/incident_memberships Makes a user a member of a private incident',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_memberships_v1_revoke' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentMembershipsV1Revoke',
  'type' => 'write',
  'name' => 'Revoke Incident Memberships V1',
  'description' => 'Revoke Incident Memberships V1 Official incident.io endpoint: POST /v1/incident_memberships/actions/revoke Revoke a user\'s membership of a private incident',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_relationships_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentRelationshipsV1List',
  'type' => 'read',
  'name' => 'List Incident Relationships V1',
  'description' => 'List Incident Relationships V1 Official incident.io endpoint: GET /v1/incident_relationships List related incidents for a specific incident.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_roles_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentRolesV1List',
  'type' => 'read',
  'name' => 'List Incident Roles V1',
  'description' => 'List Incident Roles V1 Official incident.io endpoint: GET /v1/incident_roles List all incident roles for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_roles_v1_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentRolesV1Create',
  'type' => 'write',
  'name' => 'Create Incident Roles V1',
  'description' => 'Create Incident Roles V1 Official incident.io endpoint: POST /v1/incident_roles Create a new incident role',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_roles_v1_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentRolesV1Show',
  'type' => 'read',
  'name' => 'Show Incident Roles V1',
  'description' => 'Show Incident Roles V1 Official incident.io endpoint: GET /v1/incident_roles/{id} Get a single incident role.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_roles_v1_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentRolesV1Update',
  'type' => 'write',
  'name' => 'Update Incident Roles V1',
  'description' => 'Update Incident Roles V1 Official incident.io endpoint: PUT /v1/incident_roles/{id} Update an existing incident role',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_roles_v1_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentRolesV1Delete',
  'type' => 'write',
  'name' => 'Delete Incident Roles V1',
  'description' => 'Delete Incident Roles V1 Official incident.io endpoint: DELETE /v1/incident_roles/{id} Removes an existing role',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_statuses_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentStatusesV1List',
  'type' => 'read',
  'name' => 'List Incident Statuses V1',
  'description' => 'List Incident Statuses V1 Official incident.io endpoint: GET /v1/incident_statuses List all incident statuses for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_statuses_v1_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentStatusesV1Create',
  'type' => 'write',
  'name' => 'Create Incident Statuses V1',
  'description' => 'Create Incident Statuses V1 Official incident.io endpoint: POST /v1/incident_statuses Create a new incident status',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_statuses_v1_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentStatusesV1Show',
  'type' => 'read',
  'name' => 'Show Incident Statuses V1',
  'description' => 'Show Incident Statuses V1 Official incident.io endpoint: GET /v1/incident_statuses/{id} Get a single incident status.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_statuses_v1_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentStatusesV1Update',
  'type' => 'write',
  'name' => 'Update Incident Statuses V1',
  'description' => 'Update Incident Statuses V1 Official incident.io endpoint: PUT /v1/incident_statuses/{id} Update an existing incident status',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_statuses_v1_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentStatusesV1Delete',
  'type' => 'write',
  'name' => 'Delete Incident Statuses V1',
  'description' => 'Delete Incident Statuses V1 Official incident.io endpoint: DELETE /v1/incident_statuses/{id} Delete an incident status',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_types_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentTypesV1List',
  'type' => 'read',
  'name' => 'List Incident Types V1',
  'description' => 'List Incident Types V1 Official incident.io endpoint: GET /v1/incident_types List all incident types for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_types_v1_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentTypesV1Show',
  'type' => 'read',
  'name' => 'Show Incident Types V1',
  'description' => 'Show Incident Types V1 Official incident.io endpoint: GET /v1/incident_types/{id} Get a single incident type.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incidents_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentsV1List',
  'type' => 'read',
  'name' => 'List Incidents V1',
  'description' => 'List Incidents V1 Official incident.io endpoint: GET /v1/incidents List all incidents for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incidents_v1_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentsV1Create',
  'type' => 'write',
  'name' => 'Create Incidents V1',
  'description' => 'Create Incidents V1 Official incident.io endpoint: POST /v1/incidents Create a new incident.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incidents_v1_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentsV1Show',
  'type' => 'read',
  'name' => 'Show Incidents V1',
  'description' => 'Show Incidents V1 Official incident.io endpoint: GET /v1/incidents/{id} Get a single incident.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_ipallowlists_v1_show_ipallowlist' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIpallowlistsV1ShowIpallowlist',
  'type' => 'read',
  'name' => 'ShowIPAllowlist IPAllowlists V1',
  'description' => 'ShowIPAllowlist IPAllowlists V1 Official incident.io endpoint: GET /v1/ip_allowlists Show the IP allowlist for your organisation',
  'icon' => 'ph:warning-circle',
),
  'incident_io_ipallowlists_v1_update_ipallowlist' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIpallowlistsV1UpdateIpallowlist',
  'type' => 'write',
  'name' => 'UpdateIPAllowlist IPAllowlists V1',
  'description' => 'UpdateIPAllowlist IPAllowlists V1 Official incident.io endpoint: PUT /v1/ip_allowlists Update the IP allowlist for your organisation',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_maintenance_windows_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoMaintenanceWindowsV1List',
  'type' => 'read',
  'name' => 'List MaintenanceWindows V1',
  'description' => 'List MaintenanceWindows V1 Official incident.io endpoint: GET /v1/maintenance_windows List maintenance windows for your organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_maintenance_windows_v1_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoMaintenanceWindowsV1Create',
  'type' => 'write',
  'name' => 'Create MaintenanceWindows V1',
  'description' => 'Create MaintenanceWindows V1 Official incident.io endpoint: POST /v1/maintenance_windows Create a new maintenance window.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_maintenance_windows_v1_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoMaintenanceWindowsV1Show',
  'type' => 'read',
  'name' => 'Show MaintenanceWindows V1',
  'description' => 'Show MaintenanceWindows V1 Official incident.io endpoint: GET /v1/maintenance_windows/{id} Show a particular maintenance window.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_maintenance_windows_v1_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoMaintenanceWindowsV1Update',
  'type' => 'write',
  'name' => 'Update MaintenanceWindows V1',
  'description' => 'Update MaintenanceWindows V1 Official incident.io endpoint: PUT /v1/maintenance_windows/{id} Update an existing maintenance window.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_maintenance_windows_v1_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoMaintenanceWindowsV1Delete',
  'type' => 'write',
  'name' => 'Delete MaintenanceWindows V1',
  'description' => 'Delete MaintenanceWindows V1 Official incident.io endpoint: DELETE /v1/maintenance_windows/{id} Archives a maintenance window. Cannot archive active windows.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_utilities_v1_open_api' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoUtilitiesV1OpenApi',
  'type' => 'read',
  'name' => 'OpenAPI Utilities V1',
  'description' => 'OpenAPI Utilities V1 Official incident.io endpoint: GET /v1/openapi.json Get the OpenAPI (v2) definition. **DEPRECATED**: Please use the OpenAPIV3 endpoint instead. The schema returned from this endpoint does not contain new options and end',
  'icon' => 'ph:warning-circle',
),
  'incident_io_utilities_v1_open_apiv3' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoUtilitiesV1OpenApiv3',
  'type' => 'read',
  'name' => 'OpenAPIV3 Utilities V1',
  'description' => 'OpenAPIV3 Utilities V1 Official incident.io endpoint: GET /v1/openapiV3.json Get the OpenAPI (v3) definition.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_postmortem_documents_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoPostmortemDocumentsV1List',
  'type' => 'read',
  'name' => 'List PostmortemDocuments V1',
  'description' => 'List PostmortemDocuments V1 Official incident.io endpoint: GET /v1/postmortem_documents List post-mortem documents for the organisation. Results can be filtered by incident and sorted by creation date. This endpoint returns document metadat',
  'icon' => 'ph:warning-circle',
),
  'incident_io_postmortem_documents_v1_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoPostmortemDocumentsV1Show',
  'type' => 'read',
  'name' => 'Show PostmortemDocuments V1',
  'description' => 'Show PostmortemDocuments V1 Official incident.io endpoint: GET /v1/postmortem_documents/{id} Get a single post-mortem document by ID. This returns the document\'s metadata. To retrieve the content of the post-mortem, use the ShowContent endp',
  'icon' => 'ph:warning-circle',
),
  'incident_io_postmortem_documents_v1_update_status' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoPostmortemDocumentsV1UpdateStatus',
  'type' => 'write',
  'name' => 'UpdateStatus PostmortemDocuments V1',
  'description' => 'UpdateStatus PostmortemDocuments V1 Official incident.io endpoint: PUT /v1/postmortem_documents/{id} Update the status of a post-mortem document.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_postmortem_documents_v1_show_content' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoPostmortemDocumentsV1ShowContent',
  'type' => 'read',
  'name' => 'ShowContent PostmortemDocuments V1',
  'description' => 'ShowContent PostmortemDocuments V1 Official incident.io endpoint: GET /v1/postmortem_documents/{id}/content Fetch the content of a post-mortem document, rendered as markdown. The response contains the full document content as a single markd',
  'icon' => 'ph:warning-circle',
),
  'incident_io_severities_v1_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSeveritiesV1List',
  'type' => 'read',
  'name' => 'List Severities V1',
  'description' => 'List Severities V1 Official incident.io endpoint: GET /v1/severities List all incident severities for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_severities_v1_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSeveritiesV1Create',
  'type' => 'write',
  'name' => 'Create Severities V1',
  'description' => 'Create Severities V1 Official incident.io endpoint: POST /v1/severities Create a new severity',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_severities_v1_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSeveritiesV1Show',
  'type' => 'read',
  'name' => 'Show Severities V1',
  'description' => 'Show Severities V1 Official incident.io endpoint: GET /v1/severities/{id} Get a single incident severity.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_severities_v1_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSeveritiesV1Update',
  'type' => 'write',
  'name' => 'Update Severities V1',
  'description' => 'Update Severities V1 Official incident.io endpoint: PUT /v1/severities/{id} Update an existing severity',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_severities_v1_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSeveritiesV1Delete',
  'type' => 'write',
  'name' => 'Delete Severities V1',
  'description' => 'Delete Severities V1 Official incident.io endpoint: DELETE /v1/severities/{id} Delete a severity',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_status_pages_v1_list_response_incidents' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV1ListResponseIncidents',
  'type' => 'read',
  'name' => 'ListResponseIncidents Status Pages V1',
  'description' => 'ListResponseIncidents Status Pages V1 Official incident.io endpoint: GET /v1/status-pages/{id}/incidents/{incident_id}/response-incidents List the linked Response incidents for a status page incident.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_actions_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoActionsV2List',
  'type' => 'read',
  'name' => 'List Actions V2',
  'description' => 'List Actions V2 Official incident.io endpoint: GET /v2/actions List all actions for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_actions_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoActionsV2Show',
  'type' => 'read',
  'name' => 'Show Actions V2',
  'description' => 'Show Actions V2 Official incident.io endpoint: GET /v2/actions/{id} Get a single incident action.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_alert_attributes_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertAttributesV2List',
  'type' => 'read',
  'name' => 'List Alert Attributes V2',
  'description' => 'List Alert Attributes V2 Official incident.io endpoint: GET /v2/alert_attributes List alert attributes.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_alert_attributes_v2_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertAttributesV2Create',
  'type' => 'write',
  'name' => 'Create Alert Attributes V2',
  'description' => 'Create Alert Attributes V2 Official incident.io endpoint: POST /v2/alert_attributes Create a new alert attribute.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_alert_attributes_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertAttributesV2Show',
  'type' => 'read',
  'name' => 'Show Alert Attributes V2',
  'description' => 'Show Alert Attributes V2 Official incident.io endpoint: GET /v2/alert_attributes/{id} Show an alert attribute.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_alert_attributes_v2_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertAttributesV2Update',
  'type' => 'write',
  'name' => 'Update Alert Attributes V2',
  'description' => 'Update Alert Attributes V2 Official incident.io endpoint: PUT /v2/alert_attributes/{id} Update an alert attribute.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_alert_attributes_v2_destroy' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertAttributesV2Destroy',
  'type' => 'write',
  'name' => 'Destroy Alert Attributes V2',
  'description' => 'Destroy Alert Attributes V2 Official incident.io endpoint: DELETE /v2/alert_attributes/{id} Destroy an alert attribute.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_alert_events_v2_create_http' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertEventsV2CreateHttp',
  'type' => 'write',
  'name' => 'CreateHTTP Alert Events V2',
  'description' => 'CreateHTTP Alert Events V2 Official incident.io endpoint: POST /v2/alert_events/http/{alert_source_config_id} Create an alert event using an HTTP source.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_alert_routes_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertRoutesV2List',
  'type' => 'read',
  'name' => 'List Alert Routes V2',
  'description' => 'List Alert Routes V2 Official incident.io endpoint: GET /v2/alert_routes List all alert routes in your account.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_alert_routes_v2_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertRoutesV2Create',
  'type' => 'write',
  'name' => 'Create Alert Routes V2',
  'description' => 'Create Alert Routes V2 Official incident.io endpoint: POST /v2/alert_routes Create a new alert route in your account.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_alert_routes_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertRoutesV2Show',
  'type' => 'read',
  'name' => 'Show Alert Routes V2',
  'description' => 'Show Alert Routes V2 Official incident.io endpoint: GET /v2/alert_routes/{id} Load details about a specific alert route in your account.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_alert_routes_v2_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertRoutesV2Update',
  'type' => 'write',
  'name' => 'Update Alert Routes V2',
  'description' => 'Update Alert Routes V2 Official incident.io endpoint: PUT /v2/alert_routes/{id} Update an existing alert route in your account.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_alert_routes_v2_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertRoutesV2Delete',
  'type' => 'write',
  'name' => 'Delete Alert Routes V2',
  'description' => 'Delete Alert Routes V2 Official incident.io endpoint: DELETE /v2/alert_routes/{id} Delete an existing alert route in your account.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_alert_sources_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertSourcesV2List',
  'type' => 'read',
  'name' => 'List Alert Sources V2',
  'description' => 'List Alert Sources V2 Official incident.io endpoint: GET /v2/alert_sources List all alert sources in your account.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_alert_sources_v2_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertSourcesV2Create',
  'type' => 'write',
  'name' => 'Create Alert Sources V2',
  'description' => 'Create Alert Sources V2 Official incident.io endpoint: POST /v2/alert_sources Create a new alert source in your account.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_alert_sources_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertSourcesV2Show',
  'type' => 'read',
  'name' => 'Show Alert Sources V2',
  'description' => 'Show Alert Sources V2 Official incident.io endpoint: GET /v2/alert_sources/{id} Load details about a specific alert source in your account.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_alert_sources_v2_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertSourcesV2Update',
  'type' => 'write',
  'name' => 'Update Alert Sources V2',
  'description' => 'Update Alert Sources V2 Official incident.io endpoint: PUT /v2/alert_sources/{id} Update an existing alert source in your account.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_alert_sources_v2_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertSourcesV2Delete',
  'type' => 'write',
  'name' => 'Delete Alert Sources V2',
  'description' => 'Delete Alert Sources V2 Official incident.io endpoint: DELETE /v2/alert_sources/{id} Delete an existing alert source in your account.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_alerts_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertsV2List',
  'type' => 'read',
  'name' => 'List Alerts V2',
  'description' => 'List Alerts V2 Official incident.io endpoint: GET /v2/alerts List all alerts for your account. This endpoint supports a number of filters, which can help find alerts matching certain criteria. These filters work similarly to the filters on ',
  'icon' => 'ph:warning-circle',
),
  'incident_io_alerts_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertsV2Show',
  'type' => 'read',
  'name' => 'Show Alerts V2',
  'description' => 'Show Alerts V2 Official incident.io endpoint: GET /v2/alerts/{id} Show a single alert for your account',
  'icon' => 'ph:warning-circle',
),
  'incident_io_catalog_v2_list_entries' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2ListEntries',
  'type' => 'read',
  'name' => 'ListEntries Catalog V2',
  'description' => 'ListEntries Catalog V2 Official incident.io endpoint: GET /v2/catalog_entries List entries for a catalog type.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_catalog_v2_create_entry' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2CreateEntry',
  'type' => 'write',
  'name' => 'CreateEntry Catalog V2',
  'description' => 'CreateEntry Catalog V2 Official incident.io endpoint: POST /v2/catalog_entries Create an entry within the catalog. We support a maximum of 50,000 entries per type. If you call this API with a payload where the external_id and catalog_type_i',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v2_show_entry' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2ShowEntry',
  'type' => 'read',
  'name' => 'ShowEntry Catalog V2',
  'description' => 'ShowEntry Catalog V2 Official incident.io endpoint: GET /v2/catalog_entries/{id} Show a single catalog entry.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_catalog_v2_update_entry' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2UpdateEntry',
  'type' => 'write',
  'name' => 'UpdateEntry Catalog V2',
  'description' => 'UpdateEntry Catalog V2 Official incident.io endpoint: PUT /v2/catalog_entries/{id} Updates an existing catalog entry.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v2_destroy_entry' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2DestroyEntry',
  'type' => 'write',
  'name' => 'DestroyEntry Catalog V2',
  'description' => 'DestroyEntry Catalog V2 Official incident.io endpoint: DELETE /v2/catalog_entries/{id} Archives a catalog entry.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v2_list_resources' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2ListResources',
  'type' => 'read',
  'name' => 'ListResources Catalog V2',
  'description' => 'ListResources Catalog V2 Official incident.io endpoint: GET /v2/catalog_resources List available engine resources for the catalog. A resource represents a type of data that can be held within the catalog, so this endpoint can be used to see',
  'icon' => 'ph:warning-circle',
),
  'incident_io_catalog_v2_list_types' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2ListTypes',
  'type' => 'read',
  'name' => 'ListTypes Catalog V2',
  'description' => 'ListTypes Catalog V2 Official incident.io endpoint: GET /v2/catalog_types List all catalog types for an organisation, including those synced from external resources.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_catalog_v2_create_type' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2CreateType',
  'type' => 'write',
  'name' => 'CreateType Catalog V2',
  'description' => 'CreateType Catalog V2 Official incident.io endpoint: POST /v2/catalog_types Create a catalog type. The schema must be updated using the UpdateTypeSchema endpoint.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v2_show_type' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2ShowType',
  'type' => 'read',
  'name' => 'ShowType Catalog V2',
  'description' => 'ShowType Catalog V2 Official incident.io endpoint: GET /v2/catalog_types/{id} Show a single catalog type.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_catalog_v2_update_type' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2UpdateType',
  'type' => 'write',
  'name' => 'UpdateType Catalog V2',
  'description' => 'UpdateType Catalog V2 Official incident.io endpoint: PUT /v2/catalog_types/{id} Updates an existing catalog type. The schema must be updated using the UpdateTypeSchema endpoint.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v2_destroy_type' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2DestroyType',
  'type' => 'write',
  'name' => 'DestroyType Catalog V2',
  'description' => 'DestroyType Catalog V2 Official incident.io endpoint: DELETE /v2/catalog_types/{id} Archives a catalog type and associated entries.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v2_update_type_schema' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV2UpdateTypeSchema',
  'type' => 'write',
  'name' => 'UpdateTypeSchema Catalog V2',
  'description' => 'UpdateTypeSchema Catalog V2 Official incident.io endpoint: POST /v2/catalog_types/{id}/actions/update_schema Update an existing catalog types schema, adding or removing attributes. Updating the schema is handled separately from creating and',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_custom_fields_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldsV2List',
  'type' => 'read',
  'name' => 'List Custom Fields V2',
  'description' => 'List Custom Fields V2 Official incident.io endpoint: GET /v2/custom_fields List all custom fields for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_custom_fields_v2_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldsV2Create',
  'type' => 'write',
  'name' => 'Create Custom Fields V2',
  'description' => 'Create Custom Fields V2 Official incident.io endpoint: POST /v2/custom_fields Create a new custom field',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_custom_fields_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldsV2Show',
  'type' => 'read',
  'name' => 'Show Custom Fields V2',
  'description' => 'Show Custom Fields V2 Official incident.io endpoint: GET /v2/custom_fields/{id} Get a single custom field.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_custom_fields_v2_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldsV2Update',
  'type' => 'write',
  'name' => 'Update Custom Fields V2',
  'description' => 'Update Custom Fields V2 Official incident.io endpoint: PUT /v2/custom_fields/{id} Update the details of a custom field',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_custom_fields_v2_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCustomFieldsV2Delete',
  'type' => 'write',
  'name' => 'Delete Custom Fields V2',
  'description' => 'Delete Custom Fields V2 Official incident.io endpoint: DELETE /v2/custom_fields/{id} Delete a custom field',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_escalations_v2_list_paths' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoEscalationsV2ListPaths',
  'type' => 'read',
  'name' => 'ListPaths Escalations V2',
  'description' => 'ListPaths Escalations V2 Official incident.io endpoint: GET /v2/escalation_paths List all escalation paths in your account. An escalation path is a series of steps that describe how a page should be escalated, represented as a graph, suppor',
  'icon' => 'ph:warning-circle',
),
  'incident_io_escalations_v2_create_path' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoEscalationsV2CreatePath',
  'type' => 'write',
  'name' => 'CreatePath Escalations V2',
  'description' => 'CreatePath Escalations V2 Official incident.io endpoint: POST /v2/escalation_paths Create an escalation path. An escalation path is a series of steps that describe how a page should be escalated, represented as graph, supporting conditional',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_escalations_v2_show_path' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoEscalationsV2ShowPath',
  'type' => 'read',
  'name' => 'ShowPath Escalations V2',
  'description' => 'ShowPath Escalations V2 Official incident.io endpoint: GET /v2/escalation_paths/{id} Show an escalation path. We recommend you create escalation paths in the incident.io dashboard where our path builder makes it easy to use conditions and v',
  'icon' => 'ph:warning-circle',
),
  'incident_io_escalations_v2_update_path' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoEscalationsV2UpdatePath',
  'type' => 'write',
  'name' => 'UpdatePath Escalations V2',
  'description' => 'UpdatePath Escalations V2 Official incident.io endpoint: PUT /v2/escalation_paths/{id} Updates an escalation path. We recommend you create escalation paths in the incident.io dashboard where our path builder makes it easy to use conditions ',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_escalations_v2_destroy_path' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoEscalationsV2DestroyPath',
  'type' => 'write',
  'name' => 'DestroyPath Escalations V2',
  'description' => 'DestroyPath Escalations V2 Official incident.io endpoint: DELETE /v2/escalation_paths/{id} Archives an escalation path. We recommend you create escalation paths in the incident.io dashboard where our path builder makes it easy to use condit',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_escalations_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoEscalationsV2List',
  'type' => 'read',
  'name' => 'List Escalations V2',
  'description' => 'List Escalations V2 Official incident.io endpoint: GET /v2/escalations List all escalations for your account. This endpoint supports a number of filters, which can help find escalations matching certain criteria. Note that: - Filters may be',
  'icon' => 'ph:warning-circle',
),
  'incident_io_escalations_v2_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoEscalationsV2Create',
  'type' => 'write',
  'name' => 'Create Escalations V2',
  'description' => 'Create Escalations V2 Official incident.io endpoint: POST /v2/escalations Create an escalation. An escalation pages people, either according to an escalation path, or directly to specific users. You must provide either an escalation_path_id',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_escalations_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoEscalationsV2Show',
  'type' => 'read',
  'name' => 'Show Escalations V2',
  'description' => 'Show Escalations V2 Official incident.io endpoint: GET /v2/escalations/{id} Show a specific escalation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_follow_ups_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoFollowUpsV2List',
  'type' => 'read',
  'name' => 'List Follow-ups V2',
  'description' => 'List Follow-ups V2 Official incident.io endpoint: GET /v2/follow_ups List all follow-ups for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_follow_ups_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoFollowUpsV2Show',
  'type' => 'read',
  'name' => 'Show Follow-ups V2',
  'description' => 'Show Follow-ups V2 Official incident.io endpoint: GET /v2/follow_ups/{id} Get a single incident follow-up.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_heartbeat_v2_ping_1' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoHeartbeatV2Ping1',
  'type' => 'read',
  'name' => 'Ping Heartbeat V2',
  'description' => 'Ping Heartbeat V2 Official incident.io endpoint: GET /v2/heartbeat/{alert_source_config_id}/ping Send a heartbeat ping for the specified alert source. Records a ping, indicating that the monitored job or service is healthy. The heartbeat mo',
  'icon' => 'ph:warning-circle',
),
  'incident_io_heartbeat_v2_ping' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoHeartbeatV2Ping',
  'type' => 'write',
  'name' => 'Ping Heartbeat V2',
  'description' => 'Ping Heartbeat V2 Official incident.io endpoint: POST /v2/heartbeat/{alert_source_config_id}/ping Send a heartbeat ping for the specified alert source. Records a ping, indicating that the monitored job or service is healthy. The heartbeat m',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_alerts_v2_list_incident_alerts' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoAlertsV2ListIncidentAlerts',
  'type' => 'read',
  'name' => 'ListIncidentAlerts Alerts V2',
  'description' => 'ListIncidentAlerts Alerts V2 Official incident.io endpoint: GET /v2/incident_alerts List the connections between incidents and alerts',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_roles_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentRolesV2List',
  'type' => 'read',
  'name' => 'List Incident Roles V2',
  'description' => 'List Incident Roles V2 Official incident.io endpoint: GET /v2/incident_roles List all incident roles for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_roles_v2_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentRolesV2Create',
  'type' => 'write',
  'name' => 'Create Incident Roles V2',
  'description' => 'Create Incident Roles V2 Official incident.io endpoint: POST /v2/incident_roles Create a new incident role',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_roles_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentRolesV2Show',
  'type' => 'read',
  'name' => 'Show Incident Roles V2',
  'description' => 'Show Incident Roles V2 Official incident.io endpoint: GET /v2/incident_roles/{id} Get a single incident role.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_roles_v2_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentRolesV2Update',
  'type' => 'write',
  'name' => 'Update Incident Roles V2',
  'description' => 'Update Incident Roles V2 Official incident.io endpoint: PUT /v2/incident_roles/{id} Update an existing incident role',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_roles_v2_delete' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentRolesV2Delete',
  'type' => 'write',
  'name' => 'Delete Incident Roles V2',
  'description' => 'Delete Incident Roles V2 Official incident.io endpoint: DELETE /v2/incident_roles/{id} Removes an existing role',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incident_timestamps_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentTimestampsV2List',
  'type' => 'read',
  'name' => 'List Incident Timestamps V2',
  'description' => 'List Incident Timestamps V2 Official incident.io endpoint: GET /v2/incident_timestamps List all incident timestamps for an organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_timestamps_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentTimestampsV2Show',
  'type' => 'read',
  'name' => 'Show Incident Timestamps V2',
  'description' => 'Show Incident Timestamps V2 Official incident.io endpoint: GET /v2/incident_timestamps/{id} Get a single incident timestamp.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incident_updates_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentUpdatesV2List',
  'type' => 'read',
  'name' => 'List Incident Updates V2',
  'description' => 'List Incident Updates V2 Official incident.io endpoint: GET /v2/incident_updates List all incident updates for an organisation, or for a specific incident.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incidents_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentsV2List',
  'type' => 'read',
  'name' => 'List Incidents V2',
  'description' => 'List Incidents V2 Official incident.io endpoint: GET /v2/incidents List all incidents for an organisation. This endpoint supports a number of filters, which can help find incidents matching certain criteria. Filters are provided as query pa',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incidents_v2_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentsV2Create',
  'type' => 'write',
  'name' => 'Create Incidents V2',
  'description' => 'Create Incidents V2 Official incident.io endpoint: POST /v2/incidents Create a new incident. Note that if the incident mode is set to \"retrospective\" then the new incident will not be announced in Slack.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incidents_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentsV2Show',
  'type' => 'read',
  'name' => 'Show Incidents V2',
  'description' => 'Show Incidents V2 Official incident.io endpoint: GET /v2/incidents/{id} Get a single incident. The ID supplied can be either the incident\'s full ID, or the numeric part of its reference. For example, to get INC-123, you could use either its',
  'icon' => 'ph:warning-circle',
),
  'incident_io_incidents_v2_edit' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentsV2Edit',
  'type' => 'write',
  'name' => 'Edit Incidents V2',
  'description' => 'Edit Incidents V2 Official incident.io endpoint: POST /v2/incidents/{id}/actions/edit Edit an existing incident. This endpoint allows you to edit the properties of an existing incident: e.g. set the severity or update custom fields. When us',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_incidents_v2_import_postmortem_document' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoIncidentsV2ImportPostmortemDocument',
  'type' => 'write',
  'name' => 'ImportPostmortemDocument Incidents V2',
  'description' => 'ImportPostmortemDocument Incidents V2 Official incident.io endpoint: POST /v2/incidents/{id}/actions/import_postmortem_document Import a postmortem document from markdown into an incident. The document content should be provided as GitHub-F',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_schedules_v2_list_schedule_entries' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSchedulesV2ListScheduleEntries',
  'type' => 'read',
  'name' => 'ListScheduleEntries Schedules V2',
  'description' => 'ListScheduleEntries Schedules V2 Official incident.io endpoint: GET /v2/schedule_entries Get a list of schedule entries. The endpoint will return all entries that overlap with the given window, if one is provided.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_schedules_v2_create_override' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSchedulesV2CreateOverride',
  'type' => 'write',
  'name' => 'CreateOverride Schedules V2',
  'description' => 'CreateOverride Schedules V2 Official incident.io endpoint: POST /v2/schedule_overrides Create a new schedule override.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_schedules_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSchedulesV2List',
  'type' => 'read',
  'name' => 'List Schedules V2',
  'description' => 'List Schedules V2 Official incident.io endpoint: GET /v2/schedules List configured schedules.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_schedules_v2_create' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSchedulesV2Create',
  'type' => 'write',
  'name' => 'Create Schedules V2',
  'description' => 'Create Schedules V2 Official incident.io endpoint: POST /v2/schedules Create a new schedule.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_schedules_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSchedulesV2Show',
  'type' => 'read',
  'name' => 'Show Schedules V2',
  'description' => 'Show Schedules V2 Official incident.io endpoint: GET /v2/schedules/{id} Get a single schedule.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_schedules_v2_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSchedulesV2Update',
  'type' => 'write',
  'name' => 'Update Schedules V2',
  'description' => 'Update Schedules V2 Official incident.io endpoint: PUT /v2/schedules/{id} Update a schedule.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_schedules_v2_destroy' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSchedulesV2Destroy',
  'type' => 'write',
  'name' => 'Destroy Schedules V2',
  'description' => 'Destroy Schedules V2 Official incident.io endpoint: DELETE /v2/schedules/{id} Archives a single schedule. Will fail if the schedule has active replicas — remove all replicas before deleting.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_schedules_v2_list_schedule_replicas' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSchedulesV2ListScheduleReplicas',
  'type' => 'read',
  'name' => 'ListScheduleReplicas Schedules V2',
  'description' => 'ListScheduleReplicas Schedules V2 Official incident.io endpoint: GET /v2/schedules/{schedule_id}/replicas List all replicas for a schedule.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_schedules_v2_create_schedule_replica' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSchedulesV2CreateScheduleReplica',
  'type' => 'write',
  'name' => 'CreateScheduleReplica Schedules V2',
  'description' => 'CreateScheduleReplica Schedules V2 Official incident.io endpoint: POST /v2/schedules/{schedule_id}/replicas Create a new schedule replica.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_schedules_v2_show_schedule_replica' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSchedulesV2ShowScheduleReplica',
  'type' => 'read',
  'name' => 'ShowScheduleReplica Schedules V2',
  'description' => 'ShowScheduleReplica Schedules V2 Official incident.io endpoint: GET /v2/schedules/{schedule_id}/replicas/{id} Get a single schedule replica.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_schedules_v2_destroy_schedule_replica' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoSchedulesV2DestroyScheduleReplica',
  'type' => 'write',
  'name' => 'DestroyScheduleReplica Schedules V2',
  'description' => 'DestroyScheduleReplica Schedules V2 Official incident.io endpoint: DELETE /v2/schedules/{schedule_id}/replicas/{id} Archives a single schedule replica, stopping incident.io from syncing on-call shifts to the external provider. As with disab',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_status_pages_v2_create_status_page_incident_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV2CreateStatusPageIncidentUpdate',
  'type' => 'write',
  'name' => 'CreateStatusPageIncidentUpdate Status Pages V2',
  'description' => 'CreateStatusPageIncidentUpdate Status Pages V2 Official incident.io endpoint: POST /v2/status_page_incident_updates Post an update on a Status Page incident. This is the endpoint to use when resolving an incident - set incident_status to \"r',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_status_pages_v2_list_status_page_incidents' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV2ListStatusPageIncidents',
  'type' => 'read',
  'name' => 'ListStatusPageIncidents Status Pages V2',
  'description' => 'ListStatusPageIncidents Status Pages V2 Official incident.io endpoint: GET /v2/status_page_incidents List status page incidents. This endpoint requires a valid API key but no specific scopes.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_status_pages_v2_create_status_page_incident' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV2CreateStatusPageIncident',
  'type' => 'write',
  'name' => 'CreateStatusPageIncident Status Pages V2',
  'description' => 'CreateStatusPageIncident Status Pages V2 Official incident.io endpoint: POST /v2/status_page_incidents Create a status page incident. This endpoint requires an API key with the \"Create status page incidents, status page maintenance windows,',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_status_pages_v2_show_status_page_incident' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV2ShowStatusPageIncident',
  'type' => 'read',
  'name' => 'ShowStatusPageIncident Status Pages V2',
  'description' => 'ShowStatusPageIncident Status Pages V2 Official incident.io endpoint: GET /v2/status_page_incidents/{status_page_incident_id} Show a status page incident. This endpoint requires a valid API key but no specific scopes.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_status_pages_v2_update_status_page_incident' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV2UpdateStatusPageIncident',
  'type' => 'write',
  'name' => 'UpdateStatusPageIncident Status Pages V2',
  'description' => 'UpdateStatusPageIncident Status Pages V2 Official incident.io endpoint: PUT /v2/status_page_incidents/{status_page_incident_id} Update a status page incident. This endpoint requires an API key with the \"Create status page incidents, status ',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_status_pages_v2_create_status_page_maintenance_update' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV2CreateStatusPageMaintenanceUpdate',
  'type' => 'write',
  'name' => 'CreateStatusPageMaintenanceUpdate Status Pages V2',
  'description' => 'CreateStatusPageMaintenanceUpdate Status Pages V2 Official incident.io endpoint: POST /v2/status_page_maintenance_updates Post an update on a Status Page maintenance window. This is the endpoint to use when completing a maintenance window -',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_status_pages_v2_list_status_page_maintenances' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV2ListStatusPageMaintenances',
  'type' => 'read',
  'name' => 'ListStatusPageMaintenances Status Pages V2',
  'description' => 'ListStatusPageMaintenances Status Pages V2 Official incident.io endpoint: GET /v2/status_page_maintenances List status page maintenances. This endpoint requires a valid API key but no specific scopes.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_status_pages_v2_create_status_page_maintenance' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV2CreateStatusPageMaintenance',
  'type' => 'write',
  'name' => 'CreateStatusPageMaintenance Status Pages V2',
  'description' => 'CreateStatusPageMaintenance Status Pages V2 Official incident.io endpoint: POST /v2/status_page_maintenances Schedule a Status Page maintenance window. This endpoint requires an API key with the \"Create status page incidents, status page ma',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_status_pages_v2_show_status_page_maintenance' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV2ShowStatusPageMaintenance',
  'type' => 'read',
  'name' => 'ShowStatusPageMaintenance Status Pages V2',
  'description' => 'ShowStatusPageMaintenance Status Pages V2 Official incident.io endpoint: GET /v2/status_page_maintenances/{status_page_maintenance_id} Show a status page maintenance window. This endpoint requires a valid API key but no specific scopes.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_status_pages_v2_show_status_page_structure' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV2ShowStatusPageStructure',
  'type' => 'read',
  'name' => 'ShowStatusPageStructure Status Pages V2',
  'description' => 'ShowStatusPageStructure Status Pages V2 Official incident.io endpoint: GET /v2/status_page_structures/{status_page_id} Show the structure of a status page. This endpoint requires a valid API key but no specific scopes. Returns the component',
  'icon' => 'ph:warning-circle',
),
  'incident_io_status_pages_v2_list_status_pages' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoStatusPagesV2ListStatusPages',
  'type' => 'read',
  'name' => 'ListStatusPages Status Pages V2',
  'description' => 'ListStatusPages Status Pages V2 Official incident.io endpoint: GET /v2/status_pages List all status pages for your organisation. This endpoint requires a valid API key but no specific scopes. Use this to find status page IDs for use in othe',
  'icon' => 'ph:warning-circle',
),
  'incident_io_telemetry_v2_update_data_source' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoTelemetryV2UpdateDataSource',
  'type' => 'write',
  'name' => 'UpdateDataSource Telemetry V2',
  'description' => 'UpdateDataSource Telemetry V2 Official incident.io endpoint: PUT /v2/telemetry/data_sources/{id} Update the credentials or configuration of a telemetry data source. Provide only the config block that matches your data source type (e.g. graf',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_users_v2_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoUsersV2List',
  'type' => 'read',
  'name' => 'List Users V2',
  'description' => 'List Users V2 Official incident.io endpoint: GET /v2/users List users in your account.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_users_v2_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoUsersV2Show',
  'type' => 'read',
  'name' => 'Show Users V2',
  'description' => 'Show Users V2 Official incident.io endpoint: GET /v2/users/{id} Get a single user.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_users_v2_list_notification_methods' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoUsersV2ListNotificationMethods',
  'type' => 'read',
  'name' => 'ListNotificationMethods Users V2',
  'description' => 'ListNotificationMethods Users V2 Official incident.io endpoint: GET /v2/users/{user_id}/notification_methods List notification methods for a user. Phone numbers are always partially redacted.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_users_v2_list_notification_rules' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoUsersV2ListNotificationRules',
  'type' => 'read',
  'name' => 'ListNotificationRules Users V2',
  'description' => 'ListNotificationRules Users V2 Official incident.io endpoint: GET /v2/users/{user_id}/notification_rules List notification rules for a user. Rules define how and when a user is notified for on-call pages. Only includes high_urgency and low_',
  'icon' => 'ph:warning-circle',
),
  'incident_io_workflows_v2_list_workflows' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoWorkflowsV2ListWorkflows',
  'type' => 'read',
  'name' => 'ListWorkflows Workflows V2',
  'description' => 'ListWorkflows Workflows V2 Official incident.io endpoint: GET /v2/workflows List all workflows',
  'icon' => 'ph:warning-circle',
),
  'incident_io_workflows_v2_create_workflow' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoWorkflowsV2CreateWorkflow',
  'type' => 'write',
  'name' => 'CreateWorkflow Workflows V2',
  'description' => 'CreateWorkflow Workflows V2 Official incident.io endpoint: POST /v2/workflows Create a new workflow',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_workflows_v2_show_workflow' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoWorkflowsV2ShowWorkflow',
  'type' => 'read',
  'name' => 'ShowWorkflow Workflows V2',
  'description' => 'ShowWorkflow Workflows V2 Official incident.io endpoint: GET /v2/workflows/{id} Show a workflow by ID',
  'icon' => 'ph:warning-circle',
),
  'incident_io_workflows_v2_update_workflow' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoWorkflowsV2UpdateWorkflow',
  'type' => 'write',
  'name' => 'UpdateWorkflow Workflows V2',
  'description' => 'UpdateWorkflow Workflows V2 Official incident.io endpoint: PUT /v2/workflows/{id} Updates a workflow',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_workflows_v2_destroy_workflow' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoWorkflowsV2DestroyWorkflow',
  'type' => 'write',
  'name' => 'DestroyWorkflow Workflows V2',
  'description' => 'DestroyWorkflow Workflows V2 Official incident.io endpoint: DELETE /v2/workflows/{id} Archives a workflow',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v3_list_entries' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3ListEntries',
  'type' => 'read',
  'name' => 'ListEntries Catalog V3',
  'description' => 'ListEntries Catalog V3 Official incident.io endpoint: GET /v3/catalog_entries List entries for a catalog type.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_catalog_v3_create_entry' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3CreateEntry',
  'type' => 'write',
  'name' => 'CreateEntry Catalog V3',
  'description' => 'CreateEntry Catalog V3 Official incident.io endpoint: POST /v3/catalog_entries Create an entry within the catalog. We support a maximum of 50,000 entries per type. If you call this API with a payload where the external_id and catalog_type_i',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v3_bulk_update_entries' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3BulkUpdateEntries',
  'type' => 'write',
  'name' => 'BulkUpdateEntries Catalog V3',
  'description' => 'BulkUpdateEntries Catalog V3 Official incident.io endpoint: POST /v3/catalog_entries/actions/bulk_update Update multiple catalog entries in a single operation. You can update up to 250 entries at once. This operation is atomic - either all ',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v3_show_entry' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3ShowEntry',
  'type' => 'read',
  'name' => 'ShowEntry Catalog V3',
  'description' => 'ShowEntry Catalog V3 Official incident.io endpoint: GET /v3/catalog_entries/{id} Show a single catalog entry.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_catalog_v3_update_entry' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3UpdateEntry',
  'type' => 'write',
  'name' => 'UpdateEntry Catalog V3',
  'description' => 'UpdateEntry Catalog V3 Official incident.io endpoint: PUT /v3/catalog_entries/{id} Updates an existing catalog entry.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v3_destroy_entry' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3DestroyEntry',
  'type' => 'write',
  'name' => 'DestroyEntry Catalog V3',
  'description' => 'DestroyEntry Catalog V3 Official incident.io endpoint: DELETE /v3/catalog_entries/{id} Archives a catalog entry.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v3_list_resources' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3ListResources',
  'type' => 'read',
  'name' => 'ListResources Catalog V3',
  'description' => 'ListResources Catalog V3 Official incident.io endpoint: GET /v3/catalog_resources List available engine resources for the catalog. A resource represents a type of data that can be held within the catalog, so this endpoint can be used to see',
  'icon' => 'ph:warning-circle',
),
  'incident_io_catalog_v3_list_types' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3ListTypes',
  'type' => 'read',
  'name' => 'ListTypes Catalog V3',
  'description' => 'ListTypes Catalog V3 Official incident.io endpoint: GET /v3/catalog_types List all catalog types for an organisation, including those synced from external resources.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_catalog_v3_create_type' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3CreateType',
  'type' => 'write',
  'name' => 'CreateType Catalog V3',
  'description' => 'CreateType Catalog V3 Official incident.io endpoint: POST /v3/catalog_types Create a catalog type. The schema must be updated using the UpdateTypeSchema endpoint.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v3_show_type' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3ShowType',
  'type' => 'read',
  'name' => 'ShowType Catalog V3',
  'description' => 'ShowType Catalog V3 Official incident.io endpoint: GET /v3/catalog_types/{id} Show a single catalog type.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_catalog_v3_update_type' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3UpdateType',
  'type' => 'write',
  'name' => 'UpdateType Catalog V3',
  'description' => 'UpdateType Catalog V3 Official incident.io endpoint: PUT /v3/catalog_types/{id} Updates an existing catalog type. The schema must be updated using the UpdateTypeSchema endpoint.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v3_destroy_type' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3DestroyType',
  'type' => 'write',
  'name' => 'DestroyType Catalog V3',
  'description' => 'DestroyType Catalog V3 Official incident.io endpoint: DELETE /v3/catalog_types/{id} Archives a catalog type and associated entries.',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_catalog_v3_update_type_schema' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoCatalogV3UpdateTypeSchema',
  'type' => 'write',
  'name' => 'UpdateTypeSchema Catalog V3',
  'description' => 'UpdateTypeSchema Catalog V3 Official incident.io endpoint: POST /v3/catalog_types/{id}/actions/update_schema Update an existing catalog types schema, adding or removing attributes. Updating the schema is handled separately from creating and',
  'icon' => 'ph:pencil-simple',
),
  'incident_io_teams_v3_list' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoTeamsV3List',
  'type' => 'read',
  'name' => 'List Teams V3',
  'description' => 'List Teams V3 Official incident.io endpoint: GET /v3/teams List all teams in the organisation.',
  'icon' => 'ph:warning-circle',
),
  'incident_io_teams_v3_show' => array (
  'class' => 'OpenCompany\\Integrations\\IncidentIo\\Tools\\IncidentIoTeamsV3Show',
  'type' => 'read',
  'name' => 'Show Teams V3',
  'description' => 'Show Teams V3 Official incident.io endpoint: GET /v3/teams/{id} Get a single team.',
  'icon' => 'ph:warning-circle',
),
]; }
    public function isIntegration(): bool { return true; } public function createTool(string $class, array $context = []): Tool { return new $class($this->resolveService($context)); } public function scriptDocsPath(): ?string { return __DIR__.'/../script-docs/incident-io.md'; }
    /** @param  array<string, mixed>  $context  Optional account context from the host. */ private function resolveService(array $context = []): IncidentIoService { $account=$context['account']??null; if($account!==null){$creds=app(CredentialResolver::class); return new IncidentIoService(apiKey:$creds->get('incident-io','api_key','',$account), baseUrl:$creds->get('incident-io','url','https://api.incident.io',$account));} return app(IncidentIoService::class); }
}
