<?php

namespace OpenCompany\Integrations\Tailscale;

use Illuminate\Support\Facades\Http;
use OpenCompany\IntegrationCore\Contracts\ConfigurableIntegration;
use OpenCompany\IntegrationCore\Contracts\CredentialResolver;
use OpenCompany\IntegrationCore\Contracts\HasIntegrationCapabilities;
use OpenCompany\IntegrationCore\Contracts\Tool;
use OpenCompany\IntegrationCore\Contracts\ToolProvider;

/**
 * Tool catalog and configuration metadata for Tailscale.
 *
 * Exposes the official Tailscale OpenAPI operation set as endpoint-specific
 * agent tools and resolves account-specific API tokens in multi-account hosts.
 */
class TailscaleToolProvider implements ToolProvider, ConfigurableIntegration, HasIntegrationCapabilities
{
    /** @return array<string, mixed> */ public function integrationCapabilities(): array { return ['auth'=>['strategy'=>'api_token','legacy_auth_type'=>'api_token','credential_mode'=>'secret','setup_flows'=>['manual_secret'],'requires_browser_for_setup'=>false,'refreshable'=>false,'token_keys'=>[],'notes'=>['Tailscale API access tokens are sent as the Basic auth username with an empty password.']],'host_availability'=>['web'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret'],'cli'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret','runtime_mode'=>'normal']],'runtime_requirements'=>[],'compatibility'=>['web_setup_supported'=>true,'web_runtime_supported'=>true,'cli_setup_supported'=>true,'cli_runtime_supported'=>true]]; }
    public function appName(): string { return 'tailscale'; } public function appMeta(): array { return ['label'=>'Tailscale','description'=>'Tailnets, devices, DNS, keys, ACL policy, logs, users, groups, posture, and webhooks','icon'=>'ph:network','logo'=>'ph:network']; }
    public function integrationMeta(): array { return ['name'=>'Tailscale','description'=>'Manage Tailscale tailnets, devices, routes, DNS settings, auth keys, policy files, logs, users, groups, posture integrations, and webhooks.','icon'=>'ph:network','logo'=>'ph:network','category'=>'productivity','badge'=>'verified','docs_url'=>'https://tailscale.com/docs/reference/tailscale-api']; }
    public function configSchema(): array { return [['key'=>'api_token','type'=>'secret','label'=>'API Token','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','placeholder'=>'https://api.tailscale.com/api/v2','default'=>'https://api.tailscale.com/api/v2']]; }
    /** @param  array<string, mixed>  $config  Credential and endpoint settings. @return array{success: bool, message?: string, error?: string} */ public function testConnection(array $config): array { $token=(string)($config['api_token']??''); $baseUrl=rtrim((string)($config['url']??'https://api.tailscale.com/api/v2'),'/'); if($token==='')return ['success'=>false,'error'=>'Tailscale API token is required.']; try{$response=Http::withHeaders(['Authorization'=>'Basic '.base64_encode($token.':'),'Accept'=>'application/json','Content-Type'=>'application/json'])->timeout(10)->get($baseUrl.'/tailnet/-/devices'); if(!$response->successful())return ['success'=>false,'error'=>'Tailscale API returned HTTP '.$response->status().'.']; return ['success'=>true,'message'=>'Connected to Tailscale at '.$baseUrl.'.'];}catch(\Throwable $e){return ['success'=>false,'error'=>$e->getMessage()];} }
    public function validationRules(): array { return ['api_token'=>'required|string','url'=>'nullable|url']; } public function credentialFields(): array { return [['key'=>'api_token','type'=>'secret','label'=>'API Token','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','required'=>false,'default'=>'https://api.tailscale.com/api/v2']]; }
    public function tools(): array { return [
  'tailscale_list_tailnet_devices' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListTailnetDevices',
  'type' => 'read',
  'name' => 'List tailnet devices',
  'description' => 'List tailnet devices Official Tailscale endpoint: GET /tailnet/{tailnet}/devices Lists the devices in a tailnet. OAuth Scope: `devices:core:read`.',
  'icon' => 'ph:network',
),
  'tailscale_batch_update_custom_device_posture_attributes' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleBatchUpdateCustomDevicePostureAttributes',
  'type' => 'write',
  'name' => 'Batch update custom device posture attributes',
  'description' => 'Batch update custom device posture attributes Official Tailscale endpoint: PATCH /tailnet/{tailnet}/device-attributes Batch updates posture attributes across devices in a tailnet. This endpoint uses [JSON Merge Patch](https://datatracker.ie',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_device' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetDevice',
  'type' => 'read',
  'name' => 'Get a device',
  'description' => 'Get a device Official Tailscale endpoint: GET /device/{deviceId} Retrieve the details for the specified device. OAuth Scope: `devices:core:read`.',
  'icon' => 'ph:network',
),
  'tailscale_delete_device' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleDeleteDevice',
  'type' => 'write',
  'name' => 'Delete a device',
  'description' => 'Delete a device Official Tailscale endpoint: DELETE /device/{deviceId} Deletes the device from its tailnet. The device must belong to the requesting user\'s tailnet. Deleting devices shared with the tailnet is not supported. OAuth Scope: `de',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_expire_device_key' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleExpireDeviceKey',
  'type' => 'write',
  'name' => 'Expire a device\'s key',
  'description' => 'Expire a device\'s key Official Tailscale endpoint: POST /device/{deviceId}/expire Mark a device\'s node key as expired. This will require the device to re-authenticate in order to connect to the tailnet. The device must belong to the request',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_list_device_routes' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListDeviceRoutes',
  'type' => 'read',
  'name' => 'List device routes',
  'description' => 'List device routes Official Tailscale endpoint: GET /device/{deviceId}/routes Retrieve the list of subnet routes that a device is advertising, as well as those that are enabled for it. Routes must be both advertised and enabled for a device',
  'icon' => 'ph:network',
),
  'tailscale_set_device_routes' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetDeviceRoutes',
  'type' => 'write',
  'name' => 'Set device routes',
  'description' => 'Set device routes Official Tailscale endpoint: POST /device/{deviceId}/routes Set a device\'s enabled subnet routes by replacing the existing list of subnet routes with the supplied parameters. [Advertised routes](/kb/1019/subnets#advertise-',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_authorize_device' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleAuthorizeDevice',
  'type' => 'write',
  'name' => 'Authorize device',
  'description' => 'Authorize device Official Tailscale endpoint: POST /device/{deviceId}/authorized This call marks a device as authorized or revokes its authorization for tailnets where device authorization is required, according to the authorized field in t',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_set_device_name' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetDeviceName',
  'type' => 'write',
  'name' => 'Set device name',
  'description' => 'Set device name Official Tailscale endpoint: POST /device/{deviceId}/name When a device is added to a tailnet, its Tailscale [device name](https://tailscale.com/kb/1098/machine-names) (also sometimes referred to as machine name) is generate',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_set_device_tags' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetDeviceTags',
  'type' => 'write',
  'name' => 'Set device tags',
  'description' => 'Set device tags Official Tailscale endpoint: POST /device/{deviceId}/tags Tags let you assign an identity to a device that is separate from human users, and use that identity as part of an ACL to restrict access. Tags are similar to role ac',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_update_device_key' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleUpdateDeviceKey',
  'type' => 'write',
  'name' => 'Update device key',
  'description' => 'Update device key Official Tailscale endpoint: POST /device/{deviceId}/key When a device is added to a tailnet, its key expiry is set according to the tailnet\'s key expiry setting. If the key is not refreshed and expires, the device can no ',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_set_device_ip' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetDeviceIp',
  'type' => 'write',
  'name' => 'Set device IPv4 address',
  'description' => 'Set device IPv4 address Official Tailscale endpoint: POST /device/{deviceId}/ip When a device is added to a tailnet, its Tailscale IPv4 address is set at random either from the CGNAT range, or a subset of the CGNAT range specified by an [ip',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_device_posture_attributes' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetDevicePostureAttributes',
  'type' => 'read',
  'name' => 'Get device posture attributes',
  'description' => 'Get device posture attributes Official Tailscale endpoint: GET /device/{deviceId}/attributes Retrieve all posture attributes for the specified device. This returns a JSON object of all the key-value pairs of posture attributes for the devic',
  'icon' => 'ph:network',
),
  'tailscale_set_custom_device_posture_attributes' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetCustomDevicePostureAttributes',
  'type' => 'write',
  'name' => 'Set custom device posture attributes',
  'description' => 'Set custom device posture attributes Official Tailscale endpoint: POST /device/{deviceId}/attributes/{attributeKey} Create or update a custom posture attribute on the specified device. User-managed attributes must be in the custom namespace',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_delete_custom_device_posture_attributes' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleDeleteCustomDevicePostureAttributes',
  'type' => 'write',
  'name' => 'Delete custom device posture attributes',
  'description' => 'Delete custom device posture attributes Official Tailscale endpoint: DELETE /device/{deviceId}/attributes/{attributeKey} Delete a posture attribute from the specified device. This is only applicable to user-managed posture attributes in the',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_list_device_invites' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListDeviceInvites',
  'type' => 'read',
  'name' => 'List device invites',
  'description' => 'List device invites Official Tailscale endpoint: GET /device/{deviceId}/device-invites List all share invites for a device. OAuth Scope: `device_invites:read`.',
  'icon' => 'ph:network',
),
  'tailscale_create_device_invites' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleCreateDeviceInvites',
  'type' => 'write',
  'name' => 'Create device invites',
  'description' => 'Create device invites Official Tailscale endpoint: POST /device/{deviceId}/device-invites Create new share invites for a device. Note that device invites cannot be created using an API access token generated from an OAuth client as the shar',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_list_user_invites' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListUserInvites',
  'type' => 'read',
  'name' => 'List user invites',
  'description' => 'List user invites Official Tailscale endpoint: GET /tailnet/{tailnet}/user-invites List all open (not yet accepted) user invites to the tailnet.',
  'icon' => 'ph:network',
),
  'tailscale_create_user_invites' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleCreateUserInvites',
  'type' => 'write',
  'name' => 'Create user invites',
  'description' => 'Create user invites Official Tailscale endpoint: POST /tailnet/{tailnet}/user-invites Create, and optionally email out, new user invites to join the tailnet. > ⓘ Only permitted for user-owned keys, because invites require an inviting user',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_user_invite' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetUserInvite',
  'type' => 'read',
  'name' => 'Get a user invite',
  'description' => 'Get a user invite Official Tailscale endpoint: GET /user-invites/{userInviteId} Retrieve a specific user invite.',
  'icon' => 'ph:network',
),
  'tailscale_delete_user_invite' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleDeleteUserInvite',
  'type' => 'write',
  'name' => 'Delete a user invite',
  'description' => 'Delete a user invite Official Tailscale endpoint: DELETE /user-invites/{userInviteId} Deletes a specific user invite. > ⓘ Only permitted for user-owned keys, because invites require an inviting user.',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_resend_user_invite' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleResendUserInvite',
  'type' => 'write',
  'name' => 'Resend a user invite',
  'description' => 'Resend a user invite Official Tailscale endpoint: POST /user-invites/{userInviteId}/resend Resend a user invite by email. You can only use this if the specified invite was originally created with an email specified. Refer to [creating user ',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_device_invite' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetDeviceInvite',
  'type' => 'read',
  'name' => 'Get a device invite',
  'description' => 'Get a device invite Official Tailscale endpoint: GET /device-invites/{deviceInviteId} Retrieve a specific device invite. OAuth Scope: `device_invites:read`.',
  'icon' => 'ph:network',
),
  'tailscale_delete_device_invite' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleDeleteDeviceInvite',
  'type' => 'write',
  'name' => 'Delete a device invite',
  'description' => 'Delete a device invite Official Tailscale endpoint: DELETE /device-invites/{deviceInviteId} Delete a specific device invite. OAuth Scope: `device_invites`.',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_resend_device_invite' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleResendDeviceInvite',
  'type' => 'write',
  'name' => 'Resend a device invite',
  'description' => 'Resend a device invite Official Tailscale endpoint: POST /device-invites/{deviceInviteId}/resend Resend a device invite by email. You can only use this if the specified invite was originally created with an email specified. Refer to [creati',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_accept_device_invite' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleAcceptDeviceInvite',
  'type' => 'write',
  'name' => 'Accept a device invite',
  'description' => 'Accept a device invite Official Tailscale endpoint: POST /device-invites/-/accept Accepts the invitation to share a device into the requesting user\'s tailnet. Note that device invites cannot be accepted using an API access token generated f',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_list_configuration_audit_logs' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListConfigurationAuditLogs',
  'type' => 'read',
  'name' => 'List configuration audit logs',
  'description' => 'List configuration audit logs Official Tailscale endpoint: GET /tailnet/{tailnet}/logging/configuration List all configuration audit logs for a tailnet. OAuth Scope: `logs:configuration:read`.',
  'icon' => 'ph:network',
),
  'tailscale_list_network_flow_logs' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListNetworkFlowLogs',
  'type' => 'read',
  'name' => 'List network flow logs',
  'description' => 'List network flow logs Official Tailscale endpoint: GET /tailnet/{tailnet}/logging/network List all network flow logs for a tailnet. OAuth Scope: `logs:network:read`.',
  'icon' => 'ph:network',
),
  'tailscale_get_log_streaming_status' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetLogStreamingStatus',
  'type' => 'read',
  'name' => 'Get log streaming status',
  'description' => 'Get log streaming status Official Tailscale endpoint: GET /tailnet/{tailnet}/logging/{logType}/stream/status Retrieve the log streaming status for the provided log type. OAuth Scope: `log_streaming:read`.',
  'icon' => 'ph:network',
),
  'tailscale_get_log_streaming_configuration' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetLogStreamingConfiguration',
  'type' => 'read',
  'name' => 'Get log streaming configuration',
  'description' => 'Get log streaming configuration Official Tailscale endpoint: GET /tailnet/{tailnet}/logging/{logType}/stream Retrieve the log streaming configuration for the provided log type. OAuth Scope: `log_streaming:read`.',
  'icon' => 'ph:network',
),
  'tailscale_set_log_streaming_configuration' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetLogStreamingConfiguration',
  'type' => 'write',
  'name' => 'Set log streaming configuration',
  'description' => 'Set log streaming configuration Official Tailscale endpoint: PUT /tailnet/{tailnet}/logging/{logType}/stream Set the log streaming configuration for the provided log type. OAuth Scope: `log_streaming`. `device_invites` and `policy_file` are',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_disable_log_streaming' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleDisableLogStreaming',
  'type' => 'write',
  'name' => 'Disable log streaming',
  'description' => 'Disable log streaming Official Tailscale endpoint: DELETE /tailnet/{tailnet}/logging/{logType}/stream Delete the log streaming configuration for the provided log type. OAuth Scope: `log_streaming`.',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_aws_external_id' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetAwsExternalId',
  'type' => 'write',
  'name' => 'Create or get AWS external id',
  'description' => 'Create or get AWS external id Official Tailscale endpoint: POST /tailnet/{tailnet}/aws-external-id Get an AWS external id to use for streaming tailnet logs to S3 using role-based authentication, creating a new one for this tailnet when nece',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_validate_aws_external_id' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleValidateAwsExternalId',
  'type' => 'write',
  'name' => 'Validate external ID integration with IAM role trust policy',
  'description' => 'Validate external ID integration with IAM role trust policy Official Tailscale endpoint: POST /tailnet/{tailnet}/aws-external-id/{id}/validate-aws-trust-policy Validate that Tailscale can assume your IAM role with (and only with) this exter',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_list_dns_nameservers' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListDnsNameservers',
  'type' => 'read',
  'name' => 'List DNS nameservers',
  'description' => 'List DNS nameservers Official Tailscale endpoint: GET /tailnet/{tailnet}/dns/nameservers Lists the global DNS nameservers for a tailnet.',
  'icon' => 'ph:network',
),
  'tailscale_set_dns_nameservers' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetDnsNameservers',
  'type' => 'write',
  'name' => 'Set DNS nameservers',
  'description' => 'Set DNS nameservers Official Tailscale endpoint: POST /tailnet/{tailnet}/dns/nameservers Replaces the list of global DNS nameservers for the given tailnet with the list supplied in the request. Note that changing the list of DNS nameservers',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_dns_preferences' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetDnsPreferences',
  'type' => 'read',
  'name' => 'Get DNS preferences',
  'description' => 'Get DNS preferences Official Tailscale endpoint: GET /tailnet/{tailnet}/dns/preferences Retrieves the DNS preferences that are currently set for the given tailnet.',
  'icon' => 'ph:network',
),
  'tailscale_set_dns_preferences' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetDnsPreferences',
  'type' => 'write',
  'name' => 'Set DNS preferences',
  'description' => 'Set DNS preferences Official Tailscale endpoint: POST /tailnet/{tailnet}/dns/preferences Set the DNS preferences for a tailnet; specifically, the MagicDNS setting. Note that MagicDNS is dependent on DNS servers. Learn about [MagicDNS](https',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_list_dns_search_paths' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListDnsSearchPaths',
  'type' => 'read',
  'name' => 'List DNS search paths',
  'description' => 'List DNS search paths Official Tailscale endpoint: GET /tailnet/{tailnet}/dns/searchpaths Retrieves the list of search paths, also referred to as *search domains*, that is currently set for the given tailnet.',
  'icon' => 'ph:network',
),
  'tailscale_set_dns_search_paths' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetDnsSearchPaths',
  'type' => 'write',
  'name' => 'Set DNS search paths',
  'description' => 'Set DNS search paths Official Tailscale endpoint: POST /tailnet/{tailnet}/dns/searchpaths Replaces the list of search paths for the given tailnet.',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_split_dns' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetSplitDns',
  'type' => 'read',
  'name' => 'Get split DNS',
  'description' => 'Get split DNS Official Tailscale endpoint: GET /tailnet/{tailnet}/dns/split-dns Retrieves the split DNS settings, which is a map from domains to lists of nameservers, that is currently set for the given tailnet.',
  'icon' => 'ph:network',
),
  'tailscale_set_split_dns' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetSplitDns',
  'type' => 'write',
  'name' => 'Set split DNS',
  'description' => 'Set split DNS Official Tailscale endpoint: PUT /tailnet/{tailnet}/dns/split-dns Replaces the split DNS settings for a given tailnet. Setting the value of a mapping to `null` clears the nameservers for that domain. Sending an empty object cl',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_update_split_dns' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleUpdateSplitDns',
  'type' => 'write',
  'name' => 'Update split DNS',
  'description' => 'Update split DNS Official Tailscale endpoint: PATCH /tailnet/{tailnet}/dns/split-dns Performs partial updates of the split DNS settings for a given tailnet. Only domains specified in the request map will be modified. Setting the value of a ',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_dns_configuration' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetDnsConfiguration',
  'type' => 'read',
  'name' => 'Get DNS configuration',
  'description' => 'Get DNS configuration Official Tailscale endpoint: GET /tailnet/{tailnet}/dns/configuration Retrieves the full DNS configuration for a tailnet, including global nameservers, split DNS routes, search paths, and MagicDNS configuration.',
  'icon' => 'ph:network',
),
  'tailscale_set_dns_configuration' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetDnsConfiguration',
  'type' => 'write',
  'name' => 'Set DNS configuration',
  'description' => 'Set DNS configuration Official Tailscale endpoint: POST /tailnet/{tailnet}/dns/configuration Replaces the DNS configuration for the given tailnet. - `nameservers` defines the global resolvers to use when `preferences.overrideLocalDNS` is tr',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_list_tailnet_keys' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListTailnetKeys',
  'type' => 'read',
  'name' => 'List tailnet keys',
  'description' => 'List tailnet keys Official Tailscale endpoint: GET /tailnet/{tailnet}/keys Returns a list of active auth keys, API access tokens and trust credentials. If the parameter {all} was not specified, the set of keys returned depends on the access',
  'icon' => 'ph:network',
),
  'tailscale_create_key' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleCreateKey',
  'type' => 'write',
  'name' => 'Create an auth key or trust credential',
  'description' => 'Create an auth key or trust credential Official Tailscale endpoint: POST /tailnet/{tailnet}/keys Creates a new [auth key](https://tailscale.com/kb/1085/), or [trust credential](https://tailscale.com/kb/1623/) in the specified tailnet. Trust',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_key' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetKey',
  'type' => 'read',
  'name' => 'Get key',
  'description' => 'Get key Official Tailscale endpoint: GET /tailnet/{tailnet}/keys/{keyId} Returns a JSON object with information about a specific api access token, OAuth client, federated identity, or auth key, such as its creation and expiration dates and ',
  'icon' => 'ph:network',
),
  'tailscale_set_key' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetKey',
  'type' => 'write',
  'name' => 'Set key',
  'description' => 'Set key Official Tailscale endpoint: PUT /tailnet/{tailnet}/keys/{keyId} Set the configuration for an existing OAuth client or federated identity. OAuth Scope: `oauth_keys` grants access to OAuth clients. OAuth Scope: `federated_keys` grant',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_delete_key' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleDeleteKey',
  'type' => 'write',
  'name' => 'Delete key',
  'description' => 'Delete key Official Tailscale endpoint: DELETE /tailnet/{tailnet}/keys/{keyId} Deletes a specific api access token or auth key. OAuth Scope: `api_access_tokens` grants access to personal API access tokens. OAuth Scope: `auth_keys` grants ac',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_policy_file' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetPolicyFile',
  'type' => 'read',
  'name' => 'Get policy file',
  'description' => 'Get policy file Official Tailscale endpoint: GET /tailnet/{tailnet}/acl Retrieves the current policy file for the given tailnet; this includes the ACL along with the rules and tests that have been defined. This method can return the policy ',
  'icon' => 'ph:network',
),
  'tailscale_set_policy_file' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSetPolicyFile',
  'type' => 'write',
  'name' => 'Set policy file',
  'description' => 'Set policy file Official Tailscale endpoint: POST /tailnet/{tailnet}/acl Sets the ACL for the given tailnet. HuJSON and JSON are both accepted inputs. An `If-Match` header can be set to avoid missed updates. On success, returns the updated ',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_preview_rule_matches' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscalePreviewRuleMatches',
  'type' => 'write',
  'name' => 'Preview rule matches',
  'description' => 'Preview rule matches Official Tailscale endpoint: POST /tailnet/{tailnet}/acl/preview When given a user or IP port to match against, returns the tailnet policy rules that apply to that resource, without saving the policy file to the server.',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_validate_and_test_policy_file' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleValidateAndTestPolicyFile',
  'type' => 'write',
  'name' => 'Validate and test policy file',
  'description' => 'Validate and test policy file Official Tailscale endpoint: POST /tailnet/{tailnet}/acl/validate This endpoint works in one of two modes, neither of which modifies your current tailnet policy file: - Run ACL tests: When the request body cont',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_posture_integrations' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetPostureIntegrations',
  'type' => 'read',
  'name' => 'List all posture integrations',
  'description' => 'List all posture integrations Official Tailscale endpoint: GET /tailnet/{tailnet}/posture/integrations List all of the posture integrations for a tailnet. OAuth Scope: `feature_settings:read`.',
  'icon' => 'ph:network',
),
  'tailscale_create_posture_integration' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleCreatePostureIntegration',
  'type' => 'write',
  'name' => 'Create a posture integration',
  'description' => 'Create a posture integration Official Tailscale endpoint: POST /tailnet/{tailnet}/posture/integrations Create a posture integration, returning the resulting [PostureIntegration](#model/postureintegration). Must include `provider` and `clien',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_posture_integration' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetPostureIntegration',
  'type' => 'read',
  'name' => 'Get a posture integration',
  'description' => 'Get a posture integration Official Tailscale endpoint: GET /posture/integrations/{id} Gets the posture integration identified by `{id}`. OAuth Scope: `feature_settings:read`.',
  'icon' => 'ph:network',
),
  'tailscale_update_posture_integration' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleUpdatePostureIntegration',
  'type' => 'write',
  'name' => 'Update a posture integration',
  'description' => 'Update a posture integration Official Tailscale endpoint: PATCH /posture/integrations/{id} Updates the posture integration identified by `{id}`. You may omit the `clientSecret` from your request to retain the previously configured `clientSe',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_delete_posture_integration' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleDeletePostureIntegration',
  'type' => 'write',
  'name' => 'Delete a posture integration',
  'description' => 'Delete a posture integration Official Tailscale endpoint: DELETE /posture/integrations/{id} Delete a specific posture integration. OAuth Scope: `feature_settings`.',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_list_users' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListUsers',
  'type' => 'read',
  'name' => 'List users',
  'description' => 'List users Official Tailscale endpoint: GET /tailnet/{tailnet}/users List all users of a tailnet. OAuth Scope: `users:read`.',
  'icon' => 'ph:network',
),
  'tailscale_get_user' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetUser',
  'type' => 'read',
  'name' => 'Get a user',
  'description' => 'Get a user Official Tailscale endpoint: GET /users/{userId} Retrieve details about the specified user. OAuth Scope: `users:read`.',
  'icon' => 'ph:network',
),
  'tailscale_update_user_role' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleUpdateUserRole',
  'type' => 'write',
  'name' => 'Update user role',
  'description' => 'Update user role Official Tailscale endpoint: POST /users/{userId}/role Update the role for the specified user. Learn more about [user roles](kb/1138/user-roles). OAuth Scope: `users`. > ⓘ User-based access tokens cannot update their own ',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_approve_user' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleApproveUser',
  'type' => 'write',
  'name' => 'Approve a user',
  'description' => 'Approve a user Official Tailscale endpoint: POST /users/{userId}/approve Approve a pending user\'s access to the tailnet. This is a no-op if user approval has not been enabled for the tailnet, or if the user is already approved. User approva',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_suspend_user' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleSuspendUser',
  'type' => 'write',
  'name' => 'Suspend a user',
  'description' => 'Suspend a user Official Tailscale endpoint: POST /users/{userId}/suspend Suspends a user from their tailnet. Learn more about [suspending users](/kb/1145/remove-team-members#suspending-users). OAuth Scope: `users`. > ⓘ User-based access t',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_restore_user' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleRestoreUser',
  'type' => 'write',
  'name' => 'Restore a user',
  'description' => 'Restore a user Official Tailscale endpoint: POST /users/{userId}/restore Restores a suspended user\'s access to their tailnet. Learn more about [restoring users](/kb/1145/remove-team-members#restoring-users). OAuth Scope: `users`. > ⓘ User',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_delete_user' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleDeleteUser',
  'type' => 'write',
  'name' => 'Delete a user',
  'description' => 'Delete a user Official Tailscale endpoint: POST /users/{userId}/delete Delete a user from their tailnet. Learn more about [deleting users](/kb/1145/remove-team-members#deleting-users). OAuth Scope: `users`. > ⓘ User-based access tokens ca',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_contacts' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetContacts',
  'type' => 'read',
  'name' => 'Get contacts',
  'description' => 'Get contacts Official Tailscale endpoint: GET /tailnet/{tailnet}/contacts Retrieve the tailnet\'s current contacts. OAuth Scope: `account_settings:read`.',
  'icon' => 'ph:network',
),
  'tailscale_update_contact' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleUpdateContact',
  'type' => 'write',
  'name' => 'Update contact',
  'description' => 'Update contact Official Tailscale endpoint: PATCH /tailnet/{tailnet}/contacts/{contactType} Update the preferences for this type of contact. If the email address has changed, the system will send a verification email to confirm the change. ',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_resend_contact_verification_email' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleResendContactVerificationEmail',
  'type' => 'write',
  'name' => 'Resend verification email',
  'description' => 'Resend verification email Official Tailscale endpoint: POST /tailnet/{tailnet}/contacts/{contactType}/resend-verification-email Resends the verification email for this contact, if and only if verification is still pending. OAuth Scope: `acc',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_list_webhooks' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListWebhooks',
  'type' => 'read',
  'name' => 'List webhooks',
  'description' => 'List webhooks Official Tailscale endpoint: GET /tailnet/{tailnet}/webhooks List all webhooks for a tailnet. OAuth Scope: `webhooks:read`.',
  'icon' => 'ph:network',
),
  'tailscale_create_webhook' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleCreateWebhook',
  'type' => 'write',
  'name' => 'Create a webhook',
  'description' => 'Create a webhook Official Tailscale endpoint: POST /tailnet/{tailnet}/webhooks Create a webhook within a tailnet. OAuth Scope: `webhooks`.',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_webhook' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetWebhook',
  'type' => 'read',
  'name' => 'Get webhook',
  'description' => 'Get webhook Official Tailscale endpoint: GET /webhooks/{endpointId} Retrieve a specific webhook. OAuth Scope: `webhooks:read`.',
  'icon' => 'ph:network',
),
  'tailscale_update_webhook' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleUpdateWebhook',
  'type' => 'write',
  'name' => 'Update webhook',
  'description' => 'Update webhook Official Tailscale endpoint: PATCH /webhooks/{endpointId} Update a specific webhook. OAuth Scope: `webhooks`.',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_delete_webhook' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleDeleteWebhook',
  'type' => 'write',
  'name' => 'Delete webhook',
  'description' => 'Delete webhook Official Tailscale endpoint: DELETE /webhooks/{endpointId} Delete a specific webhook. OAuth Scope: `webhooks`.',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_test_webhook' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleTestWebhook',
  'type' => 'write',
  'name' => 'Test a webhook',
  'description' => 'Test a webhook Official Tailscale endpoint: POST /webhooks/{endpointId}/test Test a specific webhook by sending out a test event to the endpoint URL. This endpoint queues the event which is sent out asynchronously. If your webhook is config',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_rotate_webhook_secret' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleRotateWebhookSecret',
  'type' => 'write',
  'name' => 'Rotate webhook secret',
  'description' => 'Rotate webhook secret Official Tailscale endpoint: POST /webhooks/{endpointId}/rotate Rotate and generate a new secret for a specific webhook. This secret is used for generating the `Tailscale-Webhook-Signature` header in requests sent to t',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_get_tailnet_settings' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetTailnetSettings',
  'type' => 'read',
  'name' => 'Get tailnet settings',
  'description' => 'Get tailnet settings Official Tailscale endpoint: GET /tailnet/{tailnet}/settings Retrieve the settings for a specific tailnet. OAuth Scope: `feature_settings:read` - required to view all settings except those governed by the below scopes. ',
  'icon' => 'ph:network',
),
  'tailscale_update_tailnet_settings' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleUpdateTailnetSettings',
  'type' => 'write',
  'name' => 'Update tailnet settings',
  'description' => 'Update tailnet settings Official Tailscale endpoint: PATCH /tailnet/{tailnet}/settings Update the settings for a specific tailnet. OAuth Scope: `feature_settings` - required to update all settings except those governed by the below scopes. ',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_list_services' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListServices',
  'type' => 'read',
  'name' => 'List all Services',
  'description' => 'List all Services Official Tailscale endpoint: GET /tailnet/{tailnet}/services List all Services configured for the tailnet. This includes all Services in the \"advertised\" tab of the Services page in the Tailscale admin console. OAuth Scope',
  'icon' => 'ph:network',
),
  'tailscale_get_service' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetService',
  'type' => 'read',
  'name' => 'Get a Service',
  'description' => 'Get a Service Official Tailscale endpoint: GET /tailnet/{tailnet}/services/{serviceName} Retrieve the details for the specified Service. OAuth Scope: `services:read`.',
  'icon' => 'ph:network',
),
  'tailscale_update_service' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleUpdateService',
  'type' => 'write',
  'name' => 'Update a Service',
  'description' => 'Update a Service Official Tailscale endpoint: PUT /tailnet/{tailnet}/services/{serviceName} Update or create the specified Service. If the Service does not exist, it will create a Service with the provided details. When creating a new Servi',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_delete_service' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleDeleteService',
  'type' => 'write',
  'name' => 'Delete a Service',
  'description' => 'Delete a Service Official Tailscale endpoint: DELETE /tailnet/{tailnet}/services/{serviceName} Delete the specified Service from the tailnet. OAuth Scope: `services`.',
  'icon' => 'ph:pencil-simple',
),
  'tailscale_list_service_hosts' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleListServiceHosts',
  'type' => 'read',
  'name' => 'List devices hosting a Service',
  'description' => 'List devices hosting a Service Official Tailscale endpoint: GET /tailnet/{tailnet}/services/{serviceName}/devices List all devices that are hosting the specified Service. OAuth Scope: `services`, `devices:core`.',
  'icon' => 'ph:network',
),
  'tailscale_get_service_device_approval' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleGetServiceDeviceApproval',
  'type' => 'read',
  'name' => 'Get approval status of Service on a device',
  'description' => 'Get approval status of Service on a device Official Tailscale endpoint: GET /tailnet/{tailnet}/services/{serviceName}/device/{deviceId}/approved Retrieve the approval status of the specified Service on a specific device. OAuth Scope: `servi',
  'icon' => 'ph:network',
),
  'tailscale_update_service_device_approval' => array (
  'class' => 'OpenCompany\\Integrations\\Tailscale\\Tools\\TailscaleUpdateServiceDeviceApproval',
  'type' => 'write',
  'name' => 'Update approval status of Service on a device',
  'description' => 'Update approval status of Service on a device Official Tailscale endpoint: POST /tailnet/{tailnet}/services/{serviceName}/device/{deviceId}/approved Update the approval status of the specified Service on a specific device. OAuth Scope: `ser',
  'icon' => 'ph:pencil-simple',
),
]; }
    public function isIntegration(): bool { return true; } public function createTool(string $class, array $context = []): Tool { return new $class($this->resolveService($context)); } public function scriptDocsPath(): ?string { return __DIR__.'/../script-docs/tailscale.md'; }
    /** @param  array<string, mixed>  $context  Optional account context from the host. */ private function resolveService(array $context = []): TailscaleService { $account=$context['account']??null; if($account!==null){$creds=app(CredentialResolver::class); return new TailscaleService(apiToken:$creds->get('tailscale','api_token','',$account), baseUrl:$creds->get('tailscale','url','https://api.tailscale.com/api/v2',$account));} return app(TailscaleService::class); }
}
