<?php

namespace OpenCompany\Integrations\Ramp\Tools;

/**
 * List business entities.
 *
 * Maps to the official Ramp endpoint get /developer/v1/entities.
 */
class RampGetEntityListWithPagination extends AbstractRampTool
{
    protected const NAME = 'ramp_get_entity_list_with_pagination';
    protected const DESCRIPTION = 'List business entities

Official Ramp endpoint: GET /developer/v1/entities';
    protected const PARAMETERS = array (
  'currency' =>
  array (
    'type' => 'string',
    'required' => false,
    'description' => 'Query parameter `currency` from the official Ramp API operation.',
    'enum' =>
    array (
      0 => 'AED',
      1 => 'AFN',
      2 => 'ALL',
      3 => 'AMD',
      4 => 'ANG',
      5 => 'AOA',
      6 => 'ARS',
      7 => 'AUD',
      8 => 'AWG',
      9 => 'AZN',
      10 => 'BAM',
      11 => 'BBD',
      12 => 'BDT',
      13 => 'BGN',
      14 => 'BHD',
      15 => 'BIF',
      16 => 'BMD',
      17 => 'BND',
      18 => 'BOB',
      19 => 'BOV',
      20 => 'BRL',
      21 => 'BSD',
      22 => 'BTN',
      23 => 'BWP',
      24 => 'BYN',
      25 => 'BZD',
      26 => 'CAD',
      27 => 'CDF',
      28 => 'CHE',
      29 => 'CHF',
      30 => 'CHW',
      31 => 'CLF',
      32 => 'CLP',
      33 => 'CNH',
      34 => 'CNY',
      35 => 'COP',
      36 => 'COU',
      37 => 'CRC',
      38 => 'CUC',
      39 => 'CUP',
      40 => 'CVE',
      41 => 'CZK',
      42 => 'DJF',
      43 => 'DKK',
      44 => 'DOP',
      45 => 'DZD',
      46 => 'EGP',
      47 => 'ERN',
      48 => 'ETB',
      49 => 'EUR',
      50 => 'EURC',
      51 => 'FJD',
      52 => 'FKP',
      53 => 'GBP',
      54 => 'GEL',
      55 => 'GHS',
      56 => 'GIP',
      57 => 'GMD',
      58 => 'GNF',
      59 => 'GTQ',
      60 => 'GYD',
      61 => 'HKD',
      62 => 'HNL',
      63 => 'HRK',
      64 => 'HTG',
      65 => 'HUF',
      66 => 'IDR',
      67 => 'ILS',
      68 => 'INR',
      69 => 'IQD',
      70 => 'IRR',
      71 => 'ISK',
      72 => 'JMD',
      73 => 'JOD',
      74 => 'JPY',
      75 => 'KES',
      76 => 'KGS',
      77 => 'KHR',
      78 => 'KMF',
      79 => 'KPW',
      80 => 'KRW',
      81 => 'KWD',
      82 => 'KYD',
      83 => 'KZT',
      84 => 'LAK',
      85 => 'LBP',
      86 => 'LKR',
      87 => 'LRD',
      88 => 'LSL',
      89 => 'LYD',
      90 => 'MAD',
      91 => 'MDL',
      92 => 'MGA',
      93 => 'MKD',
      94 => 'MMK',
      95 => 'MNT',
      96 => 'MOP',
      97 => 'MRU',
      98 => 'MUR',
      99 => 'MVR',
      100 => 'MWK',
      101 => 'MXN',
      102 => 'MXV',
      103 => 'MYR',
      104 => 'MZN',
      105 => 'NAD',
      106 => 'NGN',
      107 => 'NIO',
      108 => 'NOK',
      109 => 'NPR',
      110 => 'NZD',
      111 => 'OMR',
      112 => 'PAB',
      113 => 'PEN',
      114 => 'PGK',
      115 => 'PHP',
      116 => 'PKR',
      117 => 'PLN',
      118 => 'PYG',
      119 => 'QAR',
      120 => 'RON',
      121 => 'RSD',
      122 => 'RUB',
      123 => 'RWF',
      124 => 'SAR',
      125 => 'SBD',
      126 => 'SCR',
      127 => 'SDG',
      128 => 'SEK',
      129 => 'SGD',
      130 => 'SHP',
      131 => 'SLE',
      132 => 'SLL',
      133 => 'SOS',
      134 => 'SRD',
      135 => 'SSP',
      136 => 'STN',
      137 => 'SVC',
      138 => 'SYP',
      139 => 'SZL',
      140 => 'THB',
      141 => 'TJS',
      142 => 'TMT',
      143 => 'TND',
      144 => 'TOP',
      145 => 'TRY',
      146 => 'TTD',
      147 => 'TWD',
      148 => 'TZS',
      149 => 'UAH',
      150 => 'UGX',
      151 => 'USD',
      152 => 'USDB',
      153 => 'USDC',
      154 => 'USDT',
      155 => 'USN',
      156 => 'UYI',
      157 => 'UYU',
      158 => 'UYW',
      159 => 'UZS',
      160 => 'VED',
      161 => 'VES',
      162 => 'VND',
      163 => 'VUV',
      164 => 'WST',
      165 => 'XAD',
      166 => 'XAF',
      167 => 'XAG',
      168 => 'XAU',
      169 => 'XBA',
      170 => 'XBB',
      171 => 'XBC',
      172 => 'XBD',
      173 => 'XCD',
      174 => 'XCG',
      175 => 'XDR',
      176 => 'XOF',
      177 => 'XPD',
      178 => 'XPF',
      179 => 'XPT',
      180 => 'XSU',
      181 => 'XTS',
      182 => 'XUA',
      183 => 'XXX',
      184 => 'YER',
      185 => 'ZAR',
      186 => 'ZMW',
      187 => 'ZWG',
      188 => 'ZWL',
    ),
  ),
  'entity_name' =>
  array (
    'type' => 'string',
    'required' => false,
    'description' => 'Query parameter `entity_name` from the official Ramp API operation.',
  ),
  'is_primary' =>
  array (
    'type' => 'boolean',
    'required' => false,
    'description' => 'Query parameter `is_primary` from the official Ramp API operation.',
  ),
  'hide_inactive' =>
  array (
    'type' => 'boolean',
    'required' => false,
    'description' => 'Query parameter `hide_inactive` from the official Ramp API operation.',
  ),
  'start' =>
  array (
    'type' => 'string',
    'required' => false,
    'description' => 'Query parameter `start` from the official Ramp API operation.',
  ),
  'page_size' =>
  array (
    'type' => 'integer',
    'required' => false,
    'description' => 'Query parameter `page_size` from the official Ramp API operation.',
  ),
  'include_deleted_accounts' =>
  array (
    'type' => 'string',
    'required' => false,
    'description' => 'Query parameter `include_deleted_accounts` from the official Ramp API operation.',
  ),
);
    protected const METHOD = 'get';
    protected const PATH = '/developer/v1/entities';
    protected const PATH_PARAMS = array (
);
    protected const QUERY_PARAMS = array (
  'currency' => 'currency',
  'entity_name' => 'entity_name',
  'is_primary' => 'is_primary',
  'hide_inactive' => 'hide_inactive',
  'start' => 'start',
  'page_size' => 'page_size',
  'include_deleted_accounts' => 'include_deleted_accounts',
);
    protected const HEADER_PARAMS = array (
);
    protected const BODY_REQUIRED = false;
}
