<?php

declare(strict_types=1);

namespace OpenCompany\Integrations\Tests\ModernTreasury;

use Illuminate\Http\Client\Factory as HttpFactory;
use Illuminate\Http\Client\Request;
use Illuminate\Support\Facades\Http;
use OpenCompany\IntegrationCore\Contracts\CredentialResolver;
use OpenCompany\IntegrationCore\Support\ToolProviderRegistry;
use OpenCompany\Integrations\ModernTreasury\ModernTreasuryService;
use OpenCompany\Integrations\ModernTreasury\ModernTreasuryServiceProvider;
use OpenCompany\Integrations\ModernTreasury\ModernTreasuryToolProvider;
use OpenCompany\Integrations\ModernTreasury\Tools\ModernTreasuryCreateLedgerAccount;
use OpenCompany\Integrations\ModernTreasury\Tools\ModernTreasuryGetLedgerAccount;
use OpenCompany\Integrations\ModernTreasury\Tools\ModernTreasuryListLedgerAccounts;
use PHPUnit\Framework\TestCase;

final class ModernTreasuryServiceTest extends TestCase
{
    protected function setUp(): void { parent::setUp(); Http::swap(new HttpFactory); app()->forgetInstance(ModernTreasuryService::class); app()->forgetInstance(CredentialResolver::class); app()->forgetInstance(ToolProviderRegistry::class); }
    protected function tearDown(): void { Http::preventStrayRequests(false); Http::swap(new HttpFactory); app()->forgetInstance(ModernTreasuryService::class); app()->forgetInstance(CredentialResolver::class); app()->forgetInstance(ToolProviderRegistry::class); parent::tearDown(); }
    public function test_provider_matches_openapi_manifest_and_docs(): void { $provider=new ModernTreasuryToolProvider; $manifest=json_decode((string)file_get_contents(__DIR__.'/../../packages/modern-treasury/modern-treasury-openapi-manifest.json'),true); self::assertSame(177,$manifest['method_count']); self::assertCount($manifest['method_count'],$provider->tools()); self::assertSame('modern-treasury',$provider->appName()); self::assertSame('Modern Treasury',$provider->integrationMeta()['name']); self::assertSame('data',$provider->integrationMeta()['category']); self::assertSame('basic',$provider->integrationCapabilities()['auth']['strategy']); self::assertContains('organization_id',$provider->integrationCapabilities()['auth']['token_keys']); self::assertContains('api_key',$provider->integrationCapabilities()['auth']['token_keys']); self::assertCount(2,$provider->credentialFields()); self::assertCount(3,$provider->configSchema()); self::assertFileExists((string)$provider->scriptDocsPath()); self::assertContains('modern_treasury_list_ledger_accounts',array_keys($provider->tools())); self::assertContains('modern_treasury_create_payment_order',array_keys($provider->tools())); }
    public function test_service_maps_basic_auth_path_query_headers_and_body(): void { Http::fake(['*'=>Http::response(['ok'=>true],200)]); $service=new ModernTreasuryService('org-test','key-test','https://mt.example.test'); $service->request('GET','/api/ledger_accounts/{id}',['id'=>'ledger 1'],['per_page'=>10]); $service->request('POST','/api/ledger_accounts',[],[],['Idempotency-Key'=>'idem-1'],['name'=>'Cash']); Http::assertSent(static fn(Request $request): bool => $request->method()==='GET' && $request->url()==='https://mt.example.test/api/ledger_accounts/ledger%201?per_page=10' && $request->hasHeader('Authorization','Basic '.base64_encode('org-test:key-test'))); Http::assertSent(static fn(Request $request): bool => $request->method()==='POST' && $request->url()==='https://mt.example.test/api/ledger_accounts' && $request->hasHeader('Idempotency-Key','idem-1') && $request['name']==='Cash'); }
    public function test_tools_validate_and_map_parameters(): void { Http::fake(['*'=>Http::response(['ok'=>true],200)]); $service=new ModernTreasuryService('org-test','key-test'); $list=(new ModernTreasuryListLedgerAccounts($service))->execute(['per_page'=>10]); self::assertTrue($list->succeeded()); Http::assertSent(static fn(Request $request): bool => $request->url()==='https://app.moderntreasury.com/api/ledger_accounts?per_page=10'); $missingPath=(new ModernTreasuryGetLedgerAccount($service))->execute([]); self::assertFalse($missingPath->succeeded()); self::assertStringContainsString('id must be',(string)$missingPath->error); $created=(new ModernTreasuryCreateLedgerAccount($service))->execute(['idempotency_key'=>'idem-1','body'=>['name'=>'Cash']]); self::assertTrue($created->succeeded()); Http::assertSent(static fn(Request $request): bool => $request->hasHeader('Idempotency-Key','idem-1') && $request['name']==='Cash'); }
    public function test_connection_multi_account_and_service_provider_registration(): void { Http::fake(['mt.example.test/api/api_keys/current'=>Http::response(['id'=>'api_key_123'],200)]); $connection=(new ModernTreasuryToolProvider)->testConnection(['organization_id'=>'org-test','api_key'=>'key-test','url'=>'https://mt.example.test']); self::assertTrue($connection['success']); Http::assertSent(static fn(Request $request): bool => $request->method()==='GET' && $request->url()==='https://mt.example.test/api/api_keys/current' && $request->hasHeader('Authorization','Basic '.base64_encode('org-test:key-test')));

        Http::swap(new HttpFactory); Http::fake(['*'=>Http::response(['ok'=>true],200)]); app()->instance(CredentialResolver::class, new class implements CredentialResolver { public function get(string $integration,string $key,mixed $default=null,?string $account=null): mixed { if ($integration === 'modern-treasury') return ''; return match([$integration,$key,$account]) { ['modern_treasury','organization_id','merchant']=>'account-org', ['modern_treasury','api_key','merchant']=>'account-key', ['modern_treasury','url','merchant']=>'https://account-mt.example.test', default=>$default }; } public function isConfigured(string $integration, ?string $account=null): bool { return $integration==='modern_treasury' && $account==='merchant'; } public function getAccounts(string $integration): array { return $integration==='modern_treasury' ? ['merchant'] : []; } }); $tool=(new ModernTreasuryToolProvider)->createTool(ModernTreasuryListLedgerAccounts::class,['account'=>'merchant']); self::assertTrue($tool->execute(['per_page'=>3])->succeeded()); Http::assertSent(static fn(Request $request): bool => $request->url()==='https://account-mt.example.test/api/ledger_accounts?per_page=3' && $request->hasHeader('Authorization','Basic '.base64_encode('account-org:account-key')));

        $registry=new ToolProviderRegistry; app()->instance(ToolProviderRegistry::class,$registry); (new ModernTreasuryServiceProvider(app()))->boot(); self::assertTrue($registry->has('modern-treasury')); self::assertInstanceOf(ModernTreasuryToolProvider::class,$registry->get('modern-treasury')); }
}
