<?php

namespace OpenCompany\Integrations\SmartRecruiters\Tools;

/**
 * Search jobs.
 *
 * Maps to jobs-api.json endpoint GET /jobs.
 */
class SmartRecruitersJobsJobsAll extends AbstractSmartRecruitersTool
{
    protected const NAME = "smartrecruiters_jobs_jobs_all";
    protected const DESCRIPTION = "Search jobs\n\nOfficial SmartRecruiters endpoint: GET /jobs from jobs-api.json.";
    protected const PARAMETERS = [
        "accept_language" => [
            "type" => "string",
            "enum" => [
                "af",
                "am",
                "ar",
                "hy",
                "az",
                "eu",
                "bn",
                "bg",
                "ca",
                "zh-CN",
                "zh-TW",
                "hr",
                "cs",
                "da",
                "nl",
                "en-GB",
                "en",
                "et",
                "fi",
                "fr",
                "fr-CA",
                "gl",
                "ka",
                "de",
                "el",
                "gu",
                "iw",
                "hi",
                "hu",
                "is",
                "id",
                "ga",
                "it",
                "ja",
                "kn",
                "km",
                "ko",
                "lo",
                "lv",
                "lt",
                "ms",
                "ml",
                "mr",
                "mn",
                "ne",
                "no",
                "fa",
                "fil",
                "pl",
                "pt",
                "pt-BR",
                "pt-PT",
                "ro",
                "ru",
                "sr",
                "si",
                "sk",
                "sl",
                "es",
                "es-MX",
                "sw",
                "sv",
                "ta",
                "te",
                "tr",
                "uk",
                "ur",
                "vi",
                "cy",
                "zu",
            ],
            "required" => false,
            "description" => "language of returned content",
        ],
        "q" => [
            "type" => "string",
            "required" => false,
            "description" => "full-text search query based on a job title; case insensitive; e.g. java developer",
        ],
        "limit" => [
            "type" => "integer",
            "required" => false,
            "description" => "number of elements to return. max value is 100",
        ],
        "offset" => [
            "type" => "integer",
            "required" => false,
            "description" => "number of elements to skip while processing result; this method of paging is very slow and is deprecated, please use pageId instead",
        ],
        "page_id" => [
            "type" => "string",
            "required" => false,
            "description" => "unique identifier for next page of jobs - returned as nextPageId in previous page result. You must set job_id value for sort parameter if you use pageId.",
        ],
        "sort" => [
            "type" => "string",
            "enum" => [
                "default",
                "job_id",
            ],
            "required" => false,
            "description" => "Order in which results are returned. - default - sorts results by creation date or by match score and creation date if query (q) is set. Can't be used with pageId parameter (request might not return all results) - job_id - sorts results by job id. The only supported sorting order when using pageId based pagination.",
        ],
        "city" => [
            "type" => "array",
            "items" => [
                "type" => "string",
            ],
            "required" => false,
            "description" => "city filter (part of the location object); can be used repeatedly; case sensitive; e.g. San Francisco",
        ],
        "department" => [
            "type" => "array",
            "items" => [
                "type" => "string",
            ],
            "required" => false,
            "description" => "department filter (by department label); can be used repeatedly; case sensitive; e.g. Marketing",
        ],
        "updated_after" => [
            "type" => "string",
            "required" => false,
            "description" => "ISO8601-formatted time boundaries for the job update time, Format: yyyy-MM-ddTHH:mm:ss.SSSZZ",
        ],
        "last_activity_after" => [
            "type" => "string",
            "required" => false,
            "description" => "ISO8601-formatted time boundaries for the job lastActivityOn time, Format: yyyy-MM-ddTHH:mm:ss.SSSZZ. lastActivityOn is updated when job is edited, new candidates apply or job is published.",
        ],
        "language" => [
            "type" => "string",
            "enum" => [
                "af",
                "am",
                "ar",
                "az",
                "bg",
                "bn",
                "ca",
                "cs",
                "cy",
                "da",
                "de",
                "el",
                "en",
                "en-GB",
                "es",
                "es-MX",
                "et",
                "eu",
                "fa",
                "fi",
                "fil",
                "fr",
                "fr-CA",
                "ga",
                "gl",
                "gu",
                "he",
                "hi",
                "hr",
                "hu",
                "hy",
                "id",
                "is",
                "it",
                "ja",
                "ka",
                "km",
                "kn",
                "ko",
                "lo",
                "lt",
                "lv",
                "ml",
                "mn",
                "mr",
                "ms",
                "ne",
                "nl",
                "no",
                "pl",
                "pt",
                "pt-BR",
                "ro",
                "ru",
                "si",
                "sk",
                "sl",
                "sr",
                "sv",
                "sw",
                "ta",
                "te",
                "tr",
                "uk",
                "ur",
                "vi",
                "zh-CN",
                "zh-TW",
                "zu",
            ],
            "required" => false,
            "description" => "Exceptions to the language code ISO format: * \"en-GB\" - \"English - English (UK)\" * \"es-MX\" - \"Spanish - espaol (Mxico)\" * \"fr-CA\" - \"French - franais (Canada)\" * \"pt-BR\" - \"Portugal - portugus (Brasil)\" * \"zh-TW\" - \"Chinese (Traditional) - ()\" * \"zh-CN\" - \"Chinese (Simplified) - ()\" Value \"pt-PT\" is deprecated and will not work, use \"pt\" instead.",
        ],
        "status" => [
            "type" => "string",
            "enum" => [
                "CREATED",
                "SOURCING",
                "FILLED",
                "INTERVIEW",
                "OFFER",
                "CANCELLED",
                "ON_HOLD",
            ],
            "required" => false,
            "description" => "Status of a job. Deprecated - cannot be used repeatedly. To filter by multiple status, use \"statuses\".",
        ],
        "statuses" => [
            "type" => "array",
            "items" => [
                "type" => "string",
                "enum" => [
                    "CREATED",
                    "SOURCING",
                    "FILLED",
                    "INTERVIEW",
                    "OFFER",
                    "CANCELLED",
                    "ON_HOLD",
                ],
            ],
            "required" => false,
            "description" => "Job status filter, can be used repeatedly. When present, overrides \"status\".",
        ],
        "posting_status" => [
            "type" => "string",
            "enum" => [
                "PUBLIC",
                "INTERNAL",
                "NOT_PUBLISHED",
                "PRIVATE",
            ],
            "required" => false,
            "description" => "Posting status of a job",
        ],
        "hiring_team_member_id" => [
            "type" => "array",
            "items" => [
                "type" => "string",
            ],
            "required" => false,
            "description" => "Filter jobs to those where any of the given users is a member of the job's hiring team. Values are user identifiers.",
        ],
    ];
    protected const METHOD = "GET";
    protected const BASE_URL = "https://api.smartrecruiters.com";
    protected const PATH = "/jobs";
    protected const PATH_PARAMS = [];
    protected const QUERY_PARAMS = [
        "q" => "q",
        "limit" => "limit",
        "offset" => "offset",
        "pageId" => "page_id",
        "sort" => "sort",
        "city" => "city",
        "department" => "department",
        "updatedAfter" => "updated_after",
        "lastActivityAfter" => "last_activity_after",
        "language" => "language",
        "status" => "status",
        "statuses" => "statuses",
        "postingStatus" => "posting_status",
        "hiringTeamMemberId" => "hiring_team_member_id",
    ];
    protected const HEADER_PARAMS = [
        "Accept-Language" => "accept_language",
    ];
    protected const QUERY_STYLES = [];
    protected const BODY_REQUIRED = false;
    protected const BODY_MODE = "json";
    protected const AUTH_MODE = "either";
}
