<?php

namespace OpenCompany\Integrations\SmartRecruiters\Tools;

/**
 * Lists active postings published by given company.
 *
 * Maps to posting-api.json endpoint GET /v1/companies/{companyIdentifier}/postings.
 */
class SmartRecruitersPostingV1ListPostings extends AbstractSmartRecruitersTool
{
    protected const NAME = "smartrecruiters_posting_v1_list_postings";
    protected const DESCRIPTION = "Lists active postings published by given company\n\nOfficial SmartRecruiters endpoint: GET /v1/companies/{companyIdentifier}/postings from posting-api.json.";
    protected const PARAMETERS = [
        "accept_language" => [
            "type" => "string",
            "enum" => [
                "af",
                "am",
                "ar",
                "az",
                "bg",
                "bn",
                "ca",
                "cs",
                "cy",
                "da",
                "de",
                "el",
                "en",
                "en-GB",
                "es",
                "es-MX",
                "et",
                "eu",
                "fa",
                "fi",
                "fil",
                "fr",
                "fr-CA",
                "ga",
                "gl",
                "gu",
                "he",
                "hi",
                "hr",
                "hu",
                "hy",
                "id",
                "is",
                "it",
                "ja",
                "ka",
                "km",
                "kn",
                "ko",
                "lo",
                "lt",
                "lv",
                "ml",
                "mn",
                "mr",
                "ms",
                "ne",
                "nl",
                "no",
                "pl",
                "pt",
                "pt-BR",
                "ro",
                "ru",
                "si",
                "sk",
                "sl",
                "sr",
                "sv",
                "sw",
                "ta",
                "te",
                "tr",
                "uk",
                "ur",
                "vi",
                "zh-CN",
                "zh-TW",
                "zu",
            ],
            "required" => false,
            "description" => "Language of translation",
        ],
        "company_identifier" => [
            "type" => "string",
            "required" => true,
            "description" => "Identifier of a company",
        ],
        "q" => [
            "type" => "string",
            "required" => false,
            "description" => "full-text search query based on a job title, location",
        ],
        "limit" => [
            "type" => "integer",
            "required" => false,
            "description" => "number of elements to return. max value is 100",
        ],
        "offset" => [
            "type" => "integer",
            "required" => false,
            "description" => "number of elements to skip while processing result",
        ],
        "destination" => [
            "type" => "string",
            "enum" => [
                "PUBLIC",
                "INTERNAL",
                "INTERNAL_OR_PUBLIC",
            ],
            "required" => false,
            "description" => "Filter indicating which postings to return: * **PUBLIC**: response will include ONLY public postings * **INTERNAL**: response will include ONLY internal postings * **INTERNAL_OR_PUBLIC**: response will include internal postings or public postings, but not both for a single job. If a job has both types of postings, only internal postings will be returned. NOTE: when selected, all postings, internal and public, will be treated as internal. Among other things, this means that screening questions will not be displayed, and candidates will be marked with the EMPLOYEE label.",
        ],
        "location_type" => [
            "type" => "array",
            "items" => [
                "type" => "string",
                "enum" => [
                    "REMOTE",
                    "HYBRID",
                    "ONSITE",
                    "ANY",
                ],
            ],
            "required" => false,
            "description" => "Filter indicating which postings to return: * **REMOTE**: response will include ONLY postings with remote location type * **HYBRID**: response will include ONLY postings with hybrid location type * **ONSITE**: response will include ONLY postings with onsite location type * **ANY**: response will include ANY location type",
        ],
        "country" => [
            "type" => "string",
            "required" => false,
            "description" => "country code filter (part of the location object)",
        ],
        "region" => [
            "type" => "string",
            "required" => false,
            "description" => "region filter (part of the location object)",
        ],
        "city" => [
            "type" => "string",
            "required" => false,
            "description" => "city filter (part of the location object)",
        ],
        "department" => [
            "type" => "string",
            "required" => false,
            "description" => "department filter (department id)",
        ],
        "job_ad_id" => [
            "type" => "string",
            "required" => false,
            "description" => "job ad id filter",
        ],
        "language" => [
            "type" => "array",
            "items" => [
                "type" => "string",
                "enum" => [
                    "af",
                    "am",
                    "ar",
                    "az",
                    "bg",
                    "bn",
                    "ca",
                    "cs",
                    "cy",
                    "da",
                    "de",
                    "el",
                    "en",
                    "en-GB",
                    "es",
                    "es-MX",
                    "et",
                    "eu",
                    "fa",
                    "fi",
                    "fil",
                    "fr",
                    "fr-CA",
                    "ga",
                    "gl",
                    "gu",
                    "he",
                    "hi",
                    "hr",
                    "hu",
                    "hy",
                    "id",
                    "is",
                    "it",
                    "ja",
                    "ka",
                    "km",
                    "kn",
                    "ko",
                    "lo",
                    "lt",
                    "lv",
                    "ml",
                    "mn",
                    "mr",
                    "ms",
                    "ne",
                    "nl",
                    "no",
                    "pl",
                    "pt",
                    "pt-BR",
                    "ro",
                    "ru",
                    "si",
                    "sk",
                    "sl",
                    "sr",
                    "sv",
                    "sw",
                    "ta",
                    "te",
                    "tr",
                    "uk",
                    "ur",
                    "vi",
                    "zh-CN",
                    "zh-TW",
                    "zu",
                ],
            ],
            "required" => false,
            "description" => "Job ad language; accepts 2-letter ISO 639-1 language code; multiple codes can be provided, separated by comma (\",\") Exceptions to the language code ISO format: * \"en-GB\" - \"English - English (UK)\" * \"fr-CA\" - \"French - franais (Canada)\" * \"pt-BR\" - \"Portugal - portugus (Brasil)\" * \"pt-PT\" - \"Portugal - portugus (Portugal)\" * \"zh-TW\" - \"Chinese (Traditional) - ()\" * \"zh-CN\" - \"Chinese (Simplified) - ()\"",
        ],
        "released_after" => [
            "type" => "string",
            "required" => false,
            "description" => "Released after filter (ISO8601-formatted) Format: yyyy-MM-ddTHH:mm:ss.SSSZZ",
        ],
        "custom_field" => [
            "type" => "object",
            "required" => false,
            "description" => "Filters postings by custom fields. Multiple custom field values can be provided, separated by comma (\",\"). Format: custom_field.CUSTOM_FIELD_ID=CUSTOM_FIELD_VALUE1_ID,CUSTOM_FIELD_VALUE2_ID",
        ],
    ];
    protected const METHOD = "GET";
    protected const BASE_URL = "https://api.smartrecruiters.com";
    protected const PATH = "/v1/companies/{companyIdentifier}/postings";
    protected const PATH_PARAMS = [
        "companyIdentifier" => "company_identifier",
    ];
    protected const QUERY_PARAMS = [
        "q" => "q",
        "limit" => "limit",
        "offset" => "offset",
        "destination" => "destination",
        "locationType" => "location_type",
        "country" => "country",
        "region" => "region",
        "city" => "city",
        "department" => "department",
        "jobAdId" => "job_ad_id",
        "language" => "language",
        "releasedAfter" => "released_after",
        "customField" => "custom_field",
    ];
    protected const HEADER_PARAMS = [
        "accept-language" => "accept_language",
    ];
    protected const QUERY_STYLES = [];
    protected const BODY_REQUIRED = false;
    protected const BODY_MODE = "json";
    protected const AUTH_MODE = "public";
}
