<?php

namespace OpenCompany\Integrations\Wildix;

/**
 * Official Wildix WMS/PBX API operation metadata.
 *
 * Source: https://www.npmjs.com/package/@wildix/wms-api-client
 */
class WildixOperations
{
    /**
     * Return all supported Wildix WMS/PBX API operations.
     *
     * @return list<array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            [
                'operation' => 'call_control_answer',
                'slug' => 'wildix_call_control_answer',
                'class' => 'WildixCallControlAnswer',
                'method' => 'POST',
                'path' => '/api/v2/call-control/answer',
                'name' => 'Call Control Answer',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CallControlAnswerCommand`.

Official Wildix SDK endpoint: POST /api/v2/call-control/answer. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'user',
                        'param' => 'user',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `user`.',
                    ],
                    [
                        'name' => 'device',
                        'param' => 'device',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Can specify the device to answer the call on. If not specified, the default device for the user will be used.',
                    ],
                    [
                        'name' => 'sipCallId',
                        'param' => 'sip_call_id',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Call identifier. For makecall action it is not required, for other actions it is required.',
                    ],
                ],
            ],
            [
                'operation' => 'call_control_attendant_transfer',
                'slug' => 'wildix_call_control_attendant_transfer',
                'class' => 'WildixCallControlAttendantTransfer',
                'method' => 'POST',
                'path' => '/api/v2/call-control/attendant-transfer',
                'name' => 'Call Control Attendant Transfer',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CallControlAttendantTransferCommand`.

Official Wildix SDK endpoint: POST /api/v2/call-control/attendant-transfer. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'user',
                        'param' => 'user',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `user`.',
                    ],
                    [
                        'name' => 'destination',
                        'param' => 'destination',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The destination for a call control operation. This can be a phone number, extension, or another valid identifier.',
                    ],
                    [
                        'name' => 'sipCallId',
                        'param' => 'sip_call_id',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Call identifier. For makecall action it is not required, for other actions it is required.',
                    ],
                ],
            ],
            [
                'operation' => 'call_control_blind_transfer',
                'slug' => 'wildix_call_control_blind_transfer',
                'class' => 'WildixCallControlBlindTransfer',
                'method' => 'POST',
                'path' => '/api/v2/call-control/blind-transfer',
                'name' => 'Call Control Blind Transfer',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CallControlBlindTransferCommand`.

Official Wildix SDK endpoint: POST /api/v2/call-control/blind-transfer. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'user',
                        'param' => 'user',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `user`.',
                    ],
                    [
                        'name' => 'destination',
                        'param' => 'destination',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The destination for a call control operation. This can be a phone number, extension, or another valid identifier.',
                    ],
                    [
                        'name' => 'sipCallId',
                        'param' => 'sip_call_id',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Call identifier. For makecall action it is not required, for other actions it is required.',
                    ],
                ],
            ],
            [
                'operation' => 'call_control_dtmf',
                'slug' => 'wildix_call_control_dtmf',
                'class' => 'WildixCallControlDTMF',
                'method' => 'POST',
                'path' => '/api/v2/call-control/dtmf',
                'name' => 'Call Control DTMF',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CallControlDtmfCommand`.

Official Wildix SDK endpoint: POST /api/v2/call-control/dtmf. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'user',
                        'param' => 'user',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `user`.',
                    ],
                    [
                        'name' => 'digits',
                        'param' => 'digits',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'DTMF digits. Allowed characters: 0-9, , #',
                    ],
                    [
                        'name' => 'sipCallId',
                        'param' => 'sip_call_id',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Call identifier. For makecall action it is not required, for other actions it is required.',
                    ],
                ],
            ],
            [
                'operation' => 'call_control_hangup',
                'slug' => 'wildix_call_control_hangup',
                'class' => 'WildixCallControlHangup',
                'method' => 'POST',
                'path' => '/api/v2/call-control/hangup',
                'name' => 'Call Control Hangup',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CallControlHangupCommand`.

Official Wildix SDK endpoint: POST /api/v2/call-control/hangup. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'user',
                        'param' => 'user',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `user`.',
                    ],
                    [
                        'name' => 'reason',
                        'param' => 'reason',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Optional reason for the hangup. This can provide additional context for the action taken.',
                    ],
                    [
                        'name' => 'sipCallId',
                        'param' => 'sip_call_id',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Call identifier. For makecall action it is not required, for other actions it is required.',
                    ],
                ],
            ],
            [
                'operation' => 'call_control_hold',
                'slug' => 'wildix_call_control_hold',
                'class' => 'WildixCallControlHold',
                'method' => 'POST',
                'path' => '/api/v2/call-control/hold',
                'name' => 'Call Control Hold',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CallControlHoldCommand`.

Official Wildix SDK endpoint: POST /api/v2/call-control/hold. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'user',
                        'param' => 'user',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `user`.',
                    ],
                    [
                        'name' => 'sipCallId',
                        'param' => 'sip_call_id',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Call identifier. For makecall action it is not required, for other actions it is required.',
                    ],
                ],
            ],
            [
                'operation' => 'call_control_make_call',
                'slug' => 'wildix_call_control_make_call',
                'class' => 'WildixCallControlMakeCall',
                'method' => 'POST',
                'path' => '/api/v2/call-control/make-call',
                'name' => 'Call Control Make Call',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CallControlMakeCallCommand`.

Official Wildix SDK endpoint: POST /api/v2/call-control/make-call. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'user',
                        'param' => 'user',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `user`.',
                    ],
                    [
                        'name' => 'destination',
                        'param' => 'destination',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The destination for a call control operation. This can be a phone number, extension, or another valid identifier.',
                    ],
                    [
                        'name' => 'device',
                        'param' => 'device',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Can specify the device to answer the call on. If not specified, the default device for the user will be used.',
                    ],
                ],
            ],
            [
                'operation' => 'call_control_unhold',
                'slug' => 'wildix_call_control_unhold',
                'class' => 'WildixCallControlUnhold',
                'method' => 'POST',
                'path' => '/api/v2/call-control/unhold',
                'name' => 'Call Control Unhold',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CallControlUnholdCommand`.

Official Wildix SDK endpoint: POST /api/v2/call-control/unhold. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'user',
                        'param' => 'user',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `user`.',
                    ],
                    [
                        'name' => 'sipCallId',
                        'param' => 'sip_call_id',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Call identifier. For makecall action it is not required, for other actions it is required.',
                    ],
                ],
            ],
            [
                'operation' => 'call_control_update_contact_info',
                'slug' => 'wildix_call_control_update_contact_info',
                'class' => 'WildixCallControlUpdateContactInfo',
                'method' => 'POST',
                'path' => '/api/v2/call-control/update-contact-info',
                'name' => 'Call Control Update Contact Info',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CallControlUpdateContactInfoCommand`.

Official Wildix SDK endpoint: POST /api/v2/call-control/update-contact-info. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'user',
                        'param' => 'user',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `user`.',
                    ],
                    [
                        'name' => 'name',
                        'param' => 'name',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Contact name',
                    ],
                    [
                        'name' => 'phone',
                        'param' => 'phone',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Phone number',
                    ],
                    [
                        'name' => 'sipCallId',
                        'param' => 'sip_call_id',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Call identifier. For makecall action it is not required, for other actions it is required.',
                    ],
                ],
            ],
            [
                'operation' => 'create_pbx_acl_group',
                'slug' => 'wildix_create_pbx_acl_group',
                'class' => 'WildixCreatePBXACLGroup',
                'method' => 'POST',
                'path' => '/api/v1/pbx/aclgroups',
                'name' => 'Create PBX ACL Group',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CreatePbxAclGroupCommand`.

Official Wildix SDK endpoint: POST /api/v1/pbx/aclgroups. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'inherits',
                        'param' => 'inherits',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `inherits`.',
                    ],
                    [
                        'name' => 'name',
                        'param' => 'name',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Wildix request field `name`.',
                    ],
                    [
                        'name' => 'rules',
                        'param' => 'rules',
                        'in' => 'body',
                        'type' => 'array',
                        'required' => true,
                        'description' => 'Wildix request field `rules`.',
                    ],
                    [
                        'name' => 'wcgrp',
                        'param' => 'wcgrp',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `wcgrp`.',
                    ],
                ],
            ],
            [
                'operation' => 'create_pbx_colleague',
                'slug' => 'wildix_create_pbx_colleague',
                'class' => 'WildixCreatePBXColleague',
                'method' => 'POST',
                'path' => '/api/v1/PBX/Colleagues',
                'name' => 'Create PBX Colleague',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CreatePbxColleagueCommand`.

Official Wildix SDK endpoint: POST /api/v1/PBX/Colleagues. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'department',
                        'param' => 'department',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `department`.',
                    ],
                    [
                        'name' => 'dialplan',
                        'param' => 'dialplan',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `dialplan`.',
                    ],
                    [
                        'name' => 'email',
                        'param' => 'email',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `email`.',
                    ],
                    [
                        'name' => 'extension',
                        'param' => 'extension',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Wildix request field `extension`.',
                    ],
                    [
                        'name' => 'faxDialplan',
                        'param' => 'fax_dialplan',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `faxDialplan`.',
                    ],
                    [
                        'name' => 'faxNumber',
                        'param' => 'fax_number',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `faxNumber`.',
                    ],
                    [
                        'name' => 'groupDn',
                        'param' => 'group_dn',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `groupDn`.',
                    ],
                    [
                        'name' => 'language',
                        'param' => 'language',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `language`.',
                    ],
                    [
                        'name' => 'licenseType',
                        'param' => 'license_type',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `licenseType`.',
                    ],
                    [
                        'name' => 'login',
                        'param' => 'login',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `login`.',
                    ],
                    [
                        'name' => 'mobilePhone',
                        'param' => 'mobile_phone',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `mobilePhone`.',
                    ],
                    [
                        'name' => 'name',
                        'param' => 'name',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Wildix request field `name`.',
                    ],
                    [
                        'name' => 'officePhone',
                        'param' => 'office_phone',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `officePhone`.',
                    ],
                    [
                        'name' => 'password',
                        'param' => 'password',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `password`.',
                    ],
                    [
                        'name' => 'role',
                        'param' => 'role',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `role`.',
                    ],
                    [
                        'name' => 'sipPassword',
                        'param' => 'sip_password',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `sipPassword`.',
                    ],
                ],
            ],
            [
                'operation' => 'create_pbx_o_auth2_client',
                'slug' => 'wildix_create_pbx_o_auth2_client',
                'class' => 'WildixCreatePBXOAuth2Client',
                'method' => 'POST',
                'path' => '/api/v1/pbx/applications/oauth2',
                'name' => 'Create PBX O Auth2 Client',
                'description' => 'Execute the official Wildix WMS/PBX API operation `CreatePbxOAuth2ClientCommand`.

Official Wildix SDK endpoint: POST /api/v1/pbx/applications/oauth2. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'expireTime',
                        'param' => 'expire_time',
                        'in' => 'body',
                        'type' => 'integer',
                        'required' => true,
                        'description' => 'Timestamp for expiration of the OAuth2 application. Should not exceed 1 year.',
                    ],
                    [
                        'name' => 'name',
                        'param' => 'name',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'A name of OAuth2 client.',
                    ],
                    [
                        'name' => 'redirectUri',
                        'param' => 'redirect_uri',
                        'in' => 'body',
                        'type' => 'array',
                        'required' => true,
                        'description' => 'Array of redirect URLs, allowed for this client.',
                    ],
                ],
            ],
            [
                'operation' => 'delete_pbx_acl_group',
                'slug' => 'wildix_delete_pbx_acl_group',
                'class' => 'WildixDeletePBXACLGroup',
                'method' => 'DELETE',
                'path' => '/api/v1/pbx/aclgroups/{id}',
                'name' => 'Delete PBX ACL Group',
                'description' => 'Execute the official Wildix WMS/PBX API operation `DeletePbxAclGroupCommand`.

Official Wildix SDK endpoint: DELETE /api/v1/pbx/aclgroups/{id}. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'id',
                        'param' => 'id',
                        'in' => 'path',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Wildix path parameter `id`.',
                    ],
                ],
            ],
            [
                'operation' => 'delete_pbx_colleague',
                'slug' => 'wildix_delete_pbx_colleague',
                'class' => 'WildixDeletePBXColleague',
                'method' => 'DELETE',
                'path' => '/api/v1/PBX/Colleagues/{id}',
                'name' => 'Delete PBX Colleague',
                'description' => 'Execute the official Wildix WMS/PBX API operation `DeletePbxColleagueCommand`.

Official Wildix SDK endpoint: DELETE /api/v1/PBX/Colleagues/{id}. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'id',
                        'param' => 'id',
                        'in' => 'path',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Wildix path parameter `id`.',
                    ],
                ],
            ],
            [
                'operation' => 'delete_pbx_o_auth2_client',
                'slug' => 'wildix_delete_pbx_o_auth2_client',
                'class' => 'WildixDeletePBXOAuth2Client',
                'method' => 'DELETE',
                'path' => '/api/v1/pbx/applications/oauth2/{id}',
                'name' => 'Delete PBX O Auth2 Client',
                'description' => 'Execute the official Wildix WMS/PBX API operation `DeletePbxOAuth2ClientCommand`.

Official Wildix SDK endpoint: DELETE /api/v1/pbx/applications/oauth2/{id}. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'id',
                        'param' => 'id',
                        'in' => 'path',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Wildix path parameter `id`.',
                    ],
                ],
            ],
            [
                'operation' => 'get_call_queues_settings',
                'slug' => 'wildix_get_call_queues_settings',
                'class' => 'WildixGetCallQueuesSettings',
                'method' => 'GET',
                'path' => '/api/v1/pbx/settings/callqueues/{groupId}',
                'name' => 'Get Call Queues Settings',
                'description' => 'Execute the official Wildix WMS/PBX API operation `GetCallQueuesSettingsCommand`.

Official Wildix SDK endpoint: GET /api/v1/pbx/settings/callqueues/{groupId}. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [
                    [
                        'name' => 'groupId',
                        'param' => 'group_id',
                        'in' => 'path',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Wildix path parameter `groupId`.',
                    ],
                ],
            ],
            [
                'operation' => 'get_colleague_by_id',
                'slug' => 'wildix_get_colleague_by_id',
                'class' => 'WildixGetColleagueById',
                'method' => 'GET',
                'path' => '/api/v1/Colleagues/{id}',
                'name' => 'Get Colleague By Id',
                'description' => 'Execute the official Wildix WMS/PBX API operation `GetColleagueByIdCommand`.

Official Wildix SDK endpoint: GET /api/v1/Colleagues/{id}. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [
                    [
                        'name' => 'id',
                        'param' => 'id',
                        'in' => 'path',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Wildix path parameter `id`.',
                    ],
                ],
            ],
            [
                'operation' => 'get_pbx_acl_groups_permissions',
                'slug' => 'wildix_get_pbx_acl_groups_permissions',
                'class' => 'WildixGetPBXACLGroupsPermissions',
                'method' => 'GET',
                'path' => '/api/v1/pbx/aclgroups/permissions',
                'name' => 'Get PBX ACL Groups Permissions',
                'description' => 'Execute the official Wildix WMS/PBX API operation `GetPbxAclGroupsPermissionsCommand`.

Official Wildix SDK endpoint: GET /api/v1/pbx/aclgroups/permissions. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [
                    [
                        'name' => 'groups[]',
                        'param' => 'groups[]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `groups[]`.',
                    ],
                    [
                        'name' => 'permissions[]',
                        'param' => 'permissions[]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `permissions[]`.',
                    ],
                ],
            ],
            [
                'operation' => 'get_pbx_call_groups',
                'slug' => 'wildix_get_pbx_call_groups',
                'class' => 'WildixGetPBXCallGroups',
                'method' => 'GET',
                'path' => '/api/v1/Dialplan/CallGroups',
                'name' => 'Get PBX Call Groups',
                'description' => 'Execute the official Wildix WMS/PBX API operation `GetPbxCallGroupsCommand`.

Official Wildix SDK endpoint: GET /api/v1/Dialplan/CallGroups. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [],
            ],
            [
                'operation' => 'get_pbx_colleagues',
                'slug' => 'wildix_get_pbx_colleagues',
                'class' => 'WildixGetPBXColleagues',
                'method' => 'GET',
                'path' => '/api/v1/PBX/Colleagues',
                'name' => 'Get PBX Colleagues',
                'description' => 'Execute the official Wildix WMS/PBX API operation `GetPbxColleaguesCommand`.

Official Wildix SDK endpoint: GET /api/v1/PBX/Colleagues. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [
                    [
                        'name' => 'filter[extension][]',
                        'param' => 'filter[extension][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[extension][]`.',
                    ],
                    [
                        'name' => 'filter[id][]',
                        'param' => 'filter[id][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[id][]`.',
                    ],
                    [
                        'name' => 'filter[officePhone][]',
                        'param' => 'filter[office_phone][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[officePhone][]`.',
                    ],
                    [
                        'name' => 'filter[mobilePhone][]',
                        'param' => 'filter[mobile_phone][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[mobilePhone][]`.',
                    ],
                    [
                        'name' => 'filter[name][]',
                        'param' => 'filter[name][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[name][]`.',
                    ],
                    [
                        'name' => 'filter[email][]',
                        'param' => 'filter[email][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[email][]`.',
                    ],
                    [
                        'name' => 'filter[role][]',
                        'param' => 'filter[role][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[role][]`.',
                    ],
                    [
                        'name' => 'filter[dialplan][]',
                        'param' => 'filter[dialplan][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[dialplan][]`.',
                    ],
                    [
                        'name' => 'filter[faxDialplan][]',
                        'param' => 'filter[fax_dialplan][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[faxDialplan][]`.',
                    ],
                    [
                        'name' => 'filter[department][]',
                        'param' => 'filter[department][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[department][]`.',
                    ],
                    [
                        'name' => 'filter[login][]',
                        'param' => 'filter[login][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[login][]`.',
                    ],
                    [
                        'name' => 'filter[groupDn][]',
                        'param' => 'filter[group_dn][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[groupDn][]`.',
                    ],
                    [
                        'name' => 'filter[pbxDn][]',
                        'param' => 'filter[pbx_dn][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[pbxDn][]`.',
                    ],
                    [
                        'name' => 'filter[licenseType][]',
                        'param' => 'filter[license_type][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[licenseType][]`.',
                    ],
                    [
                        'name' => 'fields',
                        'param' => 'fields',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `fields`.',
                    ],
                    [
                        'name' => 'searchFields',
                        'param' => 'search_fields',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `searchFields`.',
                    ],
                    [
                        'name' => 'search',
                        'param' => 'search',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `search`.',
                    ],
                    [
                        'name' => 'sort',
                        'param' => 'sort',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `sort`.',
                    ],
                    [
                        'name' => 'start',
                        'param' => 'start',
                        'in' => 'query',
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Wildix query parameter `start`.',
                    ],
                    [
                        'name' => 'count',
                        'param' => 'count',
                        'in' => 'query',
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Wildix query parameter `count`.',
                    ],
                    [
                        'name' => 'dir',
                        'param' => 'dir',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `dir`.',
                    ],
                    [
                        'name' => 'searchStrategy',
                        'param' => 'search_strategy',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `searchStrategy`.',
                    ],
                ],
            ],
            [
                'operation' => 'get_pbxes',
                'slug' => 'wildix_get_pbxes',
                'class' => 'WildixGetPbxes',
                'method' => 'GET',
                'path' => '/api/v1/network/pbxes',
                'name' => 'Get Pbxes',
                'description' => 'Execute the official Wildix WMS/PBX API operation `GetPbxesCommand`.

Official Wildix SDK endpoint: GET /api/v1/network/pbxes. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [],
            ],
            [
                'operation' => 'get_pbx_o_auth2_clients',
                'slug' => 'wildix_get_pbx_o_auth2_clients',
                'class' => 'WildixGetPBXOAuth2Clients',
                'method' => 'GET',
                'path' => '/api/v1/pbx/applications/oauth2',
                'name' => 'Get PBX O Auth2 Clients',
                'description' => 'Execute the official Wildix WMS/PBX API operation `GetPbxOAuth2ClientsCommand`.

Official Wildix SDK endpoint: GET /api/v1/pbx/applications/oauth2. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [],
            ],
            [
                'operation' => 'get_personal_info',
                'slug' => 'wildix_get_personal_info',
                'class' => 'WildixGetPersonalInfo',
                'method' => 'GET',
                'path' => '/api/v1/personal/info',
                'name' => 'Get Personal Info',
                'description' => 'Execute the official Wildix WMS/PBX API operation `GetPersonalInfoCommand`.

Official Wildix SDK endpoint: GET /api/v1/personal/info. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [
                    [
                        'name' => 'filter[extension][]',
                        'param' => 'filter[extension][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[extension][]`.',
                    ],
                    [
                        'name' => 'filter[id][]',
                        'param' => 'filter[id][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[id][]`.',
                    ],
                    [
                        'name' => 'filter[officePhone][]',
                        'param' => 'filter[office_phone][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[officePhone][]`.',
                    ],
                    [
                        'name' => 'filter[mobilePhone][]',
                        'param' => 'filter[mobile_phone][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[mobilePhone][]`.',
                    ],
                    [
                        'name' => 'filter[name][]',
                        'param' => 'filter[name][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[name][]`.',
                    ],
                    [
                        'name' => 'filter[email][]',
                        'param' => 'filter[email][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[email][]`.',
                    ],
                    [
                        'name' => 'filter[role][]',
                        'param' => 'filter[role][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[role][]`.',
                    ],
                    [
                        'name' => 'filter[dialplan][]',
                        'param' => 'filter[dialplan][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[dialplan][]`.',
                    ],
                    [
                        'name' => 'filter[faxDialplan][]',
                        'param' => 'filter[fax_dialplan][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[faxDialplan][]`.',
                    ],
                    [
                        'name' => 'filter[department][]',
                        'param' => 'filter[department][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[department][]`.',
                    ],
                    [
                        'name' => 'filter[login][]',
                        'param' => 'filter[login][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[login][]`.',
                    ],
                    [
                        'name' => 'filter[groupDn][]',
                        'param' => 'filter[group_dn][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[groupDn][]`.',
                    ],
                    [
                        'name' => 'filter[pbxDn][]',
                        'param' => 'filter[pbx_dn][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[pbxDn][]`.',
                    ],
                    [
                        'name' => 'filter[licenseType][]',
                        'param' => 'filter[license_type][]',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `filter[licenseType][]`.',
                    ],
                    [
                        'name' => 'fields',
                        'param' => 'fields',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `fields`.',
                    ],
                    [
                        'name' => 'searchFields',
                        'param' => 'search_fields',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `searchFields`.',
                    ],
                    [
                        'name' => 'search',
                        'param' => 'search',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `search`.',
                    ],
                    [
                        'name' => 'sort',
                        'param' => 'sort',
                        'in' => 'query',
                        'type' => 'array',
                        'required' => false,
                        'description' => 'Wildix query parameter `sort`.',
                    ],
                    [
                        'name' => 'start',
                        'param' => 'start',
                        'in' => 'query',
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Wildix query parameter `start`.',
                    ],
                    [
                        'name' => 'count',
                        'param' => 'count',
                        'in' => 'query',
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'Wildix query parameter `count`.',
                    ],
                    [
                        'name' => 'dir',
                        'param' => 'dir',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `dir`.',
                    ],
                    [
                        'name' => 'searchStrategy',
                        'param' => 'search_strategy',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `searchStrategy`.',
                    ],
                ],
            ],
            [
                'operation' => 'list_pbx_departments',
                'slug' => 'wildix_list_pbx_departments',
                'class' => 'WildixListPBXDepartments',
                'method' => 'GET',
                'path' => '/api/v1/Departments',
                'name' => 'List PBX Departments',
                'description' => 'Execute the official Wildix WMS/PBX API operation `ListPbxDepartmentsCommand`.

Official Wildix SDK endpoint: GET /api/v1/Departments. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [],
            ],
            [
                'operation' => 'list_pbx_groups',
                'slug' => 'wildix_list_pbx_groups',
                'class' => 'WildixListPBXGroups',
                'method' => 'GET',
                'path' => '/api/v1/Groups',
                'name' => 'List PBX Groups',
                'description' => 'Execute the official Wildix WMS/PBX API operation `ListPbxGroupsCommand`.

Official Wildix SDK endpoint: GET /api/v1/Groups. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [],
            ],
            [
                'operation' => 'list_user_active_calls',
                'slug' => 'wildix_list_user_active_calls',
                'class' => 'WildixListUserActiveCalls',
                'method' => 'GET',
                'path' => '/api/v2/call-control/list-calls',
                'name' => 'List User Active Calls',
                'description' => 'Execute the official Wildix WMS/PBX API operation `ListUserActiveCallsCommand`.

Official Wildix SDK endpoint: GET /api/v2/call-control/list-calls. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [
                    [
                        'name' => 'user',
                        'param' => 'user',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `user`.',
                    ],
                ],
            ],
            [
                'operation' => 'list_user_devices',
                'slug' => 'wildix_list_user_devices',
                'class' => 'WildixListUserDevices',
                'method' => 'GET',
                'path' => '/api/v2/call-control/list-devices',
                'name' => 'List User Devices',
                'description' => 'Execute the official Wildix WMS/PBX API operation `ListUserDevicesCommand`.

Official Wildix SDK endpoint: GET /api/v2/call-control/list-devices. Source package: @wildix/wms-api-client.',
                'type' => 'read',
                'parameters' => [
                    [
                        'name' => 'user',
                        'param' => 'user',
                        'in' => 'query',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix query parameter `user`.',
                    ],
                ],
            ],
            [
                'operation' => 'notifications',
                'slug' => 'wildix_notifications',
                'class' => 'WildixNotifications',
                'method' => 'POST',
                'path' => '/api/v1/notifications',
                'name' => 'Notifications',
                'description' => 'Execute the official Wildix WMS/PBX API operation `NotificationsCommand`.

Official Wildix SDK endpoint: POST /api/v1/notifications. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'broadcastId',
                        'param' => 'broadcast_id',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The broadcast ID to which the message will be sent.',
                    ],
                    [
                        'name' => 'broadcastMessage',
                        'param' => 'broadcast_message',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The message for announcing into a conference.',
                    ],
                    [
                        'name' => 'confirmationTimeout',
                        'param' => 'confirmation_timeout',
                        'in' => 'body',
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'How many seconds the request should wait for the confirmation after the start.',
                    ],
                    [
                        'name' => 'customRid',
                        'param' => 'custom_rid',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'The custom request ID.',
                    ],
                    [
                        'name' => 'event',
                        'param' => 'event',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Information about the event. What happened.',
                    ],
                    [
                        'name' => 'from',
                        'param' => 'from',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Information about the source of the notification. For example, the name of the camera.',
                    ],
                    [
                        'name' => 'notificationType',
                        'param' => 'notification_type',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Type of the alert that is generated.',
                    ],
                    [
                        'name' => 'origin',
                        'param' => 'origin',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Indicates the source of the request.',
                    ],
                    [
                        'name' => 'playFrequency',
                        'param' => 'play_frequency',
                        'in' => 'body',
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'How often (each N seconds) a request has to be repeated.',
                    ],
                    [
                        'name' => 'priority',
                        'param' => 'priority',
                        'in' => 'body',
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'The priority of the notification.',
                    ],
                    [
                        'name' => 'queueTimeout',
                        'param' => 'queue_timeout',
                        'in' => 'body',
                        'type' => 'integer',
                        'required' => false,
                        'description' => 'How many seconds the queued request should wait for starting processing.',
                    ],
                    [
                        'name' => 'skipTranscribe',
                        'param' => 'skip_transcribe',
                        'in' => 'body',
                        'type' => 'boolean',
                        'required' => false,
                        'description' => 'Skip notification transcribing.',
                    ],
                ],
            ],
            [
                'operation' => 'originate',
                'slug' => 'wildix_originate',
                'class' => 'WildixOriginate',
                'method' => 'POST',
                'path' => '/api/v1/originate',
                'name' => 'Originate',
                'description' => 'Execute the official Wildix WMS/PBX API operation `OriginateCommand`.

Official Wildix SDK endpoint: POST /api/v1/originate. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'account',
                        'param' => 'account',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `account`.',
                    ],
                    [
                        'name' => 'actionid',
                        'param' => 'actionid',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `actionid`.',
                    ],
                    [
                        'name' => 'application',
                        'param' => 'application',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `application`.',
                    ],
                    [
                        'name' => 'async',
                        'param' => 'async',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `async`.',
                    ],
                    [
                        'name' => 'callerid',
                        'param' => 'callerid',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `callerid`.',
                    ],
                    [
                        'name' => 'channel',
                        'param' => 'channel',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Wildix request field `channel`.',
                    ],
                    [
                        'name' => 'context',
                        'param' => 'context',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `context`.',
                    ],
                    [
                        'name' => 'data',
                        'param' => 'data',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `data`.',
                    ],
                    [
                        'name' => 'exten',
                        'param' => 'exten',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `exten`.',
                    ],
                    [
                        'name' => 'priority',
                        'param' => 'priority',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `priority`.',
                    ],
                    [
                        'name' => 'timeout',
                        'param' => 'timeout',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `timeout`.',
                    ],
                    [
                        'name' => 'variable',
                        'param' => 'variable',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Wildix request field `variable`.',
                    ],
                ],
            ],
            [
                'operation' => 'originate_call',
                'slug' => 'wildix_originate_call',
                'class' => 'WildixOriginateCall',
                'method' => 'POST',
                'path' => '/api/v1/originate/call',
                'name' => 'Originate Call',
                'description' => 'Execute the official Wildix WMS/PBX API operation `OriginateCallCommand`.

Official Wildix SDK endpoint: POST /api/v1/originate/call. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'name',
                        'param' => 'name',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'The name',
                    ],
                    [
                        'name' => 'number',
                        'param' => 'number',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'The phone number.',
                    ],
                    [
                        'name' => 'postpone',
                        'param' => 'postpone',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => false,
                        'description' => 'Date of sending the delayed message. (14 07 2015 15:35)',
                    ],
                ],
            ],
            [
                'operation' => 'reload_broadcasts',
                'slug' => 'wildix_reload_broadcasts',
                'class' => 'WildixReloadBroadcasts',
                'method' => 'POST',
                'path' => '/api/v1/broadcasts/reload',
                'name' => 'Reload Broadcasts',
                'description' => 'Execute the official Wildix WMS/PBX API operation `ReloadBroadcastsCommand`.

Official Wildix SDK endpoint: POST /api/v1/broadcasts/reload. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [],
            ],
            [
                'operation' => 'update_pbx_o_auth2_client',
                'slug' => 'wildix_update_pbx_o_auth2_client',
                'class' => 'WildixUpdatePBXOAuth2Client',
                'method' => 'PUT',
                'path' => '/api/v1/pbx/applications/oauth2/{id}',
                'name' => 'Update PBX O Auth2 Client',
                'description' => 'Execute the official Wildix WMS/PBX API operation `UpdatePbxOAuth2ClientCommand`.

Official Wildix SDK endpoint: PUT /api/v1/pbx/applications/oauth2/{id}. Source package: @wildix/wms-api-client.',
                'type' => 'write',
                'parameters' => [
                    [
                        'name' => 'id',
                        'param' => 'id',
                        'in' => 'path',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'Wildix path parameter `id`.',
                    ],
                    [
                        'name' => 'name',
                        'param' => 'name',
                        'in' => 'body',
                        'type' => 'string',
                        'required' => true,
                        'description' => 'A name of OAuth2 client.',
                    ],
                    [
                        'name' => 'redirectUri',
                        'param' => 'redirect_uri',
                        'in' => 'body',
                        'type' => 'array',
                        'required' => true,
                        'description' => 'Array of redirect URLs, allowed for this client.',
                    ],
                ],
            ],
        ];
    }
}
