<?php

namespace OpenCompany\Integrations\Wildix;

use Illuminate\Http\Client\Response;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use RuntimeException;

/**
 * HTTP client for the official Wildix WMS/PBX API.
 *
 * Uses the endpoint and request shapes generated by the official
 * @wildix/wms-api-client package while keeping host credentials in PHP.
 */
class WildixService
{
    /**
     * @param  string  $accessToken  Wildix bearer token for WMS/PBX API calls.
     * @param  string  $baseUrl  PBX API base URL, usually https://{pbx}.wildixin.com.
     */
    public function __construct(
        private string $accessToken = '',
        private string $baseUrl = '',
    ) {
        $this->baseUrl = rtrim($this->normalizeBaseUrl($this->baseUrl), '/');
    }

    /**
     * Check whether the service has both a token and PBX API host.
     */
    public function isConfigured(): bool
    {
        return trim($this->accessToken) !== '' && trim($this->baseUrl) !== '';
    }

    /**
     * Return the official Wildix WMS/PBX operation map.
     *
     * @return list<array<string, mixed>>
     */
    public static function operations(): array
    {
        return WildixOperations::all();
    }

    /**
     * Return metadata for one Wildix operation by tool slug or operation key.
     *
     * @return array<string, mixed>
     */
    public function operation(string $operation): array
    {
        foreach (self::operations() as $definition) {
            if (($definition['slug'] ?? null) === $operation || ($definition['operation'] ?? null) === $operation) {
                return $definition;
            }
        }

        throw new RuntimeException("Unsupported Wildix operation: {$operation}");
    }

    /**
     * Execute an official Wildix WMS/PBX API operation.
     *
     * @param  array<string, mixed>  $args  Tool arguments.
     * @return array<string, mixed>
     */
    public function call(string $operation, array $args = []): array
    {
        $definition = $this->operation($operation);
        [$path, $query, $payload] = $this->shapeRequest($definition, $args);

        return $this->request(
            method: (string) $definition['method'],
            path: $path,
            query: $query,
            payload: $payload,
        );
    }

    /**
     * Shape tool arguments into path, query, and JSON body data.
     *
     * @param  array<string, mixed>  $definition  Operation metadata.
     * @param  array<string, mixed>  $args  Tool arguments.
     * @return array{0: string, 1: array<string, mixed>, 2: array<string, mixed>}
     */
    private function shapeRequest(array $definition, array $args): array
    {
        $path = (string) $definition['path'];
        $query = isset($args['query']) && is_array($args['query']) ? $args['query'] : [];
        $payload = isset($args['payload']) && is_array($args['payload']) ? $args['payload'] : [];
        $consumed = ['query' => true, 'payload' => true];

        foreach ($definition['parameters'] as $parameter) {
            $param = (string) $parameter['param'];
            $name = (string) $parameter['name'];
            $location = (string) $parameter['in'];
            $value = $args[$param] ?? $args[$name] ?? null;
            $consumed[$param] = true;
            $consumed[$name] = true;

            if (($parameter['required'] ?? false) && ($value === null || $value === '')) {
                throw new RuntimeException($param.' is required.');
            }

            if ($value === null || $value === '') {
                continue;
            }

            if ($location === 'path') {
                $path = str_replace('{'.$name.'}', rawurlencode((string) $value), $path);
            } elseif ($location === 'query') {
                $query[$name] = $value;
            } elseif ($location === 'body') {
                $payload[$name] = $value;
            }
        }

        if (str_contains($path, '{')) {
            throw new RuntimeException('Missing required Wildix path parameter.');
        }

        foreach ($args as $key => $value) {
            if (isset($consumed[$key])) {
                continue;
            }

            if (($definition['type'] ?? 'read') === 'write') {
                $payload[$key] = $value;
            } else {
                $query[$key] = $value;
            }
        }

        return [$path, $query, $payload];
    }

    /**
     * Normalize a Wildix PBX host, domain, or full URL into a base URL.
     */
    private function normalizeBaseUrl(string $baseUrl): string
    {
        $baseUrl = trim($baseUrl);
        if ($baseUrl === '') {
            return '';
        }

        if (!str_starts_with($baseUrl, 'http://') && !str_starts_with($baseUrl, 'https://')) {
            $domain = str_ends_with($baseUrl, '.wildixin.com') ? $baseUrl : $baseUrl.'.wildixin.com';

            return 'https://'.$domain;
        }

        return $baseUrl;
    }

    /**
     * Dispatch an authenticated Wildix request.
     *
     * @param  array<string, mixed>  $query  Query parameters.
     * @param  array<string, mixed>  $payload  JSON body fields.
     * @return array<string, mixed>
     */
    private function request(string $method, string $path, array $query = [], array $payload = []): array
    {
        $response = $this->rawRequest($method, $path, $query, $payload);

        return $this->decodeResponse($response);
    }

    /**
     * Make a raw HTTP request to the Wildix API.
     *
     * @param  array<string, mixed>  $query  Query parameters.
     * @param  array<string, mixed>  $payload  JSON body fields.
     * @return Response
     *
     * @throws RuntimeException
     */
    private function rawRequest(string $method, string $path, array $query = [], array $payload = []): Response
    {
        if (!$this->isConfigured()) {
            throw new RuntimeException('Wildix access token and PBX API base URL are required.');
        }

        $options = [];
        if ($query !== []) {
            $options['query'] = $query;
        }
        if ($payload !== []) {
            $options['json'] = $payload;
        }

        try {
            $response = Http::withToken($this->accessToken)
                ->acceptJson()
                ->timeout(30)
                ->send(strtoupper($method), $this->baseUrl.$path, $options);
        } catch (\Throwable $e) {
            Log::error("Wildix API connection error: {$method} {$path}", ['error' => $e->getMessage()]);

            throw new RuntimeException('Failed to connect to Wildix API: '.$e->getMessage());
        }

        if (!$response->successful()) {
            $this->throwApiError($method, $path, $response);
        }

        return $response;
    }

    /**
     * Throw a normalized Wildix API error.
     */
    private function throwApiError(string $method, string $path, Response $response): never
    {
        $json = $response->json();
        $message = is_array($json)
            ? (string) data_get($json, 'reason', data_get($json, 'message', data_get($json, 'error', '')))
            : trim($response->body());

        Log::error("Wildix API error: {$method} {$path}", [
            'status' => $response->status(),
            'body' => $response->body(),
        ]);

        throw new RuntimeException('Wildix API error ('.$response->status().'): '.($message !== '' ? $message : 'Unexpected API error.'));
    }

    /**
     * Decode JSON, text, or empty Wildix responses.
     *
     * @return array<string, mixed>
     */
    private function decodeResponse(Response $response): array
    {
        if ($response->body() === '') {
            return ['success' => true];
        }

        $json = $response->json();
        if (is_array($json)) {
            return $json;
        }

        return ['body' => $response->body()];
    }
}
