<?php

namespace OpenCompany\Integrations\SonarCloud\Tools;

/**
 * Restore a quality profile using an XML file. The restored profile name is taken from the backup file, so if a profile with the same name and language already exists, it will be overwritten. Requires to be logged in and the 'Administer Quality Profiles' permission..
 *
 * Maps to the official SonarCloud Web API endpoint POST /api/qualityprofiles/restore.
 */
class SonarCloudQualityprofilesRestore extends AbstractSonarCloudTool
{
    protected const NAME = 'sonarcloud_qualityprofiles_restore';
    protected const DESCRIPTION = 'Restore a quality profile using an XML file. The restored profile name is taken from the backup file, so if a profile with the same name and language already exists, it will be overwritten. Requires to be logged in and the \'Administer Quality Profiles\' permission.

Official SonarCloud Web API endpoint: POST /api/qualityprofiles/restore.';
    protected const PARAMETERS = array (
      'backup' => array (
        'type' => 'string',
        'description' => 'A profile backup file in XML format, as generated by api/qualityprofiles/backup or the former api/profiles/backup.',
        'required' => true,
      ),
      'organization' => array (
        'type' => 'string',
        'description' => 'Organization key.',
        'required' => true,
      ),
    );
    protected const METHOD = 'POST';
    protected const PATH = '/api/qualityprofiles/restore';
    protected const PARAM_MAP = array (
      'backup' => 'backup',
      'organization' => 'organization',
    );
}
