<?php

namespace OpenCompany\Integrations\SonarCloud\Tools;

/**
 * Search for issues. Requires the 'Browse' permission on the specified project(s)..
 *
 * Maps to the official SonarCloud Web API endpoint GET /api/issues/search.
 */
class SonarCloudIssuesSearch extends AbstractSonarCloudTool
{
    protected const NAME = 'sonarcloud_issues_search';
    protected const DESCRIPTION = 'Search for issues. Requires the \'Browse\' permission on the specified project(s).

Official SonarCloud Web API endpoint: GET /api/issues/search.';
    protected const PARAMETERS = array (
      'additional_fields' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of the optional fields to be returned in response. Action plans are dropped in 5.5, it is not returned in the response.',
        'required' => false,
        'enum' => array (
          '_all',
          'comments',
          'languages',
          'actionPlans',
          'rules',
          'ruleDescriptionContextKey',
          'transitions',
          'actions',
          'users',
        ),
      ),
      'asc' => array (
        'type' => 'string',
        'description' => 'Ascending sort',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'assigned' => array (
        'type' => 'string',
        'description' => 'To retrieve assigned or unassigned issues',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'assignees' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of assignee logins. The value \'__me__\' can be used as a placeholder for user who performs the request',
        'required' => false,
      ),
      'author' => array (
        'type' => 'string',
        'description' => 'SCM accounts. To set several values, the parameter must be called once for each value.',
        'required' => false,
      ),
      'branch' => array (
        'type' => 'string',
        'description' => 'Branch key',
        'required' => false,
      ),
      'clean_code_attribute_categories' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of clean code attribute categories.',
        'required' => false,
        'enum' => array (
          'ADAPTABLE',
          'CONSISTENT',
          'INTENTIONAL',
          'RESPONSIBLE',
        ),
      ),
      'compliance_standards' => array (
        'type' => 'string',
        'description' => 'Set of compliance standards to filter on. Categories within a standard are comma-separated and behave as an \'or\'. Multiple standards are separated by an ampersand and behave as an \'and\'.',
        'required' => false,
      ),
      'component_keys' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of component keys. Retrieve issues associated to a specific list of components (and all its descendants). A component can be a project, directory or file.',
        'required' => false,
      ),
      'created_after' => array (
        'type' => 'string',
        'description' => 'To retrieve issues created after the given date (inclusive). Either a date (server timezone) or datetime can be provided. If this parameter is set, createdSince must not be set',
        'required' => false,
      ),
      'created_at' => array (
        'type' => 'string',
        'description' => 'Datetime to retrieve issues created during a specific analysis',
        'required' => false,
      ),
      'created_before' => array (
        'type' => 'string',
        'description' => 'To retrieve issues created before the given date (inclusive). Either a date (server timezone) or datetime can be provided.',
        'required' => false,
      ),
      'created_in_last' => array (
        'type' => 'string',
        'description' => 'To retrieve issues created during a time span before the current time (exclusive). Accepted units are \'y\' for year, \'m\' for month, \'w\' for week and \'d\' for day. If this parameter is set, createdAfter must not be set',
        'required' => false,
      ),
      'cwe' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of CWE identifiers. Use \'unknown\' to select issues not associated to any CWE.',
        'required' => false,
      ),
      'facet_mode' => array (
        'type' => 'string',
        'description' => 'Choose the returned value for facet items, either count of issues or sum of remediation effort.',
        'required' => false,
        'enum' => array (
          'count',
          'effort',
        ),
      ),
      'facets' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of the facets to be computed. No facet is computed by default.',
        'required' => false,
        'enum' => array (
          'projects',
          'moduleUuids',
          'fileUuids',
          'assigned_to_me',
          'severities',
          'statuses',
          'issueStatuses',
          'resolutions',
          'rules',
          'assignees',
          'author',
          'directories',
          'languages',
          'tags',
          'types',
          'owaspMobileTop10-2024',
          'owaspTop10',
          'owaspTop10-2021',
          'cwe',
          'createdAt',
          'sonarsourceSecurity',
          'impactSoftwareQualities',
          'impactSeverities',
          'cleanCodeAttributeCategories',
          'complianceStandards',
        ),
      ),
      'impact_severities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of impact severities.',
        'required' => false,
        'enum' => array (
          'INFO',
          'LOW',
          'MEDIUM',
          'HIGH',
          'BLOCKER',
        ),
      ),
      'impact_software_qualities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of software qualities.',
        'required' => false,
        'enum' => array (
          'MAINTAINABILITY',
          'RELIABILITY',
          'SECURITY',
        ),
      ),
      'issue_statuses' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of issue statuses',
        'required' => false,
        'enum' => array (
          'OPEN',
          'CONFIRMED',
          'FALSE_POSITIVE',
          'ACCEPTED',
          'FIXED',
        ),
      ),
      'issues' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of issue keys',
        'required' => false,
      ),
      'languages' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of languages. Available since 4.4',
        'required' => false,
      ),
      'on_component_only' => array (
        'type' => 'string',
        'description' => 'Return only issues at a component\'s level, not on its descendants (modules, directories, files, etc). This parameter is only considered when componentKeys or componentUuids is set.',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'organization' => array (
        'type' => 'string',
        'description' => 'Organization key',
        'required' => false,
      ),
      'owasp_mobile_top10_2024' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Mobile Top 10 - 2024 lowercase categories.',
        'required' => false,
        'enum' => array (
          'm1',
          'm2',
          'm3',
          'm4',
          'm5',
          'm6',
          'm7',
          'm8',
          'm9',
          'm10',
        ),
      ),
      'owasp_top10' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Top 10 lowercase categories.',
        'required' => false,
        'enum' => array (
          'a1',
          'a2',
          'a3',
          'a4',
          'a5',
          'a6',
          'a7',
          'a8',
          'a9',
          'a10',
        ),
      ),
      'owasp_top10_2021' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Top 10 - 2021 lowercase categories.',
        'required' => false,
        'enum' => array (
          'a1',
          'a2',
          'a3',
          'a4',
          'a5',
          'a6',
          'a7',
          'a8',
          'a9',
          'a10',
        ),
      ),
      'p' => array (
        'type' => 'string',
        'description' => '1-based page number',
        'required' => false,
      ),
      'ps' => array (
        'type' => 'string',
        'description' => 'Page size. Must be greater than 0 and less or equal than 500',
        'required' => false,
      ),
      'pull_request' => array (
        'type' => 'string',
        'description' => 'Pull request id',
        'required' => false,
      ),
      'resolutions' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of resolutions',
        'required' => false,
        'enum' => array (
          'FALSE-POSITIVE',
          'WONTFIX',
          'FIXED',
          'REMOVED',
        ),
      ),
      'resolved' => array (
        'type' => 'string',
        'description' => 'To match resolved or unresolved issues',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'rules' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of coding rule keys. Format is :',
        'required' => false,
      ),
      's' => array (
        'type' => 'string',
        'description' => 'Sort field',
        'required' => false,
        'enum' => array (
          'STATUS',
          'UPDATE_DATE',
          'CLOSE_DATE',
          'HOTSPOTS',
          'FILE_LINE',
          'SEVERITY',
          'CREATION_DATE',
          'ASSIGNEE',
        ),
      ),
      'severities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of severities',
        'required' => false,
        'enum' => array (
          'INFO',
          'MINOR',
          'MAJOR',
          'CRITICAL',
          'BLOCKER',
        ),
      ),
      'since_leak_period' => array (
        'type' => 'string',
        'description' => 'To retrieve issues created since the leak period. If this parameter is set to a truthy value, createdAfter must not be set and one component id or key must be provided.',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'sonarsource_security' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of SonarSource security categories. Use \'others\' to select issues not associated with any category',
        'required' => false,
        'enum' => array (
          'buffer-overflow',
          'permission',
          'sql-injection',
          'command-injection',
          'path-traversal-injection',
          'ldap-injection',
          'xpath-injection',
          'rce',
          'dos',
          'ssrf',
          'csrf',
          'xss',
          'log-injection',
          'http-response-splitting',
          'open-redirect',
          'xxe',
          'object-injection',
          'weak-cryptography',
          'auth',
          'insecure-conf',
          'encrypt-data',
          'traceability',
          'file-manipulation',
          'others',
        ),
      ),
      'statuses' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of statuses',
        'required' => false,
        'enum' => array (
          'OPEN',
          'CONFIRMED',
          'REOPENED',
          'RESOLVED',
          'CLOSED',
        ),
      ),
      'tags' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of tags.',
        'required' => false,
      ),
      'types' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of types.',
        'required' => false,
        'enum' => array (
          'CODE_SMELL',
          'BUG',
          'VULNERABILITY',
        ),
      ),
    );
    protected const METHOD = 'GET';
    protected const PATH = '/api/issues/search';
    protected const PARAM_MAP = array (
      'additionalFields' => 'additional_fields',
      'asc' => 'asc',
      'assigned' => 'assigned',
      'assignees' => 'assignees',
      'author' => 'author',
      'branch' => 'branch',
      'cleanCodeAttributeCategories' => 'clean_code_attribute_categories',
      'complianceStandards' => 'compliance_standards',
      'componentKeys' => 'component_keys',
      'createdAfter' => 'created_after',
      'createdAt' => 'created_at',
      'createdBefore' => 'created_before',
      'createdInLast' => 'created_in_last',
      'cwe' => 'cwe',
      'facetMode' => 'facet_mode',
      'facets' => 'facets',
      'impactSeverities' => 'impact_severities',
      'impactSoftwareQualities' => 'impact_software_qualities',
      'issueStatuses' => 'issue_statuses',
      'issues' => 'issues',
      'languages' => 'languages',
      'onComponentOnly' => 'on_component_only',
      'organization' => 'organization',
      'owaspMobileTop10-2024' => 'owasp_mobile_top10_2024',
      'owaspTop10' => 'owasp_top10',
      'owaspTop10-2021' => 'owasp_top10_2021',
      'p' => 'p',
      'ps' => 'ps',
      'pullRequest' => 'pull_request',
      'resolutions' => 'resolutions',
      'resolved' => 'resolved',
      'rules' => 'rules',
      's' => 's',
      'severities' => 'severities',
      'sinceLeakPeriod' => 'since_leak_period',
      'sonarsourceSecurity' => 'sonarsource_security',
      'statuses' => 'statuses',
      'tags' => 'tags',
      'types' => 'types',
    );
}
