<?php

namespace OpenCompany\Integrations\SonarCloud\Tools;

/**
 * Search for a collection of relevant rules matching a specified query. Since 5.5, following fields in the response have been deprecated :- "effortToFixDescription" becomes "gapDescription"; - "debtRemFnCoeff" becomes "remFnGapMultiplier"; - "defaultDebtRemFnCoeff" becomes "defaultRemFnGapMultiplier"; - "debtRemFnOffset" becomes "remFnBaseEffort"; - "defaultDebtRemFnOffset" becomes "defaultRemFnBaseEffort"; - "debtOverloaded" becomes "remFnOverloaded";.
 *
 * Maps to the official SonarCloud Web API endpoint GET /api/rules/search.
 */
class SonarCloudRulesSearch extends AbstractSonarCloudTool
{
    protected const NAME = 'sonarcloud_rules_search';
    protected const DESCRIPTION = 'Search for a collection of relevant rules matching a specified query. Since 5.5, following fields in the response have been deprecated :- "effortToFixDescription" becomes "gapDescription"; - "debtRemFnCoeff" becomes "remFnGapMultiplier"; - "defaultDebtRemFnCoeff" becomes "defaultRemFnGapMultiplier"; - "debtRemFnOffset" becomes "remFnBaseEffort"; - "defaultDebtRemFnOffset" becomes "defaultRemFnBaseEffort"; - "debtOverloaded" becomes "remFnOverloaded";

Official SonarCloud Web API endpoint: GET /api/rules/search.';
    protected const PARAMETERS = array (
      'activation' => array (
        'type' => 'string',
        'description' => 'Filter rules that are activated or deactivated on the selected Quality profile. Ignored if the parameter \'qprofile\' is not set.',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'active_severities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of activation severities, i.e the severity of rules in Quality profiles.',
        'required' => false,
        'enum' => array (
          'INFO',
          'MINOR',
          'MAJOR',
          'CRITICAL',
          'BLOCKER',
        ),
      ),
      'asc' => array (
        'type' => 'string',
        'description' => 'Ascending sort',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'available_since' => array (
        'type' => 'string',
        'description' => 'Filters rules added since date. Format is yyyy-MM-dd',
        'required' => false,
      ),
      'clean_code_attribute_categories' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of Clean Code Attribute Categories',
        'required' => false,
        'enum' => array (
          'ADAPTABLE',
          'CONSISTENT',
          'INTENTIONAL',
          'RESPONSIBLE',
        ),
      ),
      'compliance_standards' => array (
        'type' => 'string',
        'description' => 'Set of compliance standards to filter on. Categories within a standard are comma-separated and behave as an \'or\'. Multiple standards are separated by an ampersand and behave as an \'and\'.',
        'required' => false,
      ),
      'cwe' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of CWE identifiers. Use \'unknown\' to select rules not associated to any CWE.',
        'required' => false,
      ),
      'f' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of the fields to be returned in response. All the fields are returned by default, except actives.Since 5.5, following fields have been deprecated :- "defaultDebtRemFn" becomes "defaultRemFn"; - "debtRemFn" becomes "remFn"; - "effortToFixDescription" becomes "gapDescription"; - "debtOverloaded" becomes "remFnOverloaded";',
        'required' => false,
        'enum' => array (
          'actives',
          'cleanCodeAttribute',
          'createdAt',
          'debtOverloaded',
          'debtRemFn',
          'defaultDebtRemFn',
          'defaultRemFn',
          'deprecatedKeys',
          'descriptionSections',
          'educationPrinciples',
          'effortToFixDescription',
          'gapDescription',
          'htmlDesc',
          'htmlNote',
          'impacts',
          'internalKey',
          'isExternal',
          'isTemplate',
          'lang',
          'langName',
          'mdDesc',
          'mdNote',
          'name',
          'noteLogin',
          'params',
          'remFn',
          'remFnOverloaded',
          'repo',
          'scope',
          'securityStandards',
          'severity',
          'status',
          'sysTags',
          'tags',
          'templateKey',
          'updatedAt',
        ),
      ),
      'facets' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of the facets to be computed. No facet is computed by default.',
        'required' => false,
        'enum' => array (
          'languages',
          'repositories',
          'tags',
          'severities',
          'active_severities',
          'statuses',
          'types',
          'true',
          'cwe',
          'owaspMobileTop10-2024',
          'owaspTop10',
          'owaspTop10-2021',
          'sonarsourceSecurity',
          'cleanCodeAttributeCategories',
          'impactSeverities',
          'impactSoftwareQualities',
          'complianceStandards',
        ),
      ),
      'impact_severities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of Software Quality Severities',
        'required' => false,
        'enum' => array (
          'INFO',
          'LOW',
          'MEDIUM',
          'HIGH',
          'BLOCKER',
        ),
      ),
      'impact_software_qualities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of Software Qualities',
        'required' => false,
        'enum' => array (
          'MAINTAINABILITY',
          'RELIABILITY',
          'SECURITY',
        ),
      ),
      'include_external' => array (
        'type' => 'string',
        'description' => 'Include external engine rules in the results',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'inheritance' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of values of inheritance for a rule within a quality profile. Used only if the parameter \'activation\' is set.',
        'required' => false,
        'enum' => array (
          'NONE',
          'INHERITED',
          'OVERRIDES',
        ),
      ),
      'is_template' => array (
        'type' => 'string',
        'description' => 'Filter template rules',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'languages' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of languages',
        'required' => false,
      ),
      'organization' => array (
        'type' => 'string',
        'description' => 'Organization key',
        'required' => false,
      ),
      'owasp_mobile_top10_2024' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Mobile Top 10 (2024) lowercase categories.',
        'required' => false,
        'enum' => array (
          'm1',
          'm2',
          'm3',
          'm4',
          'm5',
          'm6',
          'm7',
          'm8',
          'm9',
          'm10',
        ),
      ),
      'owasp_top10' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Top 10 lowercase categories.',
        'required' => false,
        'enum' => array (
          'a1',
          'a2',
          'a3',
          'a4',
          'a5',
          'a6',
          'a7',
          'a8',
          'a9',
          'a10',
        ),
      ),
      'owasp_top10_2021' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Top 10 (2021) lowercase categories.',
        'required' => false,
        'enum' => array (
          'a1',
          'a2',
          'a3',
          'a4',
          'a5',
          'a6',
          'a7',
          'a8',
          'a9',
          'a10',
        ),
      ),
      'p' => array (
        'type' => 'string',
        'description' => '1-based page number',
        'required' => false,
      ),
      'ps' => array (
        'type' => 'string',
        'description' => 'Page size. Must be greater than 0 and less or equal than 500',
        'required' => false,
      ),
      'q' => array (
        'type' => 'string',
        'description' => 'UTF-8 search query',
        'required' => false,
      ),
      'qprofile' => array (
        'type' => 'string',
        'description' => 'Quality profile key to filter on. Used only if the parameter \'activation\' is set.',
        'required' => false,
      ),
      'repositories' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of repositories',
        'required' => false,
      ),
      'rule_key' => array (
        'type' => 'string',
        'description' => 'Key of rule to search for',
        'required' => false,
      ),
      'rule_keys' => array (
        'type' => 'string',
        'description' => 'Rule keys',
        'required' => false,
      ),
      's' => array (
        'type' => 'string',
        'description' => 'Sort field',
        'required' => false,
        'enum' => array (
          'name',
          'updatedAt',
          'createdAt',
          'key',
        ),
      ),
      'severities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of default severities. Not the same than severity of rules in Quality profiles.',
        'required' => false,
        'enum' => array (
          'INFO',
          'MINOR',
          'MAJOR',
          'CRITICAL',
          'BLOCKER',
        ),
      ),
      'sonarsource_security' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of SonarSource security categories. Use \'others\' to select rules not associated with any category',
        'required' => false,
        'enum' => array (
          'buffer-overflow',
          'permission',
          'sql-injection',
          'command-injection',
          'path-traversal-injection',
          'ldap-injection',
          'xpath-injection',
          'rce',
          'dos',
          'ssrf',
          'csrf',
          'xss',
          'log-injection',
          'http-response-splitting',
          'open-redirect',
          'xxe',
          'object-injection',
          'weak-cryptography',
          'auth',
          'insecure-conf',
          'encrypt-data',
          'traceability',
          'file-manipulation',
          'others',
        ),
      ),
      'statuses' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of status codes',
        'required' => false,
        'enum' => array (
          'BETA',
          'DEPRECATED',
          'READY',
          'REMOVED',
        ),
      ),
      'tags' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of tags. Returned rules match any of the tags (OR operator)',
        'required' => false,
      ),
      'template_key' => array (
        'type' => 'string',
        'description' => 'Key of the template rule to filter on. Used to search for the custom rules based on this template.',
        'required' => false,
      ),
      'types' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of types. Returned rules match any of the tags (OR operator)',
        'required' => false,
        'enum' => array (
          'CODE_SMELL',
          'BUG',
          'VULNERABILITY',
          'SECURITY_HOTSPOT',
        ),
      ),
    );
    protected const METHOD = 'GET';
    protected const PATH = '/api/rules/search';
    protected const PARAM_MAP = array (
      'activation' => 'activation',
      'active_severities' => 'active_severities',
      'asc' => 'asc',
      'available_since' => 'available_since',
      'cleanCodeAttributeCategories' => 'clean_code_attribute_categories',
      'complianceStandards' => 'compliance_standards',
      'cwe' => 'cwe',
      'f' => 'f',
      'facets' => 'facets',
      'impactSeverities' => 'impact_severities',
      'impactSoftwareQualities' => 'impact_software_qualities',
      'include_external' => 'include_external',
      'inheritance' => 'inheritance',
      'is_template' => 'is_template',
      'languages' => 'languages',
      'organization' => 'organization',
      'owaspMobileTop10-2024' => 'owasp_mobile_top10_2024',
      'owaspTop10' => 'owasp_top10',
      'owaspTop10-2021' => 'owasp_top10_2021',
      'p' => 'p',
      'ps' => 'ps',
      'q' => 'q',
      'qprofile' => 'qprofile',
      'repositories' => 'repositories',
      'rule_key' => 'rule_key',
      'rule_keys' => 'rule_keys',
      's' => 's',
      'severities' => 'severities',
      'sonarsourceSecurity' => 'sonarsource_security',
      'statuses' => 'statuses',
      'tags' => 'tags',
      'template_key' => 'template_key',
      'types' => 'types',
    );
}
