<?php

namespace OpenCompany\Integrations\MercadoPago\Tools;

use OpenCompany\Integrations\MercadoPago\MercadoPagoService;
use OpenCompany\IntegrationCore\Contracts\Tool;
use OpenCompany\IntegrationCore\Support\ToolResult;

/**
 * Create a Mercado Pago payment.
 *
 * Builds the core payment payload with amount, method, payer email, and
 * optional card token, installments, description, and external reference.
 */
class MercadoPagoCreatePayment implements Tool
{
    /**
     * @param  MercadoPagoService  $service  The Mercado Pago API service.
     */
    public function __construct(
        private MercadoPagoService $service,
    ) {}

    public function name(): string
    {
        return 'mercado_pago_create_payment';
    }

    public function description(): string
    {
        return 'Create a new payment in Mercado Pago. Requires the transaction amount, payment method ID, and payer email. Optionally specify the number of installments.';
    }

    public function parameters(): array
    {
        return [
            'transaction_amount' => ['type' => 'number', 'required' => true, 'description' => 'The amount to charge (positive number, e.g., 100.50).'],
            'payment_method_id' => ['type' => 'string', 'required' => true, 'description' => 'The payment method ID (e.g., "visa", "master", "pix", "boleto", "amex").'],
            'payer_email' => ['type' => 'string', 'required' => true, 'description' => 'The payer\'s email address.'],
            'token' => ['type' => 'string', 'description' => 'Card token generated by Mercado Pago client-side SDK. Required for card payments.'],
            'installments' => ['type' => 'integer', 'description' => 'Number of installments for credit card payments (default: 1).'],
            'description' => ['type' => 'string', 'description' => 'Payment description shown in Mercado Pago records.'],
            'external_reference' => ['type' => 'string', 'description' => 'Merchant-side order or payment reference.'],
        ];
    }

    /**
     * Create a payment from the provided payment payload.
     *
     * @param  array<string, mixed>  $args  Tool arguments.
     */
    public function execute(array $args): ToolResult
    {
        try {
            if (!$this->service->isConfigured()) {
                return ToolResult::error('Mercado Pago integration is not configured.');
            }

            if (empty($args['transaction_amount'])) {
                return ToolResult::error('Transaction amount is required.');
            }

            if (empty($args['payment_method_id'])) {
                return ToolResult::error('Payment method ID is required.');
            }

            if (empty($args['payer_email'])) {
                return ToolResult::error('Payer email is required.');
            }

            $data = [
                'transaction_amount' => (float) $args['transaction_amount'],
                'payment_method_id' => $args['payment_method_id'],
                'payer' => [
                    'email' => $args['payer_email'],
                ],
            ];

            if (isset($args['installments'])) {
                $data['installments'] = (int) $args['installments'];
            }

            if (isset($args['token'])) {
                $data['token'] = $args['token'];
            }

            if (isset($args['description'])) {
                $data['description'] = $args['description'];
            }

            if (isset($args['external_reference'])) {
                $data['external_reference'] = $args['external_reference'];
            }

            $result = $this->service->createPayment($data);

            return ToolResult::success($result);
        } catch (\Throwable $e) {
            return ToolResult::error($e->getMessage());
        }
    }
}
