<?php

namespace OpenCompany\Integrations\Pulumi\Tools;

/**
 * UpdateSummary.
 *
 * Maps to the official Pulumi Cloud endpoint get /api/console/stacks/{orgName}/{projectName}/{stackName}/updates/{updateID}/summary.
 */
class PulumiStacksUpdateSummary extends AbstractPulumiTool
{
    protected const NAME = 'pulumi_stacks_update_summary';
    protected const DESCRIPTION = 'UpdateSummary

Official Pulumi Cloud endpoint: GET /api/console/stacks/{orgName}/{projectName}/{stackName}/updates/{updateID}/summary

Returns a human-readable summary of a specific update, identified by its update ID. The summary is formatted in the same manner as generated by the CLI on \'pulumi up\', including a tree view of resource changes, create/update/delete counts, and the overall result. This endpoint is optimized for display in the Pulumi Cloud web console. Returns 404 if the update does not exist.';
    protected const PARAMETERS = array (
  'org_name' =>
  array (
    'type' => 'string',
    'required' => true,
    'description' => 'Path parameter `orgName` from the official Pulumi Cloud API operation. The organization name',
  ),
  'project_name' =>
  array (
    'type' => 'string',
    'required' => true,
    'description' => 'Path parameter `projectName` from the official Pulumi Cloud API operation. The project name',
  ),
  'stack_name' =>
  array (
    'type' => 'string',
    'required' => true,
    'description' => 'Path parameter `stackName` from the official Pulumi Cloud API operation. The stack name',
  ),
  'update_id' =>
  array (
    'type' => 'string',
    'required' => true,
    'description' => 'Path parameter `updateID` from the official Pulumi Cloud API operation. The update ID',
  ),
);
    protected const METHOD = 'get';
    protected const PATH = '/api/console/stacks/{orgName}/{projectName}/{stackName}/updates/{updateID}/summary';
    protected const PATH_PARAMS = array (
  'orgName' => 'org_name',
  'projectName' => 'project_name',
  'stackName' => 'stack_name',
  'updateID' => 'update_id',
);
    protected const QUERY_PARAMS = array (
);
    protected const HEADER_PARAMS = array (
);
    protected const BODY_REQUIRED = false;
}
