<?php

namespace OpenCompany\Integrations\DbtCloud\Tools;

/**
 * Retry Run.
 *
 * Maps to the official dbt Cloud v2 endpoint post /api/v2/accounts/{account_id}/runs/{run_id}/retry/.
 */
class DbtCloudV2RetryRun extends AbstractDbtCloudTool
{
    protected const NAME = 'dbt_cloud_v2_retry_run';
    protected const DESCRIPTION = 'Retry Run

Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/runs/{run_id}/retry/

Use this endpoint to retry a failed run. When this endpoint returns a successful response, a new run will be enqueued. Users can poll the Get Run endpoint until it completes. After the run has completed, users can use the Get Run Artifact endpoint to download artifacts generated by the run.';
    protected const PARAMETERS = array (
  'account_id' =>
  array (
    'type' => 'integer',
    'description' => 'account_id parameter.',
    'required' => true,
  ),
  'run_id' =>
  array (
    'type' => 'integer',
    'description' => 'run_id parameter.',
    'required' => true,
  ),
);
    protected const METHOD = 'post';
    protected const PATH = '/api/v2/accounts/{account_id}/runs/{run_id}/retry/';
    protected const PATH_PARAMS = array (
  'account_id' => 'account_id',
  'run_id' => 'run_id',
);
    protected const QUERY_PARAMS = array (
);
    protected const HEADER_PARAMS = array (
);
    protected const BODY_REQUIRED = false;
}
