<?php

namespace OpenCompany\Integrations\DbtCloud\Tools;

/**
 * Trigger Job Run.
 *
 * Maps to the official dbt Cloud v2 endpoint post /api/v2/accounts/{account_id}/jobs/{job_id}/run/.
 */
class DbtCloudV2TriggerJobRun extends AbstractDbtCloudTool
{
    protected const NAME = 'dbt_cloud_v2_trigger_job_run';
    protected const DESCRIPTION = 'Trigger Job Run

Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/jobs/{job_id}/run/

Use this endpoint to kick off a run for a job. When this endpoint returns a successful response, a new run will be enqueued for the account. Users can poll the Get run endpoint to poll the run until it completes. After the run has completed, users can use the Get run artifact endpoint to download artifacts generated by the run.';
    protected const PARAMETERS = array (
  'account_id' =>
  array (
    'type' => 'integer',
    'description' => 'account_id parameter.',
    'required' => true,
  ),
  'job_id' =>
  array (
    'type' => 'integer',
    'description' => 'job_id parameter.',
    'required' => true,
  ),
  'body' =>
  array (
    'type' => 'object',
    'description' => 'JSON request body matching the dbt Cloud API schema.',
    'required' => true,
  ),
);
    protected const METHOD = 'post';
    protected const PATH = '/api/v2/accounts/{account_id}/jobs/{job_id}/run/';
    protected const PATH_PARAMS = array (
  'account_id' => 'account_id',
  'job_id' => 'job_id',
);
    protected const QUERY_PARAMS = array (
);
    protected const HEADER_PARAMS = array (
);
    protected const BODY_REQUIRED = true;
}
