<?php

namespace OpenCompany\Integrations\DbtCloud\Tools;

/**
 * Retry Failed Job.
 *
 * Maps to the official dbt Cloud v2 endpoint post /api/v2/accounts/{account_id}/jobs/{job_id}/rerun/.
 */
class DbtCloudV2RetryFailedJob extends AbstractDbtCloudTool
{
    protected const NAME = 'dbt_cloud_v2_retry_failed_job';
    protected const DESCRIPTION = 'Retry Failed Job

Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/jobs/{job_id}/rerun/

Use this endpoint to retry a failed run for a job from the point of failure, if the run failed. Otherwise trigger a new run. When this endpoint returns a successful response, a new run will be enqueued for the account. Users can poll the Get run endpoint to poll the run until it completes. After the run has completed, users can use the Get run artifact endpoint to download artifacts generated by the run.';
    protected const PARAMETERS = array (
  'account_id' =>
  array (
    'type' => 'integer',
    'description' => 'account_id parameter.',
    'required' => true,
  ),
  'job_id' =>
  array (
    'type' => 'integer',
    'description' => 'job_id parameter.',
    'required' => true,
  ),
);
    protected const METHOD = 'post';
    protected const PATH = '/api/v2/accounts/{account_id}/jobs/{job_id}/rerun/';
    protected const PATH_PARAMS = array (
  'account_id' => 'account_id',
  'job_id' => 'job_id',
);
    protected const QUERY_PARAMS = array (
);
    protected const HEADER_PARAMS = array (
);
    protected const BODY_REQUIRED = false;
}
