<?php

namespace OpenCompany\Integrations\SonarCloud;

use Illuminate\Support\Facades\Http;
use OpenCompany\IntegrationCore\Contracts\ConfigurableIntegration;
use OpenCompany\IntegrationCore\Contracts\CredentialResolver;
use OpenCompany\IntegrationCore\Contracts\HasIntegrationCapabilities;
use OpenCompany\IntegrationCore\Contracts\Tool;
use OpenCompany\IntegrationCore\Contracts\ToolProvider;

/**
 * Tool catalog and configuration metadata for SonarCloud.
 *
 * Exposes the official SonarCloud Web API registry as endpoint-specific agent
 * tools and resolves account-specific bearer tokens.
 */
class SonarCloudToolProvider implements ToolProvider, ConfigurableIntegration, HasIntegrationCapabilities
{
    /** @return array<string, mixed> */ public function integrationCapabilities(): array { return ['auth' => ['strategy' => 'bearer_token', 'legacy_auth_type' => 'api_token', 'credential_mode' => 'secret', 'setup_flows' => ['manual_secret'], 'requires_browser_for_setup' => false, 'refreshable' => false, 'token_keys' => [], 'notes' => ['Send a SonarCloud token using Authorization: Bearer <token>.']], 'host_availability' => ['web' => ['setup_supported' => true, 'runtime_supported' => true, 'setup_mode' => 'manual_secret'], 'cli' => ['setup_supported' => true, 'runtime_supported' => true, 'setup_mode' => 'manual_secret', 'runtime_mode' => 'normal']], 'runtime_requirements' => [], 'compatibility' => ['web_setup_supported' => true, 'web_runtime_supported' => true, 'cli_setup_supported' => true, 'cli_runtime_supported' => true]]; }
    public function appName(): string { return 'sonarcloud'; } public function appMeta(): array { return ['label' => 'SonarCloud', 'description' => 'Code quality, issues, measures, organizations, quality gates, projects, users, and permissions', 'icon' => 'ph:cloud-check', 'logo' => 'ph:cloud-check']; }
    public function integrationMeta(): array { return ['name' => 'SonarCloud', 'description' => 'Manage SonarCloud organizations, projects, issues, measures, quality gates, rules, users, permissions, and webhooks through the official Web API.', 'icon' => 'ph:cloud-check', 'logo' => 'ph:cloud-check', 'category' => 'data', 'badge' => 'verified', 'docs_url' => 'https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/web-api']; }
    public function configSchema(): array { return [['key' => 'api_token', 'type' => 'secret', 'label' => 'Personal Access Token', 'required' => true], ['key' => 'url', 'type' => 'url', 'label' => 'Cloud URL', 'placeholder' => 'https://sonarcloud.io', 'default' => 'https://sonarcloud.io']]; }
    /** @param  array<string, mixed>  $config  Credential and endpoint settings. @return array{success: bool, message?: string, error?: string} */ public function testConnection(array $config): array { $token = (string) ($config['api_token'] ?? ''); $baseUrl = rtrim((string) ($config['url'] ?? 'https://sonarcloud.io'), '/'); if ($token === '') return ['success' => false, 'error' => 'SonarCloud token is required.']; try { $response = Http::withHeaders(['Authorization' => 'Bearer '.$token, 'Accept' => 'application/json'])->timeout(10)->get($baseUrl.'/api/authentication/validate'); if (! $response->successful()) return ['success' => false, 'error' => 'SonarCloud API returned HTTP '.$response->status().'.']; if ($response->json('valid') === false) return ['success' => false, 'error' => 'SonarCloud token was rejected.']; return ['success' => true, 'message' => 'Connected to SonarCloud at '.$baseUrl.'.']; } catch (\Throwable $e) { return ['success' => false, 'error' => $e->getMessage()]; } }
    public function validationRules(): array { return ['api_token' => 'required|string', 'url' => 'required|url']; } public function credentialFields(): array { return [['key' => 'api_token', 'type' => 'secret', 'label' => 'Personal Access Token', 'required' => true], ['key' => 'url', 'type' => 'url', 'label' => 'Cloud URL', 'required' => true, 'default' => 'https://sonarcloud.io']]; }
    public function tools(): array { return [
  'sonarcloud_authentication_logout' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudAuthenticationLogout',
  'type' => 'write',
  'name' => 'Authentication Logout',
  'description' => 'Logout a user.  Official SonarCloud Web API endpoint: POST /api/authentication/logout.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_authentication_validate' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudAuthenticationValidate',
  'type' => 'read',
  'name' => 'Authentication Validate',
  'description' => 'Check credentials. Returns true for anonymous user.  Official SonarCloud Web API endpoint: GET /api/authentication/validate.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_ce_activity' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudCeActivity',
  'type' => 'read',
  'name' => 'Ce Activity',
  'description' => 'Search for tasks. Either componentId or component can be provided, but not both. Requires the project administration permission if componentId or component is set.  Official SonarCloud Web API endpoint: GET /api/ce/activity.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_ce_activity_status' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudCeActivityStatus',
  'type' => 'read',
  'name' => 'Ce Activity Status',
  'description' => 'Returns CE activity related metrics. Requires \'Administer\' permission on the specified project.  Official SonarCloud Web API endpoint: GET /api/ce/activity_status.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_ce_component' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudCeComponent',
  'type' => 'read',
  'name' => 'Ce Component',
  'description' => 'Get the pending tasks, in-progress tasks and the last executed task of a given component (usually a project). Requires the following permission: \'Browse\' on the specified component. Either \'componentId\' or \'component\' must be provided.  Official SonarCloud Web',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_ce_task' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudCeTask',
  'type' => 'read',
  'name' => 'Ce Task',
  'description' => 'Give Compute Engine task details such as type, status, duration and associated component. Requires \'Execute Analysis\' permission.  Official SonarCloud Web API endpoint: GET /api/ce/task.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_components_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudComponentsSearch',
  'type' => 'read',
  'name' => 'Components Search',
  'description' => 'Search for projects. Used to provide the ability to search for any component but this option has been removed and webservice \'api/components/tree\' should be used instead for this purpose  Official SonarCloud Web API endpoint: GET /api/components/search.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_components_show' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudComponentsShow',
  'type' => 'read',
  'name' => 'Components Show',
  'description' => 'Returns a component (file, directory, project) and its ancestors. The ancestors are ordered from the parent to the root project. Requires the following permission: \'Browse\' on the project of the specified component.  Official SonarCloud Web API endpoint: GET /',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_components_tree' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudComponentsTree',
  'type' => 'read',
  'name' => 'Components Tree',
  'description' => 'Navigate through components based on the chosen strategy. Requires the following permission: \'Browse\' on the specified project. When limiting search with the q parameter, directories are not returned.  Official SonarCloud Web API endpoint: GET /api/components/',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_duplications_show' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudDuplicationsShow',
  'type' => 'read',
  'name' => 'Duplications Show',
  'description' => 'Get duplications. Require Browse permission on file\'s project  Official SonarCloud Web API endpoint: GET /api/duplications/show.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_favorites_add' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudFavoritesAdd',
  'type' => 'write',
  'name' => 'Favorites Add',
  'description' => 'Add a project as favorite for the authenticated user. Only 100 components can be added as favorite. Requires authentication and the following permission: \'Browse\' on the project.  Official SonarCloud Web API endpoint: POST /api/favorites/add.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_favorites_remove' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudFavoritesRemove',
  'type' => 'write',
  'name' => 'Favorites Remove',
  'description' => 'Remove a component (project, directory, file etc.) as favorite for the authenticated user. Requires authentication.  Official SonarCloud Web API endpoint: POST /api/favorites/remove.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_favorites_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudFavoritesSearch',
  'type' => 'read',
  'name' => 'Favorites Search',
  'description' => 'Search for the authenticated user favorites. Requires authentication.  Official SonarCloud Web API endpoint: GET /api/favorites/search.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_favourites_index' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudFavouritesIndex',
  'type' => 'read',
  'name' => 'Favourites Index',
  'description' => 'The web service is removed and you\'re invited to use api/favorites instead  Official SonarCloud Web API endpoint: GET /api/favourites/index.  Deprecated since SonarCloud 6.3; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_hotspots_change_status' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudHotspotsChangeStatus',
  'type' => 'write',
  'name' => 'Hotspots Change Status',
  'description' => 'Change the status of a Security Hotpot. Requires the \'Administer Security Hotspot\' permission.  Official SonarCloud Web API endpoint: POST /api/hotspots/change_status.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_hotspots_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudHotspotsSearch',
  'type' => 'read',
  'name' => 'Hotspots Search',
  'description' => 'Search for Security Hotpots.  Official SonarCloud Web API endpoint: GET /api/hotspots/search.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_hotspots_show' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudHotspotsShow',
  'type' => 'read',
  'name' => 'Hotspots Show',
  'description' => 'Provides the details of a Security Hotspot.  Official SonarCloud Web API endpoint: GET /api/hotspots/show.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_issues_add_comment' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesAddComment',
  'type' => 'write',
  'name' => 'Issues Add Comment',
  'description' => 'Add a comment. Requires authentication and the following permission: \'Browse\' on the project of the specified issue.  Official SonarCloud Web API endpoint: POST /api/issues/add_comment.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_issues_assign' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesAssign',
  'type' => 'write',
  'name' => 'Issues Assign',
  'description' => 'Assign/Unassign an issue. Requires authentication and Browse permission on project  Official SonarCloud Web API endpoint: POST /api/issues/assign.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_issues_authors' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesAuthors',
  'type' => 'read',
  'name' => 'Issues Authors',
  'description' => 'Search SCM accounts which match a given query. Requires authentication.  Official SonarCloud Web API endpoint: GET /api/issues/authors.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_issues_bulk_change' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesBulkChange',
  'type' => 'write',
  'name' => 'Issues Bulk Change',
  'description' => 'Bulk change on issues. Requires authentication.  Official SonarCloud Web API endpoint: POST /api/issues/bulk_change.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_issues_changelog' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesChangelog',
  'type' => 'read',
  'name' => 'Issues Changelog',
  'description' => 'Display changelog of an issue. Requires the \'Browse\' permission on the project of the specified issue.  Official SonarCloud Web API endpoint: GET /api/issues/changelog.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_issues_delete_comment' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesDeleteComment',
  'type' => 'write',
  'name' => 'Issues Delete Comment',
  'description' => 'Delete a comment. Requires authentication and the following permission: \'Browse\' on the project of the specified issue.  Official SonarCloud Web API endpoint: POST /api/issues/delete_comment.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_issues_do_transition' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesDoTransition',
  'type' => 'write',
  'name' => 'Issues Do Transition',
  'description' => 'Do workflow transition on an issue. Requires authentication and Browse permission on project. The transitions \'accept\', \'wontfix\', and \'falsepositive\' require the permission \'Administer Issues\'. The transitions involving security hotspots require the permissio',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_issues_edit_comment' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesEditComment',
  'type' => 'write',
  'name' => 'Issues Edit Comment',
  'description' => 'Edit a comment. Requires authentication and the following permission: \'Browse\' on the project of the specified issue.  Official SonarCloud Web API endpoint: POST /api/issues/edit_comment.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_issues_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesSearch',
  'type' => 'read',
  'name' => 'Issues Search',
  'description' => 'Search for issues. Requires the \'Browse\' permission on the specified project(s).  Official SonarCloud Web API endpoint: GET /api/issues/search.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_issues_set_severity' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesSetSeverity',
  'type' => 'write',
  'name' => 'Issues Set Severity',
  'description' => 'Change severity. Requires the following permissions: - \'Authentication\'; - \'Browse\' rights on project of the specified issue; - \'Administer Issues\' rights on project of the specified issue;  Official SonarCloud Web API endpoint: POST /api/issues/set_severity. ',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_issues_set_tags' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesSetTags',
  'type' => 'write',
  'name' => 'Issues Set Tags',
  'description' => 'Set tags on an issue. Requires authentication and Browse permission on project  Official SonarCloud Web API endpoint: POST /api/issues/set_tags.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_issues_set_type' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesSetType',
  'type' => 'write',
  'name' => 'Issues Set Type',
  'description' => 'Change type of issue, for instance from \'code smell\' to \'bug\'. Requires the following permissions: - \'Authentication\'; - \'Browse\' rights on project of the specified issue; - \'Administer Issues\' rights on project of the specified issue;  Official SonarCloud Web',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_issues_tags' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudIssuesTags',
  'type' => 'read',
  'name' => 'Issues Tags',
  'description' => 'List tags matching a given query  Official SonarCloud Web API endpoint: GET /api/issues/tags.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_languages_list' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudLanguagesList',
  'type' => 'read',
  'name' => 'Languages List',
  'description' => 'List supported programming languages  Official SonarCloud Web API endpoint: GET /api/languages/list.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_measures_component' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudMeasuresComponent',
  'type' => 'read',
  'name' => 'Measures Component',
  'description' => 'Return component with specified measures. The componentId or the component parameter must be provided. Requires the following permission: \'Browse\' on the project of specified component.  Official SonarCloud Web API endpoint: GET /api/measures/component.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_measures_component_tree' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudMeasuresComponentTree',
  'type' => 'read',
  'name' => 'Measures Component Tree',
  'description' => 'Navigate through components based on the chosen strategy with specified measures. The baseComponentId or the component parameter must be provided. Requires the following permission: \'Browse\' on the specified project. When limiting search with the q parameter, ',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_measures_search_history' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudMeasuresSearchHistory',
  'type' => 'read',
  'name' => 'Measures Search History',
  'description' => 'Search measures history of a component. Measures are ordered chronologically. Pagination applies to the number of measures for each metric. Requires the following permission: \'Browse\' on the specified component  Official SonarCloud Web API endpoint: GET /api/m',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_metrics_domains' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudMetricsDomains',
  'type' => 'read',
  'name' => 'Metrics Domains',
  'description' => 'List all custom metric domains.  Official SonarCloud Web API endpoint: GET /api/metrics/domains.  Deprecated since SonarCloud 7.7; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_metrics_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudMetricsSearch',
  'type' => 'read',
  'name' => 'Metrics Search',
  'description' => 'Search for metrics  Official SonarCloud Web API endpoint: GET /api/metrics/search.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_metrics_types' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudMetricsTypes',
  'type' => 'read',
  'name' => 'Metrics Types',
  'description' => 'List all available metric types.  Official SonarCloud Web API endpoint: GET /api/metrics/types.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_notifications_add' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudNotificationsAdd',
  'type' => 'write',
  'name' => 'Notifications Add',
  'description' => 'Add a notification for the authenticated user. Requires one of the following permissions: - Authentication if no login is provided. If a project is provided, requires the \'Browse\' permission on the specified project.; - If a project is provided, requires the \'',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_notifications_list' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudNotificationsList',
  'type' => 'read',
  'name' => 'Notifications List',
  'description' => 'List notifications of the authenticated user  Official SonarCloud Web API endpoint: GET /api/notifications/list.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_notifications_remove' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudNotificationsRemove',
  'type' => 'write',
  'name' => 'Notifications Remove',
  'description' => 'Remove a notification for the authenticated user  Official SonarCloud Web API endpoint: POST /api/notifications/remove.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_add_group' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsAddGroup',
  'type' => 'write',
  'name' => 'Permissions Add Group',
  'description' => 'Add permission to a group. This service defaults to global permissions, but can be limited to project permissions by providing project id or project key. The group name or group id must be provided. Requires the permission \'Administer\' on the specified project',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_add_group_to_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsAddGroupToTemplate',
  'type' => 'write',
  'name' => 'Permissions Add Group To Template',
  'description' => 'Add a group to a permission template. The group id or group name must be provided. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/add_group_to_template.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_add_project_creator_to_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsAddProjectCreatorToTemplate',
  'type' => 'write',
  'name' => 'Permissions Add Project Creator To Template',
  'description' => 'Add a project creator to a permission template. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/add_project_creator_to_template.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_add_user' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsAddUser',
  'type' => 'write',
  'name' => 'Permissions Add User',
  'description' => 'Add permission to a user. This service defaults to global permissions, but can be limited to project permissions by providing project id or project key. Requires the permission \'Administer\' on the specified project.  Official SonarCloud Web API endpoint: POST ',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_add_user_to_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsAddUserToTemplate',
  'type' => 'write',
  'name' => 'Permissions Add User To Template',
  'description' => 'Add a user to a permission template. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/add_user_to_template.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_apply_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsApplyTemplate',
  'type' => 'write',
  'name' => 'Permissions Apply Template',
  'description' => 'Apply a permission template to one project. The project id or project key must be provided. The template id or name must be provided. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/apply_t',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_bulk_apply_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsBulkApplyTemplate',
  'type' => 'write',
  'name' => 'Permissions Bulk Apply Template',
  'description' => 'Apply a permission template to several projects. The template id or name must be provided. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/bulk_apply_template.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_create_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsCreateTemplate',
  'type' => 'write',
  'name' => 'Permissions Create Template',
  'description' => 'Create a permission template. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/create_template.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_delete_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsDeleteTemplate',
  'type' => 'write',
  'name' => 'Permissions Delete Template',
  'description' => 'Delete a permission template. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/delete_template.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_remove_group' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsRemoveGroup',
  'type' => 'write',
  'name' => 'Permissions Remove Group',
  'description' => 'Remove a permission from a group. This service defaults to global permissions, but can be limited to project permissions by providing project id or project key. The group id or group name must be provided, not both. Requires the permission \'Administer\' on the ',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_remove_group_from_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsRemoveGroupFromTemplate',
  'type' => 'write',
  'name' => 'Permissions Remove Group From Template',
  'description' => 'Remove a group from a permission template. The group id or group name must be provided. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/remove_group_from_template.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_remove_project_creator_from_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsRemoveProjectCreatorFromTemplate',
  'type' => 'write',
  'name' => 'Permissions Remove Project Creator From Template',
  'description' => 'Remove a project creator from a permission template. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/remove_project_creator_from_template.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_remove_user' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsRemoveUser',
  'type' => 'write',
  'name' => 'Permissions Remove User',
  'description' => 'Remove permission from a user. This service defaults to global permissions, but can be limited to project permissions by providing project id or project key. Requires the permission \'Administer\' on the specified project.  Official SonarCloud Web API endpoint: ',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_remove_user_from_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsRemoveUserFromTemplate',
  'type' => 'write',
  'name' => 'Permissions Remove User From Template',
  'description' => 'Remove a user from a permission template. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/remove_user_from_template.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_search_templates' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsSearchTemplates',
  'type' => 'read',
  'name' => 'Permissions Search Templates',
  'description' => 'List permission templates. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: GET /api/permissions/search_templates.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_permissions_set_default_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsSetDefaultTemplate',
  'type' => 'write',
  'name' => 'Permissions Set Default Template',
  'description' => 'Set a permission template as default. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/set_default_template.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_permissions_update_template' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPermissionsUpdateTemplate',
  'type' => 'write',
  'name' => 'Permissions Update Template',
  'description' => 'Update a permission template. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: POST /api/permissions/update_template.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_analyses_create_event' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectAnalysesCreateEvent',
  'type' => 'write',
  'name' => 'Project Analyses Create Event',
  'description' => 'Create a project analysis event. Only event of category \'VERSION\' and \'OTHER\' can be created. Requires the permission \'Administer\' on the specified project.  Official SonarCloud Web API endpoint: POST /api/project_analyses/create_event.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_analyses_delete' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectAnalysesDelete',
  'type' => 'write',
  'name' => 'Project Analyses Delete',
  'description' => 'Delete a project analysis. Requires the permission \'Administer\' on the project of the specified analysis.  Official SonarCloud Web API endpoint: POST /api/project_analyses/delete.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_analyses_delete_event' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectAnalysesDeleteEvent',
  'type' => 'write',
  'name' => 'Project Analyses Delete Event',
  'description' => 'Delete a project analysis event. Only event of category \'VERSION\' and \'OTHER\' can be deleted. Requires the permission \'Administer\' on the specified project.  Official SonarCloud Web API endpoint: POST /api/project_analyses/delete_event.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_analyses_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectAnalysesSearch',
  'type' => 'read',
  'name' => 'Project Analyses Search',
  'description' => 'Search a project analyses and attached events. Requires the following permission: \'Browse\' on the specified project  Official SonarCloud Web API endpoint: GET /api/project_analyses/search.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_project_analyses_set_baseline' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectAnalysesSetBaseline',
  'type' => 'write',
  'name' => 'Project Analyses Set Baseline',
  'description' => 'Set an analysis as the baseline of the New Code Period on a project or a long-lived branch. This manually set baseline overrides the `sonar.leak.period` setting. Requires the permission \'Administer\' on the specified project.  Official SonarCloud Web API endpoi',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_analyses_unset_baseline' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectAnalysesUnsetBaseline',
  'type' => 'write',
  'name' => 'Project Analyses Unset Baseline',
  'description' => 'Unset any manually-set New Code Period baseline on a project or a long-lived branch. Unsetting a manual baseline restores the use of the `sonar.leak.period` setting. Requires the permission \'Administer\' on the specified project.  Official SonarCloud Web API en',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_analyses_update_event' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectAnalysesUpdateEvent',
  'type' => 'write',
  'name' => 'Project Analyses Update Event',
  'description' => 'Update a project analysis event. Only events of category \'VERSION\' and \'OTHER\' can be updated. Requires the permission \'Administer\' on the specified project.  Official SonarCloud Web API endpoint: POST /api/project_analyses/update_event.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_badges_ai_code_assurance' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectBadgesAiCodeAssurance',
  'type' => 'read',
  'name' => 'Project Badges Ai Code Assurance',
  'description' => 'Generate a badge for project\'s AI assurance as an SVG. Requires \'Browse\' permission on the specified project.  Official SonarCloud Web API endpoint: GET /api/project_badges/ai_code_assurance.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_project_badges_measure' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectBadgesMeasure',
  'type' => 'read',
  'name' => 'Project Badges Measure',
  'description' => 'Generate badge for project\'s measure as an SVG. Requires a security token for private projects.  Official SonarCloud Web API endpoint: GET /api/project_badges/measure.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_project_badges_quality_gate' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectBadgesQualityGate',
  'type' => 'read',
  'name' => 'Project Badges Quality Gate',
  'description' => 'Generate badge for project\'s quality gate as an SVG. Requires a security token for private projects.  Official SonarCloud Web API endpoint: GET /api/project_badges/quality_gate.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_project_branches_delete' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectBranchesDelete',
  'type' => 'write',
  'name' => 'Project Branches Delete',
  'description' => 'Delete a non-main branch of a project. Requires \'Administer\' rights on the specified project.  Official SonarCloud Web API endpoint: POST /api/project_branches/delete.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_branches_list' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectBranchesList',
  'type' => 'read',
  'name' => 'Project Branches List',
  'description' => 'List the branches of a project. The statistics are the overall counts on long branches, and the count of issues detected on the changed code on short branches, and are only provided if the project parameter is specified. If the project parameter is specified, ',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_project_branches_rename' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectBranchesRename',
  'type' => 'write',
  'name' => 'Project Branches Rename',
  'description' => 'Rename the main branch of a project. Requires \'Administer\' permission on the specified project.  Official SonarCloud Web API endpoint: POST /api/project_branches/rename.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_links_create' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectLinksCreate',
  'type' => 'write',
  'name' => 'Project Links Create',
  'description' => 'Create a new project link. Requires \'Administer\' permission on the specified project, or global \'Administer\' permission.  Official SonarCloud Web API endpoint: POST /api/project_links/create.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_links_delete' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectLinksDelete',
  'type' => 'write',
  'name' => 'Project Links Delete',
  'description' => 'Delete existing project link. Requires \'Administer\' permission on the specified project, or global \'Administer\' permission.  Official SonarCloud Web API endpoint: POST /api/project_links/delete.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_links_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectLinksSearch',
  'type' => 'read',
  'name' => 'Project Links Search',
  'description' => 'List links of a project. The \'projectId\' or \'projectKey\' must be provided. Requires one of the following permissions:- \'Administer\' rights on the specified project; - \'Browse\' on the specified project;  Official SonarCloud Web API endpoint: GET /api/project_li',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_project_pull_requests_delete' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectPullRequestsDelete',
  'type' => 'write',
  'name' => 'Project Pull Requests Delete',
  'description' => 'Delete a pull request. Requires \'Administer\' rights on the specified project.  Official SonarCloud Web API endpoint: POST /api/project_pull_requests/delete.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_project_pull_requests_list' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectPullRequestsList',
  'type' => 'read',
  'name' => 'Project Pull Requests List',
  'description' => 'List the pull requests of a project. One of the following permissions is required: - \'Browse\' rights on the specified project; - \'Execute Analysis\' rights on the specified project;  Official SonarCloud Web API endpoint: GET /api/project_pull_requests/list.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_project_tags_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectTagsSearch',
  'type' => 'read',
  'name' => 'Project Tags Search',
  'description' => 'Search tags  Official SonarCloud Web API endpoint: GET /api/project_tags/search.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_project_tags_set' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectTagsSet',
  'type' => 'write',
  'name' => 'Project Tags Set',
  'description' => 'Set tags on a project. Requires the following permission: \'Administer\' rights on the specified project  Official SonarCloud Web API endpoint: POST /api/project_tags/set.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_projects_bulk_delete' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectsBulkDelete',
  'type' => 'write',
  'name' => 'Projects Bulk Delete',
  'description' => 'Delete one or several projects. Only the 1\'000 first items in project filters are taken into account. Requires \'Administer System\' permission. At least one parameter is required among analyzedBefore, projects and q  Official SonarCloud Web API endpoint: POST /',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_projects_bulk_update_key' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectsBulkUpdateKey',
  'type' => 'write',
  'name' => 'Projects Bulk Update Key',
  'description' => 'Bulk update a project or module key and all its sub-components keys. The bulk update allows to replace a part of the current key by another string on the current project and all its sub-modules. It\'s possible to simulate the bulk update by setting the paramete',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_projects_create' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectsCreate',
  'type' => 'write',
  'name' => 'Projects Create',
  'description' => 'Create a project. Requires \'Create Projects\' permission  Official SonarCloud Web API endpoint: POST /api/projects/create.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_projects_delete' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectsDelete',
  'type' => 'write',
  'name' => 'Projects Delete',
  'description' => 'Delete a project. Requires \'Administer System\' permission or \'Administer\' permission on the project.  Official SonarCloud Web API endpoint: POST /api/projects/delete.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_projects_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectsSearch',
  'type' => 'read',
  'name' => 'Projects Search',
  'description' => 'Search for projects to administrate them. Requires \'System Administrator\' permission  Official SonarCloud Web API endpoint: GET /api/projects/search.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_projects_update_key' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectsUpdateKey',
  'type' => 'write',
  'name' => 'Projects Update Key',
  'description' => 'Update a project or module key and all its sub-components keys. Requires the permission \'Administer\' on the specified project.  Official SonarCloud Web API endpoint: POST /api/projects/update_key.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_projects_update_visibility' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudProjectsUpdateVisibility',
  'type' => 'write',
  'name' => 'Projects Update Visibility',
  'description' => 'Updates visibility of a project. Requires \'Project administer\' permission on the specified project  Official SonarCloud Web API endpoint: POST /api/projects/update_visibility.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_properties_index' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudPropertiesIndex',
  'type' => 'read',
  'name' => 'Properties Index',
  'description' => 'This web service is deprecated, please use api/settings/values instead.  Official SonarCloud Web API endpoint: GET /api/properties/index.  Deprecated since SonarCloud 6.3; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualitygates_copy' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesCopy',
  'type' => 'write',
  'name' => 'Qualitygates Copy',
  'description' => 'Copy a Quality Gate. Requires the \'Administer Quality Gates\' permission.  Official SonarCloud Web API endpoint: POST /api/qualitygates/copy.  Deprecated since SonarCloud 16 September, 2025; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualitygates_create' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesCreate',
  'type' => 'write',
  'name' => 'Qualitygates Create',
  'description' => 'Create a Quality Gate. Requires the \'Administer Quality Gates\' permission.  Official SonarCloud Web API endpoint: POST /api/qualitygates/create.  Deprecated since SonarCloud 16 September, 2025; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualitygates_create_condition' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesCreateCondition',
  'type' => 'write',
  'name' => 'Qualitygates Create Condition',
  'description' => 'Add a new condition to a quality gate. Requires the \'Administer Quality Gates\' permission.  Official SonarCloud Web API endpoint: POST /api/qualitygates/create_condition.  Deprecated since SonarCloud 16 September, 2025; kept for API parity while the official r',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualitygates_delete_condition' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesDeleteCondition',
  'type' => 'write',
  'name' => 'Qualitygates Delete Condition',
  'description' => 'Delete a condition from a quality gate. Requires the \'Administer Quality Gates\' permission.  Official SonarCloud Web API endpoint: POST /api/qualitygates/delete_condition.  Deprecated since SonarCloud 16 September, 2025; kept for API parity while the official ',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualitygates_deselect' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesDeselect',
  'type' => 'write',
  'name' => 'Qualitygates Deselect',
  'description' => 'Remove the association of a project from a quality gate. Requires one of the following permissions:- \'Administer Quality Gates\'; - \'Administer\' rights on the project;  Official SonarCloud Web API endpoint: POST /api/qualitygates/deselect.  Deprecated since Son',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualitygates_destroy' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesDestroy',
  'type' => 'write',
  'name' => 'Qualitygates Destroy',
  'description' => 'Delete a Quality Gate. Requires the \'Administer Quality Gates\' permission.  Official SonarCloud Web API endpoint: POST /api/qualitygates/destroy.  Deprecated since SonarCloud 16 September, 2025; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualitygates_get_by_project' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesGetByProject',
  'type' => 'read',
  'name' => 'Qualitygates Get By Project',
  'description' => 'Get the quality gate of a project. Requires one of the following permissions:- \'Administer\' rights on the specified project; - \'Browse\' on the specified project;  Official SonarCloud Web API endpoint: GET /api/qualitygates/get_by_project.  Deprecated since Son',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualitygates_list' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesList',
  'type' => 'read',
  'name' => 'Qualitygates List',
  'description' => 'Get a list of quality gates  Official SonarCloud Web API endpoint: GET /api/qualitygates/list.  Deprecated since SonarCloud 16 September, 2025; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualitygates_project_status' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesProjectStatus',
  'type' => 'read',
  'name' => 'Qualitygates Project Status',
  'description' => 'Get the quality gate status of a project or a Compute Engine task. Either \'analysisId\', \'projectId\' or \'projectKey\' must be provided The different statuses returned are: OK, WARN, ERROR, NONE. The NONE status is returned when there is no quality gate associate',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualitygates_rename' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesRename',
  'type' => 'write',
  'name' => 'Qualitygates Rename',
  'description' => 'Rename a Quality Gate. Requires the \'Administer Quality Gates\' permission.  Official SonarCloud Web API endpoint: POST /api/qualitygates/rename.  Deprecated since SonarCloud 16 September, 2025; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualitygates_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesSearch',
  'type' => 'read',
  'name' => 'Qualitygates Search',
  'description' => 'Search for projects associated (or not) to a quality gate. Only authorized projects for current user will be returned.  Official SonarCloud Web API endpoint: GET /api/qualitygates/search.  Deprecated since SonarCloud 16 September, 2025; kept for API parity whi',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualitygates_select' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesSelect',
  'type' => 'write',
  'name' => 'Qualitygates Select',
  'description' => 'Associate a project to a quality gate. The \'projectId\' or \'projectKey\' must be provided. Project id as a numeric value is deprecated since 6.1. Please use the id similar to \'AU-TpxcA-iU5OvuD2FLz\'. Requires the \'Administer Quality Gates\' permission.  Official S',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualitygates_set_as_default' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesSetAsDefault',
  'type' => 'write',
  'name' => 'Qualitygates Set As Default',
  'description' => 'Set a quality gate as the default quality gate. Requires the \'Administer Quality Gates\' permission.  Official SonarCloud Web API endpoint: POST /api/qualitygates/set_as_default.  Deprecated since SonarCloud 16 September, 2025; kept for API parity while the off',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualitygates_show' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesShow',
  'type' => 'read',
  'name' => 'Qualitygates Show',
  'description' => 'Display the details of a quality gate  Official SonarCloud Web API endpoint: GET /api/qualitygates/show.  Deprecated since SonarCloud 16 September, 2025; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualitygates_unset_default' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesUnsetDefault',
  'type' => 'write',
  'name' => 'Qualitygates Unset Default',
  'description' => 'This webservice is no more available : a default quality gate is mandatory.  Official SonarCloud Web API endpoint: POST /api/qualitygates/unset_default.  Deprecated since SonarCloud 7.0; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualitygates_update_condition' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualitygatesUpdateCondition',
  'type' => 'write',
  'name' => 'Qualitygates Update Condition',
  'description' => 'Update a condition attached to a quality gate. Requires the \'Administer Quality Gates\' permission.  Official SonarCloud Web API endpoint: POST /api/qualitygates/update_condition.  Deprecated since SonarCloud 16 September, 2025; kept for API parity while the of',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_activate_rule' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesActivateRule',
  'type' => 'write',
  'name' => 'Qualityprofiles Activate Rule',
  'description' => 'Activate a rule on a Quality Profile. Requires one of the following permissions: - \'Administer Quality Profiles\'; - Edit right on the specified quality profile;  Official SonarCloud Web API endpoint: POST /api/qualityprofiles/activate_rule.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_activate_rules' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesActivateRules',
  'type' => 'write',
  'name' => 'Qualityprofiles Activate Rules',
  'description' => 'Bulk-activate rules on one quality profile. Requires one of the following permissions: - \'Administer Quality Profiles\'; - Edit right on the specified quality profile;  Official SonarCloud Web API endpoint: POST /api/qualityprofiles/activate_rules.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_add_project' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesAddProject',
  'type' => 'write',
  'name' => 'Qualityprofiles Add Project',
  'description' => 'Associate a project with a quality profile. Requires one of the following permissions: - \'Administer Quality Profiles\'; - Edit right on the specified quality profile; - Administer right on the specified project;  Official SonarCloud Web API endpoint: POST /api',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_backup' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesBackup',
  'type' => 'read',
  'name' => 'Qualityprofiles Backup',
  'description' => 'Backup a quality profile in XML form. The exported profile can be restored through api/qualityprofiles/restore.  Official SonarCloud Web API endpoint: GET /api/qualityprofiles/backup.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualityprofiles_change_parent' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesChangeParent',
  'type' => 'write',
  'name' => 'Qualityprofiles Change Parent',
  'description' => 'Change a quality profile\'s parent. Requires one of the following permissions: - \'Administer Quality Profiles\'; - Edit right on the specified quality profile;  Official SonarCloud Web API endpoint: POST /api/qualityprofiles/change_parent.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_changelog' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesChangelog',
  'type' => 'read',
  'name' => 'Qualityprofiles Changelog',
  'description' => 'Get the history of changes on a quality profile: rule activation/deactivation, change in parameters/severity. Events are ordered by date in descending order (most recent first).  Official SonarCloud Web API endpoint: GET /api/qualityprofiles/changelog.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualityprofiles_copy' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesCopy',
  'type' => 'write',
  'name' => 'Qualityprofiles Copy',
  'description' => 'Copy a quality profile. Requires to be logged in and the \'Administer Quality Profiles\' permission.  Official SonarCloud Web API endpoint: POST /api/qualityprofiles/copy.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_create' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesCreate',
  'type' => 'write',
  'name' => 'Qualityprofiles Create',
  'description' => 'Create a quality profile. Requires to be logged in and the \'Administer Quality Profiles\' permission.  Official SonarCloud Web API endpoint: POST /api/qualityprofiles/create.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_deactivate_rule' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesDeactivateRule',
  'type' => 'write',
  'name' => 'Qualityprofiles Deactivate Rule',
  'description' => 'Deactivate a rule on a quality profile. Requires one of the following permissions: - \'Administer Quality Profiles\'; - Edit right on the specified quality profile;  Official SonarCloud Web API endpoint: POST /api/qualityprofiles/deactivate_rule.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_deactivate_rules' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesDeactivateRules',
  'type' => 'write',
  'name' => 'Qualityprofiles Deactivate Rules',
  'description' => 'Bulk deactivate rules on Quality profiles. Requires one of the following permissions: - \'Administer Quality Profiles\'; - Edit right on the specified quality profile;  Official SonarCloud Web API endpoint: POST /api/qualityprofiles/deactivate_rules.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_delete' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesDelete',
  'type' => 'write',
  'name' => 'Qualityprofiles Delete',
  'description' => 'Delete a quality profile and all its descendants. The default quality profile cannot be deleted. Requires one of the following permissions: - \'Administer Quality Profiles\'; - Edit right on the specified quality profile;  Official SonarCloud Web API endpoint: P',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_export' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesExport',
  'type' => 'read',
  'name' => 'Qualityprofiles Export',
  'description' => 'Deprecated. Use GET /api/qualityprofiles/backup instead  Official SonarCloud Web API endpoint: GET /api/qualityprofiles/export.  Deprecated since SonarCloud 18 March, 2025; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualityprofiles_exporters' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesExporters',
  'type' => 'read',
  'name' => 'Qualityprofiles Exporters',
  'description' => 'Deprecated. No more custom profile exporters.  Official SonarCloud Web API endpoint: GET /api/qualityprofiles/exporters.  Deprecated since SonarCloud 18 March, 2025; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualityprofiles_importers' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesImporters',
  'type' => 'read',
  'name' => 'Qualityprofiles Importers',
  'description' => 'Deprecated. No more custom profile importers.  Official SonarCloud Web API endpoint: GET /api/qualityprofiles/importers.  Deprecated since SonarCloud 18 March, 2025; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualityprofiles_inheritance' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesInheritance',
  'type' => 'read',
  'name' => 'Qualityprofiles Inheritance',
  'description' => 'Show a quality profile\'s ancestors and children.  Official SonarCloud Web API endpoint: GET /api/qualityprofiles/inheritance.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualityprofiles_projects' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesProjects',
  'type' => 'read',
  'name' => 'Qualityprofiles Projects',
  'description' => 'List projects with their association status regarding a quality profile  Official SonarCloud Web API endpoint: GET /api/qualityprofiles/projects.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualityprofiles_remove_project' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesRemoveProject',
  'type' => 'write',
  'name' => 'Qualityprofiles Remove Project',
  'description' => 'Remove a project\'s association with a quality profile. Requires one of the following permissions: - \'Administer Quality Profiles\'; - Edit right on the specified quality profile; - Administer right on the specified project;  Official SonarCloud Web API endpoint',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_rename' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesRename',
  'type' => 'write',
  'name' => 'Qualityprofiles Rename',
  'description' => 'Rename a quality profile. Requires one of the following permissions: - \'Administer Quality Profiles\'; - Edit right on the specified quality profile;  Official SonarCloud Web API endpoint: POST /api/qualityprofiles/rename.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_restore' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesRestore',
  'type' => 'write',
  'name' => 'Qualityprofiles Restore',
  'description' => 'Restore a quality profile using an XML file. The restored profile name is taken from the backup file, so if a profile with the same name and language already exists, it will be overwritten. Requires to be logged in and the \'Administer Quality Profiles\' permiss',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_restore_built_in' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesRestoreBuiltIn',
  'type' => 'write',
  'name' => 'Qualityprofiles Restore Built In',
  'description' => 'This web service has no effect since 6.4. It\'s no more possible to restore built-in quality profiles because they are automatically updated and read only. Returns HTTP code 410.  Official SonarCloud Web API endpoint: POST /api/qualityprofiles/restore_built_in.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_qualityprofiles_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesSearch',
  'type' => 'read',
  'name' => 'Qualityprofiles Search',
  'description' => 'Search quality profiles  Official SonarCloud Web API endpoint: GET /api/qualityprofiles/search.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_qualityprofiles_set_default' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudQualityprofilesSetDefault',
  'type' => 'write',
  'name' => 'Qualityprofiles Set Default',
  'description' => 'Select the default profile for a given language. Requires to be logged in and the \'Administer Quality Profiles\' permission.  Official SonarCloud Web API endpoint: POST /api/qualityprofiles/set_default.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_rules_repositories' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudRulesRepositories',
  'type' => 'read',
  'name' => 'Rules Repositories',
  'description' => 'List available rule repositories  Official SonarCloud Web API endpoint: GET /api/rules/repositories.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_rules_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudRulesSearch',
  'type' => 'read',
  'name' => 'Rules Search',
  'description' => 'Search for a collection of relevant rules matching a specified query. Since 5.5, following fields in the response have been deprecated :- "effortToFixDescription" becomes "gapDescription"; - "debtRemFnCoeff" becomes "remFnGapMultiplier"; - "defaultDebtRemFnCoe',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_rules_show' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudRulesShow',
  'type' => 'read',
  'name' => 'Rules Show',
  'description' => 'Get detailed information about a rule Since 5.5, following fields in the response have been deprecated :- "effortToFixDescription" becomes "gapDescription"; - "debtRemFnCoeff" becomes "remFnGapMultiplier"; - "defaultDebtRemFnCoeff" becomes "defaultRemFnGapMult',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_rules_tags' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudRulesTags',
  'type' => 'read',
  'name' => 'Rules Tags',
  'description' => 'List rule tags  Official SonarCloud Web API endpoint: GET /api/rules/tags.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_rules_update' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudRulesUpdate',
  'type' => 'write',
  'name' => 'Rules Update',
  'description' => 'Update an existing rule. Requires the \'Administer Quality Profiles\' permission  Official SonarCloud Web API endpoint: POST /api/rules/update.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_settings_list_definitions' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudSettingsListDefinitions',
  'type' => 'read',
  'name' => 'Settings List Definitions',
  'description' => 'List settings definitions. Requires \'Browse\' permission when a component is specified To access licensed settings, authentication is required To access secured settings, one of the following permissions is required: - \'Execute Analysis\'; - \'Administer\' rights ',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_settings_reset' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudSettingsReset',
  'type' => 'write',
  'name' => 'Settings Reset',
  'description' => 'Remove a setting value. The settings defined in conf/sonar.properties are read-only and can\'t be changed. Requires the permission \'Administer\' on the specified component.  Official SonarCloud Web API endpoint: POST /api/settings/reset.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_settings_set' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudSettingsSet',
  'type' => 'write',
  'name' => 'Settings Set',
  'description' => 'Update a setting value. Either \'value\' or \'values\' must be provided. The settings defined in conf/sonar.properties are read-only and can\'t be changed. Requires the permission \'Administer\' on the specified component.  Official SonarCloud Web API endpoint: POST ',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_settings_values' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudSettingsValues',
  'type' => 'read',
  'name' => 'Settings Values',
  'description' => 'List settings values. If no value has been set for a setting, then the default value is returned. Both component and organization parameters cannot be used together. Requires \'Browse\' or \'Execute Analysis\' permission when a component is specified. Requires to ',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_sources_raw' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudSourcesRaw',
  'type' => 'read',
  'name' => 'Sources Raw',
  'description' => 'Get source code as raw text. Require \'See Source Code\' permission on file  Official SonarCloud Web API endpoint: GET /api/sources/raw.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_sources_scm' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudSourcesScm',
  'type' => 'read',
  'name' => 'Sources Scm',
  'description' => 'Get SCM information of source files. Require See Source Code permission on file\'s project Each element of the result array is composed of:- Line number; - Author of the commit; - Datetime of the commit (before 5.2 it was only the Date); - Revision of the commi',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_sources_show' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudSourcesShow',
  'type' => 'read',
  'name' => 'Sources Show',
  'description' => 'Get source code. Requires See Source Code permission on file\'s project, or organization membership on public projects. Each element of the result array is composed of:- Line number; - Content of the line;  Official SonarCloud Web API endpoint: GET /api/sources',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_timemachine_index' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudTimemachineIndex',
  'type' => 'read',
  'name' => 'Timemachine Index',
  'description' => 'The web service is removed and you\'re invited to use api/measures/search_history instead  Official SonarCloud Web API endpoint: GET /api/timemachine/index.  Deprecated since SonarCloud 6.3; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_user_groups_add_user' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUserGroupsAddUser',
  'type' => 'write',
  'name' => 'User Groups Add User',
  'description' => 'Add a user to a group. \'id\' or \'name\' must be provided. Requires the following permission: \'Administer System\'.  Official SonarCloud Web API endpoint: POST /api/user_groups/add_user.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_user_groups_create' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUserGroupsCreate',
  'type' => 'write',
  'name' => 'User Groups Create',
  'description' => 'Create a group. Requires the following permission: \'Administer System\'.  Official SonarCloud Web API endpoint: POST /api/user_groups/create.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_user_groups_delete' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUserGroupsDelete',
  'type' => 'write',
  'name' => 'User Groups Delete',
  'description' => 'Delete a group. The default groups cannot be deleted. \'id\' or \'name\' must be provided. Requires the following permission: \'Administer System\'.  Official SonarCloud Web API endpoint: POST /api/user_groups/delete.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_user_groups_remove_user' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUserGroupsRemoveUser',
  'type' => 'write',
  'name' => 'User Groups Remove User',
  'description' => 'Remove a user from a group. \'id\' or \'name\' must be provided. Requires the following permission: \'Administer System\'.  Official SonarCloud Web API endpoint: POST /api/user_groups/remove_user.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_user_groups_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUserGroupsSearch',
  'type' => 'read',
  'name' => 'User Groups Search',
  'description' => 'Search for user groups. Requires the following permission: \'Administer System\'.  Official SonarCloud Web API endpoint: GET /api/user_groups/search.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_user_groups_update' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUserGroupsUpdate',
  'type' => 'write',
  'name' => 'User Groups Update',
  'description' => 'Update a group. Requires the following permission: \'Administer System\'.  Official SonarCloud Web API endpoint: POST /api/user_groups/update.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_user_groups_users' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUserGroupsUsers',
  'type' => 'read',
  'name' => 'User Groups Users',
  'description' => 'Search for users with membership information with respect to a group. Requires the following permission: \'Administer System\'.  Official SonarCloud Web API endpoint: GET /api/user_groups/users.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_user_properties_index' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUserPropertiesIndex',
  'type' => 'read',
  'name' => 'User Properties Index',
  'description' => 'This web service is removed  Official SonarCloud Web API endpoint: GET /api/user_properties/index.  Deprecated since SonarCloud 6.3; kept for API parity while the official registry still exposes it.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_user_tokens_generate' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUserTokensGenerate',
  'type' => 'write',
  'name' => 'User Tokens Generate',
  'description' => 'Generate a user access token. Please keep your tokens secret. They enable to authenticate and analyze projects. The endpoint generates a token for the logged in user.  Official SonarCloud Web API endpoint: POST /api/user_tokens/generate.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_user_tokens_revoke' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUserTokensRevoke',
  'type' => 'write',
  'name' => 'User Tokens Revoke',
  'description' => 'Revoke an access token of the authenticated user.  Official SonarCloud Web API endpoint: POST /api/user_tokens/revoke.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_user_tokens_search' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUserTokensSearch',
  'type' => 'read',
  'name' => 'User Tokens Search',
  'description' => 'List the access tokens of the authenticated user. Field \'lastConnectionDate\' is only updated every hour, so it may not be accurate, for instance when a user is using a token many times in less than one hour.  Official SonarCloud Web API endpoint: GET /api/user',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_users_groups' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudUsersGroups',
  'type' => 'read',
  'name' => 'Users Groups',
  'description' => 'Lists the groups a user belongs to. Requires the permission \'Administer\' on the organization.  Official SonarCloud Web API endpoint: GET /api/users/groups.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_webhooks_create' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudWebhooksCreate',
  'type' => 'write',
  'name' => 'Webhooks Create',
  'description' => 'Create a Webhook. Requires \'Administer\' permission on the specified project.  Official SonarCloud Web API endpoint: POST /api/webhooks/create.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_webhooks_delete' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudWebhooksDelete',
  'type' => 'write',
  'name' => 'Webhooks Delete',
  'description' => 'Delete a Webhook. Requires \'Administer\' permission on the specified project, or global \'Administer\' permission.  Official SonarCloud Web API endpoint: POST /api/webhooks/delete.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_webhooks_deliveries' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudWebhooksDeliveries',
  'type' => 'read',
  'name' => 'Webhooks Deliveries',
  'description' => 'Get the recent deliveries for a specified project or Compute Engine task. Require \'Administer\' permission on the related project. Note that additional information are returned by api/webhooks/delivery.  Official SonarCloud Web API endpoint: GET /api/webhooks/d',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_webhooks_delivery' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudWebhooksDelivery',
  'type' => 'read',
  'name' => 'Webhooks Delivery',
  'description' => 'Get a webhook delivery by its id. Note that additional information are returned by api/webhooks/delivery.  Official SonarCloud Web API endpoint: GET /api/webhooks/delivery.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_webhooks_list' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudWebhooksList',
  'type' => 'read',
  'name' => 'Webhooks List',
  'description' => 'Search for global webhooks or project webhooks. Webhooks are ordered by name. Requires \'Administer\' permission on the specified project, or global \'Administer\' permission.  Official SonarCloud Web API endpoint: GET /api/webhooks/list.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_webhooks_update' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudWebhooksUpdate',
  'type' => 'write',
  'name' => 'Webhooks Update',
  'description' => 'Update a Webhook. Requires \'Administer\' permission on the specified project, or global \'Administer\' permission.  Official SonarCloud Web API endpoint: POST /api/webhooks/update.',
  'icon' => 'ph:pencil-simple',
),
  'sonarcloud_webservices_list' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudWebservicesList',
  'type' => 'read',
  'name' => 'Webservices List',
  'description' => 'List web services  Official SonarCloud Web API endpoint: GET /api/webservices/list.',
  'icon' => 'ph:cloud-check',
),
  'sonarcloud_webservices_response_example' => array (
  'class' => 'OpenCompany\\Integrations\\SonarCloud\\Tools\\SonarCloudWebservicesResponseExample',
  'type' => 'read',
  'name' => 'Webservices Response Example',
  'description' => 'Display web service response example  Official SonarCloud Web API endpoint: GET /api/webservices/response_example.',
  'icon' => 'ph:cloud-check',
),
    ]; }
    public function isIntegration(): bool { return true; } public function createTool(string $class, array $context = []): Tool { return new $class($this->resolveService($context)); } public function scriptDocsPath(): ?string { return __DIR__.'/../script-docs/sonarcloud.md'; }
    /** @param  array<string, mixed>  $context  Runtime account context. */ private function resolveService(array $context = []): SonarCloudService { $account = $context['account'] ?? null; if ($account !== null) { $creds = app(CredentialResolver::class); return new SonarCloudService(apiToken: $creds->get('sonarcloud', 'api_token', '', $account), baseUrl: $creds->get('sonarcloud', 'url', 'https://sonarcloud.io', $account)); } return app(SonarCloudService::class); }
}
