<?php

namespace OpenCompany\Integrations\Miro;

use Illuminate\Support\Facades\Http;
use OpenCompany\IntegrationCore\Contracts\ConfigurableIntegration;
use OpenCompany\IntegrationCore\Contracts\CredentialResolver;
use OpenCompany\IntegrationCore\Contracts\HasIntegrationCapabilities;
use OpenCompany\IntegrationCore\Contracts\Tool;
use OpenCompany\IntegrationCore\Contracts\ToolProvider;

/**
 * Tool catalog and configuration metadata for Miro.
 *
 * Exposes the official Miro OpenAPI operation set as endpoint-specific agent
 * tools and resolves account-specific OAuth access tokens.
 */
class MiroToolProvider implements ToolProvider, ConfigurableIntegration, HasIntegrationCapabilities
{
    /** @return array<string, mixed> */ public function integrationCapabilities(): array { return ['auth'=>['strategy'=>'oauth_bearer_token','legacy_auth_type'=>'oauth','credential_mode'=>'secret','setup_flows'=>['oauth','manual_secret'],'requires_browser_for_setup'=>true,'refreshable'=>true,'token_keys'=>['access_token','refresh_token'],'notes'=>['Runtime calls use Authorization: Bearer <access_token>.']],'host_availability'=>['web'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'oauth'],'cli'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret','runtime_mode'=>'normal']],'runtime_requirements'=>[],'compatibility'=>['web_setup_supported'=>true,'web_runtime_supported'=>true,'cli_setup_supported'=>true,'cli_runtime_supported'=>true]]; }
    public function appName(): string { return 'miro'; } public function appMeta(): array { return ['label'=>'Miro','description'=>'Boards, items, docs, images, frames, connectors, comments, orgs, teams, SCIM, audit, and enterprise admin','icon'=>'ph:shapes','logo'=>'ph:shapes']; }
    public function integrationMeta(): array { return ['name'=>'Miro','description'=>'Manage Miro boards, board items, documents, images, connectors, comments, tags, org/team administration, SCIM users/groups, audit logs, and enterprise APIs.','icon'=>'ph:shapes','logo'=>'ph:shapes','category'=>'productivity','badge'=>'verified','docs_url'=>'https://developers.miro.com/reference/api-reference']; }
    public function configSchema(): array { return [['key'=>'access_token','type'=>'secret','label'=>'OAuth Access Token','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','required'=>false,'default'=>'https://api.miro.com']]; }
    /** @param  array<string, mixed>  $config  Credential and endpoint settings. @return array{success: bool, message?: string, error?: string} */ public function testConnection(array $config): array { $token=(string)($config['access_token']??''); $baseUrl=rtrim((string)($config['url']??'https://api.miro.com'),'/'); if($token==='') return ['success'=>false,'error'=>'Miro access token is required.']; try{ $response=Http::withHeaders(['Authorization'=>'Bearer '.$token,'Accept'=>'application/json'])->timeout(10)->get($baseUrl.'/v2/boards'); if(!$response->successful()) return ['success'=>false,'error'=>'Miro API returned HTTP '.$response->status().'.']; return ['success'=>true,'message'=>'Connected to Miro at '.$baseUrl.'.']; }catch(\Throwable $e){ return ['success'=>false,'error'=>$e->getMessage()]; } }
    public function validationRules(): array { return ['access_token'=>'required|string','url'=>'nullable|url']; } public function credentialFields(): array { return [['key'=>'access_token','type'=>'secret','label'=>'OAuth Access Token','required'=>true],['key'=>'refresh_token','type'=>'secret','label'=>'OAuth Refresh Token','required'=>false],['key'=>'url','type'=>'url','label'=>'API Base URL','required'=>false,'default'=>'https://api.miro.com']]; }
    public function tools(): array { return [
  'miro_revoke_token' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroRevokeToken',
  'type' => 'write',
  'name' => 'Revoke Token',
  'description' => 'Please use the new revoke endpoint /v2/oauth/revoke. This endpoint is considered vulnerable and deprecated due to access token passed publicly in the URL. Revoke the current access token. Revoking an access token means that the access token will no longer work',
  'icon' => 'ph:pencil-simple',
),
  'miro_token_info' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroTokenInfo',
  'type' => 'read',
  'name' => 'Token Info',
  'description' => 'Get information about an access token, such as the token type, scopes, team, user, token creation date and time, and the user who created the token.  Official Miro endpoint: GET /v1/oauth-token.',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_get_ai_interaction_logs' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetAiInteractionLogs',
  'type' => 'read',
  'name' => 'Enterprise Get Ai Interaction Logs',
  'description' => 'Retrieves AI interaction logs for your organization. AI interaction logs capture user interactions with AI features in Miro. You can retrieve results for a specific time period. You can also filter results based on object IDs and the emails of users who intera',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_get_audit_logs' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetAuditLogs',
  'type' => 'read',
  'name' => 'Enterprise Get Audit Logs',
  'description' => 'Retrieves a page of audit events from the last 90 days. If you want to retrieve data that is older than 90 days, you can use the CSV export feature. Required scope auditlogs:read Rate limiting Level 2  Official Miro endpoint: GET /v2/audit/logs.',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_dataclassification_organization_settings_get' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDataclassificationOrganizationSettingsGet',
  'type' => 'read',
  'name' => 'Enterprise Dataclassification Organization Settings Get',
  'description' => 'Retrieves board classification settings for an existing organization. Required scope organizations:read Rate limiting Level 2 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_dataclassification_team_boards_bulk' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDataclassificationTeamBoardsBulk',
  'type' => 'write',
  'name' => 'Enterprise Dataclassification Team Boards Bulk',
  'description' => 'Updates board classification for not-classified only or all boards in an existing team. Required scope boards:write Rate limiting Level 4 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role ',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_dataclassification_team_settings_get' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDataclassificationTeamSettingsGet',
  'type' => 'read',
  'name' => 'Enterprise Dataclassification Team Settings Get',
  'description' => 'Retrieves board classification settings for an existing team. Required scope organizations:teams:read Rate limiting Level 2 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company A',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_dataclassification_team_settings_set' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDataclassificationTeamSettingsSet',
  'type' => 'write',
  'name' => 'Enterprise Dataclassification Team Settings Set',
  'description' => 'Updates board classification settings for an existing team. Required scope organizations:teams:write Rate limiting Level 2 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Ad',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_dataclassification_board_get' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDataclassificationBoardGet',
  'type' => 'read',
  'name' => 'Enterprise Dataclassification Board Get',
  'description' => 'Retrieves board classification for a board. Required scope boards:read Rate limiting Level 2 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can request temporary',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_dataclassification_board_set' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDataclassificationBoardSet',
  'type' => 'write',
  'name' => 'Enterprise Dataclassification Board Set',
  'description' => 'Updates board classification for an existing board. Required scope boards:write Rate limiting Level 2 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can request ',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_doc_format_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateDocFormatItem',
  'type' => 'write',
  'name' => 'Create Doc Format Item',
  'description' => 'Adds a doc format item to a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/docs.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_doc_format_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetDocFormatItem',
  'type' => 'read',
  'name' => 'Get Doc Format Item',
  'description' => 'Retrieves information for a specific doc format item on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/docs/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_delete_doc_format_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteDocFormatItem',
  'type' => 'write',
  'name' => 'Delete Doc Format Item',
  'description' => 'Deletes a doc format item from the board Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/docs/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_all_cases' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetAllCases',
  'type' => 'read',
  'name' => 'Get All Cases',
  'description' => 'Retrieves the list of eDiscovery cases in an organization. Required scope organization:cases:management Rate limiting Level 4 Enterprise Guard only This API is available only for Enterprise plan users with the Enterprise Guard add-on. You can only use this end',
  'icon' => 'ph:shapes',
),
  'miro_create_case' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateCase',
  'type' => 'write',
  'name' => 'Create Case',
  'description' => 'Creating a case for legal hold is the first critical step in the eDiscovery process when litigation or an investigation is anticipated. One of the purposes of creating a case is that it acts as a container that allows admins to group multiple legal holds under',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_case' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteCase',
  'type' => 'write',
  'name' => 'Delete Case',
  'description' => 'Closing a case is the final stage in the eDiscovery process, marking the conclusion of a legal matter or investigation. You must ensure that all associated legal holds within the case are closed before closing the case. Closing a case will permanently delete i',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_case' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetCase',
  'type' => 'read',
  'name' => 'Get Case',
  'description' => 'Retrieves information about a case in an organization. Required scope organization:cases:management Rate limiting Level 3 Enterprise Guard only This API is available only for Enterprise plan users with the Enterprise Guard add-on. You can only use this endpoin',
  'icon' => 'ph:shapes',
),
  'miro_edit_case' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEditCase',
  'type' => 'write',
  'name' => 'Edit Case',
  'description' => 'Editing a case allows eDiscovery Admins to keep case details accurate and aligned with the evolving scope of a legal matter. As investigations progress, it may be necessary to update the case name or description to reflect changes in focus, terminology, or int',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_all_legal_holds' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetAllLegalHolds',
  'type' => 'read',
  'name' => 'Get All Legal Holds',
  'description' => 'Retrieves the list of all legal holds within a case for an organization. Required scope organization:cases:management Rate limiting Level 4 Enterprise Guard only This API is available only for Enterprise plan users with the Enterprise Guard add-on. You can onl',
  'icon' => 'ph:shapes',
),
  'miro_create_legal_hold' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateLegalHold',
  'type' => 'write',
  'name' => 'Create Legal Hold',
  'description' => 'After creating a case it is possible to add one or multiple legal holds to the case. Creating a legal hold involves identifying the relevant users associated with a case and applying the hold to prevent permanent deletion of content that those users own, co-ow',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_legal_hold_export_jobs' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetLegalHoldExportJobs',
  'type' => 'read',
  'name' => 'Get Legal Hold Export Jobs',
  'description' => 'Retrieves board export jobs for a case. Required scope organization:cases:management Rate limiting Level 4 Enterprise Guard only This API is available only for Enterprise plan users with the Enterprise Guard add-on. You can only use this endpoint if you have b',
  'icon' => 'ph:shapes',
),
  'miro_delete_legal_hold' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteLegalHold',
  'type' => 'write',
  'name' => 'Delete Legal Hold',
  'description' => 'Closing a legal hold is one of the final steps in the eDiscovery process once the litigation or investigation has concluded. This process involves releasing the Miro boards and custodians that were under legal hold, allowing the preserved boards to return to n',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_legal_hold' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetLegalHold',
  'type' => 'read',
  'name' => 'Get Legal Hold',
  'description' => 'Retrieves information about a legal hold within a case for an organization. Required scope organization:cases:management Rate limiting Level 3 Enterprise Guard only This API is available only for Enterprise plan users with the Enterprise Guard add-on. You can ',
  'icon' => 'ph:shapes',
),
  'miro_edit_legal_hold' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEditLegalHold',
  'type' => 'write',
  'name' => 'Edit Legal Hold',
  'description' => 'Editing a legal hold allows eDiscovery Admins to adjust and refine ongoing legal preservation efforts as case requirements evolve. Whether new custodians are identified, additional Miro boards become relevant, or existing boards or users are no longer in scope',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_legal_hold_content_items' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetLegalHoldContentItems',
  'type' => 'read',
  'name' => 'Get Legal Hold Content Items',
  'description' => 'Once a legal hold is in place you can review or explore the preserved Miro boards to ensure that all relevant data is intact and ready for legal proceedings or investigations. For more information, see our Help Center page on reviewing boards under legal hold.',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_create_board_export' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseCreateBoardExport',
  'type' => 'write',
  'name' => 'Enterprise Create Board Export',
  'description' => 'Creates an export job for one or more boards. Required scope boards:export Rate limiting Level 4 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin and eDiscovery is enab',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_board_export_jobs' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseBoardExportJobs',
  'type' => 'read',
  'name' => 'Enterprise Board Export Jobs',
  'description' => 'Retrieves the list of board export jobs based on the filters provided in the request. Required scope boards:export Rate limiting Level 4 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role o',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_board_export_job_status' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseBoardExportJobStatus',
  'type' => 'read',
  'name' => 'Enterprise Board Export Job Status',
  'description' => 'Retrieves the status of the board export job. Required scope boards:export Rate limiting Level 4 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin and eDiscovery is enab',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_board_export_job_results' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseBoardExportJobResults',
  'type' => 'read',
  'name' => 'Enterprise Board Export Job Results',
  'description' => 'Retrieves the result of the board export job. The response provides more information about the board export job, such as the S3 link to the files created. Required scope boards:export Rate limiting Level 4 Enterprise only This API is available only for Enterpr',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_update_board_export_job' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseUpdateBoardExportJob',
  'type' => 'write',
  'name' => 'Enterprise Update Board Export Job',
  'description' => 'Updates the status of the board export job. Currently, only the cancellation of an ongoing export job is supported. Required scope boards:export Rate limiting Level 4 Enterprise only This API is available only for Enterprise plan users. You can only use this e',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_board_export_job_tasks' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseBoardExportJobTasks',
  'type' => 'read',
  'name' => 'Enterprise Board Export Job Tasks',
  'description' => 'Retrieves the list of tasks for the board export job. Required scope boards:export Rate limiting Level 4 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin and eDiscovery',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_create_board_export_task_export_link' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseCreateBoardExportTaskExportLink',
  'type' => 'write',
  'name' => 'Enterprise Create Board Export Task Export Link',
  'description' => 'Creates a link to download the results of a board export task. Required scope boards:export Rate limiting Level 4 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin and e',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_board_content_item_logs_fetch' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseBoardContentItemLogsFetch',
  'type' => 'read',
  'name' => 'Enterprise Board Content Item Logs Fetch',
  'description' => 'Retrieves content changes for board items within your organization. Content changes are actions that users can perform on board items, such as updating a sticky note\'s text. You can retrieve results for a specific time period. You can also filter results based',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_post_user_sessions_reset' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterprisePostUserSessionsReset',
  'type' => 'write',
  'name' => 'Enterprise Post User Sessions Reset',
  'description' => 'Reset all sessions of a user. Admins can now take immediate action to restrict user access to company data in case of security concerns. Calling this API ends all active Miro sessions across devices for a particular user, requiring the user to sign in again. T',
  'icon' => 'ph:pencil-simple',
),
  'miro_list_users' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroListUsers',
  'type' => 'read',
  'name' => 'List Users',
  'description' => 'Retrieves the list of users in your organization. Note: The API returns users that are members in the organization, it does not return users that are added in the organization as guests.  Official Miro endpoint: GET /Users.',
  'icon' => 'ph:shapes',
),
  'miro_create_user' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateUser',
  'type' => 'write',
  'name' => 'Create User',
  'description' => 'Creates a new user in the organization. Note: All newly provisioned users are added to the default team.  Official Miro endpoint: POST /Users.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_user' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetUser',
  'type' => 'read',
  'name' => 'Get User',
  'description' => 'Retrieves a single user resource. Note: Returns only users that are members in the organization. It does not return users that are added in the organization as guests.  Official Miro endpoint: GET /Users/{id}.',
  'icon' => 'ph:shapes',
),
  'miro_replace_user' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroReplaceUser',
  'type' => 'write',
  'name' => 'Replace User',
  'description' => 'Updates an existing user resource. This is the easiest way to replace user information. If the user is deactivated, userName, userType, and roles.value cannot be updated. emails.value, emails.display, emails.primary get ignored and do not return any error. Not',
  'icon' => 'ph:pencil-simple',
),
  'miro_patch_user' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroPatchUser',
  'type' => 'write',
  'name' => 'Patch User',
  'description' => 'Updates an existing user resource, overwriting values for specified attributes. Attributes that are not provided will remain unchanged. PATCH operation only updates the fields provided. Note: If the user is not a member in the organization, they cannot be upda',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_user' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteUser',
  'type' => 'write',
  'name' => 'Delete User',
  'description' => 'Deletes a single user from the organization. Note: A user who is the last admin in the team or the last admin in the organization cannot be deleted. User must be a member in the organization to be deleted. Users that have guest role in the organization cannot ',
  'icon' => 'ph:pencil-simple',
),
  'miro_list_groups' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroListGroups',
  'type' => 'read',
  'name' => 'List Groups',
  'description' => 'Retrieves the list of groups (teams) in the organization. Note: Along with groups (teams), the users that are part of those groups (teams) are also retrieved. Only users that have member role in the organization are fetched.  Official Miro endpoint: GET /Group',
  'icon' => 'ph:shapes',
),
  'miro_get_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetGroup',
  'type' => 'read',
  'name' => 'Get Group',
  'description' => 'Retrieves a single Group resource. Note: Along with groups (teams), the users that are part of those groups (teams) are also retrieved. Only users that have member role in the organization are fetched.  Official Miro endpoint: GET /Groups/{id}.',
  'icon' => 'ph:shapes',
),
  'miro_patch_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroPatchGroup',
  'type' => 'write',
  'name' => 'Patch Group',
  'description' => 'Updates an existing group resource, i.e. a team, overwriting values for specified attributes. Patch operation for group can be used to add, remove, or replace team members and to update the display name of the group (team). To add a user to the group (team), u',
  'icon' => 'ph:pencil-simple',
),
  'miro_list_service_provider_configs' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroListServiceProviderConfigs',
  'type' => 'read',
  'name' => 'List Service Provider Configs',
  'description' => 'Retrieve supported operations and SCIM API basic configuration.  Official Miro endpoint: GET /ServiceProviderConfig.',
  'icon' => 'ph:shapes',
),
  'miro_list_resource_types' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroListResourceTypes',
  'type' => 'read',
  'name' => 'List Resource Types',
  'description' => 'Retrieve information about which SCIM resources are supported. Currently, Miro supports Users and Groups as Resource Types.  Official Miro endpoint: GET /ResourceTypes.',
  'icon' => 'ph:shapes',
),
  'miro_get_resource_type' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetResourceType',
  'type' => 'read',
  'name' => 'Get Resource Type',
  'description' => 'Retrieve metadata for the available resource types (User and Group) that are supported.  Official Miro endpoint: GET /ResourceTypes/{resource}.',
  'icon' => 'ph:shapes',
),
  'miro_list_schemas' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroListSchemas',
  'type' => 'read',
  'name' => 'List Schemas',
  'description' => 'Retrieve metadata about Users, Groups, and extension attributes that are currently supported.  Official Miro endpoint: GET /Schemas.',
  'icon' => 'ph:shapes',
),
  'miro_get_schema' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetSchema',
  'type' => 'read',
  'name' => 'Get Schema',
  'description' => 'Retrieve information about how users, groups, and enterprise-user attributes URIs that are formatted.  Official Miro endpoint: GET /Schemas/{uri}.',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_get_organization' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetOrganization',
  'type' => 'read',
  'name' => 'Enterprise Get Organization',
  'description' => 'Retrieves organization information. Required scope organizations:read Rate limiting Level 3 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can request temporary ',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_get_organization_members' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetOrganizationMembers',
  'type' => 'read',
  'name' => 'Enterprise Get Organization Members',
  'description' => 'Retrieves organization members based on the organization ID and the cursor, or based on the user emails provided in the request. Required scope organizations:read Rate limiting Level 3 Enterprise only This API is available only for Enterprise plan users. You c',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_get_organization_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetOrganizationMember',
  'type' => 'read',
  'name' => 'Enterprise Get Organization Member',
  'description' => 'Retrieves organization member information for an existing organization. Required scope organizations:read Rate limiting Level 3 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Compa',
  'icon' => 'ph:shapes',
),
  'miro_create_board' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateBoard',
  'type' => 'write',
  'name' => 'Create Board',
  'description' => 'Creates a board with the specified name and sharing policies. Note You can only create up to 3 team boards with the free plan. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: POST /v2/boards.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_boards' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetBoards',
  'type' => 'read',
  'name' => 'Get Boards',
  'description' => 'Retrieves a list of boards accessible to the user associated with the provided access token. This endpoint supports filtering and sorting through URL query parameters. Customize the response by specifying `team_id`, `project_id`, or other query parameters. Fil',
  'icon' => 'ph:shapes',
),
  'miro_copy_board' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCopyBoard',
  'type' => 'write',
  'name' => 'Copy Board',
  'description' => 'Creates a copy of an existing board. You can also update the name, description, sharing policy, and permissions policy for the new board in the request body. Required scope boards:write Rate limiting Level 4  Official Miro endpoint: PUT /v2/boards.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_specific_board' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetSpecificBoard',
  'type' => 'read',
  'name' => 'Get Specific Board',
  'description' => 'Retrieves information about a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_board' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateBoard',
  'type' => 'write',
  'name' => 'Update Board',
  'description' => 'Updates a specific board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_board' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteBoard',
  'type' => 'write',
  'name' => 'Delete Board',
  'description' => 'Deletes a board. Deleted boards go to Trash (on paid plans) and can be restored via UI within 90 days after deletion. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_app_card_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateAppCardItem',
  'type' => 'write',
  'name' => 'Create App Card Item',
  'description' => 'Adds an app card item to a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/app_cards.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_app_card_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetAppCardItem',
  'type' => 'read',
  'name' => 'Get App Card Item',
  'description' => 'Retrieves information for a specific app card item on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/app_cards/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_app_card_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateAppCardItem',
  'type' => 'write',
  'name' => 'Update App Card Item',
  'description' => 'Updates an app card item on a board based on the data and style properties provided in the request body. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/app_cards/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_app_card_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteAppCardItem',
  'type' => 'write',
  'name' => 'Delete App Card Item',
  'description' => 'Deletes an app card item from a board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/app_cards/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_card_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateCardItem',
  'type' => 'write',
  'name' => 'Create Card Item',
  'description' => 'Adds a card item to a board Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/cards.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_card_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetCardItem',
  'type' => 'read',
  'name' => 'Get Card Item',
  'description' => 'Retrieves information for a specific card item on a board Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/cards/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_card_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateCardItem',
  'type' => 'write',
  'name' => 'Update Card Item',
  'description' => 'Updates a card item on a board based on the data and style properties provided in the request body. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/cards/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_card_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteCardItem',
  'type' => 'write',
  'name' => 'Delete Card Item',
  'description' => 'Deletes a card item from the board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/cards/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_connector' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateConnector',
  'type' => 'write',
  'name' => 'Create Connector',
  'description' => 'Adds a connector to a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/connectors.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_connectors' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetConnectors',
  'type' => 'read',
  'name' => 'Get Connectors',
  'description' => 'Retrieves a list of connectors for a specific board. This method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of',
  'icon' => 'ph:shapes',
),
  'miro_get_connector' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetConnector',
  'type' => 'read',
  'name' => 'Get Connector',
  'description' => 'Retrieves information for a specific connector on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/connectors/{connector_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_connector' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateConnector',
  'type' => 'write',
  'name' => 'Update Connector',
  'description' => 'Updates a connector on a board based on the data and style properties provided in the request body. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/connectors/{connector_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_connector' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteConnector',
  'type' => 'write',
  'name' => 'Delete Connector',
  'description' => 'Deletes the specified connector from the board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/connectors/{connector_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_document_item_using_url' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateDocumentItemUsingUrl',
  'type' => 'write',
  'name' => 'Create Document Item Using Url',
  'description' => 'Adds a document item to a board by specifying the URL where the document is hosted. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/documents.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_document_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetDocumentItem',
  'type' => 'read',
  'name' => 'Get Document Item',
  'description' => 'Retrieves information for a specific document item on a board Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/documents/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_document_item_using_url' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateDocumentItemUsingUrl',
  'type' => 'write',
  'name' => 'Update Document Item Using Url',
  'description' => 'Updates a document item on a board Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/documents/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_document_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteDocumentItem',
  'type' => 'write',
  'name' => 'Delete Document Item',
  'description' => 'Deletes a document item from the board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/documents/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_embed_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateEmbedItem',
  'type' => 'write',
  'name' => 'Create Embed Item',
  'description' => 'Adds an embed item containing external content to a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/embeds.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_embed_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetEmbedItem',
  'type' => 'read',
  'name' => 'Get Embed Item',
  'description' => 'Retrieves information for a specific embed item on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/embeds/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_embed_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateEmbedItem',
  'type' => 'write',
  'name' => 'Update Embed Item',
  'description' => 'Updates an embed item on a board based on the data properties provided in the request body. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/embeds/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_embed_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteEmbedItem',
  'type' => 'write',
  'name' => 'Delete Embed Item',
  'description' => 'Deletes an embed item from the board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/embeds/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_image_item_using_url' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateImageItemUsingUrl',
  'type' => 'write',
  'name' => 'Create Image Item Using Url',
  'description' => 'Adds an image item to a board by specifying an image URL. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/images.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_image_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetImageItem',
  'type' => 'read',
  'name' => 'Get Image Item',
  'description' => 'Retrieves information for a specific image item on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/images/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_image_item_using_url' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateImageItemUsingUrl',
  'type' => 'write',
  'name' => 'Update Image Item Using Url',
  'description' => 'Updates an image item on a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/images/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_image_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteImageItem',
  'type' => 'write',
  'name' => 'Delete Image Item',
  'description' => 'Deletes an image item from the board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/images/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_items' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetItems',
  'type' => 'read',
  'name' => 'Get Items',
  'description' => 'Retrieves a list of items for a specific board. You can retrieve all items on the board, a list of child items inside a parent item, or a list of specific types of items by specifying URL query parameter values. This method returns results using a cursor-based',
  'icon' => 'ph:shapes',
),
  'miro_get_specific_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetSpecificItem',
  'type' => 'read',
  'name' => 'Get Specific Item',
  'description' => 'Retrieves information for a specific item on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/items/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_item_position_or_parent' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateItemPositionOrParent',
  'type' => 'write',
  'name' => 'Update Item Position Or Parent',
  'description' => 'Updates the position or the parent of an item on a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/items/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteItem',
  'type' => 'write',
  'name' => 'Delete Item',
  'description' => 'Deletes an item from a board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/items/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_share_board' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroShareBoard',
  'type' => 'write',
  'name' => 'Share Board',
  'description' => 'Shares the board and Invites new members to collaborate on a board by sending an invitation email. Depending on the board\'s Sharing policy, there might be various scenarios where membership in the team is required in order to share the board with a user. Requi',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_board_members' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetBoardMembers',
  'type' => 'read',
  'name' => 'Get Board Members',
  'description' => 'Retrieves a pageable list of members for a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/members.',
  'icon' => 'ph:shapes',
),
  'miro_get_specific_board_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetSpecificBoardMember',
  'type' => 'read',
  'name' => 'Get Specific Board Member',
  'description' => 'Retrieves information for a board member. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/members/{board_member_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_board_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateBoardMember',
  'type' => 'write',
  'name' => 'Update Board Member',
  'description' => 'Updates the role of a board member. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/members/{board_member_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_remove_board_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroRemoveBoardMember',
  'type' => 'write',
  'name' => 'Remove Board Member',
  'description' => 'Removes a board member from a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: DELETE /v2/boards/{board_id}/members/{board_member_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_shape_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateShapeItem',
  'type' => 'write',
  'name' => 'Create Shape Item',
  'description' => 'Adds a shape item to a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/shapes.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_shape_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetShapeItem',
  'type' => 'read',
  'name' => 'Get Shape Item',
  'description' => 'Retrieves information for a specific shape item on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/shapes/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_shape_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateShapeItem',
  'type' => 'write',
  'name' => 'Update Shape Item',
  'description' => 'Updates a shape item on a board based on the data and style properties provided in the request body. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/shapes/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_shape_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteShapeItem',
  'type' => 'write',
  'name' => 'Delete Shape Item',
  'description' => 'Deletes a shape item from the board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/shapes/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_sticky_note_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateStickyNoteItem',
  'type' => 'write',
  'name' => 'Create Sticky Note Item',
  'description' => 'Adds a sticky note item to a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/sticky_notes.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_sticky_note_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetStickyNoteItem',
  'type' => 'read',
  'name' => 'Get Sticky Note Item',
  'description' => 'Retrieves information for a specific sticky note item on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/sticky_notes/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_sticky_note_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateStickyNoteItem',
  'type' => 'write',
  'name' => 'Update Sticky Note Item',
  'description' => 'Updates a sticky note item on a board based on the data and style properties provided in the request body. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/sticky_notes/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_sticky_note_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteStickyNoteItem',
  'type' => 'write',
  'name' => 'Delete Sticky Note Item',
  'description' => 'Deletes a sticky note item from the board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/sticky_notes/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_text_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateTextItem',
  'type' => 'write',
  'name' => 'Create Text Item',
  'description' => 'Adds a text item to a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/texts.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_text_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetTextItem',
  'type' => 'read',
  'name' => 'Get Text Item',
  'description' => 'Retrieves information for a specific text item on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/texts/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_text_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateTextItem',
  'type' => 'write',
  'name' => 'Update Text Item',
  'description' => 'Updates a text item on a board based on the data and style properties provided in the request body. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/texts/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_text_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteTextItem',
  'type' => 'write',
  'name' => 'Delete Text Item',
  'description' => 'Deletes a text item from the board Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/texts/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_items' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateItems',
  'type' => 'write',
  'name' => 'Create Items',
  'description' => 'Adds different types of items to a board. You can add up to 20 items of the same or different type per create call. For example, you can create 3 shape items, 4 card items, and 5 sticky notes in one create call. The bulk create operation is transactional. If a',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_frame_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateFrameItem',
  'type' => 'write',
  'name' => 'Create Frame Item',
  'description' => 'Adds a frame to a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/frames.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_frame_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetFrameItem',
  'type' => 'read',
  'name' => 'Get Frame Item',
  'description' => 'Retrieves information for a specific frame on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/frames/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_frame_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateFrameItem',
  'type' => 'write',
  'name' => 'Update Frame Item',
  'description' => 'Updates a frame on a board based on the data, style, or geometry properties provided in the request body. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id}/frames/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_frame_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteFrameItem',
  'type' => 'write',
  'name' => 'Delete Frame Item',
  'description' => 'Deletes a frame from a board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/frames/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_items_within_frame' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetItemsWithinFrame',
  'type' => 'read',
  'name' => 'Get Items Within Frame',
  'description' => 'Retrieves a list of items within a specific frame. A frame is a parent item and all items within a frame are child items. This method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based o',
  'icon' => 'ph:shapes',
),
  'miro_create_items_in_bulk_using_file_from_device' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateItemsInBulkUsingFileFromDevice',
  'type' => 'write',
  'name' => 'Create Items In Bulk Using File From Device',
  'description' => 'Adds different types of items to a board using files from a device. You can add up to 20 items of the same or different type per create call. For example, you can create 5 document items and 5 images in one create call. The bulk create operation is transaction',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_metrics' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetMetrics',
  'type' => 'read',
  'name' => 'Get Metrics',
  'description' => 'Returns a list of usage metrics for a specific app for a given time range, grouped by requested time period. This endpoint requires an app management API token. It can be generated in the Your Apps section of Developer Hub. Required scope boards:read Rate limi',
  'icon' => 'ph:shapes',
),
  'miro_get_metrics_total' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetMetricsTotal',
  'type' => 'read',
  'name' => 'Get Metrics Total',
  'description' => 'Returns total usage metrics for a specific app since the app was created. This endpoint requires an app management API token. It can be generated in your apps section of Developer Hub. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: G',
  'icon' => 'ph:shapes',
),
  'miro_get_mindmap_node_experimental' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetMindmapNodeExperimental',
  'type' => 'read',
  'name' => 'Get Mindmap Node Experimental',
  'description' => 'Retrieves information for a specific mind map node on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2-experimental/boards/{board_id}/mindmap_nodes/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_delete_mindmap_node_experimental' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteMindmapNodeExperimental',
  'type' => 'write',
  'name' => 'Delete Mindmap Node Experimental',
  'description' => 'Deletes a mind map node item and its child nodes from the board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2-experimental/boards/{board_id}/mindmap_nodes/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_mindmap_nodes_experimental' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetMindmapNodesExperimental',
  'type' => 'read',
  'name' => 'Get Mindmap Nodes Experimental',
  'description' => 'Retrieves a list of mind map nodes for a specific board. This method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portio',
  'icon' => 'ph:shapes',
),
  'miro_create_mindmap_nodes_experimental' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateMindmapNodesExperimental',
  'type' => 'write',
  'name' => 'Create Mindmap Nodes Experimental',
  'description' => 'Adds a mind map node to a board. A root node is the starting point of a mind map. A node that is created under a root node is a child node. For information on mind maps, use cases, mind map structure, and more, see the Mind Map Overview page. Required scope bo',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_items_experimental' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetItemsExperimental',
  'type' => 'read',
  'name' => 'Get Items Experimental',
  'description' => 'Retrieves a list of items for a specific board. You can retrieve all items on the board, a list of child items inside a parent item, or a list of specific types of items by specifying URL query parameter values. This method returns results using a cursor-based',
  'icon' => 'ph:shapes',
),
  'miro_get_specific_item_experimental' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetSpecificItemExperimental',
  'type' => 'read',
  'name' => 'Get Specific Item Experimental',
  'description' => 'Retrieves information for a specific item on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2-experimental/boards/{board_id}/items/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_delete_item_experimental' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteItemExperimental',
  'type' => 'write',
  'name' => 'Delete Item Experimental',
  'description' => 'Deletes an item from a board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2-experimental/boards/{board_id}/items/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_shape_item_flowchart' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateShapeItemFlowchart',
  'type' => 'write',
  'name' => 'Create Shape Item Flowchart',
  'description' => 'Adds a flowchart shape item to a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2-experimental/boards/{board_id}/shapes.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_shape_item_flowchart' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetShapeItemFlowchart',
  'type' => 'read',
  'name' => 'Get Shape Item Flowchart',
  'description' => 'Retrieves information for a specific shape item on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2-experimental/boards/{board_id}/shapes/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_shape_item_flowchart' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateShapeItemFlowchart',
  'type' => 'write',
  'name' => 'Update Shape Item Flowchart',
  'description' => 'Updates a flowchart shape item on a board based on the data and style properties provided in the request body. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2-experimental/boards/{board_id}/shapes/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_shape_item_flowchart' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteShapeItemFlowchart',
  'type' => 'write',
  'name' => 'Delete Shape Item Flowchart',
  'description' => 'Deletes a flowchart shape item from the board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2-experimental/boards/{board_id}/shapes/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_code_widget_items' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetCodeWidgetItems',
  'type' => 'read',
  'name' => 'Get Code Widget Items',
  'description' => 'Retrieves a list of code widget items for a specific board. This method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next por',
  'icon' => 'ph:shapes',
),
  'miro_create_code_widget_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateCodeWidgetItem',
  'type' => 'write',
  'name' => 'Create Code Widget Item',
  'description' => 'Adds a code widget item to a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2-experimental/boards/{board_id}/code_widgets.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_code_widget_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetCodeWidgetItem',
  'type' => 'read',
  'name' => 'Get Code Widget Item',
  'description' => 'Retrieves information for a specific code widget item on a board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2-experimental/boards/{board_id}/code_widgets/{item_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_code_widget_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateCodeWidgetItem',
  'type' => 'write',
  'name' => 'Update Code Widget Item',
  'description' => 'Updates a code widget item on a board based on the data properties provided in the request body. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2-experimental/boards/{board_id}/code_widgets/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_code_widget_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteCodeWidgetItem',
  'type' => 'write',
  'name' => 'Delete Code Widget Item',
  'description' => 'Deletes a code widget item from the board. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2-experimental/boards/{board_id}/code_widgets/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_move_code_widget_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroMoveCodeWidgetItem',
  'type' => 'write',
  'name' => 'Move Code Widget Item',
  'description' => 'Updates the position of a code widget item on a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2-experimental/boards/{board_id}/code_widgets/{item_id}/position.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_document_item_using_file_from_device' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateDocumentItemUsingFileFromDevice',
  'type' => 'write',
  'name' => 'Create Document Item Using File From Device',
  'description' => 'Adds a document item to a board by selecting file from device. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id_PlatformFileUpload}/documents.',
  'icon' => 'ph:pencil-simple',
),
  'miro_update_document_item_using_file_from_device' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateDocumentItemUsingFileFromDevice',
  'type' => 'write',
  'name' => 'Update Document Item Using File From Device',
  'description' => 'Updates a document item on a board by using file from a device. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id_PlatformFileUpload}/documents/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_image_item_using_local_file' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateImageItemUsingLocalFile',
  'type' => 'write',
  'name' => 'Create Image Item Using Local File',
  'description' => 'Adds an image item to a board by specifying a file from device. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id_PlatformFileUpload}/images.',
  'icon' => 'ph:pencil-simple',
),
  'miro_update_image_item_using_file_from_device' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateImageItemUsingFileFromDevice',
  'type' => 'write',
  'name' => 'Update Image Item Using File From Device',
  'description' => 'Updates an image item on a board. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PATCH /v2/boards/{board_id_PlatformFileUpload}/images/{item_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_create_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateGroup',
  'type' => 'write',
  'name' => 'Create Group',
  'description' => 'Creates a group of items on a board. The group is created with the items that are passed in the request body. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: POST /v2/boards/{board_id}/groups.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_all_groups' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetAllGroups',
  'type' => 'read',
  'name' => 'Get All Groups',
  'description' => 'Returns all the groups and the items of the respective groups within a specific board. This method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor ',
  'icon' => 'ph:shapes',
),
  'miro_get_items_by_group_id' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetItemsByGroupId',
  'type' => 'read',
  'name' => 'Get Items By Group Id',
  'description' => 'Returns a list of items that are a part of any group, within a specific board. This method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that poi',
  'icon' => 'ph:shapes',
),
  'miro_get_group_by_id' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetGroupById',
  'type' => 'read',
  'name' => 'Get Group By Id',
  'description' => 'Returns a list of items in a specific group. Required scope boards:read Rate limiting Level 2 per item ID  Official Miro endpoint: GET /v2/boards/{board_id}/groups/{group_id}.',
  'icon' => 'ph:shapes',
),
  'miro_un_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUnGroup',
  'type' => 'write',
  'name' => 'Un Group',
  'description' => 'Ungroups items from a group. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/groups/{group_id}.',
  'icon' => 'ph:pencil-simple',
),
  'miro_update_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateGroup',
  'type' => 'write',
  'name' => 'Update Group',
  'description' => 'This endpoint updates an existing group by replacing it entirely with a new group. When the update is made, the original group is completely replaced, and a new group ID is assigned. Required scope boards:write Rate limiting Level 2  Official Miro endpoint: PU',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteGroup',
  'type' => 'write',
  'name' => 'Delete Group',
  'description' => 'Deletes a group from a board. All the items in the group are deleted along with the group. Note - this endpoint will delete items which are locked as well. Required scope boards:write Rate limiting Level 3  Official Miro endpoint: DELETE /v2/boards/{board_id}/',
  'icon' => 'ph:pencil-simple',
),
  'miro_revoke_token_v2' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroRevokeTokenV2',
  'type' => 'write',
  'name' => 'Revoke Token V2',
  'description' => 'Revoke the current access token. Revoking an access token means that the access token will no longer work. When an access token is revoked, the refresh token is also revoked and no longer valid. This does not uninstall the application for the user.  Official M',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_tags_from_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetTagsFromItem',
  'type' => 'read',
  'name' => 'Get Tags From Item',
  'description' => 'Retrieves all the tags from the specified item. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/items/{item_id}/tags.',
  'icon' => 'ph:shapes',
),
  'miro_create_tag' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroCreateTag',
  'type' => 'write',
  'name' => 'Create Tag',
  'description' => 'Creates a tag on a board. Required scope boards:write Rate limiting Level 1  Official Miro endpoint: POST /v2/boards/{board_id}/tags.',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_tags_from_board' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetTagsFromBoard',
  'type' => 'read',
  'name' => 'Get Tags From Board',
  'description' => 'Retrieves all the tags from the specified board. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/tags.',
  'icon' => 'ph:shapes',
),
  'miro_get_tag' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetTag',
  'type' => 'read',
  'name' => 'Get Tag',
  'description' => 'Retrieves information for a specific tag. Required scope boards:write Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id}/tags/{tag_id}.',
  'icon' => 'ph:shapes',
),
  'miro_update_tag' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroUpdateTag',
  'type' => 'write',
  'name' => 'Update Tag',
  'description' => 'Updates a tag based on the data properties provided in the request body. Note: Updates to tags made via the REST API will not be reflected on the board in realtime. To see REST API updates to tags on a board, you need to refresh the board. This applies to the ',
  'icon' => 'ph:pencil-simple',
),
  'miro_delete_tag' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroDeleteTag',
  'type' => 'write',
  'name' => 'Delete Tag',
  'description' => 'Deletes the specified tag from the board. The tag is also removed from all cards and sticky notes on the board. Note: Updates to tags made via the REST API will not be reflected on the board in realtime. To see REST API updates to tags on a board, you need to ',
  'icon' => 'ph:pencil-simple',
),
  'miro_get_items_by_tag' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroGetItemsByTag',
  'type' => 'read',
  'name' => 'Get Items By Tag',
  'description' => 'Retrieves all the items that have the specified tag. Required scope boards:read Rate limiting Level 1  Official Miro endpoint: GET /v2/boards/{board_id_PlatformTags}/items.',
  'icon' => 'ph:shapes',
),
  'miro_attach_tag_to_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroAttachTagToItem',
  'type' => 'write',
  'name' => 'Attach Tag To Item',
  'description' => 'Attach an existing tag to the specified item. Card and sticky note items can have up to 8 tags. Note: Updates to tags made via the REST API will not be reflected on the board in realtime. To see REST API updates to tags on a board, you need to refresh the boar',
  'icon' => 'ph:pencil-simple',
),
  'miro_remove_tag_from_item' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroRemoveTagFromItem',
  'type' => 'write',
  'name' => 'Remove Tag From Item',
  'description' => 'Removes the specified tag from the specified item. The tag still exists on the board. Note: Updates to tags made via the REST API will not be reflected on the board in realtime. To see REST API updates to tags on a board, you need to refresh the board. This ap',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_create_project' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseCreateProject',
  'type' => 'write',
  'name' => 'Enterprise Create Project',
  'description' => 'Projects are essentially folders of boards with the option to manage user access for a smaller group of people within a team. Projects are here to help you organize your boards and make them easier to find and share. In other words, a project is a group of boa',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_get_projects' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetProjects',
  'type' => 'read',
  'name' => 'Enterprise Get Projects',
  'description' => 'Retrieves the list of projects in an existing team of an organization. You can retrieve all projects, including all private projects (projects that haven\'t been specifically shared with you) by enabling Content Admin permissions. To enable Content Admin permis',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_get_project' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetProject',
  'type' => 'read',
  'name' => 'Enterprise Get Project',
  'description' => 'Retrieves project information, such as a name for an existing project.Note Projects have been renamed to Spaces, and the terms can be used interchangeably.Required scope projects:read Rate limiting Level 1 Enterprise only This API is available only for Enterpr',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_update_project' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseUpdateProject',
  'type' => 'write',
  'name' => 'Enterprise Update Project',
  'description' => 'Update information about a project, such as the project name.Note Projects have been renamed to Spaces, and the terms can be used interchangeably.Required scope projects:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_delete_project' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDeleteProject',
  'type' => 'write',
  'name' => 'Enterprise Delete Project',
  'description' => 'Deletes a project. After a project is deleted, all boards and users that belong to the project remain in the team.Note Projects have been renamed to Spaces, and the terms can be used interchangeably.Required scope projects:write Rate limiting Level 4 Enterpris',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_get_project_settings' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetProjectSettings',
  'type' => 'read',
  'name' => 'Enterprise Get Project Settings',
  'description' => 'Retrieves the project settings.Note Projects have been renamed to Spaces, and the terms can be used interchangeably.Required scope projects:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this e',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_update_project_settings' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseUpdateProjectSettings',
  'type' => 'write',
  'name' => 'Enterprise Update Project Settings',
  'description' => 'Updates the settings of a project.Note Projects have been renamed to Spaces, and the terms can be used interchangeably.Required scope projects:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use th',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_add_project_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseAddProjectMember',
  'type' => 'write',
  'name' => 'Enterprise Add Project Member',
  'description' => 'Add a Miro user to a project.Note Projects have been renamed to Spaces, and the terms can be used interchangeably.Required scope projects:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this en',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_get_project_members' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetProjectMembers',
  'type' => 'read',
  'name' => 'Enterprise Get Project Members',
  'description' => 'Retrieves the list of members for a specific project.Note Projects have been renamed to Spaces, and the terms can be used interchangeably.Required scope projects:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. Y',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_get_project_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetProjectMember',
  'type' => 'read',
  'name' => 'Enterprise Get Project Member',
  'description' => 'Retrieves information for a specific project member.Note Projects have been renamed to Spaces, and the terms can be used interchangeably.Required scope projects:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. Yo',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_update_project_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseUpdateProjectMember',
  'type' => 'write',
  'name' => 'Enterprise Update Project Member',
  'description' => 'Updates details of a project member, such as the member\'s role.Note Projects have been renamed to Spaces, and the terms can be used interchangeably.Required scope projects:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise pl',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_delete_project_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDeleteProjectMember',
  'type' => 'write',
  'name' => 'Enterprise Delete Project Member',
  'description' => 'Remove a member from a project. The user remains in the team even after the member is removed from a project.Note Projects have been renamed to Spaces, and the terms can be used interchangeably.Required scope projects:write Rate limiting Level 4 Enterprise onl',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_create_team' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseCreateTeam',
  'type' => 'write',
  'name' => 'Enterprise Create Team',
  'description' => 'Creates a new team in an existing organization. Required scope organizations:teams:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_get_teams' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetTeams',
  'type' => 'read',
  'name' => 'Enterprise Get Teams',
  'description' => 'Retrieves list of teams in an existing organization. Required scope organizations:teams:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_get_team' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetTeam',
  'type' => 'read',
  'name' => 'Enterprise Get Team',
  'description' => 'Retrieves team information for an existing team. Required scope organizations:teams:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_update_team' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseUpdateTeam',
  'type' => 'write',
  'name' => 'Enterprise Update Team',
  'description' => 'Updates an existing team. Required scope organizations:teams:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can request temporary acc',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_delete_team' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDeleteTeam',
  'type' => 'write',
  'name' => 'Enterprise Delete Team',
  'description' => 'Deletes an existing team. Required scope organizations:teams:write Rate limiting Level 4 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can request temporary acc',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_invite_team_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseInviteTeamMember',
  'type' => 'write',
  'name' => 'Enterprise Invite Team Member',
  'description' => 'Invites a new Miro user to an existing team. The user must exist in your Miro organization. Users who do not exist in your Miro organization can be invited to the team via [SCIM](https://developers.miro.com/docs/scim) and an external identity provider, such as',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_get_team_members' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetTeamMembers',
  'type' => 'read',
  'name' => 'Enterprise Get Team Members',
  'description' => 'Retrieves team members by cursor. Required scope organizations:teams:read Rate limiting Level 2 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can request tempor',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_get_team_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetTeamMember',
  'type' => 'read',
  'name' => 'Enterprise Get Team Member',
  'description' => 'Retrieves team member by id. Required scope organizations:teams:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can request temporary a',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_update_team_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseUpdateTeamMember',
  'type' => 'write',
  'name' => 'Enterprise Update Team Member',
  'description' => 'Updates team member role in team by id. Required scope organizations:teams:write Rate limiting Level 2 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can request',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_delete_team_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDeleteTeamMember',
  'type' => 'write',
  'name' => 'Enterprise Delete Team Member',
  'description' => 'Deletes team member from team by id. Required scope organizations:teams:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can request te',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_get_default_team_settings' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetDefaultTeamSettings',
  'type' => 'read',
  'name' => 'Enterprise Get Default Team Settings',
  'description' => 'Retrieves default team settings of an existing organization. Required scope organizations:teams:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Ad',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_get_team_settings' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetTeamSettings',
  'type' => 'read',
  'name' => 'Enterprise Get Team Settings',
  'description' => 'Retrieves team settings of an existing team. Required scope organizations:teams:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can req',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_update_team_settings' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseUpdateTeamSettings',
  'type' => 'write',
  'name' => 'Enterprise Update Team Settings',
  'description' => 'Updates team settings of an existing team. Required scope organizations:teams:write Rate limiting Level 2 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can requ',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_get_groups' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetGroups',
  'type' => 'read',
  'name' => 'Enterprise Get Groups',
  'description' => 'Retrieves the list of user groups in an organization. Required scope organizations:groups:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. Y',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_create_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseCreateGroup',
  'type' => 'write',
  'name' => 'Enterprise Create Group',
  'description' => 'Creates a new user group in an organization. Required scope organizations:groups:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can r',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_get_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetGroup',
  'type' => 'read',
  'name' => 'Enterprise Get Group',
  'description' => 'Retrieves a user group in an organization. Required scope organizations:groups:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can requ',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_update_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseUpdateGroup',
  'type' => 'write',
  'name' => 'Enterprise Update Group',
  'description' => 'Updates a user group in an organization. Required scope organizations:groups:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can reque',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_delete_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDeleteGroup',
  'type' => 'write',
  'name' => 'Enterprise Delete Group',
  'description' => 'Deletes a user group from an organization. Required scope organizations:groups:write Rate limiting Level 4 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You can req',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_get_group_members' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetGroupMembers',
  'type' => 'read',
  'name' => 'Enterprise Get Group Members',
  'description' => 'Retrieves the list of members who are part of a team in an existing organization. Required scope organizations:groups:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have th',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_create_group_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseCreateGroupMember',
  'type' => 'write',
  'name' => 'Enterprise Create Group Member',
  'description' => 'Adds a member to a user group in an organization. Required scope organizations:groups:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin. You ',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_update_group_members' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseUpdateGroupMembers',
  'type' => 'write',
  'name' => 'Enterprise Update Group Members',
  'description' => 'Add and remove members in one request. For example, remove user A and add user B. You can add or remove up to 500 users at a time. Required scope organizations:groups:write Rate limiting Level 1 per item. For example, if you want to add 10 users and remove 5, ',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_get_group_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGetGroupMember',
  'type' => 'read',
  'name' => 'Enterprise Get Group Member',
  'description' => 'Retrieves information about a user group member in an organization. Required scope organizations:groups:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Co',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_delete_group_member' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseDeleteGroupMember',
  'type' => 'write',
  'name' => 'Enterprise Delete Group Member',
  'description' => 'Removes a member from a user group in an organization. Required scope organizations:groups:write Rate limiting Level 4 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Admin.',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_groups_get_teams' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGroupsGetTeams',
  'type' => 'read',
  'name' => 'Enterprise Groups Get Teams',
  'description' => 'Retrieves the list of teams that the user group is a part of. Required scope organizations:groups:read organizations:teams:readRate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you hav',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_groups_get_team' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseGroupsGetTeam',
  'type' => 'read',
  'name' => 'Enterprise Groups Get Team',
  'description' => 'Retrieves information of a team that the user group is a part of in an organization. Required scope organizations:groups:read organizations:teams:readRate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use t',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_teams_get_groups' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseTeamsGetGroups',
  'type' => 'read',
  'name' => 'Enterprise Teams Get Groups',
  'description' => 'Retrieves the list of user groups that are part of a team in an organization. Required scope organizations:groups:read organizations:teams:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this en',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_teams_create_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseTeamsCreateGroup',
  'type' => 'write',
  'name' => 'Enterprise Teams Create Group',
  'description' => 'Adds a user group to a team in an organization. Required scope organizations:groups:read organizations:teams:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role o',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_teams_get_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseTeamsGetGroup',
  'type' => 'read',
  'name' => 'Enterprise Teams Get Group',
  'description' => 'Retrieves information about a specific user group of a team. Required scope organizations:groups:read organizations:teams:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you hav',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_teams_delete_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseTeamsDeleteGroup',
  'type' => 'write',
  'name' => 'Enterprise Teams Delete Group',
  'description' => 'Removes a user group from a team in an existing organization. Required scope organizations:groups:read organizations:teams:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you h',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_boards_get_groups' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseBoardsGetGroups',
  'type' => 'read',
  'name' => 'Enterprise Boards Get Groups',
  'description' => 'Retrieves information about user groups invited to the specified board. Required scope organizations:groups:read boards:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have ',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_boards_create_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseBoardsCreateGroup',
  'type' => 'write',
  'name' => 'Enterprise Boards Create Group',
  'description' => 'Shares a board with user groups with a specified role. Updates the role if already shared. Required scope organizations:groups:read boards:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this e',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_boards_delete_groups' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseBoardsDeleteGroups',
  'type' => 'write',
  'name' => 'Enterprise Boards Delete Groups',
  'description' => 'Removes a user group from the specified board. Required scope organizations:groups:read boards:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Company Ad',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_projects_get_groups' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseProjectsGetGroups',
  'type' => 'read',
  'name' => 'Enterprise Projects Get Groups',
  'description' => 'Retrieves information about user groups invited to the specified project. Required scope organizations:groups:read projects:read Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you h',
  'icon' => 'ph:shapes',
),
  'miro_enterprise_project_create_group' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseProjectCreateGroup',
  'type' => 'write',
  'name' => 'Enterprise Project Create Group',
  'description' => 'Shares a project with user groups with a specified role. Updates the role if already shared. Required scope organizations:groups:read projects:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use th',
  'icon' => 'ph:pencil-simple',
),
  'miro_enterprise_project_delete_groups' => array (
  'class' => 'OpenCompany\\Integrations\\Miro\\Tools\\MiroEnterpriseProjectDeleteGroups',
  'type' => 'write',
  'name' => 'Enterprise Project Delete Groups',
  'description' => 'Removes a user group from the specified project. Required scope organizations:groups:read projects:write Rate limiting Level 1 Enterprise only This API is available only for Enterprise plan users. You can only use this endpoint if you have the role of a Compan',
  'icon' => 'ph:pencil-simple',
),
    ]; }
    public function isIntegration(): bool { return true; } public function createTool(string $class, array $context = []): Tool { return new $class($this->resolveService($context)); } public function luaDocsPath(): ?string { return __DIR__.'/../lua-docs/miro.md'; }
    /** @param  array<string, mixed>  $context  Runtime account context. */ private function resolveService(array $context=[]): MiroService { $account=$context['account']??null; if($account!==null){ $creds=app(CredentialResolver::class); return new MiroService(accessToken:$creds->get('miro','access_token','',$account), baseUrl:$creds->get('miro','url','https://api.miro.com',$account)); } return app(MiroService::class); }
}
