<?php

namespace OpenCompany\Integrations\FusionAuth\Tools;

/**
 * retrieve User Change Password With Id.
 *
 * Maps to GET /api/user/change-password/{changePasswordId} in the official FusionAuth OpenAPI document.
 */
class FusionAuthRetrieveUserChangePasswordWithId extends AbstractFusionAuthTool
{
    protected const OPERATION = array (
  'slug' => 'fusionauth_retrieve_user_change_password_with_id',
  'class' => 'FusionAuthRetrieveUserChangePasswordWithId',
  'method' => 'GET',
  'path' => '/api/user/change-password/{changePasswordId}',
  'operation_id' => 'retrieveUserChangePasswordWithId',
  'summary' => 'retrieve User Change Password With Id',
  'description' => 'Check to see if the user must obtain a Trust Token Id in order to complete a change password request. When a user has enabled Two-Factor authentication, before you are allowed to use the Change Password API to change your password, you must obtain a Trust Token by completing a Two-Factor Step-Up authentication. An HTTP status code of 400 with a general error code of [TrustTokenRequired] indicates that a Trust Token is required to make a POST request to this API. OR Check to see if the user must ',
  'parameters' =>
  array (
    'ip_address' =>
    array (
      'type' => 'string',
      'required' => false,
      'description' => 'IP address of the user changing their password. This is used for MFA risk assessment.',
    ),
    'change_password_id' =>
    array (
      'type' => 'string',
      'required' => true,
      'description' => 'The change password Id used to find the user. This value is generated by FusionAuth once the change password workflow has been initiated.',
    ),
  ),
  'path_params' =>
  array (
    'changePasswordId' => 'change_password_id',
  ),
  'query_params' =>
  array (
    'ipAddress' => 'ip_address',
  ),
  'header_params' =>
  array (
  ),
  'body_required' => false,
  'content_type' => NULL,
  'type' => 'read',
);
}
