<?php

namespace OpenCompany\Integrations\FusionAuth\Tools;

/**
 * change Password With Id.
 *
 * Maps to POST /api/user/change-password/{changePasswordId} in the official FusionAuth OpenAPI document.
 */
class FusionAuthChangePasswordWithId extends AbstractFusionAuthTool
{
    protected const OPERATION = array (
  'slug' => 'fusionauth_change_password_with_id',
  'class' => 'FusionAuthChangePasswordWithId',
  'method' => 'POST',
  'path' => '/api/user/change-password/{changePasswordId}',
  'operation_id' => 'changePasswordWithId',
  'summary' => 'change Password With Id',
  'description' => 'Changes a user\'s password using the change password Id. This usually occurs after an email has been sent to the user and they clicked on a link to reset their password. As of version 1.32.2, prefer sending the changePasswordId in the request body. To do this, omit the first parameter, and set the value in the request body.',
  'parameters' =>
  array (
    'change_password_id' =>
    array (
      'type' => 'string',
      'required' => true,
      'description' => 'The change password Id used to find the user. This value is generated by FusionAuth once the change password workflow has been initiated.',
    ),
    'body' =>
    array (
      'type' => 'object',
      'required' => false,
      'description' => 'Request body matching the official FusionAuth OpenAPI schema for this endpoint.',
    ),
  ),
  'path_params' =>
  array (
    'changePasswordId' => 'change_password_id',
  ),
  'query_params' =>
  array (
  ),
  'header_params' =>
  array (
  ),
  'body_required' => false,
  'content_type' => 'application/json',
  'type' => 'write',
);
}
