<?php

namespace OpenCompany\Integrations\Binance\Tools;

/**
 * Margin Account Cancel OCO (TRADE).
 *
 * Maps to the official Binance Spot endpoint DELETE /sapi/v1/margin/orderList.
 */
class BinanceDeleteSapiV1MarginOrderlist extends AbstractBinanceTool
{
    protected const NAME = 'binance_delete_sapi_v1_margin_orderlist';
    protected const DESCRIPTION = 'Margin Account Cancel OCO (TRADE)

Cancel an entire Order List for a margin account - Canceling an individual leg will cancel the entire OCO - Either `orderListId` or `listClientOrderId` must be provided Weight(UID): 1

Official Binance Spot endpoint: DELETE /sapi/v1/margin/orderList.';
    protected const PARAMETERS = [
        'symbol' => [
            'type' => 'string',
            'required' => true,
            'description' => 'Trading symbol, e.g. BNBUSDT',
        ],
        'is_isolated' => [
            'type' => 'string',
            'required' => false,
            'description' => '* `TRUE` - For isolated margin * `FALSE` - Default, not for isolated margin',
            'enum' => [
                'TRUE',
                'FALSE',
            ],
        ],
        'order_list_id' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'Order list id',
        ],
        'list_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'A unique Id for the entire orderList',
        ],
        'new_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Used to uniquely identify this cancel. Automatically generated by default',
        ],
        'recv_window' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'The value cannot be greater than 60000',
        ],
        'timestamp' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'UTC timestamp in ms',
        ],
    ];
    protected const METHOD = 'DELETE';
    protected const PATH = '/sapi/v1/margin/orderList';
    protected const PATH_PARAMS = [];
    protected const QUERY_PARAMS = [
        'symbol' => 'symbol',
        'isIsolated' => 'is_isolated',
        'orderListId' => 'order_list_id',
        'listClientOrderId' => 'list_client_order_id',
        'newClientOrderId' => 'new_client_order_id',
        'recvWindow' => 'recv_window',
        'timestamp' => 'timestamp',
    ];
    protected const HEADER_PARAMS = [];
    protected const AUTH_MODE = 'signed';
}
