<?php

namespace OpenCompany\Integrations\Binance\Tools;

/**
 * Margin Account New Order (TRADE).
 *
 * Maps to the official Binance Spot endpoint POST /sapi/v1/margin/order.
 */
class BinancePostSapiV1MarginOrder extends AbstractBinanceTool
{
    protected const NAME = 'binance_post_sapi_v1_margin_order';
    protected const DESCRIPTION = 'Margin Account New Order (TRADE)

Post a new order for margin account. Weight(UID): 6

Official Binance Spot endpoint: POST /sapi/v1/margin/order.';
    protected const PARAMETERS = [
        'symbol' => [
            'type' => 'string',
            'required' => true,
            'description' => 'Trading symbol, e.g. BNBUSDT',
        ],
        'is_isolated' => [
            'type' => 'string',
            'required' => false,
            'description' => '* `TRUE` - For isolated margin * `FALSE` - Default, not for isolated margin',
            'enum' => [
                'TRUE',
                'FALSE',
            ],
        ],
        'side' => [
            'type' => 'string',
            'required' => true,
            'description' => 'query parameter `side`.',
            'enum' => [
                'SELL',
                'BUY',
            ],
        ],
        'type' => [
            'type' => 'string',
            'required' => true,
            'description' => 'Order type',
            'enum' => [
                'LIMIT',
                'MARKET',
                'STOP_LOSS',
                'STOP_LOSS_LIMIT',
                'TAKE_PROFIT',
                'TAKE_PROFIT_LIMIT',
                'LIMIT_MAKER',
            ],
        ],
        'quantity' => [
            'type' => 'number',
            'required' => true,
            'description' => 'query parameter `quantity`.',
        ],
        'quote_order_qty' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Quote quantity',
        ],
        'price' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Order price',
        ],
        'stop_price' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Used with STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, and TAKE_PROFIT_LIMIT orders.',
        ],
        'new_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Used to uniquely identify this cancel. Automatically generated by default',
        ],
        'iceberg_qty' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Used with LIMIT, STOP_LOSS_LIMIT, and TAKE_PROFIT_LIMIT to create an iceberg order.',
        ],
        'new_order_resp_type' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Set the response JSON.',
            'enum' => [
                'ACK',
                'RESULT',
                'FULL',
            ],
        ],
        'side_effect_type' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Default `NO_SIDE_EFFECT`',
            'enum' => [
                'NO_SIDE_EFFECT',
                'MARGIN_BUY',
                'AUTO_REPAY',
            ],
        ],
        'time_in_force' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Order time in force',
            'enum' => [
                'GTC',
                'IOC',
                'FOK',
            ],
        ],
        'auto_repay_at_cancel' => [
            'type' => 'boolean',
            'required' => true,
            'description' => 'query parameter `autoRepayAtCancel`.',
        ],
        'self_trade_prevention_mode' => [
            'type' => 'string',
            'required' => false,
            'description' => 'The allowed enums is dependent on what is configured on the symbol. The possible supported values are EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH, NONE.',
            'enum' => [
                'EXPIRE_TAKER',
                'EXPIRE_MAKER',
                'EXPIRE_BOTH',
                'NONE',
            ],
        ],
        'recv_window' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'The value cannot be greater than 60000',
        ],
        'timestamp' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'UTC timestamp in ms',
        ],
    ];
    protected const METHOD = 'POST';
    protected const PATH = '/sapi/v1/margin/order';
    protected const PATH_PARAMS = [];
    protected const QUERY_PARAMS = [
        'symbol' => 'symbol',
        'isIsolated' => 'is_isolated',
        'side' => 'side',
        'type' => 'type',
        'quantity' => 'quantity',
        'quoteOrderQty' => 'quote_order_qty',
        'price' => 'price',
        'stopPrice' => 'stop_price',
        'newClientOrderId' => 'new_client_order_id',
        'icebergQty' => 'iceberg_qty',
        'newOrderRespType' => 'new_order_resp_type',
        'sideEffectType' => 'side_effect_type',
        'timeInForce' => 'time_in_force',
        'autoRepayAtCancel' => 'auto_repay_at_cancel',
        'selfTradePreventionMode' => 'self_trade_prevention_mode',
        'recvWindow' => 'recv_window',
        'timestamp' => 'timestamp',
    ];
    protected const HEADER_PARAMS = [];
    protected const AUTH_MODE = 'signed';
}
