<?php

namespace OpenCompany\Integrations\Binance\Tools;

/**
 * Test new order using SOR (TRADE).
 *
 * Maps to the official Binance Spot endpoint POST /api/v3/sor/order/test.
 */
class BinancePostApiV3SorOrderTest extends AbstractBinanceTool
{
    protected const NAME = 'binance_post_api_v3_sor_order_test';
    protected const DESCRIPTION = 'Test new order using SOR (TRADE)

Test new order creation and signature/recvWindow using smart order routing (SOR). Creates and validates a new order but does not send it into the matching engine. Weight(IP): - Without computeCommissionRates: `1` - With computeCommissionRates: `20`

Official Binance Spot endpoint: POST /api/v3/sor/order/test.';
    protected const PARAMETERS = [
        'symbol' => [
            'type' => 'string',
            'required' => true,
            'description' => 'Trading symbol, e.g. BNBUSDT',
        ],
        'side' => [
            'type' => 'string',
            'required' => true,
            'description' => 'query parameter `side`.',
            'enum' => [
                'SELL',
                'BUY',
            ],
        ],
        'type' => [
            'type' => 'string',
            'required' => true,
            'description' => 'Order type',
            'enum' => [
                'LIMIT',
                'MARKET',
                'STOP_LOSS',
                'STOP_LOSS_LIMIT',
                'TAKE_PROFIT',
                'TAKE_PROFIT_LIMIT',
                'LIMIT_MAKER',
            ],
        ],
        'time_in_force' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Order time in force',
            'enum' => [
                'GTC',
                'IOC',
                'FOK',
            ],
        ],
        'quantity' => [
            'type' => 'number',
            'required' => true,
            'description' => 'query parameter `quantity`.',
        ],
        'price' => [
            'type' => 'number',
            'required' => false,
            'description' => 'query parameter `price`.',
        ],
        'new_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Used to uniquely identify this cancel. Automatically generated by default',
        ],
        'strategy_id' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'query parameter `strategyId`.',
        ],
        'strategy_type' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'The value cannot be less than 1000000.',
        ],
        'iceberg_qty' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Used with LIMIT, STOP_LOSS_LIMIT, and TAKE_PROFIT_LIMIT to create an iceberg order.',
        ],
        'new_order_resp_type' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Set the response JSON. MARKET and LIMIT order types default to FULL, all other orders default to ACK.',
            'enum' => [
                'ACK',
                'RESULT',
                'FULL',
            ],
        ],
        'self_trade_prevention_mode' => [
            'type' => 'string',
            'required' => false,
            'description' => 'The allowed enums is dependent on what is configured on the symbol. The possible supported values are EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH, NONE.',
            'enum' => [
                'EXPIRE_TAKER',
                'EXPIRE_MAKER',
                'EXPIRE_BOTH',
                'NONE',
            ],
        ],
        'compute_commission_rates' => [
            'type' => 'boolean',
            'required' => false,
            'description' => 'Default: false',
        ],
        'recv_window' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'The value cannot be greater than 60000',
        ],
        'timestamp' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'UTC timestamp in ms',
        ],
    ];
    protected const METHOD = 'POST';
    protected const PATH = '/api/v3/sor/order/test';
    protected const PATH_PARAMS = [];
    protected const QUERY_PARAMS = [
        'symbol' => 'symbol',
        'side' => 'side',
        'type' => 'type',
        'timeInForce' => 'time_in_force',
        'quantity' => 'quantity',
        'price' => 'price',
        'newClientOrderId' => 'new_client_order_id',
        'strategyId' => 'strategy_id',
        'strategyType' => 'strategy_type',
        'icebergQty' => 'iceberg_qty',
        'newOrderRespType' => 'new_order_resp_type',
        'selfTradePreventionMode' => 'self_trade_prevention_mode',
        'computeCommissionRates' => 'compute_commission_rates',
        'recvWindow' => 'recv_window',
        'timestamp' => 'timestamp',
    ];
    protected const HEADER_PARAMS = [];
    protected const AUTH_MODE = 'signed';
}
