<?php

namespace OpenCompany\Integrations\Binance\Tools;

/**
 * Cancel Order (TRADE).
 *
 * Maps to the official Binance Spot endpoint DELETE /api/v3/order.
 */
class BinanceDeleteApiV3Order extends AbstractBinanceTool
{
    protected const NAME = 'binance_delete_api_v3_order';
    protected const DESCRIPTION = 'Cancel Order (TRADE)

Cancel an active order. Either `orderId` or `origClientOrderId` must be sent. Weight(IP): 1

Official Binance Spot endpoint: DELETE /api/v3/order.';
    protected const PARAMETERS = [
        'symbol' => [
            'type' => 'string',
            'required' => true,
            'description' => 'Trading symbol, e.g. BNBUSDT',
        ],
        'order_id' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'Order id',
        ],
        'orig_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Order id from client',
        ],
        'new_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Used to uniquely identify this cancel. Automatically generated by default',
        ],
        'cancel_restrictions' => [
            'type' => 'string',
            'required' => false,
            'description' => 'query parameter `cancelRestrictions`.',
            'enum' => [
                'ONLY_NEW',
                'ONLY_PARTIALLY_FILLED',
            ],
        ],
        'recv_window' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'The value cannot be greater than 60000',
        ],
        'timestamp' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'UTC timestamp in ms',
        ],
    ];
    protected const METHOD = 'DELETE';
    protected const PATH = '/api/v3/order';
    protected const PATH_PARAMS = [];
    protected const QUERY_PARAMS = [
        'symbol' => 'symbol',
        'orderId' => 'order_id',
        'origClientOrderId' => 'orig_client_order_id',
        'newClientOrderId' => 'new_client_order_id',
        'cancelRestrictions' => 'cancel_restrictions',
        'recvWindow' => 'recv_window',
        'timestamp' => 'timestamp',
    ];
    protected const HEADER_PARAMS = [];
    protected const AUTH_MODE = 'signed';
}
