<?php

namespace OpenCompany\Integrations\Binance\Tools;

/**
 * Cancel OCO (TRADE).
 *
 * Maps to the official Binance Spot endpoint DELETE /api/v3/orderList.
 */
class BinanceDeleteApiV3Orderlist extends AbstractBinanceTool
{
    protected const NAME = 'binance_delete_api_v3_orderlist';
    protected const DESCRIPTION = 'Cancel OCO (TRADE)

Cancel an entire Order List Canceling an individual leg will cancel the entire OCO Weight(IP): 1

Official Binance Spot endpoint: DELETE /api/v3/orderList.';
    protected const PARAMETERS = [
        'symbol' => [
            'type' => 'string',
            'required' => true,
            'description' => 'Trading symbol, e.g. BNBUSDT',
        ],
        'order_list_id' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'Order list id',
        ],
        'list_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'A unique Id for the entire orderList',
        ],
        'new_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Used to uniquely identify this cancel. Automatically generated by default',
        ],
        'recv_window' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'The value cannot be greater than 60000',
        ],
        'timestamp' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'UTC timestamp in ms',
        ],
    ];
    protected const METHOD = 'DELETE';
    protected const PATH = '/api/v3/orderList';
    protected const PATH_PARAMS = [];
    protected const QUERY_PARAMS = [
        'symbol' => 'symbol',
        'orderListId' => 'order_list_id',
        'listClientOrderId' => 'list_client_order_id',
        'newClientOrderId' => 'new_client_order_id',
        'recvWindow' => 'recv_window',
        'timestamp' => 'timestamp',
    ];
    protected const HEADER_PARAMS = [];
    protected const AUTH_MODE = 'signed';
}
