<?php

namespace OpenCompany\Integrations\Binance\Tools;

/**
 * New Order (TRADE).
 *
 * Maps to the official Binance Spot endpoint POST /api/v3/order.
 */
class BinancePostApiV3Order extends AbstractBinanceTool
{
    protected const NAME = 'binance_post_api_v3_order';
    protected const DESCRIPTION = 'New Order (TRADE)

Send in a new order. - `LIMIT_MAKER` are `LIMIT` orders that will be rejected if they would immediately match and trade as a taker. - `STOP_LOSS` and `TAKE_PROFIT` will execute a `MARKET` order when the `stopPrice` is reached. - Any `LIMIT` or `LIMIT_MAKER` type order can be made an iceberg order by sending an `icebergQty`. - Any order with an `icebergQty` MUST have `timeInForce` set to `GTC`. - `MARKET` orders using `quantity` specifies how much a user wants to buy or sell based on the market price. - `MARKET` orders using `quoteOrderQty` specifies the amount the user wants to spend (when buying) or receive (when selling) of the quote asset; the correct quantity will be determined based on the market liquidity and `quoteOrderQty`. - `MARKET` orders using `quoteOrderQty` will not break `LOT_SIZE` filter rules; the order will execute a quantity that will have the notional value as close as possible to `quoteOrderQty`. - same `newClientOrderId` can be accepted only when the previous one

Official Binance Spot endpoint: POST /api/v3/order.';
    protected const PARAMETERS = [
        'symbol' => [
            'type' => 'string',
            'required' => true,
            'description' => 'Trading symbol, e.g. BNBUSDT',
        ],
        'side' => [
            'type' => 'string',
            'required' => true,
            'description' => 'query parameter `side`.',
            'enum' => [
                'SELL',
                'BUY',
            ],
        ],
        'type' => [
            'type' => 'string',
            'required' => true,
            'description' => 'Order type',
            'enum' => [
                'LIMIT',
                'MARKET',
                'STOP_LOSS',
                'STOP_LOSS_LIMIT',
                'TAKE_PROFIT',
                'TAKE_PROFIT_LIMIT',
                'LIMIT_MAKER',
            ],
        ],
        'time_in_force' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Order time in force',
            'enum' => [
                'GTC',
                'IOC',
                'FOK',
            ],
        ],
        'quantity' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Order quantity',
        ],
        'quote_order_qty' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Quote quantity',
        ],
        'price' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Order price',
        ],
        'new_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Used to uniquely identify this cancel. Automatically generated by default',
        ],
        'strategy_id' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'query parameter `strategyId`.',
        ],
        'strategy_type' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'The value cannot be less than 1000000.',
        ],
        'stop_price' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Used with STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, and TAKE_PROFIT_LIMIT orders.',
        ],
        'trailing_delta' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Used with STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, and TAKE_PROFIT_LIMIT orders.',
        ],
        'iceberg_qty' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Used with LIMIT, STOP_LOSS_LIMIT, and TAKE_PROFIT_LIMIT to create an iceberg order.',
        ],
        'new_order_resp_type' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Set the response JSON. MARKET and LIMIT order types default to FULL, all other orders default to ACK.',
            'enum' => [
                'ACK',
                'RESULT',
                'FULL',
            ],
        ],
        'self_trade_prevention_mode' => [
            'type' => 'string',
            'required' => false,
            'description' => 'The allowed enums is dependent on what is configured on the symbol. The possible supported values are EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH, NONE.',
            'enum' => [
                'EXPIRE_TAKER',
                'EXPIRE_MAKER',
                'EXPIRE_BOTH',
                'NONE',
            ],
        ],
        'recv_window' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'The value cannot be greater than 60000',
        ],
        'timestamp' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'UTC timestamp in ms',
        ],
    ];
    protected const METHOD = 'POST';
    protected const PATH = '/api/v3/order';
    protected const PATH_PARAMS = [];
    protected const QUERY_PARAMS = [
        'symbol' => 'symbol',
        'side' => 'side',
        'type' => 'type',
        'timeInForce' => 'time_in_force',
        'quantity' => 'quantity',
        'quoteOrderQty' => 'quote_order_qty',
        'price' => 'price',
        'newClientOrderId' => 'new_client_order_id',
        'strategyId' => 'strategy_id',
        'strategyType' => 'strategy_type',
        'stopPrice' => 'stop_price',
        'trailingDelta' => 'trailing_delta',
        'icebergQty' => 'iceberg_qty',
        'newOrderRespType' => 'new_order_resp_type',
        'selfTradePreventionMode' => 'self_trade_prevention_mode',
        'recvWindow' => 'recv_window',
        'timestamp' => 'timestamp',
    ];
    protected const HEADER_PARAMS = [];
    protected const AUTH_MODE = 'signed';
}
