<?php

namespace OpenCompany\Integrations\Binance\Tools;

/**
 * Cancel an Existing Order and Send a New Order (Trade).
 *
 * Maps to the official Binance Spot endpoint POST /api/v3/order/cancelReplace.
 */
class BinancePostApiV3OrderCancelreplace extends AbstractBinanceTool
{
    protected const NAME = 'binance_post_api_v3_order_cancelreplace';
    protected const DESCRIPTION = 'Cancel an Existing Order and Send a New Order (Trade)

Cancels an existing order and places a new order on the same symbol. Filters and Order Count are evaluated before the processing of the cancellation and order placement occurs. A new order that was not attempted (i.e. when newOrderResult: NOT_ATTEMPTED), will still increase the order count by 1. Weight(IP): 1

Official Binance Spot endpoint: POST /api/v3/order/cancelReplace.';
    protected const PARAMETERS = [
        'symbol' => [
            'type' => 'string',
            'required' => true,
            'description' => 'Trading symbol, e.g. BNBUSDT',
        ],
        'side' => [
            'type' => 'string',
            'required' => true,
            'description' => 'query parameter `side`.',
            'enum' => [
                'SELL',
                'BUY',
            ],
        ],
        'type' => [
            'type' => 'string',
            'required' => true,
            'description' => 'Order type',
            'enum' => [
                'LIMIT',
                'MARKET',
                'STOP_LOSS',
                'STOP_LOSS_LIMIT',
                'TAKE_PROFIT',
                'TAKE_PROFIT_LIMIT',
                'LIMIT_MAKER',
            ],
        ],
        'cancel_replace_mode' => [
            'type' => 'string',
            'required' => true,
            'description' => '- `STOP_ON_FAILURE` If the cancel request fails, the new order placement will not be attempted. - `ALLOW_FAILURES` If new order placement will be attempted even if cancel request fails.',
        ],
        'cancel_restrictions' => [
            'type' => 'string',
            'required' => false,
            'description' => 'query parameter `cancelRestrictions`.',
            'enum' => [
                'ONLY_NEW',
                'ONLY_PARTIALLY_FILLED',
            ],
        ],
        'time_in_force' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Order time in force',
            'enum' => [
                'GTC',
                'IOC',
                'FOK',
            ],
        ],
        'quantity' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Order quantity',
        ],
        'quote_order_qty' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Quote quantity',
        ],
        'price' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Order price',
        ],
        'cancel_new_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Used to uniquely identify this cancel. Automatically generated by default',
        ],
        'cancel_orig_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Either the cancelOrigClientOrderId or cancelOrderId must be provided. If both are provided, cancelOrderId takes precedence.',
        ],
        'cancel_order_id' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'Either the cancelOrigClientOrderId or cancelOrderId must be provided. If both are provided, cancelOrderId takes precedence.',
        ],
        'new_client_order_id' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Used to uniquely identify this cancel. Automatically generated by default',
        ],
        'strategy_id' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'query parameter `strategyId`.',
        ],
        'strategy_type' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'The value cannot be less than 1000000.',
        ],
        'stop_price' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Used with STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, and TAKE_PROFIT_LIMIT orders.',
        ],
        'trailing_delta' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Used with STOP_LOSS, STOP_LOSS_LIMIT, TAKE_PROFIT, and TAKE_PROFIT_LIMIT orders.',
        ],
        'iceberg_qty' => [
            'type' => 'number',
            'required' => false,
            'description' => 'Used with LIMIT, STOP_LOSS_LIMIT, and TAKE_PROFIT_LIMIT to create an iceberg order.',
        ],
        'new_order_resp_type' => [
            'type' => 'string',
            'required' => false,
            'description' => 'Set the response JSON. MARKET and LIMIT order types default to FULL, all other orders default to ACK.',
            'enum' => [
                'ACK',
                'RESULT',
                'FULL',
            ],
        ],
        'self_trade_prevention_mode' => [
            'type' => 'string',
            'required' => false,
            'description' => 'The allowed enums is dependent on what is configured on the symbol. The possible supported values are EXPIRE_TAKER, EXPIRE_MAKER, EXPIRE_BOTH, NONE.',
            'enum' => [
                'EXPIRE_TAKER',
                'EXPIRE_MAKER',
                'EXPIRE_BOTH',
                'NONE',
            ],
        ],
        'recv_window' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'The value cannot be greater than 60000',
        ],
        'timestamp' => [
            'type' => 'integer',
            'required' => false,
            'description' => 'UTC timestamp in ms',
        ],
    ];
    protected const METHOD = 'POST';
    protected const PATH = '/api/v3/order/cancelReplace';
    protected const PATH_PARAMS = [];
    protected const QUERY_PARAMS = [
        'symbol' => 'symbol',
        'side' => 'side',
        'type' => 'type',
        'cancelReplaceMode' => 'cancel_replace_mode',
        'cancelRestrictions' => 'cancel_restrictions',
        'timeInForce' => 'time_in_force',
        'quantity' => 'quantity',
        'quoteOrderQty' => 'quote_order_qty',
        'price' => 'price',
        'cancelNewClientOrderId' => 'cancel_new_client_order_id',
        'cancelOrigClientOrderId' => 'cancel_orig_client_order_id',
        'cancelOrderId' => 'cancel_order_id',
        'newClientOrderId' => 'new_client_order_id',
        'strategyId' => 'strategy_id',
        'strategyType' => 'strategy_type',
        'stopPrice' => 'stop_price',
        'trailingDelta' => 'trailing_delta',
        'icebergQty' => 'iceberg_qty',
        'newOrderRespType' => 'new_order_resp_type',
        'selfTradePreventionMode' => 'self_trade_prevention_mode',
        'recvWindow' => 'recv_window',
        'timestamp' => 'timestamp',
    ];
    protected const HEADER_PARAMS = [];
    protected const AUTH_MODE = 'signed';
}
