<?php

namespace OpenCompany\Integrations\Temporal\Tools;

/**
 * Start nexus operation execution.
 *
 * Maps to the official Temporal endpoint post /api/v1/namespaces/{namespace}/nexus-operations/{operationId}.
 */
class TemporalStartNexusOperationExecution extends AbstractTemporalTool
{
    protected const NAME = 'temporal_start_nexus_operation_execution';
    protected const DESCRIPTION = 'Start nexus operation execution

Official Temporal endpoint: POST /api/v1/namespaces/{namespace}/nexus-operations/{operationId}

StartNexusOperationExecution starts a new Nexus operation.

 Returns a `NexusOperationExecutionAlreadyStarted` error if an instance already exists with same operation ID in this
 namespace unless permitted by the specified ID conflict policy.';
    protected const PARAMETERS = array (
  'namespace' => array (
  'type' => 'string',
  'description' => 'namespace parameter.',
  'required' => true,
),
  'operation_id' => array (
  'type' => 'string',
  'description' => 'Identifier for this operation. This is a caller-side ID, distinct from any internal
 operation identifiers generated by the handler. Must be unique among operations in the
 same namespace, subject to the rules imposed by id_reuse_policy and id_conflict_policy.',
  'required' => true,
),
  'body' => array (
  'type' => 'object',
  'description' => 'JSON request body matching the Temporal API schema.',
  'required' => true,
),
);
    protected const METHOD = 'post';
    protected const PATH = '/api/v1/namespaces/{namespace}/nexus-operations/{operationId}';
    protected const PATH_PARAMS = array (
  'namespace' => 'namespace',
  'operationId' => 'operation_id',
);
    protected const QUERY_PARAMS = array (
);
    protected const HEADER_PARAMS = array (
);
    protected const BODY_REQUIRED = true;
}
