<?php

namespace OpenCompany\Integrations\Checkly;

use Illuminate\Support\Facades\Http;
use OpenCompany\IntegrationCore\Contracts\ConfigurableIntegration;
use OpenCompany\IntegrationCore\Contracts\CredentialResolver;
use OpenCompany\IntegrationCore\Contracts\HasIntegrationCapabilities;
use OpenCompany\IntegrationCore\Contracts\Tool;
use OpenCompany\IntegrationCore\Contracts\ToolProvider;

/**
 * Tool catalog and configuration metadata for Checkly.
 *
 * Exposes the official Checkly OpenAPI operation set as endpoint-specific agent
 * tools and resolves account-specific API keys and account IDs.
 */
class ChecklyToolProvider implements ToolProvider, ConfigurableIntegration, HasIntegrationCapabilities
{
    /** @return array<string, mixed> */ public function integrationCapabilities(): array { return ['auth'=>['strategy'=>'bearer_token_with_account_header','legacy_auth_type'=>'api_key','credential_mode'=>'secret','setup_flows'=>['manual_secret'],'requires_browser_for_setup'=>false,'refreshable'=>false,'token_keys'=>[],'notes'=>['Runtime calls send Authorization: Bearer <api_key> and X-Checkly-Account: <account_id>.']],'host_availability'=>['web'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret'],'cli'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret','runtime_mode'=>'normal']],'runtime_requirements'=>[],'compatibility'=>['web_setup_supported'=>true,'web_runtime_supported'=>true,'cli_setup_supported'=>true,'cli_runtime_supported'=>true]]; }
    public function appName(): string { return 'checkly'; } public function appMeta(): array { return ['label'=>'Checkly','description'=>'Checks, monitors, alert channels, dashboards, environments, snippets, groups, private locations, status pages, and analytics','icon'=>'ph:heartbeat','logo'=>'ph:heartbeat']; }
    public function integrationMeta(): array { return ['name'=>'Checkly','description'=>'Manage Checkly API/browser/multistep checks, monitors, alerting, dashboards, groups, environments, private locations, status pages, maintenance windows, incidents, and analytics.','icon'=>'ph:heartbeat','logo'=>'ph:heartbeat','category'=>'analytics','badge'=>'verified','docs_url'=>'https://www.checklyhq.com/docs/api/']; }
    public function configSchema(): array { return [['key'=>'api_key','type'=>'secret','label'=>'API Key','required'=>true],['key'=>'account_id','type'=>'string','label'=>'Account ID','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','required'=>false,'default'=>'https://api.checklyhq.com']]; }
    /** @param  array<string, mixed>  $config  Credential and endpoint settings. @return array{success: bool, message?: string, error?: string} */ public function testConnection(array $config): array { $key=(string)($config['api_key']??''); $accountId=(string)($config['account_id']??''); $baseUrl=rtrim((string)($config['url']??'https://api.checklyhq.com'),'/'); if($key===''||$accountId==='') return ['success'=>false,'error'=>'Checkly API key and account ID are required.']; try{ $response=Http::withHeaders(['Authorization'=>'Bearer '.$key,'X-Checkly-Account'=>$accountId,'Accept'=>'application/json'])->timeout(10)->get($baseUrl.'/v1/accounts/me'); if(!$response->successful()) return ['success'=>false,'error'=>'Checkly API returned HTTP '.$response->status().'.']; return ['success'=>true,'message'=>'Connected to Checkly at '.$baseUrl.'.']; }catch(\Throwable $e){ return ['success'=>false,'error'=>$e->getMessage()]; } }
    public function validationRules(): array { return ['api_key'=>'required|string','account_id'=>'required|string','url'=>'nullable|url']; } public function credentialFields(): array { return [['key'=>'api_key','type'=>'secret','label'=>'API Key','required'=>true],['key'=>'account_id','type'=>'string','label'=>'Account ID','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','required'=>false,'default'=>'https://api.checklyhq.com']]; }
    public function tools(): array { return [
  'checkly_get_v1_accounts' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Accounts',
  'type' => 'read',
  'name' => 'Get V1 Accounts',
  'description' => 'List account details based on supplied API key.  Official Checkly endpoint: GET /v1/accounts.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_accounts_me' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AccountsMe',
  'type' => 'read',
  'name' => 'Get V1 Accounts Me',
  'description' => 'Get details from the current account.  Official Checkly endpoint: GET /v1/accounts/me.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_accounts_me_entitlements' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AccountsMeEntitlements',
  'type' => 'read',
  'name' => 'Get V1 Accounts Me Entitlements',
  'description' => 'Fetch the entitlements for the account, including feature access and limits based on the current plan.  Official Checkly endpoint: GET /v1/accounts/me/entitlements.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_accounts_accountid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AccountsAccountid',
  'type' => 'read',
  'name' => 'Get V1 Accounts Accountid',
  'description' => 'Get details from a specific account.  Official Checkly endpoint: GET /v1/accounts/{accountId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_accounts_accountid_entitlements' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AccountsAccountidEntitlements',
  'type' => 'read',
  'name' => 'Get V1 Accounts Accountid Entitlements',
  'description' => 'Fetch the entitlements for the account, including feature access and limits based on the current plan.  Official Checkly endpoint: GET /v1/accounts/{accountId}/entitlements.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_alertchannels' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Alertchannels',
  'type' => 'read',
  'name' => 'Get V1 Alertchannels',
  'description' => 'Lists all configured alert channels and their subscribed checks.  Official Checkly endpoint: GET /v1/alert-channels.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_alertchannels' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1Alertchannels',
  'type' => 'write',
  'name' => 'Post V1 Alertchannels',
  'description' => 'Creates a new alert channel  Official Checkly endpoint: POST /v1/alert-channels.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_alertchannels_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1AlertchannelsId',
  'type' => 'write',
  'name' => 'Delete V1 Alertchannels Id',
  'description' => 'Permanently removes an alert channel  Official Checkly endpoint: DELETE /v1/alert-channels/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_alertchannels_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AlertchannelsId',
  'type' => 'read',
  'name' => 'Get V1 Alertchannels Id',
  'description' => 'Show details of a specific alert channel.  Official Checkly endpoint: GET /v1/alert-channels/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_alertchannels_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1AlertchannelsId',
  'type' => 'write',
  'name' => 'Put V1 Alertchannels Id',
  'description' => 'Update an alert channel  Official Checkly endpoint: PUT /v1/alert-channels/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_put_v1_alertchannels_id_subscriptions' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1AlertchannelsIdSubscriptions',
  'type' => 'write',
  'name' => 'Put V1 Alertchannels Id Subscriptions',
  'description' => 'Update the subscriptions of an alert channel. Use this to add a check to an alert channel so failure and recovery alerts are send out for that check. Note: when passing the subscription object, you can only specify a "checkId" or a "groupId, not both.  Officia',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_alertnotifications' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Alertnotifications',
  'type' => 'read',
  'name' => 'Get V1 Alertnotifications',
  'description' => 'Lists the alert notifications that have been sent for your account. You can filter by alert channel ID or limit to only failing notifications. Use the `to` and `from` parameters to specify a date range (UNIX timestamp in seconds). This endpoint will return dat',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_analytics_apichecks_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AnalyticsApichecksId',
  'type' => 'read',
  'name' => 'Get V1 Analytics Apichecks Id',
  'description' => 'Fetch detailed availability metrics and aggregated or non-aggregated API Check metrics across custom time ranges. For example, you can get the p99 and p95 of all the DNS phases of your API check together with the availability percentage for any time range. Rat',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_analytics_browserchecks_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AnalyticsBrowserchecksId',
  'type' => 'read',
  'name' => 'Get V1 Analytics Browserchecks Id',
  'description' => 'Fetch detailed availability metrics and aggregated or non-aggregated Browser Check metrics across custom time ranges. For example, you can get the average amount of console errors, the p99 of your FCP and the standard deviation of your TTFB for the second page',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_analytics_checks' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1AnalyticsChecks',
  'type' => 'write',
  'name' => 'Post V1 Analytics Checks',
  'description' => 'Returns availability, response times, and latency metrics for the given checks. Response shape is polymorphic per check type: fields are present only when the metric applies to that type. A null value means no data in the requested time range; an absent field ',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_analytics_dns_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AnalyticsDnsId',
  'type' => 'read',
  'name' => 'Get V1 Analytics Dns Id',
  'description' => 'Fetch detailed availability metrics and aggregated or non-aggregated DNS Monitor metrics across custom time ranges. For example, you can get the p99 and p95 of the total DNS query time together with the availability percentage for any time range. Rate-limiting',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_analytics_heartbeatchecks_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AnalyticsHeartbeatchecksId',
  'type' => 'read',
  'name' => 'Get V1 Analytics Heartbeatchecks Id',
  'description' => 'Fetch detailed availability metrics and aggregated or non-aggregated Heartbeat Check metrics across custom time ranges. Rate-limiting is applied to this endpoint, you can send 600 requests / 60 seconds at most.  Official Checkly endpoint: GET /v1/analytics/hea',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_analytics_icmp_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AnalyticsIcmpId',
  'type' => 'read',
  'name' => 'Get V1 Analytics Icmp Id',
  'description' => 'Fetch detailed availability metrics and aggregated or non-aggregated ICMP Monitor metrics across custom time ranges. For example, you can get the p99 and p95 of latency metrics together with the packet loss percentage for any time range. Rate-limiting is appli',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_analytics_metrics' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AnalyticsMetrics',
  'type' => 'read',
  'name' => 'Get V1 Analytics Metrics',
  'description' => 'List all available reporting metrics.  Official Checkly endpoint: GET /v1/analytics/metrics.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_analytics_multistepchecks_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AnalyticsMultistepchecksId',
  'type' => 'read',
  'name' => 'Get V1 Analytics Multistepchecks Id',
  'description' => 'Fetch detailed availability metrics and aggregated or non-aggregated Multistep Check metrics across custom time ranges. Rate-limiting is applied to this endpoint, you can send 30 requests / 60 seconds at most.  Official Checkly endpoint: GET /v1/analytics/mult',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_analytics_playwrightchecks_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AnalyticsPlaywrightchecksId',
  'type' => 'read',
  'name' => 'Get V1 Analytics Playwrightchecks Id',
  'description' => 'Fetch detailed availability metrics and aggregated or non-aggregated Playwright Check metrics across custom time ranges. Rate-limiting is applied to this endpoint, you can send 30 requests / 60 seconds at most.  Official Checkly endpoint: GET /v1/analytics/pla',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_analytics_tcpchecks_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AnalyticsTcpchecksId',
  'type' => 'read',
  'name' => 'Get V1 Analytics Tcpchecks Id',
  'description' => 'Fetch detailed availability metrics and aggregated or non-aggregated TCP Check metrics across custom time ranges. For example, you can get the p99 and p95 of all the check phases of your TCP check together with the availability percentage for any time range. R',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_analytics_urlmonitors_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1AnalyticsUrlmonitorsId',
  'type' => 'read',
  'name' => 'Get V1 Analytics Urlmonitors Id',
  'description' => 'Fetch detailed availability metrics and aggregated or non-aggregated API Check metrics across custom time ranges. For example, you can get the p99 and p95 of all the DNS phases of your API check together with the availability percentage for any time range. Rat',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_badges_checks_checkid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1BadgesChecksCheckid',
  'type' => 'read',
  'name' => 'Get V1 Badges Checks Checkid',
  'description' => 'Get check status badge. You can enable the badges feature in account settings  Official Checkly endpoint: GET /v1/badges/checks/{checkId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_badges_groups_groupid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1BadgesGroupsGroupid',
  'type' => 'read',
  'name' => 'Get V1 Badges Groups Groupid',
  'description' => 'Get group status badge. You can enable the badges feature in account settings  Official Checkly endpoint: GET /v1/badges/groups/{groupId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_cancel' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyCancel',
  'type' => 'write',
  'name' => 'Cancel',
  'description' => 'Cancel a check run, check session, test run, or test session  Official Checkly endpoint: POST /v1/cancel.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_checkalerts' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Checkalerts',
  'type' => 'read',
  'name' => 'Get V1 Checkalerts',
  'description' => 'Lists all alerts that have been sent for your account. Use the `to` and `from` parameters to specify a date range (UNIX timestamp in seconds). This endpoint will return data within a 6-hour timeframe. If the `from` and `to` params are set, they must be at most',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_checkalerts_checkid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1CheckalertsCheckid',
  'type' => 'read',
  'name' => 'Get V1 Checkalerts Checkid',
  'description' => 'Lists all the alerts for a specific check. Use the `to` and `from` parameters to specify a date range (UNIX timestamp in seconds). This endpoint will return data within a 6-hour timeframe. If the `from` and `to` params are set, they must be at most 6 hours apa',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_checkgroups' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Checkgroups',
  'type' => 'read',
  'name' => 'Get V1 Checkgroups',
  'description' => 'Lists all current check groups in your account. The "checks" property is an array of check UUID\'s for convenient referencing. It is read only and you cannot use it to add checks to a group.  Official Checkly endpoint: GET /v1/check-groups.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_checkgroups' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1Checkgroups',
  'type' => 'write',
  'name' => 'Post V1 Checkgroups',
  'description' => 'Creates a new check group. You can add checks to the group by setting the "groupId" property of individual checks.  Official Checkly endpoint: POST /v1/check-groups.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_checkgroups_groupid_checks_checkid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1CheckgroupsGroupidChecksCheckid',
  'type' => 'read',
  'name' => 'Get V1 Checkgroups Groupid Checks Checkid',
  'description' => 'Show details of one check in a specific check group with the group settings applied.  Official Checkly endpoint: GET /v1/check-groups/{groupId}/checks/{checkId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_delete_v1_checkgroups_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1CheckgroupsId',
  'type' => 'write',
  'name' => 'Delete V1 Checkgroups Id',
  'description' => 'Permanently removes a check group. You cannot delete a check group if it still contains checks.  Official Checkly endpoint: DELETE /v1/check-groups/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_checkgroups_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1CheckgroupsId',
  'type' => 'read',
  'name' => 'Get V1 Checkgroups Id',
  'description' => 'Show details of a specific check group  Official Checkly endpoint: GET /v1/check-groups/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_checkgroups_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1CheckgroupsId',
  'type' => 'write',
  'name' => 'Put V1 Checkgroups Id',
  'description' => 'Updates a check group.  Official Checkly endpoint: PUT /v1/check-groups/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_checkgroups_id_checks' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1CheckgroupsIdChecks',
  'type' => 'read',
  'name' => 'Get V1 Checkgroups Id Checks',
  'description' => 'Lists all checks in a specific check group with the group settings applied.  Official Checkly endpoint: GET /v1/check-groups/{id}/checks.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_checkresults_checkid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1CheckresultsCheckid',
  'type' => 'read',
  'name' => 'Get V1 Checkresults Checkid',
  'description' => '[DEPRECATED] This endpoint will be removed soon. Please use the GET /v2/check-results/{checkId} endpoint instead. Lists the full, raw check results for a specific check. We keep raw results for 30 days. After 30 days they are erased. However, we keep the rolle',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_checkresults_checkid_checkresultid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1CheckresultsCheckidCheckresultid',
  'type' => 'read',
  'name' => 'Get V1 Checkresults Checkid Checkresultid',
  'description' => 'Show details of a specific check result.  Official Checkly endpoint: GET /v1/check-results/{checkId}/{checkResultId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_checksessions_trigger' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1ChecksessionsTrigger',
  'type' => 'write',
  'name' => 'Post V1 Checksessions Trigger',
  'description' => 'Starts a check session for each check that matches the provided target filters. If no filters are given, matches all eligible checks. This endpoint does not wait for the check session to complete. Use the `GET /v1/check-sessions/{checkSessionId}/completion` or',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_checksessions_checksessionid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1ChecksessionsChecksessionid',
  'type' => 'read',
  'name' => 'Get V1 Checksessions Checksessionid',
  'description' => 'Retrieves a check session. Results may be incomplete if the check session is still in progress. Once a check session has finished, results will include at least one check result for each run location: one result with `resultType` equal to `"FINAL"`, and zero o',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_checksessions_checksessionid_completion' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1ChecksessionsChecksessionidCompletion',
  'type' => 'read',
  'name' => 'Get V1 Checksessions Checksessionid Completion',
  'description' => 'Call this endpoint to await the completion of a check session. A successful response will be returned once the check session reaches its final state (i.e. when it passes or fails). If the check session takes a long time to complete, the endpoint will return a ',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_checkstatuses' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Checkstatuses',
  'type' => 'read',
  'name' => 'Get V1 Checkstatuses',
  'description' => 'Shows the current status information for all checks in your account. The check status records are continuously updated as new check results come in.  Official Checkly endpoint: GET /v1/check-statuses.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_checkstatuses_checkid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1CheckstatusesCheckid',
  'type' => 'read',
  'name' => 'Get V1 Checkstatuses Checkid',
  'description' => 'Show the current status information for a specific check.  Official Checkly endpoint: GET /v1/check-statuses/{checkId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_checks' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Checks',
  'type' => 'read',
  'name' => 'Get V1 Checks',
  'description' => 'Lists all current checks in your account.  Official Checkly endpoint: GET /v1/checks.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_checks' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1Checks',
  'type' => 'write',
  'name' => 'Post V1 Checks',
  'description' => '[DEPRECATED] This endpoint will be removed soon. Instead use POST /checks/api or POST /checks/browser. Creates a new API or browser check. Will return a `402` when you are over the limit of your plan. When using the `globalAlertSettings`, the `alertSettings` c',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_checks_api' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1ChecksApi',
  'type' => 'write',
  'name' => 'Post V1 Checks Api',
  'description' => 'Creates a new API check. Will return a `402` when you are over the limit of your plan. When using the `globalAlertSetting`, the `alertSetting` can be `null`  Official Checkly endpoint: POST /v1/checks/api.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_put_v1_checks_api_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1ChecksApiId',
  'type' => 'write',
  'name' => 'Put V1 Checks Api Id',
  'description' => 'Updates an API check.  Official Checkly endpoint: PUT /v1/checks/api/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_checks_browser' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1ChecksBrowser',
  'type' => 'write',
  'name' => 'Post V1 Checks Browser',
  'description' => 'Creates a new browser check. Will return a `402` when you are over the limit of your plan. When using the `globalAlertSetting`, the `alertSetting` can be `null`  Official Checkly endpoint: POST /v1/checks/browser.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_put_v1_checks_browser_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1ChecksBrowserId',
  'type' => 'write',
  'name' => 'Put V1 Checks Browser Id',
  'description' => 'Updates a browser check.  Official Checkly endpoint: PUT /v1/checks/browser/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_checks_dns' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1ChecksDns',
  'type' => 'write',
  'name' => 'Post V1 Checks Dns',
  'description' => 'Creates a new DNS monitor. Will return a `402` when you are over the limit of your plan. When using the `globalAlertSetting`, the `alertSetting` can be `null`  Official Checkly endpoint: POST /v1/checks/dns.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_put_v1_checks_dns_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1ChecksDnsId',
  'type' => 'write',
  'name' => 'Put V1 Checks Dns Id',
  'description' => 'Updates an DNS monitor.  Official Checkly endpoint: PUT /v1/checks/dns/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_checks_heartbeat' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1ChecksHeartbeat',
  'type' => 'write',
  'name' => 'Post V1 Checks Heartbeat',
  'description' => 'Creates a new Heartbeat check. Will return a `402` when you are over the limit of your plan. When using the `globalAlertSetting`, the `alertSetting` can be `null`  Official Checkly endpoint: POST /v1/checks/heartbeat.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_put_v1_checks_heartbeat_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1ChecksHeartbeatId',
  'type' => 'write',
  'name' => 'Put V1 Checks Heartbeat Id',
  'description' => 'Updates a Heartbeat check.  Official Checkly endpoint: PUT /v1/checks/heartbeat/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_checks_heartbeats_checkid_availability' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1ChecksHeartbeatsCheckidAvailability',
  'type' => 'read',
  'name' => 'Get V1 Checks Heartbeats Checkid Availability',
  'description' => 'Get heartbeat availability.  Official Checkly endpoint: GET /v1/checks/heartbeats/{checkId}/availability.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_checks_heartbeats_checkid_events' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1ChecksHeartbeatsCheckidEvents',
  'type' => 'read',
  'name' => 'Get V1 Checks Heartbeats Checkid Events',
  'description' => 'Get all events from a heartbeat.  Official Checkly endpoint: GET /v1/checks/heartbeats/{checkId}/events.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_checks_heartbeats_checkid_events_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1ChecksHeartbeatsCheckidEventsId',
  'type' => 'read',
  'name' => 'Get V1 Checks Heartbeats Checkid Events Id',
  'description' => 'Get a specific event by its id.  Official Checkly endpoint: GET /v1/checks/heartbeats/{checkId}/events/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_checks_icmp' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1ChecksIcmp',
  'type' => 'write',
  'name' => 'Post V1 Checks Icmp',
  'description' => 'Creates a new ICMP monitor. Will return a `402` when you are over the limit of your plan. When using the `globalAlertSetting`, the `alertSetting` can be `null`  Official Checkly endpoint: POST /v1/checks/icmp.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_put_v1_checks_icmp_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1ChecksIcmpId',
  'type' => 'write',
  'name' => 'Put V1 Checks Icmp Id',
  'description' => 'Updates an ICMP monitor.  Official Checkly endpoint: PUT /v1/checks/icmp/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_checks_multistep' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1ChecksMultistep',
  'type' => 'write',
  'name' => 'Post V1 Checks Multistep',
  'description' => 'Creates a new Multi-Step check. Will return a `402` when you are over the limit of your plan. When using the `globalAlertSetting`, the `alertSetting` can be `null`  Official Checkly endpoint: POST /v1/checks/multistep.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_put_v1_checks_multistep_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1ChecksMultistepId',
  'type' => 'write',
  'name' => 'Put V1 Checks Multistep Id',
  'description' => 'Updates a Multi-Step check.  Official Checkly endpoint: PUT /v1/checks/multistep/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_checks_tcp' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1ChecksTcp',
  'type' => 'write',
  'name' => 'Post V1 Checks Tcp',
  'description' => 'Creates a new TCP check. Will return a `402` when you are over the limit of your plan. When using the `globalAlertSetting`, the `alertSetting` can be `null`  Official Checkly endpoint: POST /v1/checks/tcp.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_put_v1_checks_tcp_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1ChecksTcpId',
  'type' => 'write',
  'name' => 'Put V1 Checks Tcp Id',
  'description' => 'Updates an TCP check.  Official Checkly endpoint: PUT /v1/checks/tcp/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_checks_url' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1ChecksUrl',
  'type' => 'write',
  'name' => 'Post V1 Checks Url',
  'description' => 'Creates a new URL monitor. Will return a `402` when you are over the limit of your plan. When using the `globalAlertSetting`, the `alertSetting` can be `null`  Official Checkly endpoint: POST /v1/checks/url.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_put_v1_checks_url_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1ChecksUrlId',
  'type' => 'write',
  'name' => 'Put V1 Checks Url Id',
  'description' => 'Updates an URL monitor.  Official Checkly endpoint: PUT /v1/checks/url/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_checks_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1ChecksId',
  'type' => 'write',
  'name' => 'Delete V1 Checks Id',
  'description' => 'Permanently removes a API or browser check and all its related status and results data.  Official Checkly endpoint: DELETE /v1/checks/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_checks_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1ChecksId',
  'type' => 'read',
  'name' => 'Get V1 Checks Id',
  'description' => 'Show details of a specific API or browser check  Official Checkly endpoint: GET /v1/checks/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_checks_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1ChecksId',
  'type' => 'write',
  'name' => 'Put V1 Checks Id',
  'description' => '[DEPRECATED] This endpoint will be removed soon. Instead use PUT /checks/api/{id} or PUT /checks/browser/{id}. Updates a new API or browser check.  Official Checkly endpoint: PUT /v1/checks/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_clientcertificates' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Clientcertificates',
  'type' => 'read',
  'name' => 'Get V1 Clientcertificates',
  'description' => 'Lists all client certificates.  Official Checkly endpoint: GET /v1/client-certificates.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_clientcertificates' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1Clientcertificates',
  'type' => 'write',
  'name' => 'Post V1 Clientcertificates',
  'description' => 'Creates a new client certificate.  Official Checkly endpoint: POST /v1/client-certificates.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_clientcertificates_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1ClientcertificatesId',
  'type' => 'write',
  'name' => 'Delete V1 Clientcertificates Id',
  'description' => 'Permanently removes a client certificate.  Official Checkly endpoint: DELETE /v1/client-certificates/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_clientcertificates_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1ClientcertificatesId',
  'type' => 'read',
  'name' => 'Get V1 Clientcertificates Id',
  'description' => 'Shows one client certificate.  Official Checkly endpoint: GET /v1/client-certificates/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_dashboards' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Dashboards',
  'type' => 'read',
  'name' => 'Get V1 Dashboards',
  'description' => 'Lists all current dashboards in your account.  Official Checkly endpoint: GET /v1/dashboards.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_dashboards' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1Dashboards',
  'type' => 'write',
  'name' => 'Post V1 Dashboards',
  'description' => 'Creates a new dashboard. Will return a 409 when attempting to create a dashboard with a custom URL or custom domain that is already taken.  Official Checkly endpoint: POST /v1/dashboards.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_dashboards_dashboardid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1DashboardsDashboardid',
  'type' => 'write',
  'name' => 'Delete V1 Dashboards Dashboardid',
  'description' => 'Permanently removes a dashboard.  Official Checkly endpoint: DELETE /v1/dashboards/{dashboardId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_dashboards_dashboardid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1DashboardsDashboardid',
  'type' => 'read',
  'name' => 'Get V1 Dashboards Dashboardid',
  'description' => 'Show details of a specific dashboard. Rate-limiting is applied to this endpoint, you can send 10 requests / 20 seconds at most.  Official Checkly endpoint: GET /v1/dashboards/{dashboardId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_dashboards_dashboardid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1DashboardsDashboardid',
  'type' => 'write',
  'name' => 'Put V1 Dashboards Dashboardid',
  'description' => 'Updates a dashboard. Will return a 409 when attempting to create a dashboard with a custom URL or custom domain that is already taken.  Official Checkly endpoint: PUT /v1/dashboards/{dashboardId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_errorgroups' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Errorgroups',
  'type' => 'read',
  'name' => 'Get V1 Errorgroups',
  'description' => 'List all error groups in your account.  Official Checkly endpoint: GET /v1/error-groups.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_errorgroups_checks_checkid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1ErrorgroupsChecksCheckid',
  'type' => 'read',
  'name' => 'Get V1 Errorgroups Checks Checkid',
  'description' => 'List all error groups for a specific check.  Official Checkly endpoint: GET /v1/error-groups/checks/{checkId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_errorgroups_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1ErrorgroupsId',
  'type' => 'read',
  'name' => 'Get V1 Errorgroups Id',
  'description' => 'Retrieve one error group.  Official Checkly endpoint: GET /v1/error-groups/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_patch_v1_errorgroups_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPatchV1ErrorgroupsId',
  'type' => 'write',
  'name' => 'Patch V1 Errorgroups Id',
  'description' => 'Update an error group. Mainly used for archiving error groups.  Official Checkly endpoint: PATCH /v1/error-groups/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_incidents' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1Incidents',
  'type' => 'write',
  'name' => 'Post V1 Incidents',
  'description' => 'Creates a new incident.  Official Checkly endpoint: POST /v1/incidents.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_incidents_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1IncidentsId',
  'type' => 'write',
  'name' => 'Delete V1 Incidents Id',
  'description' => 'Permanently removes an incident and all its updates.  Official Checkly endpoint: DELETE /v1/incidents/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_incidents_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1IncidentsId',
  'type' => 'read',
  'name' => 'Get V1 Incidents Id',
  'description' => 'Shows details of a specific incident. Uses the "includeAllIncidentUpdates" query parameter to obtain all updates.  Official Checkly endpoint: GET /v1/incidents/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_incidents_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1IncidentsId',
  'type' => 'write',
  'name' => 'Put V1 Incidents Id',
  'description' => 'Updates an incident.  Official Checkly endpoint: PUT /v1/incidents/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_incidents_incidentid_updates' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1IncidentsIncidentidUpdates',
  'type' => 'write',
  'name' => 'Post V1 Incidents Incidentid Updates',
  'description' => 'Creates a new update for an incident.  Official Checkly endpoint: POST /v1/incidents/{incidentId}/updates.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_incidents_incidentid_updates_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1IncidentsIncidentidUpdatesId',
  'type' => 'write',
  'name' => 'Delete V1 Incidents Incidentid Updates Id',
  'description' => 'Permanently removes an incident update.  Official Checkly endpoint: DELETE /v1/incidents/{incidentId}/updates/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_put_v1_incidents_incidentid_updates_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1IncidentsIncidentidUpdatesId',
  'type' => 'write',
  'name' => 'Put V1 Incidents Incidentid Updates Id',
  'description' => 'Modifies an incident update.  Official Checkly endpoint: PUT /v1/incidents/{incidentId}/updates/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_locations' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Locations',
  'type' => 'read',
  'name' => 'Get V1 Locations',
  'description' => 'Lists all supported locationss.  Official Checkly endpoint: GET /v1/locations.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_maintenancewindows' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Maintenancewindows',
  'type' => 'read',
  'name' => 'Get V1 Maintenancewindows',
  'description' => 'Lists all maintenance windows in your account.  Official Checkly endpoint: GET /v1/maintenance-windows.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_maintenancewindows' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1Maintenancewindows',
  'type' => 'write',
  'name' => 'Post V1 Maintenancewindows',
  'description' => 'Creates a new maintenance window.  Official Checkly endpoint: POST /v1/maintenance-windows.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_maintenancewindows_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1MaintenancewindowsId',
  'type' => 'write',
  'name' => 'Delete V1 Maintenancewindows Id',
  'description' => 'Permanently removes a maintenance window.  Official Checkly endpoint: DELETE /v1/maintenance-windows/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_maintenancewindows_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1MaintenancewindowsId',
  'type' => 'read',
  'name' => 'Get V1 Maintenancewindows Id',
  'description' => 'Show details of a specific maintenance window.  Official Checkly endpoint: GET /v1/maintenance-windows/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_maintenancewindows_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1MaintenancewindowsId',
  'type' => 'write',
  'name' => 'Put V1 Maintenancewindows Id',
  'description' => 'Updates a maintenance window.  Official Checkly endpoint: PUT /v1/maintenance-windows/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_privatelocations' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Privatelocations',
  'type' => 'read',
  'name' => 'Get V1 Privatelocations',
  'description' => 'Lists all private locations in your account.  Official Checkly endpoint: GET /v1/private-locations.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_privatelocations' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1Privatelocations',
  'type' => 'write',
  'name' => 'Post V1 Privatelocations',
  'description' => 'Creates a new private location.  Official Checkly endpoint: POST /v1/private-locations.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_privatelocations_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1PrivatelocationsId',
  'type' => 'write',
  'name' => 'Delete V1 Privatelocations Id',
  'description' => 'Permanently removes a private location.  Official Checkly endpoint: DELETE /v1/private-locations/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_privatelocations_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1PrivatelocationsId',
  'type' => 'read',
  'name' => 'Get V1 Privatelocations Id',
  'description' => 'Show details of a specific private location.  Official Checkly endpoint: GET /v1/private-locations/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_privatelocations_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1PrivatelocationsId',
  'type' => 'write',
  'name' => 'Put V1 Privatelocations Id',
  'description' => 'Updates a private location.  Official Checkly endpoint: PUT /v1/private-locations/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_privatelocations_id_keys' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1PrivatelocationsIdKeys',
  'type' => 'write',
  'name' => 'Post V1 Privatelocations Id Keys',
  'description' => 'Creates an api key on the private location.  Official Checkly endpoint: POST /v1/private-locations/{id}/keys.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_privatelocations_id_keys_keyid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1PrivatelocationsIdKeysKeyid',
  'type' => 'write',
  'name' => 'Delete V1 Privatelocations Id Keys Keyid',
  'description' => 'Permanently removes an api key from a private location.  Official Checkly endpoint: DELETE /v1/private-locations/{id}/keys/{keyId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_privatelocations_id_metrics' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1PrivatelocationsIdMetrics',
  'type' => 'read',
  'name' => 'Get V1 Privatelocations Id Metrics',
  'description' => 'Get private location health metrics from a window of time. Rate-limiting is applied to this endpoint, you can send 300 requests per day at most.  Official Checkly endpoint: GET /v1/private-locations/{id}/metrics.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_reporting' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Reporting',
  'type' => 'read',
  'name' => 'Get V1 Reporting',
  'description' => 'Generates a report with aggregated statistics for all checks or a filtered set of checks over a specified time window.  Official Checkly endpoint: GET /v1/reporting.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_rootcauseanalyses_errorgroups_errorgroupid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1RootcauseanalysesErrorgroupsErrorgroupid',
  'type' => 'write',
  'name' => 'Post V1 Rootcauseanalyses Errorgroups Errorgroupid',
  'description' => 'Asynchronously generates a root cause analysis for a specific check error group. Returns an `id` which you can use to poll the `/root-cause-analyses/{id}` endpoint.  Official Checkly endpoint: POST /v1/root-cause-analyses/error-groups/{errorGroupId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_rootcauseanalyses_testsessionerrorgroups_testsessionerrorgroupid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1RootcauseanalysesTestsessionerrorgroupsTestsessionerrorgroupid',
  'type' => 'write',
  'name' => 'Post V1 Rootcauseanalyses Testsessionerrorgroups Testsessionerrorgroupid',
  'description' => 'Asynchronously generates a root cause analysis for a specific test session error group. Returns an `id` which you can use to poll the `/root-cause-analyses/{id}` endpoint.  Official Checkly endpoint: POST /v1/root-cause-analyses/test-session-error-groups/{test',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_rootcauseanalyses_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1RootcauseanalysesId',
  'type' => 'read',
  'name' => 'Get V1 Rootcauseanalyses Id',
  'description' => 'Retrieves a specific root cause analysis. Use the `id` returned from either POST endpoint and poll until the response is HTTP 200. While the analysis is being generated the endpoint returns HTTP 202 with `{"id":"","status":"PENDING"}`. A genuine HTTP 404 means',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_runtimes' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Runtimes',
  'type' => 'read',
  'name' => 'Get V1 Runtimes',
  'description' => 'Lists all supported runtimes and the included NPM packages for Browser checks and setup & teardown scripts for API checks.  Official Checkly endpoint: GET /v1/runtimes.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_runtimes_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1RuntimesId',
  'type' => 'read',
  'name' => 'Get V1 Runtimes Id',
  'description' => 'Shows the details of all included NPM packages and their version for one specific runtime  Official Checkly endpoint: GET /v1/runtimes/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_snippets' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Snippets',
  'type' => 'read',
  'name' => 'Get V1 Snippets',
  'description' => 'Lists all current snippets in your account.  Official Checkly endpoint: GET /v1/snippets.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_snippets' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1Snippets',
  'type' => 'write',
  'name' => 'Post V1 Snippets',
  'description' => 'Creates a new snippet.  Official Checkly endpoint: POST /v1/snippets.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_snippets_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1SnippetsId',
  'type' => 'write',
  'name' => 'Delete V1 Snippets Id',
  'description' => 'Permanently removes a snippet.  Official Checkly endpoint: DELETE /v1/snippets/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_snippets_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1SnippetsId',
  'type' => 'read',
  'name' => 'Get V1 Snippets Id',
  'description' => 'Show details of a specific snippet.  Official Checkly endpoint: GET /v1/snippets/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_snippets_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1SnippetsId',
  'type' => 'write',
  'name' => 'Put V1 Snippets Id',
  'description' => 'Updates a snippet.  Official Checkly endpoint: PUT /v1/snippets/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_staticips' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Staticips',
  'type' => 'read',
  'name' => 'Get V1 Staticips',
  'description' => 'Lists all source IPs for check runs as a single JSON array.  Official Checkly endpoint: GET /v1/static-ips.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_staticipsbyregion' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Staticipsbyregion',
  'type' => 'read',
  'name' => 'Get V1 Staticipsbyregion',
  'description' => 'Lists all source IPs for check runs as object with regions as keys and an array of IPs as value.  Official Checkly endpoint: GET /v1/static-ips-by-region.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_staticipstxt' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Staticipstxt',
  'type' => 'read',
  'name' => 'Get V1 Staticipstxt',
  'description' => 'Lists all IPs for check runs as a TXT file. Each line has one IP.  Official Checkly endpoint: GET /v1/static-ips.txt.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_staticipv6s' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Staticipv6s',
  'type' => 'read',
  'name' => 'Get V1 Staticipv6S',
  'description' => 'Lists all source IPv6s for check runs as a single JSON array.  Official Checkly endpoint: GET /v1/static-ipv6s.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_staticipv6sbyregion' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Staticipv6sbyregion',
  'type' => 'read',
  'name' => 'Get V1 Staticipv6Sbyregion',
  'description' => 'Lists all source IPs for check runs as an object with regions as keys and an Ipv6 as value.  Official Checkly endpoint: GET /v1/static-ipv6s-by-region.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_staticipv6stxt' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Staticipv6stxt',
  'type' => 'read',
  'name' => 'Get V1 Staticipv6Stxt',
  'description' => 'Lists all IPv6s for check runs as a TXT file. Each line has one IP.  Official Checkly endpoint: GET /v1/static-ipv6s.txt.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_statuspages' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Statuspages',
  'type' => 'read',
  'name' => 'Get V1 Statuspages',
  'description' => 'Get all status pages for an account.  Official Checkly endpoint: GET /v1/status-pages.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_statuspages' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1Statuspages',
  'type' => 'write',
  'name' => 'Post V1 Statuspages',
  'description' => 'Create a new status page with its related services and cards.  Official Checkly endpoint: POST /v1/status-pages.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_statuspages_incidents' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1StatuspagesIncidents',
  'type' => 'read',
  'name' => 'Get V1 Statuspages Incidents',
  'description' => 'Get the latest 100 incidents for all services.  Official Checkly endpoint: GET /v1/status-pages/incidents.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_statuspages_incidents' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1StatuspagesIncidents',
  'type' => 'write',
  'name' => 'Post V1 Statuspages Incidents',
  'description' => 'Creates a new incident.  Official Checkly endpoint: POST /v1/status-pages/incidents.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_statuspages_incidents_incidentid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1StatuspagesIncidentsIncidentid',
  'type' => 'write',
  'name' => 'Delete V1 Statuspages Incidents Incidentid',
  'description' => 'Permanently removes an incident and all its updates.  Official Checkly endpoint: DELETE /v1/status-pages/incidents/{incidentId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_statuspages_incidents_incidentid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1StatuspagesIncidentsIncidentid',
  'type' => 'read',
  'name' => 'Get V1 Statuspages Incidents Incidentid',
  'description' => 'Get incident details including incident history and affected services.  Official Checkly endpoint: GET /v1/status-pages/incidents/{incidentId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_statuspages_incidents_incidentid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1StatuspagesIncidentsIncidentid',
  'type' => 'write',
  'name' => 'Put V1 Statuspages Incidents Incidentid',
  'description' => 'Updates an incident.  Official Checkly endpoint: PUT /v1/status-pages/incidents/{incidentId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_statuspages_incidents_incidentid_incidentupdates' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1StatuspagesIncidentsIncidentidIncidentupdates',
  'type' => 'read',
  'name' => 'Get V1 Statuspages Incidents Incidentid Incidentupdates',
  'description' => 'Lists all updates for a specific incident.  Official Checkly endpoint: GET /v1/status-pages/incidents/{incidentId}/incident-updates.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_statuspages_incidents_incidentid_incidentupdates' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1StatuspagesIncidentsIncidentidIncidentupdates',
  'type' => 'write',
  'name' => 'Post V1 Statuspages Incidents Incidentid Incidentupdates',
  'description' => 'Creates a new update for an incident.  Official Checkly endpoint: POST /v1/status-pages/incidents/{incidentId}/incident-updates.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_statuspages_incidents_incidentid_incidentupdates_incidentupdateid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1StatuspagesIncidentsIncidentidIncidentupdatesIncidentupdateid',
  'type' => 'write',
  'name' => 'Delete V1 Statuspages Incidents Incidentid Incidentupdates Incidentupdateid',
  'description' => 'Permanently removes an incident update.  Official Checkly endpoint: DELETE /v1/status-pages/incidents/{incidentId}/incident-updates/{incidentUpdateId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_statuspages_incidents_incidentid_incidentupdates_incidentupdateid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1StatuspagesIncidentsIncidentidIncidentupdatesIncidentupdateid',
  'type' => 'read',
  'name' => 'Get V1 Statuspages Incidents Incidentid Incidentupdates Incidentupdateid',
  'description' => 'Shows details of a specific incident update.  Official Checkly endpoint: GET /v1/status-pages/incidents/{incidentId}/incident-updates/{incidentUpdateId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_statuspages_incidents_incidentid_incidentupdates_incidentupdateid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1StatuspagesIncidentsIncidentidIncidentupdatesIncidentupdateid',
  'type' => 'write',
  'name' => 'Put V1 Statuspages Incidents Incidentid Incidentupdates Incidentupdateid',
  'description' => 'Modifies an incident update.  Official Checkly endpoint: PUT /v1/status-pages/incidents/{incidentId}/incident-updates/{incidentUpdateId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_statuspages_services' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1StatuspagesServices',
  'type' => 'read',
  'name' => 'Get V1 Statuspages Services',
  'description' => 'Get all services  Official Checkly endpoint: GET /v1/status-pages/services.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_statuspages_services' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1StatuspagesServices',
  'type' => 'write',
  'name' => 'Post V1 Statuspages Services',
  'description' => 'Create a service  Official Checkly endpoint: POST /v1/status-pages/services.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_statuspages_services_serviceid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1StatuspagesServicesServiceid',
  'type' => 'write',
  'name' => 'Delete V1 Statuspages Services Serviceid',
  'description' => 'Delete a service  Official Checkly endpoint: DELETE /v1/status-pages/services/{serviceId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_statuspages_services_serviceid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1StatuspagesServicesServiceid',
  'type' => 'read',
  'name' => 'Get V1 Statuspages Services Serviceid',
  'description' => 'Get a single service  Official Checkly endpoint: GET /v1/status-pages/services/{serviceId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_statuspages_services_serviceid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1StatuspagesServicesServiceid',
  'type' => 'write',
  'name' => 'Put V1 Statuspages Services Serviceid',
  'description' => 'Update a service  Official Checkly endpoint: PUT /v1/status-pages/services/{serviceId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_statuspages_statuspageid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1StatuspagesStatuspageid',
  'type' => 'write',
  'name' => 'Delete V1 Statuspages Statuspageid',
  'description' => 'Delete a status page.  Official Checkly endpoint: DELETE /v1/status-pages/{statusPageId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_statuspages_statuspageid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1StatuspagesStatuspageid',
  'type' => 'read',
  'name' => 'Get V1 Statuspages Statuspageid',
  'description' => 'Get status page data, including cards and services.  Official Checkly endpoint: GET /v1/status-pages/{statusPageId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_statuspages_statuspageid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1StatuspagesStatuspageid',
  'type' => 'write',
  'name' => 'Put V1 Statuspages Statuspageid',
  'description' => 'Update a status page with its related services and cards.  Official Checkly endpoint: PUT /v1/status-pages/{statusPageId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_statuspages_statuspageid_subscriptions' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1StatuspagesStatuspageidSubscriptions',
  'type' => 'read',
  'name' => 'Get V1 Statuspages Statuspageid Subscriptions',
  'description' => 'Get all subscriptions for a specific status page  Official Checkly endpoint: GET /v1/status-pages/{statusPageId}/subscriptions.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_statuspages_statuspageid_subscriptions_bulk' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1StatuspagesStatuspageidSubscriptionsBulk',
  'type' => 'write',
  'name' => 'Post V1 Statuspages Statuspageid Subscriptions Bulk',
  'description' => 'Bulk create subscriptions for a specific status page.  Official Checkly endpoint: POST /v1/status-pages/{statusPageId}/subscriptions/bulk.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_statuspages_statuspageid_subscriptions_subscriptionid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1StatuspagesStatuspageidSubscriptionsSubscriptionid',
  'type' => 'write',
  'name' => 'Delete V1 Statuspages Statuspageid Subscriptions Subscriptionid',
  'description' => 'Delete a subscription belonging to a specific status page using the subscription id  Official Checkly endpoint: DELETE /v1/status-pages/{statusPageId}/subscriptions/{subscriptionId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_testsessionerrorgroups' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Testsessionerrorgroups',
  'type' => 'read',
  'name' => 'Get V1 Testsessionerrorgroups',
  'description' => 'List all test session error groups in your account.  Official Checkly endpoint: GET /v1/test-session-error-groups.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_testsessionerrorgroups_projects_projectid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1TestsessionerrorgroupsProjectsProjectid',
  'type' => 'read',
  'name' => 'Get V1 Testsessionerrorgroups Projects Projectid',
  'description' => 'List all test session error groups for a specific project.  Official Checkly endpoint: GET /v1/test-session-error-groups/projects/{projectId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_testsessionerrorgroups_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1TestsessionerrorgroupsId',
  'type' => 'read',
  'name' => 'Get V1 Testsessionerrorgroups Id',
  'description' => 'Retrieve one test session error group.  Official Checkly endpoint: GET /v1/test-session-error-groups/{id}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_patch_v1_testsessionerrorgroups_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPatchV1TestsessionerrorgroupsId',
  'type' => 'write',
  'name' => 'Patch V1 Testsessionerrorgroups Id',
  'description' => 'Update a test session error group. Mainly used for archiving test session error groups.  Official Checkly endpoint: PATCH /v1/test-session-error-groups/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v1_testsessions_trigger' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1TestsessionsTrigger',
  'type' => 'write',
  'name' => 'Post V1 Testsessions Trigger',
  'description' => 'Starts a tests session with checks matching the provided target filters. If no filters are given, matches all eligible checks. This endpoint does not wait for the test session to complete. Use the `GET /v1/test-sessions/{testSessionId}/completion` or `GET /v1/',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_testsessions_testsessionid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1TestsessionsTestsessionid',
  'type' => 'read',
  'name' => 'Get V1 Testsessions Testsessionid',
  'description' => 'Retrieves a test session. Note that the returned data may be incomplete if the test session is still in progress.  Official Checkly endpoint: GET /v1/test-sessions/{testSessionId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v1_testsessions_testsessionid_completion' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1TestsessionsTestsessionidCompletion',
  'type' => 'read',
  'name' => 'Get V1 Testsessions Testsessionid Completion',
  'description' => 'Call this endpoint to await the completion of a test session. A successful response code will be returned once the test session reaches its final state (i.e. when it passes or fails). If the test session takes a long time to complete, the endpoint will return ',
  'icon' => 'ph:heartbeat',
),
  'checkly_delete_v1_triggers_checkgroups_groupid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1TriggersCheckgroupsGroupid',
  'type' => 'write',
  'name' => 'Delete V1 Triggers Checkgroups Groupid',
  'description' => '[DEPRECATED] This endpoint will be removed soon. Please use the Checkly CLI to test and trigger checks. Deletes the check groups trigger  Official Checkly endpoint: DELETE /v1/triggers/check-groups/{groupId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_triggers_checkgroups_groupid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1TriggersCheckgroupsGroupid',
  'type' => 'read',
  'name' => 'Get V1 Triggers Checkgroups Groupid',
  'description' => '[DEPRECATED] This endpoint will be removed soon. Please use the Checkly CLI to test and trigger checks. Finds the check group trigger  Official Checkly endpoint: GET /v1/triggers/check-groups/{groupId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_triggers_checkgroups_groupid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1TriggersCheckgroupsGroupid',
  'type' => 'write',
  'name' => 'Post V1 Triggers Checkgroups Groupid',
  'description' => '[DEPRECATED] This endpoint will be removed soon. Please use the Checkly CLI to test and trigger checks. Creates the check group trigger  Official Checkly endpoint: POST /v1/triggers/check-groups/{groupId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_triggers_checks_checkid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1TriggersChecksCheckid',
  'type' => 'write',
  'name' => 'Delete V1 Triggers Checks Checkid',
  'description' => '[DEPRECATED] This endpoint will be removed soon. Please use the Checkly CLI to test and trigger checks. Deletes the check trigger  Official Checkly endpoint: DELETE /v1/triggers/checks/{checkId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_triggers_checks_checkid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1TriggersChecksCheckid',
  'type' => 'read',
  'name' => 'Get V1 Triggers Checks Checkid',
  'description' => '[DEPRECATED] This endpoint will be removed soon. Please use the Checkly CLI to test and trigger checks. Finds the check trigger.  Official Checkly endpoint: GET /v1/triggers/checks/{checkId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_triggers_checks_checkid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1TriggersChecksCheckid',
  'type' => 'write',
  'name' => 'Post V1 Triggers Checks Checkid',
  'description' => '[DEPRECATED] This endpoint will be removed soon. Please use the Checkly CLI to test and trigger checks. Creates the check trigger  Official Checkly endpoint: POST /v1/triggers/checks/{checkId}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_variables' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1Variables',
  'type' => 'read',
  'name' => 'Get V1 Variables',
  'description' => 'Lists all current environment variables in your account.  Official Checkly endpoint: GET /v1/variables.',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v1_variables' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV1Variables',
  'type' => 'write',
  'name' => 'Post V1 Variables',
  'description' => 'Creates a new environment variable.  Official Checkly endpoint: POST /v1/variables.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_delete_v1_variables_key' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyDeleteV1VariablesKey',
  'type' => 'write',
  'name' => 'Delete V1 Variables Key',
  'description' => 'Permanently removes an environment variable. Uses the "key" field as the ID for deletion.  Official Checkly endpoint: DELETE /v1/variables/{key}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v1_variables_key' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV1VariablesKey',
  'type' => 'read',
  'name' => 'Get V1 Variables Key',
  'description' => 'Show details of a specific environment variable. Uses the "key" field for selection.  Official Checkly endpoint: GET /v1/variables/{key}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_put_v1_variables_key' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV1VariablesKey',
  'type' => 'write',
  'name' => 'Put V1 Variables Key',
  'description' => 'Updates an environment variable. Uses the "key" field as the ID for updating. Only updates value, locked, and secret properties. Once a value is set to secret, it cannot be unset.  Official Checkly endpoint: PUT /v1/variables/{key}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_post_v2_checkgroups' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV2Checkgroups',
  'type' => 'write',
  'name' => 'Post V2 Checkgroups',
  'description' => 'Creates a new check group. You can add checks to the group by setting the "groupId" property of individual checks.  Official Checkly endpoint: POST /v2/check-groups.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_put_v2_checkgroups_id' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPutV2CheckgroupsId',
  'type' => 'write',
  'name' => 'Put V2 Checkgroups Id',
  'description' => 'Updates a check group.  Official Checkly endpoint: PUT /v2/check-groups/{id}.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v2_checkresults_checkid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV2CheckresultsCheckid',
  'type' => 'read',
  'name' => 'Get V2 Checkresults Checkid',
  'description' => 'Lists the full, raw check results for a specific check. We keep raw results for 30 days. After 30 days they are erased. However, we keep the rolled up results for an indefinite period. You can filter by check type and result type to narrow down the list. Use t',
  'icon' => 'ph:heartbeat',
),
  'checkly_post_v2_checksessions_trigger' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyPostV2ChecksessionsTrigger',
  'type' => 'write',
  'name' => 'Post V2 Checksessions Trigger',
  'description' => 'Trigger a new check session  Official Checkly endpoint: POST /v2/check-sessions/trigger.',
  'icon' => 'ph:pencil-simple',
),
  'checkly_get_v2_checksessions_checksessionid' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV2ChecksessionsChecksessionid',
  'type' => 'read',
  'name' => 'Get V2 Checksessions Checksessionid',
  'description' => 'Retrieve a check session  Official Checkly endpoint: GET /v2/check-sessions/{checkSessionId}.',
  'icon' => 'ph:heartbeat',
),
  'checkly_get_v2_checksessions_checksessionid_completion' => array (
  'class' => 'OpenCompany\\Integrations\\Checkly\\Tools\\ChecklyGetV2ChecksessionsChecksessionidCompletion',
  'type' => 'read',
  'name' => 'Get V2 Checksessions Checksessionid Completion',
  'description' => 'Await the completion of a check session  Official Checkly endpoint: GET /v2/check-sessions/{checkSessionId}/completion.',
  'icon' => 'ph:heartbeat',
),
    ]; }
    public function isIntegration(): bool { return true; } public function createTool(string $class, array $context = []): Tool { return new $class($this->resolveService($context)); } public function scriptDocsPath(): ?string { return __DIR__.'/../script-docs/checkly.md'; }
    /** @param  array<string, mixed>  $context  Runtime account context. */ private function resolveService(array $context=[]): ChecklyService { $account=$context['account']??null; if($account!==null){ $creds=app(CredentialResolver::class); return new ChecklyService(apiKey:$creds->get('checkly','api_key','',$account), accountId:$creds->get('checkly','account_id','',$account), baseUrl:$creds->get('checkly','url','https://api.checklyhq.com',$account)); } return app(ChecklyService::class); }
}
