<?php

namespace OpenCompany\Integrations\DbtCloud;

use Illuminate\Support\Facades\Http;
use OpenCompany\IntegrationCore\Contracts\ConfigurableIntegration;
use OpenCompany\IntegrationCore\Contracts\CredentialResolver;
use OpenCompany\IntegrationCore\Contracts\HasIntegrationCapabilities;
use OpenCompany\IntegrationCore\Contracts\Tool;
use OpenCompany\IntegrationCore\Contracts\ToolProvider;

/**
 * Tool catalog and configuration metadata for dbt Cloud.
 *
 * Exposes the official dbt Labs OpenAPI v2 and v3 operation sets as endpoint-specific
 * agent tools and resolves account-specific API tokens in multi-account hosts.
 */
class DbtCloudToolProvider implements ToolProvider, ConfigurableIntegration, HasIntegrationCapabilities
{
    /** @return array<string, mixed> */ public function integrationCapabilities(): array { return ['auth'=>['strategy'=>'api_token','legacy_auth_type'=>'api_token','credential_mode'=>'secret','setup_flows'=>['manual_secret'],'requires_browser_for_setup'=>false,'refreshable'=>false,'token_keys'=>[],'notes'=>['Send a dbt Cloud API token with the Bearer authorization scheme.']],'host_availability'=>['web'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret'],'cli'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret','runtime_mode'=>'normal']],'runtime_requirements'=>[],'compatibility'=>['web_setup_supported'=>true,'web_runtime_supported'=>true,'cli_setup_supported'=>true,'cli_runtime_supported'=>true]]; }
    public function appName(): string { return 'dbt-cloud'; } public function appMeta(): array { return ['label'=>'dbt Cloud','description'=>'Accounts, projects, jobs, runs, environments, connections, groups, webhooks, and semantic-layer resources','icon'=>'ph:git-branch','logo'=>'simple-icons:dbt']; }
    public function integrationMeta(): array { return ['name'=>'dbt Cloud','description'=>'Manage dbt Cloud accounts, projects, environments, jobs, runs, artifacts, credentials, connections, groups, users, webhooks, audit logs, and semantic-layer resources.','icon'=>'ph:git-branch','logo'=>'simple-icons:dbt','category'=>'data','badge'=>'verified','docs_url'=>'https://github.com/dbt-labs/dbt-cloud-openapi-spec']; }
    public function configSchema(): array { return [['key'=>'access_token','type'=>'secret','label'=>'Access Token','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','placeholder'=>'https://cloud.getdbt.com','default'=>'https://cloud.getdbt.com']]; }
    /** @param  array<string, mixed>  $config  Credential and endpoint settings. @return array{success: bool, message?: string, error?: string} */ public function testConnection(array $config): array { $token=(string)($config['access_token']??''); $baseUrl=rtrim((string)($config['url']??'https://cloud.getdbt.com'),'/'); if($token==='')return ['success'=>false,'error'=>'dbt Cloud access token is required.']; try{$response=Http::withHeaders(['Authorization'=>'Bearer '.$token,'Accept'=>'application/json','Content-Type'=>'application/json'])->timeout(10)->get($baseUrl.'/api/v3/accounts/'); if(!$response->successful())return ['success'=>false,'error'=>'dbt Cloud API returned HTTP '.$response->status().'.']; return ['success'=>true,'message'=>'Connected to dbt Cloud at '.$baseUrl.'.'];}catch(\Throwable $e){return ['success'=>false,'error'=>$e->getMessage()];} }
    public function validationRules(): array { return ['access_token'=>'required|string','url'=>'nullable|url']; } public function credentialFields(): array { return [['key'=>'access_token','type'=>'secret','label'=>'Access Token','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','required'=>false,'default'=>'https://cloud.getdbt.com']]; }
    public function tools(): array { return [
  'dbt_cloud_v2_list_accounts' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListAccounts',
  'type' => 'read',
  'name' => 'List Accounts',
  'description' => 'List Accounts Official dbt Cloud v2 endpoint: GET /api/v2/accounts/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_retrieve_account' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveAccount',
  'type' => 'read',
  'name' => 'Retrieve Account',
  'description' => 'Retrieve Account Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/ Retrieve an Account',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_update_account' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2UpdateAccount',
  'type' => 'write',
  'name' => 'Update Account',
  'description' => 'Update Account Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/ Update an account',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_partial_update_account' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2PartialUpdateAccount',
  'type' => 'write',
  'name' => 'Partial Update Account',
  'description' => 'Partial Update Account Official dbt Cloud v2 endpoint: PATCH /api/v2/accounts/{account_id}/ Partial Account update',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_list_ssh_tunnels' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListSshTunnels',
  'type' => 'read',
  'name' => 'List SSH Tunnels',
  'description' => 'List SSH Tunnels Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/encryptions/ List SSH tunnels',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_create_ssh_tunnel' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2CreateSshTunnel',
  'type' => 'write',
  'name' => 'Create SSH Tunnel',
  'description' => 'Create SSH Tunnel Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/encryptions/ Create a new SSH tunnel to encrypt traffic for a given connection',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_retrieve_ssh_tunnel' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveSshTunnel',
  'type' => 'read',
  'name' => 'Retrieve SSH Tunnel',
  'description' => 'Retrieve SSH Tunnel Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/encryptions/{id}/ Retrieve an SSH tunnel',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_update_ssh_tunnel' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2UpdateSshTunnel',
  'type' => 'write',
  'name' => 'Update SSH Tunnel',
  'description' => 'Update SSH Tunnel Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/encryptions/{id}/ Update an SSH tunnel',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_destroy_ssh_tunnel' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2DestroySshTunnel',
  'type' => 'write',
  'name' => 'Destroy SSH Tunnel',
  'description' => 'Destroy SSH Tunnel Official dbt Cloud v2 endpoint: DELETE /api/v2/accounts/{account_id}/encryptions/{id}/ Delete an SSH tunnel',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_list_environments' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListEnvironments',
  'type' => 'read',
  'name' => 'List Environments',
  'description' => 'List Environments Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/environments/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_create_environment' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2CreateEnvironment',
  'type' => 'write',
  'name' => 'Create Environment',
  'description' => 'Create Environment Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/environments/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_retrieve_environment' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveEnvironment',
  'type' => 'read',
  'name' => 'Retrieve Environment',
  'description' => 'Retrieve Environment Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/environments/{id}/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_update_environment' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2UpdateEnvironment',
  'type' => 'write',
  'name' => 'Update Environment',
  'description' => 'Update Environment Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/environments/{id}/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_destroy_environment' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2DestroyEnvironment',
  'type' => 'write',
  'name' => 'Destroy Environment',
  'description' => 'Destroy Environment Official dbt Cloud v2 endpoint: DELETE /api/v2/accounts/{account_id}/environments/{id}/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_list_invites' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListInvites',
  'type' => 'read',
  'name' => 'List Invites',
  'description' => 'List Invites Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/invites/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_retrieve_invite' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveInvite',
  'type' => 'read',
  'name' => 'Retrieve Invite',
  'description' => 'Retrieve Invite Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/invites/{id}/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_list_jobs' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListJobs',
  'type' => 'read',
  'name' => 'List Jobs',
  'description' => 'List Jobs Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/jobs/ List jobs for the given account',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_create_job' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2CreateJob',
  'type' => 'write',
  'name' => 'Create Job',
  'description' => 'Create Job Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/jobs/ Create a new job.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_retrieve_job_artifact' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveJobArtifact',
  'type' => 'read',
  'name' => 'Retrieve Job Artifact',
  'description' => 'Retrieve Job Artifact Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/jobs/{job_id}/artifacts/{remainder} Given a job id and *a set of Run filters* return the latest matching artifact for that job.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_retry_failed_job' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetryFailedJob',
  'type' => 'write',
  'name' => 'Retry Failed Job',
  'description' => 'Retry Failed Job Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/jobs/{job_id}/rerun/ Use this endpoint to retry a failed run for a job from the point of failure, if the run failed. Otherwise trigger a new run. When this ',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_trigger_job_run' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2TriggerJobRun',
  'type' => 'write',
  'name' => 'Trigger Job Run',
  'description' => 'Trigger Job Run Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/jobs/{job_id}/run/ Use this endpoint to kick off a run for a job. When this endpoint returns a successful response, a new run will be enqueued for the accoun',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_retrieve_job' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveJob',
  'type' => 'read',
  'name' => 'Retrieve Job',
  'description' => 'Retrieve Job Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/jobs/{id}/ Retrieve the details of a job.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_update_job' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2UpdateJob',
  'type' => 'write',
  'name' => 'Update Job',
  'description' => 'Update Job Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/jobs/{id}/ Update a job.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_destroy_job' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2DestroyJob',
  'type' => 'write',
  'name' => 'Destroy Job',
  'description' => 'Destroy Job Official dbt Cloud v2 endpoint: DELETE /api/v2/accounts/{account_id}/jobs/{id}/ Delete a job',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_list_account_license_allocations' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListAccountLicenseAllocations',
  'type' => 'read',
  'name' => 'List Account License Allocations',
  'description' => 'List Account License Allocations Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/licenses/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_list_notifications' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListNotifications',
  'type' => 'read',
  'name' => 'List Notifications',
  'description' => 'List Notifications Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/notifications/ List notification configurations',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_create_notification' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2CreateNotification',
  'type' => 'write',
  'name' => 'Create Notification',
  'description' => 'Create Notification Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/notifications/ Create a new Job Notification configuration to trigger notifications for job successes, failures, or cancelations. Notifications can be se',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_retrieve_notification' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveNotification',
  'type' => 'read',
  'name' => 'Retrieve Notification',
  'description' => 'Retrieve Notification Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/notifications/{id}/ Fetch notification configurations',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_update_notification' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2UpdateNotification',
  'type' => 'write',
  'name' => 'Update Notification',
  'description' => 'Update Notification Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/notifications/{id}/ Update an existing Job Notification configuration.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_destroy_notification' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2DestroyNotification',
  'type' => 'write',
  'name' => 'Destroy Notification',
  'description' => 'Destroy Notification Official dbt Cloud v2 endpoint: DELETE /api/v2/accounts/{account_id}/notifications/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_update_license_permissions' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2UpdateLicensePermissions',
  'type' => 'write',
  'name' => 'Update License Permissions',
  'description' => 'Update License Permissions Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/permissions/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_list_projects' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListProjects',
  'type' => 'read',
  'name' => 'List Projects',
  'description' => 'List Projects Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/projects/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_create_project' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2CreateProject',
  'type' => 'write',
  'name' => 'Create Project',
  'description' => 'Create Project Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/projects/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_retrieve_project' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveProject',
  'type' => 'read',
  'name' => 'Retrieve Project',
  'description' => 'Retrieve Project Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/projects/{id}/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_update_project' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2UpdateProject',
  'type' => 'write',
  'name' => 'Update Project',
  'description' => 'Update Project Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/projects/{id}/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_destroy_project' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2DestroyProject',
  'type' => 'write',
  'name' => 'Destroy Project',
  'description' => 'Destroy Project Official dbt Cloud v2 endpoint: DELETE /api/v2/accounts/{account_id}/projects/{id}/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_list_repositories' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListRepositories',
  'type' => 'read',
  'name' => 'List Repositories',
  'description' => 'List Repositories Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/repositories/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_create_repository' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2CreateRepository',
  'type' => 'write',
  'name' => 'Create Repository',
  'description' => 'Create Repository Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/repositories/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_retrieve_repository' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveRepository',
  'type' => 'read',
  'name' => 'Retrieve Repository',
  'description' => 'Retrieve Repository Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/repositories/{id}/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_destroy_repository' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2DestroyRepository',
  'type' => 'write',
  'name' => 'Destroy Repository',
  'description' => 'Destroy Repository Official dbt Cloud v2 endpoint: DELETE /api/v2/accounts/{account_id}/repositories/{id}/ Deprecated. Consider using the v3 API instead.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_list_runs' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListRuns',
  'type' => 'read',
  'name' => 'List Runs',
  'description' => 'List Runs Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/runs/ List runs for an account.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_retrieve_run' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveRun',
  'type' => 'read',
  'name' => 'Retrieve Run',
  'description' => 'Retrieve Run Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/runs/{id}/ Retrieve details of a run.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_list_run_artifacts' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListRunArtifacts',
  'type' => 'read',
  'name' => 'List Run Artifacts',
  'description' => 'List Run Artifacts Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/runs/{run_id}/artifacts/ Retrieve the list of artifacts generated for a run.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_retrieve_run_artifact' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveRunArtifact',
  'type' => 'read',
  'name' => 'Retrieve Run Artifact',
  'description' => 'Retrieve Run Artifact Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/runs/{run_id}/artifacts/{remainder} Use this endpoint to fetch artifacts from a completed run. Once a run has been completed, you can use this endpoint ',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_cancel_run' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2CancelRun',
  'type' => 'write',
  'name' => 'Cancel Run',
  'description' => 'Cancel Run Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/runs/{run_id}/cancel/ Cancel a run.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_retrieve_run_failure_details' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveRunFailureDetails',
  'type' => 'read',
  'name' => 'Retrieve Run Failure Details',
  'description' => 'Retrieve Run Failure Details Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/runs/{run_id}/retry/ Use this endpoint to get details about a retryable run that has failed.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_retry_run' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetryRun',
  'type' => 'write',
  'name' => 'Retry Run',
  'description' => 'Retry Run Official dbt Cloud v2 endpoint: POST /api/v2/accounts/{account_id}/runs/{run_id}/retry/ Use this endpoint to retry a failed run. When this endpoint returns a successful response, a new run will be enqueued. Users can poll the Get ',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_retrieve_run_step' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveRunStep',
  'type' => 'read',
  'name' => 'Retrieve Run Step',
  'description' => 'Retrieve Run Step Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/steps/{id}/ Retrieve the details of a specific step of a run.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_list_users' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2ListUsers',
  'type' => 'read',
  'name' => 'List Users',
  'description' => 'List Users Official dbt Cloud v2 endpoint: GET /api/v2/accounts/{account_id}/users/ List the Users associated with the specified Account.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_unsubscribe_from_notifications' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2UnsubscribeFromNotifications',
  'type' => 'write',
  'name' => 'Unsubscribe from Notifications',
  'description' => 'Unsubscribe from Notifications Official dbt Cloud v2 endpoint: POST /api/v2/notifications/unsubscribe/ Clear out all email notification configurations for the user making the request.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v2_retrieve_user' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2RetrieveUser',
  'type' => 'read',
  'name' => 'Retrieve User',
  'description' => 'Retrieve User Official dbt Cloud v2 endpoint: GET /api/v2/users/{id}/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v2_update_user' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV2UpdateUser',
  'type' => 'write',
  'name' => 'Update User',
  'description' => 'Update User Official dbt Cloud v2 endpoint: POST /api/v2/users/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_accounts' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListAccounts',
  'type' => 'read',
  'name' => 'List Accounts',
  'description' => 'List Accounts Official dbt Cloud v3 endpoint: GET /api/v3/accounts/ List the Accounts that your API Token is authorized to access.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_assign_user_to_groups' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3AssignUserToGroups',
  'type' => 'write',
  'name' => 'Assign User to Groups',
  'description' => 'Assign User to Groups Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/assign-groups/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_recent_audit_log_events' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListRecentAuditLogEvents',
  'type' => 'read',
  'name' => 'List Recent Audit Log Events',
  'description' => 'List Recent Audit Log Events Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/audit-logs/ Fetch paginated audit log events. Note: This API is only available to enterprise customers.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_get_recent_audit_log_events_csv' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetRecentAuditLogEventsCsv',
  'type' => 'read',
  'name' => 'Get Recent Audit Log Events CSV',
  'description' => 'Get Recent Audit Log Events CSV Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/audit-logs/download/ Generate audit log CSV Note: This API is only available to enterprise customers.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_get_bulk_audit_log_export_status' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetBulkAuditLogExportStatus',
  'type' => 'read',
  'name' => 'Get Bulk Audit Log Export Status',
  'description' => 'Get Bulk Audit Log Export Status Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/audit-logs/export/ Check the status of a bulk export request. Note: This API is only available to enterprise customers.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_submit_bulk_audit_log_export_request' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3SubmitBulkAuditLogExportRequest',
  'type' => 'write',
  'name' => 'Submit Bulk Audit Log Export Request',
  'description' => 'Submit Bulk Audit Log Export Request Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/audit-logs/export/ Submit a bulk export request. Note: This API is only available to enterprise customers.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_download_bulk_audit_log_export' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DownloadBulkAuditLogExport',
  'type' => 'read',
  'name' => 'Download Bulk Audit Log Export',
  'description' => 'Download Bulk Audit Log Export Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/audit-logs/export/{job_identifier}/download/ Download a bulk export of audit log events. Note: This API is only available to enterprise custome',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_account_connections' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListAccountConnections',
  'type' => 'read',
  'name' => 'List Account Connections',
  'description' => 'List Account Connections Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/connections/ List all Account Connections.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_account_connection' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateAccountConnection',
  'type' => 'write',
  'name' => 'Create Account Connection',
  'description' => 'Create Account Connection Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/connections/ Create a new Account Connection.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_account_connection' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveAccountConnection',
  'type' => 'read',
  'name' => 'Retrieve Account Connection',
  'description' => 'Retrieve Account Connection Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/connections/{id}/ Retrieve details of a specific Account Connection.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_account_connection' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateAccountConnection',
  'type' => 'write',
  'name' => 'Update Account Connection',
  'description' => 'Update Account Connection Official dbt Cloud v3 endpoint: PATCH /api/v3/accounts/{account_id}/connections/{id}/ Update an existing Account Connection.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_delete_account_connection_delete' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DeleteAccountConnectionDelete',
  'type' => 'write',
  'name' => 'Delete Account Connection Delete',
  'description' => 'Delete Account Connection Delete Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/connections/{id}/ Delete an existing Account Connection Delete.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_delete_environment_sao_cache' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DeleteEnvironmentSaoCache',
  'type' => 'write',
  'name' => 'Delete Environment SAO Cache',
  'description' => 'Delete Environment SAO Cache Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/environments/{environment_id}/sao-cache/ Clear the environment SAO (State Aware Orchestration) cache in Redis for the given environment',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_favorite_asset_responses' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListFavoriteAssetResponses',
  'type' => 'read',
  'name' => 'List Favorite Asset Responses',
  'description' => 'List Favorite Asset Responses Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/favorite-assets/ List all Favorite Asset Responses.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_assign_group_permissions' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3AssignGroupPermissions',
  'type' => 'write',
  'name' => 'Assign Group Permissions',
  'description' => 'Assign Group Permissions Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/group-permissions/{group_id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_groups' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListGroups',
  'type' => 'read',
  'name' => 'List Groups',
  'description' => 'List Groups Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/groups/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_group' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateGroup',
  'type' => 'write',
  'name' => 'Create Group',
  'description' => 'Create Group Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/groups/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_group' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveGroup',
  'type' => 'read',
  'name' => 'Retrieve Group',
  'description' => 'Retrieve Group Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/groups/{id}/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_group' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateGroup',
  'type' => 'write',
  'name' => 'Update Group',
  'description' => 'Update Group Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/groups/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_send_user_invites' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3SendUserInvites',
  'type' => 'write',
  'name' => 'Send user invites',
  'description' => 'Send user invites Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/invites/ Send email invites to users who you wish to add to this account',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_ip_restrictions' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListIpRestrictions',
  'type' => 'read',
  'name' => 'List IP Restrictions',
  'description' => 'List IP Restrictions Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/ip-restrictions/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_save_ip_restriction' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3SaveIpRestriction',
  'type' => 'write',
  'name' => 'Save IP Restriction',
  'description' => 'Save IP Restriction Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/ip-restrictions/ Save net-new ip restriction rule Note: As long as at least one cidr was successfully saved a 2XX will be returned. Check the `extra` key',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_enable_ip_restrictions' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3EnableIpRestrictions',
  'type' => 'write',
  'name' => 'Enable IP Restrictions',
  'description' => 'Enable IP Restrictions Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/ip-restrictions-set/ Toggle the enablement of the IP restriction feature.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_validate_client_ip_against_ip_restrictions' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ValidateClientIpAgainstIpRestrictions',
  'type' => 'read',
  'name' => 'Validate Client IP Against IP Restrictions',
  'description' => 'Validate Client IP Against IP Restrictions Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/ip-restrictions-set/{id}/validate/ This endpoint returns whether the client ip is acceptable based on the configured ip restriction',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_validate_client_ip_against_ip_restrictions_excluding_specified_ip_rule' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ValidateClientIpAgainstIpRestrictionsExcludingSpecifiedIpRule',
  'type' => 'read',
  'name' => 'Validate Client IP Against IP Restrictions Excluding Specified IP Rule',
  'description' => 'Validate Client IP Against IP Restrictions Excluding Specified IP Rule Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/ip-restrictions-set/{id}/validate/{rule_id} This endpoint returns whether the client ip is acceptable b',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_retrieve_ip_restriction' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveIpRestriction',
  'type' => 'read',
  'name' => 'Retrieve IP Restriction',
  'description' => 'Retrieve IP Restriction Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/ip-restrictions/{id}',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_ip_restriction' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateIpRestriction',
  'type' => 'write',
  'name' => 'Update IP Restriction',
  'description' => 'Update IP Restriction Official dbt Cloud v3 endpoint: PUT /api/v3/accounts/{account_id}/ip-restrictions/{id} Update an existing ip restriction rule Note: As long as at least one cidr was successfully saved a 2XX will be returned. Check the ',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_delete_ip_restriction' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DeleteIpRestriction',
  'type' => 'write',
  'name' => 'Delete IP Restriction',
  'description' => 'Delete IP Restriction Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/ip-restrictions/{id}',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_license_maps' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListLicenseMaps',
  'type' => 'read',
  'name' => 'List License Maps',
  'description' => 'List License Maps Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/license-maps/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_license_map' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateLicenseMap',
  'type' => 'write',
  'name' => 'Create License Map',
  'description' => 'Create License Map Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/license-maps/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_license_map' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveLicenseMap',
  'type' => 'read',
  'name' => 'Retrieve License Map',
  'description' => 'Retrieve License Map Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/license-maps/{id}/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_license_map' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateLicenseMap',
  'type' => 'write',
  'name' => 'Update License Map',
  'description' => 'Update License Map Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/license-maps/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_license_map' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyLicenseMap',
  'type' => 'write',
  'name' => 'Destroy License Map',
  'description' => 'Destroy License Map Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/license-maps/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_oauth_configurations' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListOauthConfigurations',
  'type' => 'read',
  'name' => 'List OAuthConfigurations',
  'description' => 'List OAuthConfigurations Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/oauth-configurations/ List OAuthConfigurations',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_oauth_configuration' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateOauthConfiguration',
  'type' => 'write',
  'name' => 'Create OAuthConfiguration',
  'description' => 'Create OAuthConfiguration Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/oauth-configurations/ Create a new OAuthConfiguration',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_oauth_configuration' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveOauthConfiguration',
  'type' => 'read',
  'name' => 'Retrieve OAuth Configuration',
  'description' => 'Retrieve OAuth Configuration Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/oauth-configurations/{id}/ Retrieve an OAuth Configuration',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_oauth_configuration' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateOauthConfiguration',
  'type' => 'write',
  'name' => 'Update OAuth Configuration',
  'description' => 'Update OAuth Configuration Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/oauth-configurations/{id}/ Update an OAuthConfiguration',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_oauth_configuration' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyOauthConfiguration',
  'type' => 'write',
  'name' => 'Destroy OAuth Configuration',
  'description' => 'Destroy OAuth Configuration Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/oauth-configurations/{id}/ Delete an OAuth Configuration',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_projects' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListProjects',
  'type' => 'read',
  'name' => 'List Projects',
  'description' => 'List Projects Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/ List Projects',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_project' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateProject',
  'type' => 'write',
  'name' => 'Create Project',
  'description' => 'Create Project Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/ Create a new Project',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_project' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveProject',
  'type' => 'read',
  'name' => 'Retrieve Project',
  'description' => 'Retrieve Project Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{id}/ Retrieve a Project',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_project' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateProject',
  'type' => 'write',
  'name' => 'Update Project',
  'description' => 'Update Project Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{id}/ Update a Project',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_project' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyProject',
  'type' => 'write',
  'name' => 'Destroy Project',
  'description' => 'Destroy Project Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/projects/{id}/ Delete Project',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_create_adapter' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateAdapter',
  'type' => 'write',
  'name' => 'Create Adapter',
  'description' => 'Create Adapter Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/adapters/ Create a new adapter for a project. The ID from this adapter can be used to create Connections or Credentials when necessary.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_adapter' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveAdapter',
  'type' => 'read',
  'name' => 'Retrieve Adapter',
  'description' => 'Retrieve Adapter Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/adapters/{id}/ Get an adapter by ID.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_adapter' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateAdapter',
  'type' => 'write',
  'name' => 'Update Adapter',
  'description' => 'Update Adapter Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/adapters/{id}/ Update an adapter.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_adapter' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyAdapter',
  'type' => 'write',
  'name' => 'Destroy Adapter',
  'description' => 'Destroy Adapter Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/projects/{project_id}/adapters/{id}/ Delete an adapter.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_connections' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListConnections',
  'type' => 'read',
  'name' => 'List Connections',
  'description' => 'List Connections Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/connections/ List Connections',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_connection' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateConnection',
  'type' => 'write',
  'name' => 'Create Connection',
  'description' => 'Create Connection Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/connections/ Create a new Connection',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_connection' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveConnection',
  'type' => 'read',
  'name' => 'Retrieve Connection',
  'description' => 'Retrieve Connection Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/connections/{id}/ Retrieve a Connection',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_connection' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateConnection',
  'type' => 'write',
  'name' => 'Update Connection',
  'description' => 'Update Connection Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/connections/{id}/ Update a Connection',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_connection' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyConnection',
  'type' => 'write',
  'name' => 'Destroy Connection',
  'description' => 'Destroy Connection Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/projects/{project_id}/connections/{id}/ Delete a Connection',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListCredentials',
  'type' => 'read',
  'name' => 'List Credentials',
  'description' => 'List Credentials Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/credentials/ List the credentials for a given project.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateCredentials',
  'type' => 'write',
  'name' => 'Create Credentials',
  'description' => 'Create Credentials Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/credentials/ Create a new set of credentials to associate with a user or environment.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_get_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetCredentials',
  'type' => 'read',
  'name' => 'Get Credentials',
  'description' => 'Get Credentials Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/credentials/{id}/ Fetch a specific set of credentials.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateCredentials',
  'type' => 'write',
  'name' => 'Update Credentials',
  'description' => 'Update Credentials Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/credentials/{id}/ Update a set of credentials.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_partial_update_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3PartialUpdateCredentials',
  'type' => 'write',
  'name' => 'Partial Update Credentials',
  'description' => 'Partial Update Credentials Official dbt Cloud v3 endpoint: PATCH /api/v3/accounts/{account_id}/projects/{project_id}/credentials/{id}/ Partially update a set of credentials.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_delete_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DeleteCredentials',
  'type' => 'write',
  'name' => 'Delete Credentials',
  'description' => 'Delete Credentials Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/projects/{project_id}/credentials/{id}/ Delete a set of credentials.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_create_projects_environment_variable' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateProjectsEnvironmentVariable',
  'type' => 'write',
  'name' => 'Create Projects Environment Variable',
  'description' => 'Create Projects Environment Variable Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/environment-variables/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_update_projects_environment_variable' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateProjectsEnvironmentVariable',
  'type' => 'write',
  'name' => 'Update Projects Environment Variable',
  'description' => 'Update Projects Environment Variable Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/environment-variables/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_projects_environment_variable' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyProjectsEnvironmentVariable',
  'type' => 'write',
  'name' => 'Destroy Projects Environment Variable',
  'description' => 'Destroy Projects Environment Variable Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/projects/{project_id}/environment-variables/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_create_projects_environment_variables_bulk' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateProjectsEnvironmentVariablesBulk',
  'type' => 'write',
  'name' => 'Create Projects Environment Variables Bulk',
  'description' => 'Create Projects Environment Variables Bulk Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/environment-variables/bulk/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_update_projects_environment_variables_bulk' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateProjectsEnvironmentVariablesBulk',
  'type' => 'write',
  'name' => 'Update Projects Environment Variables Bulk',
  'description' => 'Update Projects Environment Variables Bulk Official dbt Cloud v3 endpoint: PUT /api/v3/accounts/{account_id}/projects/{project_id}/environment-variables/bulk/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_projects_environment_variables_bulk' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyProjectsEnvironmentVariablesBulk',
  'type' => 'write',
  'name' => 'Destroy Projects Environment Variables Bulk',
  'description' => 'Destroy Projects Environment Variables Bulk Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/projects/{project_id}/environment-variables/bulk/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_projects_environment_variables_environment' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveProjectsEnvironmentVariablesEnvironment',
  'type' => 'read',
  'name' => 'Retrieve Projects Environment Variables Environment',
  'description' => 'Retrieve Projects Environment Variables Environment Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/environment-variables/environment/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_retrieve_projects_environment_variables_job' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveProjectsEnvironmentVariablesJob',
  'type' => 'read',
  'name' => 'Retrieve Projects Environment Variables Job',
  'description' => 'Retrieve Projects Environment Variables Job Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/environment-variables/job/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_retrieve_projects_environment_variables_user' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveProjectsEnvironmentVariablesUser',
  'type' => 'read',
  'name' => 'Retrieve Projects Environment Variables User',
  'description' => 'Retrieve Projects Environment Variables User Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/environment-variables/user/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_environments' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListEnvironments',
  'type' => 'read',
  'name' => 'List Environments',
  'description' => 'List Environments Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/environments/ List Environments',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_environment' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateEnvironment',
  'type' => 'write',
  'name' => 'Create Environment',
  'description' => 'Create Environment Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/environments/ Create a new Environment',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_environment' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveEnvironment',
  'type' => 'read',
  'name' => 'Retrieve Environment',
  'description' => 'Retrieve Environment Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/environments/{id}/ Retrieve an Environment',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_environment' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateEnvironment',
  'type' => 'write',
  'name' => 'Update Environment',
  'description' => 'Update Environment Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/environments/{id}/ Replace an Environment. This is a full replace operation — all fields must be provided. Any omitted fields will',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_environment' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyEnvironment',
  'type' => 'write',
  'name' => 'Destroy Environment',
  'description' => 'Destroy Environment Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/projects/{project_id}/environments/{id}/ Delete an Environment',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_create_extended_attributes' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateExtendedAttributes',
  'type' => 'write',
  'name' => 'Create Extended Attributes',
  'description' => 'Create Extended Attributes Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/extended-attributes/ Create a new Extended Attributes record.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_extended_attributes' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveExtendedAttributes',
  'type' => 'read',
  'name' => 'Retrieve Extended Attributes',
  'description' => 'Retrieve Extended Attributes Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/extended-attributes/{id}/ Given an account_id, project_id, and primary key: retrieve an existing Extended Attributes record',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_extended_attributes' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateExtendedAttributes',
  'type' => 'write',
  'name' => 'Update Extended Attributes',
  'description' => 'Update Extended Attributes Official dbt Cloud v3 endpoint: PATCH /api/v3/accounts/{account_id}/projects/{project_id}/extended-attributes/{id}/ Update an existing Extended Attributes record by ID.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_extended_attributes' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyExtendedAttributes',
  'type' => 'write',
  'name' => 'Destroy Extended Attributes',
  'description' => 'Destroy Extended Attributes Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/projects/{project_id}/extended-attributes/{id}/ Delete an existing Extended Attributes record by ID.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_lineage_integrations' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListLineageIntegrations',
  'type' => 'read',
  'name' => 'List Lineage Integrations',
  'description' => 'List Lineage Integrations Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/integrations/lineage/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_lineage_integration' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateLineageIntegration',
  'type' => 'write',
  'name' => 'Create Lineage Integration',
  'description' => 'Create Lineage Integration Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/integrations/lineage/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_get_lineage_integration' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetLineageIntegration',
  'type' => 'read',
  'name' => 'Get Lineage Integration',
  'description' => 'Get Lineage Integration Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/integrations/lineage/{id}/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_lineage_integration' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateLineageIntegration',
  'type' => 'write',
  'name' => 'Update Lineage Integration',
  'description' => 'Update Lineage Integration Official dbt Cloud v3 endpoint: PATCH /api/v3/accounts/{account_id}/projects/{project_id}/integrations/lineage/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_delete_lineage_integration' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DeleteLineageIntegration',
  'type' => 'write',
  'name' => 'Delete Lineage Integration',
  'description' => 'Delete Lineage Integration Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/projects/{project_id}/integrations/lineage/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_collections_from_bi_tool' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListCollectionsFromBiTool',
  'type' => 'read',
  'name' => 'List collections from BI tool',
  'description' => 'List collections from BI tool Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/integrations/lineage/{id}/collections/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_collections_from_bi_tool_2' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListCollectionsFromBiTool2',
  'type' => 'read',
  'name' => 'List collections from BI tool_2',
  'description' => 'List collections from BI tool_2 Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/integrations/lineage/{id}/collections/{collection_id}/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_lineage_integration_selections' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateLineageIntegrationSelections',
  'type' => 'write',
  'name' => 'Update Lineage Integration Selections',
  'description' => 'Update Lineage Integration Selections Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/integrations/lineage/{id}/selections',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_create_managed_repository' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateManagedRepository',
  'type' => 'write',
  'name' => 'Create Managed Repository',
  'description' => 'Create Managed Repository Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/managed-repositories/ Create a new dbt Cloud managed repository.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_projects_managed_repositories_download' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveProjectsManagedRepositoriesDownload',
  'type' => 'read',
  'name' => 'Retrieve Projects Managed Repositories Download',
  'description' => 'Retrieve Projects Managed Repositories Download Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/managed-repositories/{repository_id}/download/ Download a managed repository as a ZIP archive',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_profiles' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListProfiles',
  'type' => 'read',
  'name' => 'List Profiles',
  'description' => 'List Profiles Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/profiles/ List profiles. Note: Profiles are in the process of being rolled out and may not be available for your account yet. Profiles are',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_profile' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateProfile',
  'type' => 'write',
  'name' => 'Create Profile',
  'description' => 'Create Profile Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/profiles/ Create a new profile. Note: Profiles are in the process of being rolled out and may not be available for your account yet. Pro',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_profile' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveProfile',
  'type' => 'read',
  'name' => 'Retrieve Profile',
  'description' => 'Retrieve Profile Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/profiles/{id}/ Retrieve a specific profile. Note: Profiles are in the process of being rolled out and may not be available for your acc',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_profile' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateProfile',
  'type' => 'write',
  'name' => 'Update Profile',
  'description' => 'Update Profile Official dbt Cloud v3 endpoint: PATCH /api/v3/accounts/{account_id}/projects/{project_id}/profiles/{id}/ Update an existing profile. Note: Profiles are in the process of being rolled out and may not be available for your acco',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_delete_profile' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DeleteProfile',
  'type' => 'write',
  'name' => 'Delete Profile',
  'description' => 'Delete Profile Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/projects/{project_id}/profiles/{id}/ Delete an existing profile. The profile must not be assigned to any deployment environments in order to be deleted. Not',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_repositories' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListRepositories',
  'type' => 'read',
  'name' => 'List Repositories',
  'description' => 'List Repositories Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/repositories/ List repositories for the given project',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_repository' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateRepository',
  'type' => 'write',
  'name' => 'Create Repository',
  'description' => 'Create Repository Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/repositories/ Create a new repository for the given project',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_repository' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveRepository',
  'type' => 'read',
  'name' => 'Retrieve Repository',
  'description' => 'Retrieve Repository Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/projects/{project_id}/repositories/{id}/ Get a repository by ID',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_repository' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateRepository',
  'type' => 'write',
  'name' => 'Update Repository',
  'description' => 'Update Repository Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/projects/{project_id}/repositories/{id}/ Update a repository',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_repository' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyRepository',
  'type' => 'write',
  'name' => 'Destroy Repository',
  'description' => 'Destroy Repository Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/projects/{project_id}/repositories/{id}/ Delete a repository',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_scim_configuration' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveScimConfiguration',
  'type' => 'read',
  'name' => 'Retrieve SCIM configuration',
  'description' => 'Retrieve SCIM configuration Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim-config/ Retrieve the SCIM configuration for the account',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_scim_configuration' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateScimConfiguration',
  'type' => 'write',
  'name' => 'Create SCIM configuration',
  'description' => 'Create SCIM configuration Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/scim-config/ Create SCIM configuration for the account',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_scim_tokens' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveScimTokens',
  'type' => 'read',
  'name' => 'Retrieve SCIM tokens',
  'description' => 'Retrieve SCIM tokens Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim-config/tokens/ Retrieve all SCIM tokens',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_scim_token' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateScimToken',
  'type' => 'write',
  'name' => 'Create SCIM token',
  'description' => 'Create SCIM token Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/scim-config/tokens/ Create a SCIM token',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_scim_token' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveScimToken',
  'type' => 'read',
  'name' => 'Retrieve SCIM token',
  'description' => 'Retrieve SCIM token Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim-config/tokens/{id}/ Retrieve the specified SCIM token',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_delete_scim_token' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DeleteScimToken',
  'type' => 'write',
  'name' => 'Delete SCIM token',
  'description' => 'Delete SCIM token Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/scim-config/tokens/{id}/ Delete the specified SCIM token',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_scim_groups' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListScimGroups',
  'type' => 'read',
  'name' => 'List SCIM Groups',
  'description' => 'List SCIM Groups Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim/v2/Groups List all groups via SCIM',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_scim_group' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateScimGroup',
  'type' => 'write',
  'name' => 'Create SCIM Group',
  'description' => 'Create SCIM Group Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/scim/v2/Groups Create a group via SCIM',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_get_scim_group' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetScimGroup',
  'type' => 'read',
  'name' => 'Get SCIM Group',
  'description' => 'Get SCIM Group Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim/v2/Groups/{group_id} Get a group via SCIM',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_scim_group' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateScimGroup',
  'type' => 'write',
  'name' => 'Update SCIM Group',
  'description' => 'Update SCIM Group Official dbt Cloud v3 endpoint: PUT /api/v3/accounts/{account_id}/scim/v2/Groups/{group_id} Update a group via SCIM using PUT',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_patch_scim_group' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3PatchScimGroup',
  'type' => 'write',
  'name' => 'Patch SCIM Group',
  'description' => 'Patch SCIM Group Official dbt Cloud v3 endpoint: PATCH /api/v3/accounts/{account_id}/scim/v2/Groups/{group_id} Update a group via SCIM using PATCH',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_delete_scim_group' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DeleteScimGroup',
  'type' => 'write',
  'name' => 'Delete SCIM Group',
  'description' => 'Delete SCIM Group Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/scim/v2/Groups/{group_id} Delete a group via SCIM',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_get_scim_resource_types' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetScimResourceTypes',
  'type' => 'read',
  'name' => 'Get SCIM Resource Types',
  'description' => 'Get SCIM Resource Types Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim/v2/ResourceTypes Get Supported SCIM Resource Types',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_get_scim_resource_type_details' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetScimResourceTypeDetails',
  'type' => 'read',
  'name' => 'Get SCIM Resource Type Details',
  'description' => 'Get SCIM Resource Type Details Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim/v2/ResourceTypes/{resource_type} Get Supported SCIM Resource Type Details',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_get_scim_schemas' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetScimSchemas',
  'type' => 'read',
  'name' => 'Get SCIM Schemas',
  'description' => 'Get SCIM Schemas Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim/v2/Schemas Get Supported SCIM Schemas',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_get_scim_schema_details' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetScimSchemaDetails',
  'type' => 'read',
  'name' => 'Get SCIM Schema Details',
  'description' => 'Get SCIM Schema Details Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim/v2/Schemas/{schema_uri} Get Supported SCIM Schema Details',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_retrieve_scim_v2_serviceproviderconfig' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveScimV2Serviceproviderconfig',
  'type' => 'read',
  'name' => 'Retrieve Scim V2 Serviceproviderconfig',
  'description' => 'Retrieve Scim V2 Serviceproviderconfig Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim/v2/ServiceProviderConfig Get the SCIM Service Provider Config',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_scim_users' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListScimUsers',
  'type' => 'read',
  'name' => 'List SCIM Users',
  'description' => 'List SCIM Users Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim/v2/Users List all users via SCIM',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_scim_user' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateScimUser',
  'type' => 'write',
  'name' => 'Create SCIM User',
  'description' => 'Create SCIM User Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/scim/v2/Users Create a user via SCIM',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_get_scim_user' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetScimUser',
  'type' => 'read',
  'name' => 'Get SCIM User',
  'description' => 'Get SCIM User Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/scim/v2/Users/{user_id} Get a user via SCIM',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_replace_scim_user' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ReplaceScimUser',
  'type' => 'write',
  'name' => 'Replace SCIM User',
  'description' => 'Replace SCIM User Official dbt Cloud v3 endpoint: PUT /api/v3/accounts/{account_id}/scim/v2/Users/{user_id} Replace a user via SCIM using PUT',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_update_scim_user' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateScimUser',
  'type' => 'write',
  'name' => 'Update SCIM User',
  'description' => 'Update SCIM User Official dbt Cloud v3 endpoint: PATCH /api/v3/accounts/{account_id}/scim/v2/Users/{user_id} Update a user attribute(s) via SCIM',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_delete_scim_user' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DeleteScimUser',
  'type' => 'write',
  'name' => 'Delete SCIM User',
  'description' => 'Delete SCIM User Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/scim/v2/Users/{user_id} Delete a user via SCIM. This endpoint will remove the users license from the account.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_semantic_layer_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListSemanticLayerCredentials',
  'type' => 'read',
  'name' => 'List Semantic Layer Credentials',
  'description' => 'List Semantic Layer Credentials Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/semantic-layer-credentials/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_service_tokens' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListServiceTokens',
  'type' => 'read',
  'name' => 'List Service Tokens',
  'description' => 'List Service Tokens Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/service-tokens/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_service_token' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateServiceToken',
  'type' => 'write',
  'name' => 'Create Service Token',
  'description' => 'Create Service Token Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/service-tokens/ This endpoint is used to generate a new service token for the account.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_service_token' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveServiceToken',
  'type' => 'read',
  'name' => 'Retrieve Service Token',
  'description' => 'Retrieve Service Token Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/service-tokens/{id}/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_service_token' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateServiceToken',
  'type' => 'write',
  'name' => 'Update Service Token',
  'description' => 'Update Service Token Official dbt Cloud v3 endpoint: PUT /api/v3/accounts/{account_id}/service-tokens/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_service_token' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyServiceToken',
  'type' => 'write',
  'name' => 'Destroy Service Token',
  'description' => 'Destroy Service Token Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/service-tokens/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_service_tokens_permission' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveServiceTokensPermission',
  'type' => 'read',
  'name' => 'Retrieve Service Tokens Permission',
  'description' => 'Retrieve Service Tokens Permission Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/service-tokens/{service_token_id}/permissions/ List permissions of a given ServiceToken for an account.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_users' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListUsers',
  'type' => 'read',
  'name' => 'List Users',
  'description' => 'List Users Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/users/ List users for a given account.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_retrieve_user' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveUser',
  'type' => 'read',
  'name' => 'Retrieve User',
  'description' => 'Retrieve User Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/users/{id}/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_account_scoped_pats' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListAccountScopedPats',
  'type' => 'read',
  'name' => 'List Account Scoped PATs',
  'description' => 'List Account Scoped PATs Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/users/{user_id}/account-apikeys/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_account_scoped_pat' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateAccountScopedPat',
  'type' => 'write',
  'name' => 'Create Account Scoped PAT',
  'description' => 'Create Account Scoped PAT Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/users/{user_id}/account-apikeys/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_get_account_scoped_pat' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetAccountScopedPat',
  'type' => 'read',
  'name' => 'Get Account Scoped PAT',
  'description' => 'Get Account Scoped PAT Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/users/{user_id}/account-apikeys/{id}/',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_rotate_account_scoped_pat' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RotateAccountScopedPat',
  'type' => 'write',
  'name' => 'Rotate Account Scoped PAT',
  'description' => 'Rotate Account Scoped PAT Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/users/{user_id}/account-apikeys/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_delete_account_scoped_pat' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DeleteAccountScopedPat',
  'type' => 'write',
  'name' => 'Delete Account Scoped PAT',
  'description' => 'Delete Account Scoped PAT Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/users/{user_id}/account-apikeys/{id}/',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_webhooks_event' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveWebhooksEvent',
  'type' => 'read',
  'name' => 'Retrieve Webhooks Event',
  'description' => 'Retrieve Webhooks Event Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/webhooks/event/{event_id} Get a specific event given an event_id. This endpoint is deprecated and should not be called anymore.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_webhooks_event_receipts' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListWebhooksEventReceipts',
  'type' => 'read',
  'name' => 'List Webhooks Event Receipts',
  'description' => 'List Webhooks Event Receipts Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/webhooks/event/{event_id}/receipts Get all receipts for a given event id',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_retrieve_webhooks_receipt' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveWebhooksReceipt',
  'type' => 'read',
  'name' => 'Retrieve Webhooks Receipt',
  'description' => 'Retrieve Webhooks Receipt Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/webhooks/receipt/{receipt_id} Get a specific receipt given its id. This endpoint is deprecated and should not be called anymore.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_retrieve_webhooks_subscription' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveWebhooksSubscription',
  'type' => 'read',
  'name' => 'Retrieve Webhooks Subscription',
  'description' => 'Retrieve Webhooks Subscription Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/webhooks/subscription/{subscription_id} Get a specific subscription with a subscription id',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_webhooks_subscription' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateWebhooksSubscription',
  'type' => 'write',
  'name' => 'Update Webhooks Subscription',
  'description' => 'Update Webhooks Subscription Official dbt Cloud v3 endpoint: PUT /api/v3/accounts/{account_id}/webhooks/subscription/{subscription_id} Edit a subscription given a subscription id',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_destroy_webhooks_subscription' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DestroyWebhooksSubscription',
  'type' => 'write',
  'name' => 'Destroy Webhooks Subscription',
  'description' => 'Destroy Webhooks Subscription Official dbt Cloud v3 endpoint: DELETE /api/v3/accounts/{account_id}/webhooks/subscription/{subscription_id} Delete a specific subscription',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_list_webhooks_subscription_event_receipt' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListWebhooksSubscriptionEventReceipt',
  'type' => 'read',
  'name' => 'List Webhooks Subscription Event Receipt',
  'description' => 'List Webhooks Subscription Event Receipt Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/webhooks/subscription/{subscription_id}/event/{event_id}/receipt Get the receipt for a given subscription id and event id. This endpo',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_webhooks_events' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListWebhooksEvents',
  'type' => 'read',
  'name' => 'List Webhooks Events',
  'description' => 'List Webhooks Events Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/webhooks/subscription/{subscription_id}/events Get all events for a specific subscription',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_test_webhooks_subscription' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3TestWebhooksSubscription',
  'type' => 'read',
  'name' => 'Test Webhooks Subscription',
  'description' => 'Test Webhooks Subscription Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/webhooks/subscription/{subscription_id}/test Test the client endpoint for a given subscription',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_webhooks_subscriptions' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListWebhooksSubscriptions',
  'type' => 'read',
  'name' => 'List Webhooks Subscriptions',
  'description' => 'List Webhooks Subscriptions Official dbt Cloud v3 endpoint: GET /api/v3/accounts/{account_id}/webhooks/subscriptions Given an account id list all webhook subscriptions',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_webhooks_subscription' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateWebhooksSubscription',
  'type' => 'write',
  'name' => 'Create Webhooks Subscription',
  'description' => 'Create Webhooks Subscription Official dbt Cloud v3 endpoint: POST /api/v3/accounts/{account_id}/webhooks/subscriptions Create a new webhook subscription',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_retrieve_adapter_schema' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3RetrieveAdapterSchema',
  'type' => 'read',
  'name' => 'Retrieve Adapter Schema',
  'description' => 'Retrieve Adapter Schema Official dbt Cloud v3 endpoint: GET /api/v3/adapter-schema/ \" Fetch the schema for a given adapter. The schema will include details on available fields for connections and credentials. Notes: - salesforce_v0 is curre',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_list_user_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3ListUserCredentials',
  'type' => 'read',
  'name' => 'List User Credentials',
  'description' => 'List User Credentials Official dbt Cloud v3 endpoint: GET /api/v3/users/{user_id}/credentials/ List the development credentials associated with a given user.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_create_user_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3CreateUserCredentials',
  'type' => 'write',
  'name' => 'Create User Credentials',
  'description' => 'Create User Credentials Official dbt Cloud v3 endpoint: POST /api/v3/users/{user_id}/credentials/ Associate a set of development credentials with a given user.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_get_user_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3GetUserCredentials',
  'type' => 'read',
  'name' => 'Get User Credentials',
  'description' => 'Get User Credentials Official dbt Cloud v3 endpoint: GET /api/v3/users/{user_id}/credentials/{id}/ Get a development credentials association for a given user.',
  'icon' => 'ph:git-branch',
),
  'dbt_cloud_v3_update_user_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3UpdateUserCredentials',
  'type' => 'write',
  'name' => 'Update User Credentials',
  'description' => 'Update User Credentials Official dbt Cloud v3 endpoint: POST /api/v3/users/{user_id}/credentials/{id}/ Update which development credentials are associated with a specific user.',
  'icon' => 'ph:pencil-simple',
),
  'dbt_cloud_v3_delete_user_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\DbtCloud\\Tools\\DbtCloudV3DeleteUserCredentials',
  'type' => 'write',
  'name' => 'Delete User Credentials',
  'description' => 'Delete User Credentials Official dbt Cloud v3 endpoint: DELETE /api/v3/users/{user_id}/credentials/{id}/ Delete a development credentials / user association.',
  'icon' => 'ph:pencil-simple',
),
]; }
    public function isIntegration(): bool { return true; } public function createTool(string $class, array $context = []): Tool { return new $class($this->resolveService($context)); } public function scriptDocsPath(): ?string { return __DIR__.'/../script-docs/dbt-cloud.md'; }
    /** @param  array<string, mixed>  $context  Optional account context from the host. */ private function resolveService(array $context = []): DbtCloudService { $account=$context['account']??null; if($account!==null){$creds=app(CredentialResolver::class); return new DbtCloudService(accessToken:$creds->get('dbt-cloud','access_token','',$account), baseUrl:$creds->get('dbt-cloud','url','https://cloud.getdbt.com',$account));} return app(DbtCloudService::class); }
}
