<?php

namespace OpenCompany\Integrations\SonarQube\Tools;

/**
 * Search for a collection of relevant rules matching a specified query..
 *
 * Maps to the official SonarQube Web API endpoint GET /api/rules/search.
 */
class SonarQubeRulesSearch extends AbstractSonarQubeTool
{
    protected const NAME = 'sonarqube_rules_search';
    protected const DESCRIPTION = 'Search for a collection of relevant rules matching a specified query.

Official SonarQube Web API endpoint: GET /api/rules/search.';
    protected const PARAMETERS = array (
      'activation' => array (
        'type' => 'string',
        'description' => 'Filter rules that are activated or deactivated on the selected Quality profile. Ignored if the parameter \'qprofile\' is not set.',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'active_impact_severities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of Activation Software Quality Severities, i.e the impact severity of rules in Quality profiles.',
        'required' => false,
        'enum' => array (
          'INFO',
          'LOW',
          'MEDIUM',
          'HIGH',
          'BLOCKER',
        ),
      ),
      'active_severities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of activation severities, i.e the severity of rules in Quality profiles.',
        'required' => false,
        'enum' => array (
          'INFO',
          'MINOR',
          'MAJOR',
          'CRITICAL',
          'BLOCKER',
        ),
      ),
      'asc' => array (
        'type' => 'string',
        'description' => 'Ascending sort',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'available_since' => array (
        'type' => 'string',
        'description' => 'Filters rules added since date. Format is yyyy-MM-dd',
        'required' => false,
      ),
      'clean_code_attribute_categories' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of Clean Code Attribute Categories',
        'required' => false,
        'enum' => array (
          'ADAPTABLE',
          'CONSISTENT',
          'INTENTIONAL',
          'RESPONSIBLE',
        ),
      ),
      'compliance_standards' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of compliance standards',
        'required' => false,
      ),
      'cwe' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of CWE identifiers. Use \'unknown\' to select rules not associated to any CWE.',
        'required' => false,
      ),
      'f' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of additional fields to be returned in the response. All the fields are returned by default, except actives.',
        'required' => false,
        'enum' => array (
          'actives',
          'cleanCodeAttribute',
          'createdAt',
          'debtRemFn',
          'defaultDebtRemFn',
          'defaultRemFn',
          'deprecatedKeys',
          'descriptionSections',
          'educationPrinciples',
          'gapDescription',
          'htmlDesc',
          'htmlNote',
          'internalKey',
          'isExternal',
          'isTemplate',
          'lang',
          'langName',
          'mdDesc',
          'mdNote',
          'name',
          'noteLogin',
          'params',
          'remFn',
          'remFnOverloaded',
          'repo',
          'scope',
          'severity',
          'status',
          'sysTags',
          'tags',
          'templateKey',
          'updatedAt',
        ),
      ),
      'facets' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of the facets to be computed. No facet is computed by default.',
        'required' => false,
        'enum' => array (
          'languages',
          'repositories',
          'tags',
          'severities',
          'active_severities',
          'statuses',
          'types',
          'true',
          'cwe',
          'owaspTop10',
          'owaspTop10-2021',
          'owaspMobileTop10-2024',
          'sansTop25',
          'sonarsourceSecurity',
          'cleanCodeAttributeCategories',
          'impactSeverities',
          'impactSoftwareQualities',
          'active_impactSeverities',
          'complianceStandards',
        ),
      ),
      'impact_severities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of Software Quality Severities',
        'required' => false,
        'enum' => array (
          'INFO',
          'LOW',
          'MEDIUM',
          'HIGH',
          'BLOCKER',
        ),
      ),
      'impact_software_qualities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of Software Qualities',
        'required' => false,
        'enum' => array (
          'MAINTAINABILITY',
          'RELIABILITY',
          'SECURITY',
        ),
      ),
      'include_external' => array (
        'type' => 'string',
        'description' => 'Include external engine rules in the results',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'inheritance' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of values of inheritance for a rule within a quality profile. Used only if the parameter \'activation\' is set.',
        'required' => false,
        'enum' => array (
          'NONE',
          'INHERITED',
          'OVERRIDES',
        ),
      ),
      'is_template' => array (
        'type' => 'string',
        'description' => 'Filter template rules',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'languages' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of languages',
        'required' => false,
      ),
      'owasp_mobile_top10_2024' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Mobile Top 10 2024 lowercase categories.',
        'required' => false,
        'enum' => array (
          'm1',
          'm2',
          'm3',
          'm4',
          'm5',
          'm6',
          'm7',
          'm8',
          'm9',
          'm10',
        ),
      ),
      'owasp_top10' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Top 10 2017 lowercase categories.',
        'required' => false,
        'enum' => array (
          'a1',
          'a2',
          'a3',
          'a4',
          'a5',
          'a6',
          'a7',
          'a8',
          'a9',
          'a10',
        ),
      ),
      'owasp_top10_2021' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Top 10 2021 lowercase categories.',
        'required' => false,
        'enum' => array (
          'a1',
          'a2',
          'a3',
          'a4',
          'a5',
          'a6',
          'a7',
          'a8',
          'a9',
          'a10',
        ),
      ),
      'p' => array (
        'type' => 'string',
        'description' => '1-based page number',
        'required' => false,
      ),
      'prioritized_rule' => array (
        'type' => 'string',
        'description' => 'Filter on prioritized rules. Ignored if the parameter \'qprofile\' is not set.',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'ps' => array (
        'type' => 'string',
        'description' => 'Page size. Must be greater than 0 and less or equal than 500',
        'required' => false,
      ),
      'q' => array (
        'type' => 'string',
        'description' => 'UTF-8 search query',
        'required' => false,
      ),
      'qprofile' => array (
        'type' => 'string',
        'description' => 'Quality profile key to filter on. Only rules of the same language as this profile are returned. By default only rules activated in this profile are returned. You can change that using the \'activation\' parameter.',
        'required' => false,
      ),
      'repositories' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of repositories',
        'required' => false,
      ),
      'rule_key' => array (
        'type' => 'string',
        'description' => 'Key of rule to search for',
        'required' => false,
      ),
      's' => array (
        'type' => 'string',
        'description' => 'Sort field',
        'required' => false,
        'enum' => array (
          'name',
          'createdAt',
          'updatedAt',
          'key',
        ),
      ),
      'sans_top25' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of SANS Top 25 categories.',
        'required' => false,
        'enum' => array (
          'insecure-interaction',
          'risky-resource',
          'porous-defenses',
        ),
      ),
      'severities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of default severities. Not the same than severity of rules in Quality profiles.',
        'required' => false,
        'enum' => array (
          'INFO',
          'MINOR',
          'MAJOR',
          'CRITICAL',
          'BLOCKER',
        ),
      ),
      'sonarsource_security' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of SonarSource security categories. Use \'others\' to select rules not associated with any category',
        'required' => false,
        'enum' => array (
          'malicious-dependencies',
          'buffer-overflow',
          'sql-injection',
          'rce',
          'object-injection',
          'command-injection',
          'path-traversal-injection',
          'ldap-injection',
          'xpath-injection',
          'log-injection',
          'xxe',
          'xss',
          'dos',
          'ssrf',
          'csrf',
          'http-response-splitting',
          'open-redirect',
          'weak-cryptography',
          'auth',
          'insecure-conf',
          'file-manipulation',
          'encrypt-data',
          'traceability',
          'permission',
          'others',
        ),
      ),
      'statuses' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of status codes',
        'required' => false,
        'enum' => array (
          'BETA',
          'DEPRECATED',
          'READY',
          'REMOVED',
        ),
      ),
      'tags' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of tags. Returned rules match any of the tags (OR operator)',
        'required' => false,
      ),
      'template_key' => array (
        'type' => 'string',
        'description' => 'Key of the template rule to filter on. Used to search for the custom rules based on this template.',
        'required' => false,
      ),
      'types' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of types. Returned rules match any of the tags (OR operator)',
        'required' => false,
        'enum' => array (
          'CODE_SMELL',
          'BUG',
          'VULNERABILITY',
          'SECURITY_HOTSPOT',
        ),
      ),
    );
    protected const METHOD = 'GET';
    protected const PATH = '/api/rules/search';
    protected const PARAM_MAP = array (
      'activation' => 'activation',
      'active_impactSeverities' => 'active_impact_severities',
      'active_severities' => 'active_severities',
      'asc' => 'asc',
      'available_since' => 'available_since',
      'cleanCodeAttributeCategories' => 'clean_code_attribute_categories',
      'complianceStandards' => 'compliance_standards',
      'cwe' => 'cwe',
      'f' => 'f',
      'facets' => 'facets',
      'impactSeverities' => 'impact_severities',
      'impactSoftwareQualities' => 'impact_software_qualities',
      'include_external' => 'include_external',
      'inheritance' => 'inheritance',
      'is_template' => 'is_template',
      'languages' => 'languages',
      'owaspMobileTop10-2024' => 'owasp_mobile_top10_2024',
      'owaspTop10' => 'owasp_top10',
      'owaspTop10-2021' => 'owasp_top10_2021',
      'p' => 'p',
      'prioritizedRule' => 'prioritized_rule',
      'ps' => 'ps',
      'q' => 'q',
      'qprofile' => 'qprofile',
      'repositories' => 'repositories',
      'rule_key' => 'rule_key',
      's' => 's',
      'sansTop25' => 'sans_top25',
      'severities' => 'severities',
      'sonarsourceSecurity' => 'sonarsource_security',
      'statuses' => 'statuses',
      'tags' => 'tags',
      'template_key' => 'template_key',
      'types' => 'types',
    );
}
