<?php

namespace OpenCompany\Integrations\SonarQube\Tools;

/**
 * Restore a quality profile using an XML file. The restored profile name is taken from the backup file, so if a profile with the same name and language already exists, it will be overwritten. Requires to be logged in and the 'Administer Quality Profiles' permission..
 *
 * Maps to the official SonarQube Web API endpoint POST /api/qualityprofiles/restore.
 */
class SonarQubeQualityprofilesRestore extends AbstractSonarQubeTool
{
    protected const NAME = 'sonarqube_qualityprofiles_restore';
    protected const DESCRIPTION = 'Restore a quality profile using an XML file. The restored profile name is taken from the backup file, so if a profile with the same name and language already exists, it will be overwritten. Requires to be logged in and the \'Administer Quality Profiles\' permission.

Official SonarQube Web API endpoint: POST /api/qualityprofiles/restore.';
    protected const PARAMETERS = array (
      'backup' => array (
        'type' => 'string',
        'description' => 'A profile backup file in XML format, as generated by api/qualityprofiles/backup or the former api/profiles/backup.',
        'required' => true,
      ),
    );
    protected const METHOD = 'POST';
    protected const PATH = '/api/qualityprofiles/restore';
    protected const PARAM_MAP = array (
      'backup' => 'backup',
    );
}
