<?php

namespace OpenCompany\Integrations\SonarQube\Tools;

/**
 * Search for issues. Requires the 'Browse' permission on the specified project(s). For applications, it also requires 'Browse' permission on its child projects. When issue indexing is in progress returns 503 service unavailable HTTP code..
 *
 * Maps to the official SonarQube Web API endpoint GET /api/issues/search.
 */
class SonarQubeIssuesSearch extends AbstractSonarQubeTool
{
    protected const NAME = 'sonarqube_issues_search';
    protected const DESCRIPTION = 'Search for issues. Requires the \'Browse\' permission on the specified project(s). For applications, it also requires \'Browse\' permission on its child projects. When issue indexing is in progress returns 503 service unavailable HTTP code.

Official SonarQube Web API endpoint: GET /api/issues/search.';
    protected const PARAMETERS = array (
      'additional_fields' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of the optional fields to be returned in response. Action plans are dropped in 5.5, it is not returned in the response.',
        'required' => false,
        'enum' => array (
          '_all',
          'comments',
          'languages',
          'rules',
          'ruleDescriptionContextKey',
          'transitions',
          'actions',
          'users',
        ),
      ),
      'asc' => array (
        'type' => 'string',
        'description' => 'Ascending sort',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'assigned' => array (
        'type' => 'string',
        'description' => 'To retrieve assigned or unassigned issues',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'assignees' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of assignee logins. The value \'__me__\' can be used as a placeholder for user who performs the request',
        'required' => false,
      ),
      'author' => array (
        'type' => 'string',
        'description' => 'SCM accounts. To set several values, the parameter must be called once for each value.',
        'required' => false,
      ),
      'branch' => array (
        'type' => 'string',
        'description' => 'Branch key. Not available in the community edition.',
        'required' => false,
      ),
      'casa' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of CASA categories.',
        'required' => false,
      ),
      'clean_code_attribute_categories' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of Clean Code Attribute Categories',
        'required' => false,
        'enum' => array (
          'ADAPTABLE',
          'CONSISTENT',
          'INTENTIONAL',
          'RESPONSIBLE',
        ),
      ),
      'code_variants' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of code variants.',
        'required' => false,
      ),
      'compliance_standards' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of compliance standards',
        'required' => false,
      ),
      'components' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of component keys. Retrieve issues associated to a specific list of components (and all its descendants). A component can be a portfolio, project, module, directory or file.',
        'required' => false,
      ),
      'created_after' => array (
        'type' => 'string',
        'description' => 'To retrieve issues created after the given date (inclusive). Either a date (use \'timeZone\' attribute or it will default to server timezone) or datetime can be provided. If this parameter is set, createdInLast must not be set',
        'required' => false,
      ),
      'created_at' => array (
        'type' => 'string',
        'description' => 'Datetime to retrieve issues created during a specific analysis',
        'required' => false,
      ),
      'created_before' => array (
        'type' => 'string',
        'description' => 'To retrieve issues created before the given date (exclusive). Either a date (use \'timeZone\' attribute or it will default to server timezone) or datetime can be provided.',
        'required' => false,
      ),
      'created_in_last' => array (
        'type' => 'string',
        'description' => 'To retrieve issues created during a time span before the current time (exclusive). Accepted units are \'y\' for year, \'m\' for month, \'w\' for week and \'d\' for day. If this parameter is set, createdAfter must not be set',
        'required' => false,
      ),
      'cwe' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of CWE identifiers. Use \'unknown\' to select issues not associated to any CWE.',
        'required' => false,
      ),
      'facets' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of the facets to be computed. No facet is computed by default.',
        'required' => false,
        'enum' => array (
          'projects',
          'files',
          'assigned_to_me',
          'severities',
          'statuses',
          'resolutions',
          'rules',
          'assignees',
          'author',
          'directories',
          'scopes',
          'languages',
          'tags',
          'types',
          'pciDss-3.2',
          'pciDss-4.0',
          'owaspAsvs-4.0',
          'owaspMobileTop10-2024',
          'owaspTop10',
          'owaspTop10-2021',
          'stig-ASD_V5R3',
          'casa',
          'sansTop25',
          'cwe',
          'createdAt',
          'sonarsourceSecurity',
          'codeVariants',
          'cleanCodeAttributeCategories',
          'impactSoftwareQualities',
          'impactSeverities',
          'issueStatuses',
          'prioritizedRule',
          'complianceStandards',
          'fromSonarQubeUpdate',
          'linkedTicketStatus',
        ),
      ),
      'fixed_in_pull_request' => array (
        'type' => 'string',
        'description' => 'Pull request id to filter issues that would be fixed in the specified project or branch by the pull request. Should not be used together with + \'pullRequest\'. At least the \'components\' must be be specified when this param is used. Not available in the community edition.',
        'required' => false,
      ),
      'from_sonar_qube_update' => array (
        'type' => 'string',
        'description' => 'To match issues detected because of SonarQube updates',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'impact_severities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of Software Quality Severities',
        'required' => false,
        'enum' => array (
          'INFO',
          'LOW',
          'MEDIUM',
          'HIGH',
          'BLOCKER',
        ),
      ),
      'impact_software_qualities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of Software Qualities',
        'required' => false,
        'enum' => array (
          'MAINTAINABILITY',
          'RELIABILITY',
          'SECURITY',
        ),
      ),
      'in_new_code_period' => array (
        'type' => 'string',
        'description' => 'To retrieve issues created in the new code period. If this parameter is set to a truthy value, createdAfter must not be set and one component uuid or key must be provided. This parameter is ignored if the requested component is Application or Portfolio.',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'issue_statuses' => array (
        'type' => 'string',
        'description' => 'issueStatuses parameter.',
        'required' => false,
        'enum' => array (
          'OPEN',
          'CONFIRMED',
          'FALSE_POSITIVE',
          'ACCEPTED',
          'FIXED',
          'IN_SANDBOX',
        ),
      ),
      'issues' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of issue keys',
        'required' => false,
      ),
      'languages' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of languages. Available since 4.4',
        'required' => false,
      ),
      'linked_ticket_status' => array (
        'type' => 'string',
        'description' => 'Has linked JIRA work item',
        'required' => false,
        'enum' => array (
          'LINKED',
          'NOT_LINKED',
        ),
      ),
      'on_component_only' => array (
        'type' => 'string',
        'description' => 'Return only issues at a component\'s level, not on its descendants (modules, directories, files, etc). This parameter is only considered when componentKeys is set.',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'owasp_asvs_4_0' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP ASVS v4.0 categories.',
        'required' => false,
      ),
      'owasp_asvs_level' => array (
        'type' => 'string',
        'description' => 'Level of OWASP ASVS categories.',
        'required' => false,
        'enum' => array (
          '1',
          '2',
          '3',
        ),
      ),
      'owasp_mobile_top10_2024' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Mobile Top 10 2024 lowercase categories.',
        'required' => false,
        'enum' => array (
          'm1',
          'm2',
          'm3',
          'm4',
          'm5',
          'm6',
          'm7',
          'm8',
          'm9',
          'm10',
        ),
      ),
      'owasp_top10' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Top 10 2017 lowercase categories.',
        'required' => false,
        'enum' => array (
          'a1',
          'a2',
          'a3',
          'a4',
          'a5',
          'a6',
          'a7',
          'a8',
          'a9',
          'a10',
        ),
      ),
      'owasp_top10_2021' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of OWASP Top 10 2021 lowercase categories.',
        'required' => false,
        'enum' => array (
          'a1',
          'a2',
          'a3',
          'a4',
          'a5',
          'a6',
          'a7',
          'a8',
          'a9',
          'a10',
        ),
      ),
      'p' => array (
        'type' => 'string',
        'description' => '1-based page number',
        'required' => false,
      ),
      'pci_dss_3_2' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of PCI DSS v3.2 categories.',
        'required' => false,
      ),
      'pci_dss_4_0' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of PCI DSS v4.0 categories.',
        'required' => false,
      ),
      'prioritized_rule' => array (
        'type' => 'string',
        'description' => 'To match issues with prioritized rule or not',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'ps' => array (
        'type' => 'string',
        'description' => 'Page size. Must be greater than 0 and less or equal than 500',
        'required' => false,
      ),
      'pull_request' => array (
        'type' => 'string',
        'description' => 'Pull request id. Not available in the community edition.',
        'required' => false,
      ),
      'resolutions' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of resolutions',
        'required' => false,
        'enum' => array (
          'FALSE-POSITIVE',
          'WONTFIX',
          'FIXED',
          'REMOVED',
        ),
      ),
      'resolved' => array (
        'type' => 'string',
        'description' => 'To match resolved or unresolved issues',
        'required' => false,
        'enum' => array (
          'true',
          'false',
          'yes',
          'no',
        ),
      ),
      'rules' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of coding rule keys. Format is :',
        'required' => false,
      ),
      's' => array (
        'type' => 'string',
        'description' => 'Sort field',
        'required' => false,
        'enum' => array (
          'UPDATE_DATE',
          'CREATION_DATE',
          'CLOSE_DATE',
          'SEVERITY',
          'STATUS',
          'FILE_LINE',
          'HOTSPOTS',
        ),
      ),
      'sans_top25' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of SANS Top 25 categories.',
        'required' => false,
        'enum' => array (
          'insecure-interaction',
          'risky-resource',
          'porous-defenses',
        ),
      ),
      'scopes' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of scopes. Available since 8.5',
        'required' => false,
        'enum' => array (
          'MAIN',
          'TEST',
        ),
      ),
      'severities' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of severities',
        'required' => false,
        'enum' => array (
          'INFO',
          'MINOR',
          'MAJOR',
          'CRITICAL',
          'BLOCKER',
        ),
      ),
      'sonarsource_security' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of SonarSource security categories. Use \'others\' to select issues not associated with any category',
        'required' => false,
        'enum' => array (
          'malicious-dependencies',
          'buffer-overflow',
          'sql-injection',
          'rce',
          'object-injection',
          'command-injection',
          'path-traversal-injection',
          'ldap-injection',
          'xpath-injection',
          'log-injection',
          'xxe',
          'xss',
          'dos',
          'ssrf',
          'csrf',
          'http-response-splitting',
          'open-redirect',
          'weak-cryptography',
          'auth',
          'insecure-conf',
          'file-manipulation',
          'encrypt-data',
          'traceability',
          'permission',
          'others',
        ),
      ),
      'statuses' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of statuses',
        'required' => false,
        'enum' => array (
          'OPEN',
          'CONFIRMED',
          'REOPENED',
          'RESOLVED',
          'CLOSED',
          'IN_SANDBOX',
        ),
      ),
      'stig_asd_v5_r3' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of STIG V5R3 categories.',
        'required' => false,
      ),
      'tags' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of tags.',
        'required' => false,
      ),
      'time_zone' => array (
        'type' => 'string',
        'description' => 'To resolve dates passed to \'createdAfter\' or \'createdBefore\' (does not apply to datetime) and to compute creation date histogram',
        'required' => false,
      ),
      'types' => array (
        'type' => 'string',
        'description' => 'Comma-separated list of types.',
        'required' => false,
        'enum' => array (
          'CODE_SMELL',
          'BUG',
          'VULNERABILITY',
        ),
      ),
    );
    protected const METHOD = 'GET';
    protected const PATH = '/api/issues/search';
    protected const PARAM_MAP = array (
      'additionalFields' => 'additional_fields',
      'asc' => 'asc',
      'assigned' => 'assigned',
      'assignees' => 'assignees',
      'author' => 'author',
      'branch' => 'branch',
      'casa' => 'casa',
      'cleanCodeAttributeCategories' => 'clean_code_attribute_categories',
      'codeVariants' => 'code_variants',
      'complianceStandards' => 'compliance_standards',
      'components' => 'components',
      'createdAfter' => 'created_after',
      'createdAt' => 'created_at',
      'createdBefore' => 'created_before',
      'createdInLast' => 'created_in_last',
      'cwe' => 'cwe',
      'facets' => 'facets',
      'fixedInPullRequest' => 'fixed_in_pull_request',
      'fromSonarQubeUpdate' => 'from_sonar_qube_update',
      'impactSeverities' => 'impact_severities',
      'impactSoftwareQualities' => 'impact_software_qualities',
      'inNewCodePeriod' => 'in_new_code_period',
      'issueStatuses' => 'issue_statuses',
      'issues' => 'issues',
      'languages' => 'languages',
      'linkedTicketStatus' => 'linked_ticket_status',
      'onComponentOnly' => 'on_component_only',
      'owaspAsvs-4.0' => 'owasp_asvs_4_0',
      'owaspAsvsLevel' => 'owasp_asvs_level',
      'owaspMobileTop10-2024' => 'owasp_mobile_top10_2024',
      'owaspTop10' => 'owasp_top10',
      'owaspTop10-2021' => 'owasp_top10_2021',
      'p' => 'p',
      'pciDss-3.2' => 'pci_dss_3_2',
      'pciDss-4.0' => 'pci_dss_4_0',
      'prioritizedRule' => 'prioritized_rule',
      'ps' => 'ps',
      'pullRequest' => 'pull_request',
      'resolutions' => 'resolutions',
      'resolved' => 'resolved',
      'rules' => 'rules',
      's' => 's',
      'sansTop25' => 'sans_top25',
      'scopes' => 'scopes',
      'severities' => 'severities',
      'sonarsourceSecurity' => 'sonarsource_security',
      'statuses' => 'statuses',
      'stig-ASD_V5R3' => 'stig_asd_v5_r3',
      'tags' => 'tags',
      'timeZone' => 'time_zone',
      'types' => 'types',
    );
}
