<?php

namespace OpenCompany\IntegrationCore\Contracts;

/**
 * Host-provided context for trigger lifecycle methods.
 *
 * The integration repo defines what it needs; the host application
 * provides the implementation. This keeps integration packages
 * decoupled from any specific database, queue, or HTTP layer.
 */
interface TriggerContext
{
    /**
     * The webhook URL the external service should POST events to.
     *
     * Generated by the host and unique per trigger subscription.
     * Only meaningful for webhook triggers; polling triggers may ignore this.
     */
    public function webhookUrl(): string;

    /**
     * Key-value store scoped to this trigger subscription.
     *
     * Use to persist: webhook IDs, webhook secrets, polling cursors,
     * last-seen timestamps, or any state needed across invocations.
     */
    public function store(): TriggerStore;

    /**
     * The trigger configuration values provided by the user when enabling.
     *
     * Keys correspond to the trigger's parameters() definition.
     * E.g., ['events' => ['taskCreated', 'taskUpdated'], 'space_id' => '123']
     *
     * @return array<string, mixed>
     */
    public function config(): array;
}
