<?php

namespace OpenCompany\Integrations\Logto\Tools;

/**
 * Delete custom phrase.
 *
 * Maps to DELETE /api/custom-phrases/{languageTag} in the official Logto OpenAPI source.
 */
class LogtoDeleteCustomPhrase extends AbstractLogtoTool
{
    protected const OPERATION = array (
  'slug' => 'logto_delete_custom_phrase',
  'class' => 'LogtoDeleteCustomPhrase',
  'method' => 'DELETE',
  'path' => '/api/custom-phrases/{languageTag}',
  'operation_id' => 'DeleteCustomPhrase',
  'summary' => 'Delete custom phrase',
  'description' => 'Delete custom phrases for the specified language tag.',
  'parameters' =>
  array (
    'language_tag' =>
    array (
      'type' => 'string',
      'required' => true,
      'description' => 'Official Logto path parameter `languageTag`.',
      'enum' =>
      array (
        0 => 'af-ZA',
        1 => 'am-ET',
        2 => 'ar',
        3 => 'ar-AR',
        4 => 'as-IN',
        5 => 'az-AZ',
        6 => 'be-BY',
        7 => 'bg-BG',
        8 => 'bn-IN',
        9 => 'br-FR',
        10 => 'bs-BA',
        11 => 'ca-ES',
        12 => 'cb-IQ',
        13 => 'co-FR',
        14 => 'cs',
        15 => 'cs-CZ',
        16 => 'cx-PH',
        17 => 'cy-GB',
        18 => 'da-DK',
        19 => 'de',
        20 => 'de-DE',
        21 => 'el-GR',
        22 => 'en',
        23 => 'en-GB',
        24 => 'en-US',
        25 => 'eo-EO',
        26 => 'es',
        27 => 'es-ES',
        28 => 'es-419',
        29 => 'et-EE',
        30 => 'eu-ES',
        31 => 'fa-IR',
        32 => 'ff-NG',
        33 => 'fi',
        34 => 'fi-FI',
        35 => 'fo-FO',
        36 => 'fr',
        37 => 'fr-CA',
        38 => 'fr-FR',
        39 => 'fy-NL',
        40 => 'ga-IE',
        41 => 'gl-ES',
        42 => 'gn-PY',
        43 => 'gu-IN',
        44 => 'ha-NG',
        45 => 'he-IL',
        46 => 'hi-IN',
        47 => 'hr-HR',
        48 => 'ht-HT',
        49 => 'hu-HU',
        50 => 'hy-AM',
        51 => 'id-ID',
        52 => 'ik-US',
        53 => 'is-IS',
        54 => 'it',
        55 => 'it-IT',
        56 => 'iu-CA',
        57 => 'ja',
        58 => 'ja-JP',
        59 => 'ja-KS',
        60 => 'jv-ID',
        61 => 'ka-GE',
        62 => 'kk-KZ',
        63 => 'km-KH',
        64 => 'kn-IN',
        65 => 'ko',
        66 => 'ko-KR',
        67 => 'ku-TR',
        68 => 'ky-KG',
        69 => 'lo-LA',
        70 => 'lt-LT',
        71 => 'lv-LV',
        72 => 'mg-MG',
        73 => 'mk-MK',
        74 => 'ml-IN',
        75 => 'mn-MN',
        76 => 'mr-IN',
        77 => 'ms-MY',
        78 => 'mt-MT',
        79 => 'my-MM',
        80 => 'nb-NO',
        81 => 'ne-NP',
        82 => 'nl',
        83 => 'nl-BE',
        84 => 'nl-NL',
        85 => 'nn-NO',
        86 => 'or-IN',
        87 => 'pa-IN',
        88 => 'pl-PL',
        89 => 'ps-AF',
        90 => 'pt',
        91 => 'pt-BR',
        92 => 'pt-PT',
        93 => 'ro-RO',
        94 => 'ru',
        95 => 'ru-RU',
        96 => 'rw-RW',
        97 => 'sc-IT',
        98 => 'si-LK',
        99 => 'sk-SK',
        100 => 'sl-SI',
        101 => 'sn-ZW',
        102 => 'sq-AL',
        103 => 'sr-RS',
        104 => 'sv',
        105 => 'sv-SE',
        106 => 'sw-KE',
        107 => 'sy-SY',
        108 => 'sz-PL',
        109 => 'ta-IN',
        110 => 'te-IN',
        111 => 'tg-TJ',
        112 => 'th',
        113 => 'th-TH',
        114 => 'tl-PH',
        115 => 'tr',
        116 => 'tr-TR',
        117 => 'tt-RU',
        118 => 'tz-MA',
        119 => 'uk-UA',
        120 => 'ur-PK',
        121 => 'uz-UZ',
        122 => 'vi-VN',
        123 => 'zh',
        124 => 'zh-CN',
        125 => 'zh-HK',
        126 => 'zh-MO',
        127 => 'zh-TW',
        128 => 'zz-TR',
      ),
    ),
  ),
  'path_params' =>
  array (
    'languageTag' => 'language_tag',
  ),
  'query_params' =>
  array (
  ),
  'header_params' =>
  array (
  ),
  'body_required' => false,
  'content_type' => NULL,
  'type' => 'write',
);
}
