<?php

namespace OpenCompany\Integrations\Logto\Tools;

/**
 * Verify passkey sign-in WebAuthn authentication.
 *
 * Maps to POST /api/experience/verification/sign-in-passkey/authentication/verify in the official Logto OpenAPI source.
 */
class LogtoVerifySignInPasskeyAuthentication extends AbstractLogtoTool
{
    protected const OPERATION = array (
  'slug' => 'logto_verify_sign_in_passkey_authentication',
  'class' => 'LogtoVerifySignInPasskeyAuthentication',
  'method' => 'POST',
  'path' => '/api/experience/verification/sign-in-passkey/authentication/verify',
  'operation_id' => 'VerifySignInPasskeyAuthentication',
  'summary' => 'Verify passkey sign-in WebAuthn authentication',
  'description' => 'Verify the passkey sign-in WebAuthn authentication response against the stored authentication challenge. When `verificationId` is provided, it verifies against the challenge generated by the identifier-based authentication endpoint. When omitted, it verifies against the preflight authentication options stored in the interaction. Upon successful verification, the verification record will be marked as verified and the user will be resolved by the credential if not provided earlier.',
  'parameters' =>
  array (
    'body' =>
    array (
      'type' => 'object',
      'required' => true,
      'description' => 'Request body matching the official Logto OpenAPI schema for this endpoint.',
    ),
  ),
  'path_params' =>
  array (
  ),
  'query_params' =>
  array (
  ),
  'header_params' =>
  array (
  ),
  'body_required' => true,
  'content_type' => 'application/json',
  'type' => 'write',
);
}
