<?php

namespace OpenCompany\Integrations\ClickHouseCloud;

use Illuminate\Support\Facades\Http;
use OpenCompany\IntegrationCore\Contracts\ConfigurableIntegration;
use OpenCompany\IntegrationCore\Contracts\CredentialResolver;
use OpenCompany\IntegrationCore\Contracts\HasIntegrationCapabilities;
use OpenCompany\IntegrationCore\Contracts\Tool;
use OpenCompany\IntegrationCore\Contracts\ToolProvider;

/**
 * Tool catalog and configuration metadata for ClickHouse Cloud.
 *
 * Exposes the official ClickHouse Cloud OpenAPI operation set as endpoint-specific
 * agent tools and resolves account-specific API keys in multi-account hosts.
 */
class ClickHouseCloudToolProvider implements ToolProvider, ConfigurableIntegration, HasIntegrationCapabilities
{
    /** @return array<string, mixed> */ public function integrationCapabilities(): array { return ['auth'=>['strategy'=>'basic','legacy_auth_type'=>'api_key','credential_mode'=>'secret_pair','setup_flows'=>['manual_secret'],'requires_browser_for_setup'=>false,'refreshable'=>false,'token_keys'=>[],'notes'=>['Use the ClickHouse Cloud API key ID as the Basic auth username and key secret as the password.']],'host_availability'=>['web'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret'],'cli'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret','runtime_mode'=>'normal']],'runtime_requirements'=>[],'compatibility'=>['web_setup_supported'=>true,'web_runtime_supported'=>true,'cli_setup_supported'=>true,'cli_runtime_supported'=>true]]; }
    public function appName(): string { return 'clickhouse-cloud'; } public function appMeta(): array { return ['label'=>'ClickHouse Cloud','description'=>'Cloud organizations, services, backups, roles, API keys, metrics, and ClickStack resources','icon'=>'ph:database','logo'=>'simple-icons:clickhouse']; }
    public function integrationMeta(): array { return ['name'=>'ClickHouse Cloud','description'=>'Manage ClickHouse Cloud organizations, services, backups, roles, API keys, metrics, private endpoints, and ClickStack resources.','icon'=>'ph:database','logo'=>'simple-icons:clickhouse','category'=>'data','badge'=>'verified','docs_url'=>'https://api.clickhouse.cloud/v1']; }
    public function configSchema(): array { return [['key'=>'key_id','type'=>'text','label'=>'API Key ID','required'=>true],['key'=>'key_secret','type'=>'secret','label'=>'API Key Secret','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','placeholder'=>'https://api.clickhouse.cloud','default'=>'https://api.clickhouse.cloud']]; }
    /** @param  array<string, mixed>  $config  Credential and endpoint settings. @return array{success: bool, message?: string, error?: string} */ public function testConnection(array $config): array { $keyId=(string)($config['key_id']??''); $keySecret=(string)($config['key_secret']??''); $baseUrl=rtrim((string)($config['url']??'https://api.clickhouse.cloud'),'/'); if($keyId===''||$keySecret==='')return ['success'=>false,'error'=>'ClickHouse Cloud key ID and key secret are required.']; try{$response=Http::withHeaders(['Authorization'=>'Basic '.base64_encode($keyId.':'.$keySecret),'Accept'=>'application/json','Content-Type'=>'application/json'])->timeout(10)->get($baseUrl.'/v1/organizations'); if(!$response->successful())return ['success'=>false,'error'=>'ClickHouse Cloud API returned HTTP '.$response->status().'.']; return ['success'=>true,'message'=>'Connected to ClickHouse Cloud at '.$baseUrl.'.'];}catch(\Throwable $e){return ['success'=>false,'error'=>$e->getMessage()];} }
    public function validationRules(): array { return ['key_id'=>'required|string','key_secret'=>'required|string','url'=>'nullable|url']; } public function credentialFields(): array { return [['key'=>'key_id','type'=>'text','label'=>'API Key ID','required'=>true],['key'=>'key_secret','type'=>'secret','label'=>'API Key Secret','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','required'=>false,'default'=>'https://api.clickhouse.cloud']]; }
    public function tools(): array { return [
  'clickhouse_cloud_organization_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationGetList',
  'type' => 'read',
  'name' => 'Get list of available organizations',
  'description' => 'Get list of available organizations Official ClickHouse Cloud endpoint: GET /v1/organizations Returns a list with a single organization associated with the API key in the request.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_organization_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationGet',
  'type' => 'read',
  'name' => 'Get organization details',
  'description' => 'Get organization details Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId} Returns details of a single organization. In order to get the details, the auth key must belong to the organization.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_organization_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationUpdate',
  'type' => 'write',
  'name' => 'Update organization details',
  'description' => 'Update organization details Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId} Updates organization fields. Requires ADMIN auth key role.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_organization_prometheus_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationPrometheusGet',
  'type' => 'read',
  'name' => 'Get organization metrics',
  'description' => 'Get organization metrics Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/prometheus Returns prometheus metrics for all services in an organization.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_organization_roles_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationRolesGetList',
  'type' => 'read',
  'name' => 'List all available roles for an organization',
  'description' => 'List all available roles for an organization Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/roles Returns all available roles (system + custom) for an organization.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_organization_role_post' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationRolePost',
  'type' => 'write',
  'name' => 'Create a new role',
  'description' => 'Create a new role Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/roles Creates a new custom role for an organization with specified policies and actors.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_organization_role_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationRoleGet',
  'type' => 'read',
  'name' => 'Get role details',
  'description' => 'Get role details Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/roles/{roleId} Returns details for a specific role.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_organization_role_patch' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationRolePatch',
  'type' => 'write',
  'name' => 'Update a role',
  'description' => 'Update a role Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/roles/{roleId} Updates an existing custom role. System roles cannot be updated. All fields are optional - only provided fields will be updated.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_organization_role_delete' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationRoleDelete',
  'type' => 'write',
  'name' => 'Delete a role',
  'description' => 'Delete a role Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/roles/{roleId} Deletes an existing custom role. System roles cannot be deleted. This operation will remove the role and all its associated policies.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_instance_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstanceGetList',
  'type' => 'read',
  'name' => 'List of organization services',
  'description' => 'List of organization services Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services Returns a list of all services in the organization.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_instance_create' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstanceCreate',
  'type' => 'write',
  'name' => 'Create new service',
  'description' => 'Create new service Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/services Creates a new service in the organization, and returns the current service state and a password to access the service. The service is st',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_instance_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstanceGet',
  'type' => 'read',
  'name' => 'Get service details',
  'description' => 'Get service details Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId} Returns a service that belongs to the organization',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_instance_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstanceUpdate',
  'type' => 'write',
  'name' => 'Update service basic details',
  'description' => 'Update service basic details Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId} Updates basic service details like service name or IP access list.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_instance_delete' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstanceDelete',
  'type' => 'write',
  'name' => 'Delete service',
  'description' => 'Delete service Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/services/{serviceId} Deletes the service. The service must be in stopped state and is deleted asynchronously after this method call.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_instance_private_endpoint_config_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstancePrivateEndpointConfigGet',
  'type' => 'read',
  'name' => 'Get private endpoint configuration',
  'description' => 'Get private endpoint configuration Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/privateEndpointConfig Information required to set up a private endpoint',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_instance_query_endpoint_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstanceQueryEndpointGet',
  'type' => 'read',
  'name' => 'Get the service query endpoint for a given instance',
  'description' => 'Get the service query endpoint for a given instance Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/serviceQueryEndpoint Get the configuration for the service query endpoint that allows execut',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_instance_query_endpoint_upsert' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstanceQueryEndpointUpsert',
  'type' => 'write',
  'name' => 'Upsert the service query endpoint for a given instance',
  'description' => 'Upsert the service query endpoint for a given instance Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/services/{serviceId}/serviceQueryEndpoint Create the service query endpoint that allows executing queries via',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_instance_query_endpoint_delete' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstanceQueryEndpointDelete',
  'type' => 'write',
  'name' => 'Delete the service query endpoint for a given instance',
  'description' => 'Delete the service query endpoint for a given instance Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/services/{serviceId}/serviceQueryEndpoint Removes the service query endpoint.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_instance_state_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstanceStateUpdate',
  'type' => 'write',
  'name' => 'Update service state',
  'description' => 'Update service state Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId}/state Starts or stop service',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_instance_scaling_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstanceScalingUpdate',
  'type' => 'write',
  'name' => 'Update service auto scaling settings',
  'description' => 'Update service auto scaling settings Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId}/scaling Updates minimum and maximum total memory limits and idle mode scaling behavior for the service. T',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_instance_replica_scaling_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstanceReplicaScalingUpdate',
  'type' => 'write',
  'name' => 'Update service auto scaling settings',
  'description' => 'Update service auto scaling settings Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId}/replicaScaling Updates minimum and maximum memory limits per replica and idle mode scaling behavior for t',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_instance_password_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstancePasswordUpdate',
  'type' => 'write',
  'name' => 'Update service password',
  'description' => 'Update service password Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId}/password Sets a new password for the service',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_instance_private_endpoint_create' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstancePrivateEndpointCreate',
  'type' => 'write',
  'name' => 'Create a private endpoint',
  'description' => 'Create a private endpoint Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/services/{serviceId}/privateEndpoint Create a new private endpoint. The private endpoint will be associated with this service and organiza',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_instance_prometheus_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInstancePrometheusGet',
  'type' => 'read',
  'name' => 'Get service metrics',
  'description' => 'Get service metrics Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/prometheus Returns prometheus metrics for a service.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_service_clickhouse_settings_list_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudServiceClickhouseSettingsListGet',
  'type' => 'read',
  'name' => 'List ClickHouse settings',
  'description' => 'List ClickHouse settings Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings **Disclaimer:** This beta endpoint is evolving; the API contract may change. Returns the configured ',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_service_clickhouse_settings_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudServiceClickhouseSettingsUpdate',
  'type' => 'write',
  'name' => 'Update ClickHouse settings',
  'description' => 'Update ClickHouse settings Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings **Disclaimer:** This beta endpoint is evolving; the API contract may change. Updates one or more',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_service_clickhouse_settings_schema_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudServiceClickhouseSettingsSchemaGet',
  'type' => 'read',
  'name' => 'Get ClickHouse settings schema',
  'description' => 'Get ClickHouse settings schema Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings/schema **Disclaimer:** This beta endpoint is evolving; the API contract may change. Returns th',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_service_clickhouse_setting_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudServiceClickhouseSettingGet',
  'type' => 'read',
  'name' => 'Get ClickHouse setting',
  'description' => 'Get ClickHouse setting Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickhouseSettings/{settingName} **Disclaimer:** This beta endpoint is evolving; the API contract may change. Returns the',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_backup_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudBackupGetList',
  'type' => 'read',
  'name' => 'List of service backups',
  'description' => 'List of service backups Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/backups Returns a list of all backups for the service. The most recent backups comes first in the list.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_backup_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudBackupGet',
  'type' => 'read',
  'name' => 'Get backup details',
  'description' => 'Get backup details Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/backups/{backupId} Returns a single backup info.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_backup_configuration_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudBackupConfigurationGet',
  'type' => 'read',
  'name' => 'Get service backup configuration',
  'description' => 'Get service backup configuration Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/backupConfiguration Returns the service backup configuration.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_backup_configuration_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudBackupConfigurationUpdate',
  'type' => 'write',
  'name' => 'Update service backup configuration',
  'description' => 'Update service backup configuration Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId}/backupConfiguration Updates service backup configuration. Requires ADMIN auth key role. Setting the proper',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_backup_bucket_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudBackupBucketGet',
  'type' => 'read',
  'name' => 'Get service backup bucket',
  'description' => 'Get service backup bucket Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/backupBucket **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the future.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_backup_bucket_create' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudBackupBucketCreate',
  'type' => 'write',
  'name' => 'Create service backup bucket',
  'description' => 'Create service backup bucket Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/services/{serviceId}/backupBucket **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the fut',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_backup_bucket_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudBackupBucketUpdate',
  'type' => 'write',
  'name' => 'Update service backup bucket',
  'description' => 'Update service backup bucket Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId}/backupBucket **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the fu',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_backup_bucket_delete' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudBackupBucketDelete',
  'type' => 'write',
  'name' => 'Delete service backup bucket',
  'description' => 'Delete service backup bucket Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/services/{serviceId}/backupBucket **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the f',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_openapi_key_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOpenapiKeyGetList',
  'type' => 'read',
  'name' => 'Get list of all keys',
  'description' => 'Get list of all keys Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/keys Returns a list of all keys in the organization.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_openapi_key_create' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOpenapiKeyCreate',
  'type' => 'write',
  'name' => 'Create key',
  'description' => 'Create key Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/keys Creates new API key.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_openapi_key_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOpenapiKeyGet',
  'type' => 'read',
  'name' => 'Get key details',
  'description' => 'Get key details Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/keys/{keyId} Returns a single key details.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_openapi_key_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOpenapiKeyUpdate',
  'type' => 'write',
  'name' => 'Update key',
  'description' => 'Update key Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/keys/{keyId} Updates API key properties.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_openapi_key_delete' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOpenapiKeyDelete',
  'type' => 'write',
  'name' => 'Delete key',
  'description' => 'Delete key Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/keys/{keyId} Deletes API key. Only a key not used to authenticate the active request can be deleted.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_member_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudMemberGetList',
  'type' => 'read',
  'name' => 'List organization members',
  'description' => 'List organization members Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/members Returns a list of all members in the organization.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_member_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudMemberGet',
  'type' => 'read',
  'name' => 'Get member details',
  'description' => 'Get member details Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/members/{userId} Returns a single organization member details.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_member_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudMemberUpdate',
  'type' => 'write',
  'name' => 'Update organization member',
  'description' => 'Update organization member Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/members/{userId} Updates organization member role.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_member_delete' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudMemberDelete',
  'type' => 'write',
  'name' => 'Remove an organization member',
  'description' => 'Remove an organization member Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/members/{userId} Removes a user from the organization',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_invitation_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInvitationGetList',
  'type' => 'read',
  'name' => 'List all invitations',
  'description' => 'List all invitations Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/invitations Returns list of all organization invitations.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_invitation_create' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInvitationCreate',
  'type' => 'write',
  'name' => 'Create an invitation',
  'description' => 'Create an invitation Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/invitations Creates organization invitation.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_invitation_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInvitationGet',
  'type' => 'read',
  'name' => 'Get invitation details',
  'description' => 'Get invitation details Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/invitations/{invitationId} Returns details for a single organization invitation.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_invitation_delete' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudInvitationDelete',
  'type' => 'write',
  'name' => 'Delete organization invitation',
  'description' => 'Delete organization invitation Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/invitations/{invitationId} Deletes a single organization invitation.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_activity_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudActivityGetList',
  'type' => 'read',
  'name' => 'List of organization activities',
  'description' => 'List of organization activities Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/activities Returns a list of all organization activities.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_activity_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudActivityGet',
  'type' => 'read',
  'name' => 'Organization activity',
  'description' => 'Organization activity Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/activities/{activityId} Returns a single organization activity by ID.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_usage_cost_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudUsageCostGet',
  'type' => 'read',
  'name' => 'Get organization usage costs',
  'description' => 'Get organization usage costs Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/usageCost Returns a grand total and a list of daily, per-entity organization usage cost records for the organization in the queried time',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_pipe_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeGetList',
  'type' => 'read',
  'name' => 'List ClickPipes',
  'description' => 'List ClickPipes Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickpipes Returns a list of ClickPipes.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_pipe_create' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeCreate',
  'type' => 'write',
  'name' => 'Create ClickPipe',
  'description' => 'Create ClickPipe Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/services/{serviceId}/clickpipes Create a new ClickPipe.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_pipe_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeGet',
  'type' => 'read',
  'name' => 'Get ClickPipe',
  'description' => 'Get ClickPipe Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickpipes/{clickPipeId} Returns the specified ClickPipe.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_pipe_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeUpdate',
  'type' => 'write',
  'name' => 'Update ClickPipe',
  'description' => 'Update ClickPipe Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId}/clickpipes/{clickPipeId} Update the specified ClickPipe.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_pipe_delete' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeDelete',
  'type' => 'write',
  'name' => 'Delete ClickPipe',
  'description' => 'Delete ClickPipe Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/services/{serviceId}/clickpipes/{clickPipeId} Delete the specified ClickPipe.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_pipe_settings_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeSettingsGet',
  'type' => 'read',
  'name' => 'Get ClickPipe settings',
  'description' => 'Get ClickPipe settings Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickpipes/{clickPipeId}/settings Returns the advanced settings for the specified ClickPipe.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_pipe_settings_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeSettingsUpdate',
  'type' => 'write',
  'name' => 'Update ClickPipe settings',
  'description' => 'Update ClickPipe settings Official ClickHouse Cloud endpoint: PUT /v1/organizations/{organizationId}/services/{serviceId}/clickpipes/{clickPipeId}/settings Update the advanced settings for the specified ClickPipe. Send key-value pairs where',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_pipe_scaling_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeScalingUpdate',
  'type' => 'write',
  'name' => 'Update ClickPipe scaling',
  'description' => 'Update ClickPipe scaling Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId}/clickpipes/{clickPipeId}/scaling Change scaling settings for the specified ClickPipe. This endpoint supports Kafka, K',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_pipe_state_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeStateUpdate',
  'type' => 'write',
  'name' => 'Update ClickPipe state',
  'description' => 'Update ClickPipe state Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId}/clickpipes/{clickPipeId}/state Start, stop or resync ClickPipe. Stopping a ClickPipe will stop the ingestion process fr',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_pipe_cdc_scaling_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeCdcScalingGet',
  'type' => 'read',
  'name' => 'Get CDC ClickPipes scaling',
  'description' => 'Get CDC ClickPipes scaling Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickpipesCdcScaling Get scaling settings for database ClickPipes (PostgreSQL, MySQL, MongoDB, BigQuery). The infrast',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_pipe_cdc_scaling_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeCdcScalingUpdate',
  'type' => 'write',
  'name' => 'Update CDC ClickPipes scaling',
  'description' => 'Update CDC ClickPipes scaling Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/services/{serviceId}/clickpipesCdcScaling Update scaling settings for database ClickPipes (PostgreSQL, MySQL, MongoDB, BigQuery). The',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_stack_list_dashboards' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackListDashboards',
  'type' => 'read',
  'name' => 'ClickStack: List Dashboards',
  'description' => 'ClickStack: List Dashboards Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickstack/dashboards **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in ',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_stack_create_dashboard' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackCreateDashboard',
  'type' => 'write',
  'name' => 'ClickStack: Create Dashboard',
  'description' => 'ClickStack: Create Dashboard Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/services/{serviceId}/clickstack/dashboards **This endpoint is in beta.** API contract is stable, and no breaking changes are expected i',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_stack_get_dashboard' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackGetDashboard',
  'type' => 'read',
  'name' => 'ClickStack: Get Dashboard',
  'description' => 'ClickStack: Get Dashboard Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickstack/dashboards/{clickStackDashboardId} **This endpoint is in beta.** API contract is stable, and no breaking ch',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_stack_update_dashboard' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackUpdateDashboard',
  'type' => 'write',
  'name' => 'ClickStack: Update Dashboard',
  'description' => 'ClickStack: Update Dashboard Official ClickHouse Cloud endpoint: PUT /v1/organizations/{organizationId}/services/{serviceId}/clickstack/dashboards/{clickStackDashboardId} **This endpoint is in beta.** API contract is stable, and no breaking',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_stack_delete_dashboard' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackDeleteDashboard',
  'type' => 'write',
  'name' => 'ClickStack: Delete Dashboard',
  'description' => 'ClickStack: Delete Dashboard Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/services/{serviceId}/clickstack/dashboards/{clickStackDashboardId} **This endpoint is in beta.** API contract is stable, and no break',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_stack_list_alerts' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackListAlerts',
  'type' => 'read',
  'name' => 'ClickStack: List Alerts',
  'description' => 'ClickStack: List Alerts Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickstack/alerts **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the futu',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_stack_create_alert' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackCreateAlert',
  'type' => 'write',
  'name' => 'ClickStack: Create Alert',
  'description' => 'ClickStack: Create Alert Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/services/{serviceId}/clickstack/alerts **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the fu',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_stack_list_sources' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackListSources',
  'type' => 'read',
  'name' => 'ClickStack: List Sources',
  'description' => 'ClickStack: List Sources Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickstack/sources **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the fu',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_stack_get_alert' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackGetAlert',
  'type' => 'read',
  'name' => 'ClickStack: Get Alert',
  'description' => 'ClickStack: Get Alert Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickstack/alerts/{clickStackAlertId} **This endpoint is in beta.** API contract is stable, and no breaking changes are ex',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_stack_update_alert' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackUpdateAlert',
  'type' => 'write',
  'name' => 'ClickStack: Update Alert',
  'description' => 'ClickStack: Update Alert Official ClickHouse Cloud endpoint: PUT /v1/organizations/{organizationId}/services/{serviceId}/clickstack/alerts/{clickStackAlertId} **This endpoint is in beta.** API contract is stable, and no breaking changes are',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_stack_delete_alert' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackDeleteAlert',
  'type' => 'write',
  'name' => 'ClickStack: Delete Alert',
  'description' => 'ClickStack: Delete Alert Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/services/{serviceId}/clickstack/alerts/{clickStackAlertId} **This endpoint is in beta.** API contract is stable, and no breaking changes ',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_stack_list_webhooks' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickStackListWebhooks',
  'type' => 'read',
  'name' => 'ClickStack: List Webhooks',
  'description' => 'ClickStack: List Webhooks Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickstack/webhooks **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the ',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_postgres_service_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresServiceGetList',
  'type' => 'read',
  'name' => 'List of organization Postgres services',
  'description' => 'List of organization Postgres services Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/postgres **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the future. Returns a l',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_postgres_service_create' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresServiceCreate',
  'type' => 'write',
  'name' => 'Create new Postgres service',
  'description' => 'Create new Postgres service Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/postgres **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the future. Creates a new Postgre',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_postgres_service_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresServiceGet',
  'type' => 'read',
  'name' => 'Get PostgreSQL service details',
  'description' => 'Get PostgreSQL service details Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/postgres/{postgresId} **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the future. Return',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_postgres_service_patch' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresServicePatch',
  'type' => 'write',
  'name' => 'Update a PostgreSQL service',
  'description' => 'Update a PostgreSQL service Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/postgres/{postgresId} **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the future. Update ',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_postgres_service_delete' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresServiceDelete',
  'type' => 'write',
  'name' => 'Delete a PostgreSQL service',
  'description' => 'Delete a PostgreSQL service Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/postgres/{postgresId} **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the future. Delete',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_postgres_service_certs_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresServiceCertsGet',
  'type' => 'read',
  'name' => 'Get Postgres CA certs',
  'description' => 'Get Postgres CA certs Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/postgres/{postgresId}/caCertificates **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the future. ',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_postgres_instance_restore' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresInstanceRestore',
  'type' => 'write',
  'name' => 'Restore a Postgres service',
  'description' => 'Restore a Postgres service Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/postgres/{postgresId}/restoredService **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the f',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_postgres_service_set_password' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresServiceSetPassword',
  'type' => 'write',
  'name' => 'Update Postgres superuser password',
  'description' => 'Update Postgres superuser password Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/postgres/{postgresId}/password **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_postgres_service_patch_state' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresServicePatchState',
  'type' => 'write',
  'name' => 'Update Postgres service state',
  'description' => 'Update Postgres service state Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/postgres/{postgresId}/state **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the future.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_postgres_instance_create_read_replica' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresInstanceCreateReadReplica',
  'type' => 'write',
  'name' => 'Create a read replica for a Postgres service',
  'description' => 'Create a read replica for a Postgres service Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/postgres/{postgresId}/readReplica **This endpoint is in beta.** API contract is stable, and no breaking changes are exp',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_postgres_instance_config_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresInstanceConfigGet',
  'type' => 'read',
  'name' => 'Get PostgreSQL service configuration',
  'description' => 'Get PostgreSQL service configuration Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/postgres/{postgresId}/config **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in the f',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_postgres_instance_config_post' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresInstanceConfigPost',
  'type' => 'write',
  'name' => 'Replace Postgres service configuration',
  'description' => 'Replace Postgres service configuration Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/postgres/{postgresId}/config **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in th',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_postgres_instance_config_patch' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudPostgresInstanceConfigPatch',
  'type' => 'write',
  'name' => 'Update Postgres service configuration',
  'description' => 'Update Postgres service configuration Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/postgres/{postgresId}/config **This endpoint is in beta.** API contract is stable, and no breaking changes are expected in th',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_organization_private_endpoint_config_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationPrivateEndpointConfigGetList',
  'type' => 'read',
  'name' => 'Get private endpoint configuration for region within cloud provider for an organization',
  'description' => 'Get private endpoint configuration for region within cloud provider for an organization Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/privateEndpointConfig Deprecated. Please follow [documentation](https://click',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_organization_byoc_infrastructure_create' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationByocInfrastructureCreate',
  'type' => 'write',
  'name' => 'Create BYOC Infrastructure',
  'description' => 'Create BYOC Infrastructure Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/byocInfrastructure Create a new BYOC Infrastructure in the organization. Returns the configuration of the newly created infrastructure',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_organization_byoc_infrastructure_update' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationByocInfrastructureUpdate',
  'type' => 'write',
  'name' => 'Update BYOC Infrastructure',
  'description' => 'Update BYOC Infrastructure Official ClickHouse Cloud endpoint: PATCH /v1/organizations/{organizationId}/byocInfrastructure/{byocInfrastructureId} Update configuration of the BYOC infrastructure. Returns the modified infrastructure',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_organization_byoc_infrastructure_delete' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudOrganizationByocInfrastructureDelete',
  'type' => 'write',
  'name' => 'Remove a BYOC infrastructure',
  'description' => 'Remove a BYOC infrastructure Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/byocInfrastructure/{byocInfrastructureId} Removes a BYOC Infrastructure from the organization',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_pipe_reverse_private_endpoint_get_list' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeReversePrivateEndpointGetList',
  'type' => 'read',
  'name' => 'List reverse private endpoints',
  'description' => 'List reverse private endpoints Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickpipesReversePrivateEndpoints Returns a list of reverse private endpoints for the specified service.',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_pipe_reverse_private_endpoint_create' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeReversePrivateEndpointCreate',
  'type' => 'write',
  'name' => 'Create reverse private endpoint',
  'description' => 'Create reverse private endpoint Official ClickHouse Cloud endpoint: POST /v1/organizations/{organizationId}/services/{serviceId}/clickpipesReversePrivateEndpoints Create a new reverse private endpoint.',
  'icon' => 'ph:pencil-simple',
),
  'clickhouse_cloud_click_pipe_reverse_private_endpoint_get' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeReversePrivateEndpointGet',
  'type' => 'read',
  'name' => 'Get reverse private endpoint',
  'description' => 'Get reverse private endpoint Official ClickHouse Cloud endpoint: GET /v1/organizations/{organizationId}/services/{serviceId}/clickpipesReversePrivateEndpoints/{reversePrivateEndpointId} Returns the reverse private endpoint with the specifie',
  'icon' => 'ph:database',
),
  'clickhouse_cloud_click_pipe_reverse_private_endpoint_delete' => array (
  'class' => 'OpenCompany\\Integrations\\ClickHouseCloud\\Tools\\ClickHouseCloudClickPipeReversePrivateEndpointDelete',
  'type' => 'write',
  'name' => 'Delete reverse private endpoint',
  'description' => 'Delete reverse private endpoint Official ClickHouse Cloud endpoint: DELETE /v1/organizations/{organizationId}/services/{serviceId}/clickpipesReversePrivateEndpoints/{reversePrivateEndpointId} Delete the reverse private endpoint with the spe',
  'icon' => 'ph:pencil-simple',
),
]; }
    public function isIntegration(): bool { return true; } public function createTool(string $class, array $context = []): Tool { return new $class($this->resolveService($context)); } public function scriptDocsPath(): ?string { return __DIR__.'/../script-docs/clickhouse-cloud.md'; }
    /** @param  array<string, mixed>  $context  Optional account context from the host. */ private function resolveService(array $context = []): ClickHouseCloudService { $account=$context['account']??null; if($account!==null){$creds=app(CredentialResolver::class); return new ClickHouseCloudService(keyId:$creds->get('clickhouse-cloud','key_id','',$account), keySecret:$creds->get('clickhouse-cloud','key_secret','',$account), baseUrl:$creds->get('clickhouse-cloud','url','https://api.clickhouse.cloud',$account));} return app(ClickHouseCloudService::class); }
}
