<?php

namespace OpenCompany\Integrations\Fivetran;

use Illuminate\Support\Facades\Http;
use OpenCompany\IntegrationCore\Contracts\ConfigurableIntegration;
use OpenCompany\IntegrationCore\Contracts\CredentialResolver;
use OpenCompany\IntegrationCore\Contracts\HasIntegrationCapabilities;
use OpenCompany\IntegrationCore\Contracts\Tool;
use OpenCompany\IntegrationCore\Contracts\ToolProvider;

/**
 * Tool catalog and configuration metadata for Fivetran.
 *
 * Exposes the official Fivetran OpenAPI operation set as endpoint-specific
 * agent tools and resolves account-specific API credentials in multi-account hosts.
 */
class FivetranToolProvider implements ToolProvider, ConfigurableIntegration, HasIntegrationCapabilities
{
    /** @return array<string, mixed> */ public function integrationCapabilities(): array { return ['auth'=>['strategy'=>'basic','legacy_auth_type'=>'api_key','credential_mode'=>'secret','setup_flows'=>['manual_secret'],'requires_browser_for_setup'=>false,'refreshable'=>false,'token_keys'=>[],'notes'=>['Use a Fivetran API key and API secret with HTTP Basic authentication.']],'host_availability'=>['web'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret'],'cli'=>['setup_supported'=>true,'runtime_supported'=>true,'setup_mode'=>'manual_secret','runtime_mode'=>'normal']],'runtime_requirements'=>[],'compatibility'=>['web_setup_supported'=>true,'web_runtime_supported'=>true,'cli_setup_supported'=>true,'cli_runtime_supported'=>true]]; }
    public function appName(): string { return 'fivetran'; } public function appMeta(): array { return ['label'=>'Fivetran','description'=>'Data pipeline management, connectors, destinations, transformations, users, teams, and webhooks','icon'=>'ph:database','logo'=>'ph:database']; }
    public function integrationMeta(): array { return ['name'=>'Fivetran','description'=>'Manage Fivetran connectors, destinations, groups, transformations, users, teams, certificates, private links, and webhooks.','icon'=>'ph:database','logo'=>'ph:database','category'=>'data','badge'=>'verified','docs_url'=>'https://fivetran.com/docs/rest-api/api-reference/open-api-definition']; }
    public function configSchema(): array { return [['key'=>'api_key','type'=>'secret','label'=>'API Key','required'=>true],['key'=>'api_secret','type'=>'secret','label'=>'API Secret','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','placeholder'=>'https://api.fivetran.com','default'=>'https://api.fivetran.com']]; }
    /** @param  array<string, mixed>  $config  Credential and endpoint settings. @return array{success: bool, message?: string, error?: string} */ public function testConnection(array $config): array { $key=(string)($config['api_key']??''); $secret=(string)($config['api_secret']??''); $baseUrl=rtrim((string)($config['url']??'https://api.fivetran.com'),'/'); if($key===''||$secret==='')return ['success'=>false,'error'=>'Fivetran API key and secret are required.']; try{$response=Http::withHeaders(['Authorization'=>'Basic '.base64_encode($key.':'.$secret),'Accept'=>'application/json'])->timeout(10)->get($baseUrl.'/v1/account/info'); if(!$response->successful())return ['success'=>false,'error'=>'Fivetran API returned HTTP '.$response->status().'.']; return ['success'=>true,'message'=>'Connected to Fivetran at '.$baseUrl.'.'];}catch(\Throwable $e){return ['success'=>false,'error'=>$e->getMessage()];} }
    public function validationRules(): array { return ['api_key'=>'required|string','api_secret'=>'required|string','url'=>'nullable|url']; } public function credentialFields(): array { return [['key'=>'api_key','type'=>'secret','label'=>'API Key','required'=>true],['key'=>'api_secret','type'=>'secret','label'=>'API Secret','required'=>true],['key'=>'url','type'=>'url','label'=>'API Base URL','required'=>false,'default'=>'https://api.fivetran.com']]; }
    public function tools(): array { return [
  'fivetran_delete_user' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteUser',
  'type' => 'write',
  'name' => 'Delete a User',
  'description' => 'Delete a User Official Fivetran endpoint: DELETE /v1/users/{id} Deletes a user from your Fivetran account. You will be unable to delete an account owner user if there is only one remaining.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_user_memberships_in_groups' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetUserMembershipsInGroups',
  'type' => 'read',
  'name' => 'List All Group Memberships',
  'description' => 'List All Group Memberships Official Fivetran endpoint: GET /v1/users/{userId}/groups Returns the membership details for all groups a user belongs to.',
  'icon' => 'ph:database',
),
  'fivetran_add_user_membership_in_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranAddUserMembershipInGroup',
  'type' => 'write',
  'name' => 'Add Group Membership',
  'description' => 'Add Group Membership Official Fivetran endpoint: POST /v1/users/{userId}/groups Adds a user membership in a group.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_group_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGroupDetails',
  'type' => 'read',
  'name' => 'Retrieve Group Details',
  'description' => 'Retrieve Group Details Official Fivetran endpoint: GET /v1/groups/{groupId} Returns a group object if a valid identifier was provided.',
  'icon' => 'ph:database',
),
  'fivetran_delete_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteGroup',
  'type' => 'write',
  'name' => 'Delete a Group',
  'description' => 'Delete a Group Official Fivetran endpoint: DELETE /v1/groups/{groupId} Deletes a group from your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_modify_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyGroup',
  'type' => 'write',
  'name' => 'Update a Group',
  'description' => 'Update a Group Official Fivetran endpoint: PATCH /v1/groups/{groupId} Updates information for an existing group within your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_account_info' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetAccountInfo',
  'type' => 'read',
  'name' => 'Get Account Info from the API Key',
  'description' => 'Get Account Info from the API Key Official Fivetran endpoint: GET /v1/account/info Returns information about current account from API key.',
  'icon' => 'ph:database',
),
  'fivetran_get_hybrid_deployment_agent_list' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetHybridDeploymentAgentList',
  'type' => 'read',
  'name' => 'List Hybrid Deployment Agents',
  'description' => 'List Hybrid Deployment Agents Official Fivetran endpoint: GET /v1/hybrid-deployment-agents Returns list of all Hybrid Deployment Agents within your Fivetran account, along with usage. Optionally filtered to a single g...',
  'icon' => 'ph:database',
),
  'fivetran_create_hybrid_deployment_agent' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateHybridDeploymentAgent',
  'type' => 'write',
  'name' => 'Create a Hybrid Deployment Agent',
  'description' => 'Create a Hybrid Deployment Agent Official Fivetran endpoint: POST /v1/hybrid-deployment-agents Creates a new Hybrid Deployment Agent in a group.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_team_memberships_in_groups' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetTeamMembershipsInGroups',
  'type' => 'read',
  'name' => 'List All Group Memberships',
  'description' => 'List All Group Memberships Official Fivetran endpoint: GET /v1/teams/{teamId}/groups Returns all groups in which a team has membership.',
  'icon' => 'ph:database',
),
  'fivetran_add_team_membership_in_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranAddTeamMembershipInGroup',
  'type' => 'write',
  'name' => 'Add Group Membership',
  'description' => 'Add Group Membership Official Fivetran endpoint: POST /v1/teams/{teamId}/groups Adds a team as a member of a group.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_metadata_connectors' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranMetadataConnectors',
  'type' => 'read',
  'name' => 'Retrieve Source Metadata',
  'description' => 'Retrieve Source Metadata Official Fivetran endpoint: GET /v1/metadata/connector-types Returns all available source types within your Fivetran account. This endpoint makes it easier to display Fivetran connectors withi...',
  'icon' => 'ph:database',
),
  'fivetran_re_auth_hybrid_deployment_agent' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranReAuthHybridDeploymentAgent',
  'type' => 'write',
  'name' => 'Regenerate Authentication Keys',
  'description' => 'Regenerate Authentication Keys Official Fivetran endpoint: PATCH /v1/hybrid-deployment-agents/{agentId}/re-auth Regenerate authentication for a Hybrid Deployment Agent.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_team_membership_in_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetTeamMembershipInGroup',
  'type' => 'read',
  'name' => 'Retrieve Group Membership Details',
  'description' => 'Retrieve Group Membership Details Official Fivetran endpoint: GET /v1/teams/{teamId}/groups/{groupId} Returns details of a team membership in a group.',
  'icon' => 'ph:database',
),
  'fivetran_delete_team_membership_in_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteTeamMembershipInGroup',
  'type' => 'write',
  'name' => 'Delete Group Membership',
  'description' => 'Delete Group Membership Official Fivetran endpoint: DELETE /v1/teams/{teamId}/groups/{groupId} Removes a team\'s membership in a group.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_update_team_membership_in_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUpdateTeamMembershipInGroup',
  'type' => 'write',
  'name' => 'Update Group Membership',
  'description' => 'Update Group Membership Official Fivetran endpoint: PATCH /v1/teams/{teamId}/groups/{groupId} Updates team membership in a group.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_rotate_system_key' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranRotateSystemKey',
  'type' => 'write',
  'name' => 'Rotate a System Key',
  'description' => 'Rotate a System Key Official Fivetran endpoint: POST /v1/system-keys/{keyId}/rotate Updates the secret value and expired_at date for an existing system key within your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_connection_fingerprints_list' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetConnectionFingerprintsList',
  'type' => 'read',
  'name' => 'List Fingerprints Approved for the Connection',
  'description' => 'List Fingerprints Approved for the Connection Official Fivetran endpoint: GET /v1/connections/{connectionId}/fingerprints Returns the list of approved SSH fingerprints for specified connection',
  'icon' => 'ph:database',
),
  'fivetran_approve_connection_fingerprint' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranApproveConnectionFingerprint',
  'type' => 'write',
  'name' => 'Approve a Fingerprint for the Connection',
  'description' => 'Approve a Fingerprint for the Connection Official Fivetran endpoint: POST /v1/connections/{connectionId}/fingerprints Approves a fingerprint, enabling Fivetran to trust it for a source database and establish connectio...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_transformation_package_metadata_list' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranTransformationPackageMetadataList',
  'type' => 'read',
  'name' => 'List All Quickstart Package Metadata',
  'description' => 'List All Quickstart Package Metadata Official Fivetran endpoint: GET /v1/transformations/package-metadata Returns a list of available Quickstart transformation package metadata details.',
  'icon' => 'ph:database',
),
  'fivetran_connection_column_config' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranConnectionColumnConfig',
  'type' => 'read',
  'name' => 'Retrieve Source Table Columns Config',
  'description' => 'Retrieve Source Table Columns Config Official Fivetran endpoint: GET /v1/connections/{connectionId}/schemas/{schema}/tables/{table}/columns Returns the real-time column list for one source table by querying the source...',
  'icon' => 'ph:database',
),
  'fivetran_get_destination_fingerprints_list' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetDestinationFingerprintsList',
  'type' => 'read',
  'name' => 'List Fingerprints Approved for the Destination',
  'description' => 'List Fingerprints Approved for the Destination Official Fivetran endpoint: GET /v1/destinations/{destinationId}/fingerprints Returns the list of approved SSH fingerprints for specified destination',
  'icon' => 'ph:database',
),
  'fivetran_approve_destination_fingerprint' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranApproveDestinationFingerprint',
  'type' => 'write',
  'name' => 'Approve a Fingerprint for the Destination',
  'description' => 'Approve a Fingerprint for the Destination Official Fivetran endpoint: POST /v1/destinations/{destinationId}/fingerprints Approves a fingerprint, enabling Fivetran to trust it for a destination database and establish c...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_modify_connection_table_config' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyConnectionTableConfig',
  'type' => 'write',
  'name' => 'Update a Connection Table Config',
  'description' => 'Update a Connection Table Config Official Fivetran endpoint: PATCH /v1/connections/{connectionId}/schemas/{schemaName}/tables/{tableName} Updates the table config within your database schema for an existing connection...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_connection_certificate_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetConnectionCertificateDetails',
  'type' => 'read',
  'name' => 'Retrieve Connection Certificate Details',
  'description' => 'Retrieve Connection Certificate Details Official Fivetran endpoint: GET /v1/connections/{connectionId}/certificates/{hash} Returns details of the certificate approved for the specified connection with specified certif...',
  'icon' => 'ph:database',
),
  'fivetran_revoke_connection_certificate' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranRevokeConnectionCertificate',
  'type' => 'write',
  'name' => 'Revoke Connection Certificate',
  'description' => 'Revoke Connection Certificate Official Fivetran endpoint: DELETE /v1/connections/{connectionId}/certificates/{hash} Revokes a certificate, so Fivetran no longer trusts it while connecting to the source database.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_create_group_webhook' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateGroupWebhook',
  'type' => 'write',
  'name' => 'Create a Group Webhook',
  'description' => 'Create a Group Webhook Official Fivetran endpoint: POST /v1/webhooks/group/{groupId} This endpoint allows you to create a new webhook for a given group',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_team_membership_in_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetTeamMembershipInConnection',
  'type' => 'read',
  'name' => 'Retrieve Connection Membership',
  'description' => 'Retrieve Connection Membership Official Fivetran endpoint: GET /v1/teams/{teamId}/connections/{connectionId} Returns details of a team membership in a connection.',
  'icon' => 'ph:database',
),
  'fivetran_delete_team_membership_in_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteTeamMembershipInConnection',
  'type' => 'write',
  'name' => 'Delete Connection Membership',
  'description' => 'Delete Connection Membership Official Fivetran endpoint: DELETE /v1/teams/{teamId}/connections/{connectionId} Removes team membership in a connection.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_update_team_membership_in_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUpdateTeamMembershipInConnection',
  'type' => 'write',
  'name' => 'Update Connection Membership',
  'description' => 'Update Connection Membership Official Fivetran endpoint: PATCH /v1/teams/{teamId}/connections/{connectionId} Updates team membership in a connection',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_delete_user_from_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteUserFromGroup',
  'type' => 'write',
  'name' => 'Remove a User from a Group',
  'description' => 'Remove a User from a Group Official Fivetran endpoint: DELETE /v1/groups/{groupId}/users/{userId} Removes an existing user from a group in your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_connection_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranConnectionDetails',
  'type' => 'read',
  'name' => 'Retrieve Connection Details',
  'description' => 'Retrieve Connection Details Official Fivetran endpoint: GET /v1/connections/{connectionId} Returns a connection configuration and status details if a valid identifier was provided.',
  'icon' => 'ph:database',
),
  'fivetran_delete_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteConnection',
  'type' => 'write',
  'name' => 'Delete a Connection',
  'description' => 'Delete a Connection Official Fivetran endpoint: DELETE /v1/connections/{connectionId} Deletes a connection from your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_modify_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyConnection',
  'type' => 'write',
  'name' => 'Update a Connection',
  'description' => 'Update a Connection Official Fivetran endpoint: PATCH /v1/connections/{connectionId} Updates connection parameters for an existing connection within your Fivetran account. This endpoint requires at least one persisten...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_test_transformation_project' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranTestTransformationProject',
  'type' => 'write',
  'name' => 'Test Transformation Project',
  'description' => 'Test Transformation Project Official Fivetran endpoint: POST /v1/transformation-projects/{projectId}/test Triggers tests for an existing transformation project.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_all_connections_in_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListAllConnectionsInGroup',
  'type' => 'read',
  'name' => 'List All Connections within a Group',
  'description' => 'List All Connections within a Group Official Fivetran endpoint: GET /v1/groups/{groupId}/connections Returns a list of information about all connections within a group in your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_delete_multiple_columns_connection_config' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteMultipleColumnsConnectionConfig',
  'type' => 'write',
  'name' => 'Drop Blocked Columns from the Destination.',
  'description' => 'Drop Blocked Columns from the Destination. Official Fivetran endpoint: POST /v1/connections/{connectionId}/schemas/drop-columns Mark multiple blocked columns for deletion from your destination tables. The columns will...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_destination_certificate_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetDestinationCertificateDetails',
  'type' => 'read',
  'name' => 'Retrieve Destination Certificate Details',
  'description' => 'Retrieve Destination Certificate Details Official Fivetran endpoint: GET /v1/destinations/{destinationId}/certificates/{hash} Returns details of the certificate approved for the specified destination with specified ce...',
  'icon' => 'ph:database',
),
  'fivetran_revoke_destination_certificate' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranRevokeDestinationCertificate',
  'type' => 'write',
  'name' => 'Revoke Destination Certificate',
  'description' => 'Revoke Destination Certificate Official Fivetran endpoint: DELETE /v1/destinations/{destinationId}/certificates/{hash} Revokes a certificate, so Fivetran no longer trusts it while connecting to the destination database.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_connection_schema_config' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranConnectionSchemaConfig',
  'type' => 'read',
  'name' => 'Retrieve a Connection Schema Config',
  'description' => 'Retrieve a Connection Schema Config Official Fivetran endpoint: GET /v1/connections/{connectionId}/schemas Returns the top-level schema configuration for an existing connection within your Fivetran account. The respon...',
  'icon' => 'ph:database',
),
  'fivetran_pre_create_connection_schema_config' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranPreCreateConnectionSchemaConfig',
  'type' => 'write',
  'name' => 'Set Up a New Connection Schema Config',
  'description' => 'Set Up a New Connection Schema Config Official Fivetran endpoint: POST /v1/connections/{connectionId}/schemas Configures a Connection Schema for a new connection before the schema is captured from the source. > Note: ...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_modify_connection_schema_config' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyConnectionSchemaConfig',
  'type' => 'write',
  'name' => 'Update a Connection Schema Config',
  'description' => 'Update a Connection Schema Config Official Fivetran endpoint: PATCH /v1/connections/{connectionId}/schemas Updates the schema config for an existing connection within your Fivetran account. > NOTE: For backward compat...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_destination_certificates_list' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetDestinationCertificatesList',
  'type' => 'read',
  'name' => 'List Certificates Approved for the Destination',
  'description' => 'List Certificates Approved for the Destination Official Fivetran endpoint: GET /v1/destinations/{destinationId}/certificates Returns the list of approved certificates for the specified destination.',
  'icon' => 'ph:database',
),
  'fivetran_approve_destination_certificate' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranApproveDestinationCertificate',
  'type' => 'write',
  'name' => 'Approve a Certificate for the Destination',
  'description' => 'Approve a Certificate for the Destination Official Fivetran endpoint: POST /v1/destinations/{destinationId}/certificates Approves a certificate, so Fivetran trusts this certificate for a destination database connectio...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_regenerate_secrets_proxy_agent' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranRegenerateSecretsProxyAgent',
  'type' => 'write',
  'name' => 'Regenerate Secrets for Proxy Agent',
  'description' => 'Regenerate Secrets for Proxy Agent Official Fivetran endpoint: POST /v1/proxy/{agentId}/regenerate-secrets Regenerate secrets for proxy agent within your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_connector_sdk_packages' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListConnectorSdkPackages',
  'type' => 'read',
  'name' => 'List All Connector SDK Packages',
  'description' => 'List All Connector SDK Packages Official Fivetran endpoint: GET /v1/connector-sdk/packages Returns a list of all Connector SDK packages in your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_create_connector_sdk_package' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateConnectorSdkPackage',
  'type' => 'write',
  'name' => 'Create Connector SDK Package',
  'description' => 'Create Connector SDK Package Official Fivetran endpoint: POST /v1/connector-sdk/packages Uploads a new Connector SDK package to your Fivetran account. The package must be a ZIP file containing your custom connector co...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_connections' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListConnections',
  'type' => 'read',
  'name' => 'List All Connections',
  'description' => 'List All Connections Official Fivetran endpoint: GET /v1/connections Returns a list of all accessible connections within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_create_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateConnection',
  'type' => 'write',
  'name' => 'Create a Connection',
  'description' => 'Create a Connection Official Fivetran endpoint: POST /v1/connections Creates a new connection within a specified group in your Fivetran account. Runs setup tests and returns testing results. > IMPORTANT: The `destinat...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_all_webhooks' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListAllWebhooks',
  'type' => 'read',
  'name' => 'List all Webhooks',
  'description' => 'List all Webhooks Official Fivetran endpoint: GET /v1/webhooks The endpoint allows you to retrieve the list of existing webhooks available for the current account',
  'icon' => 'ph:database',
),
  'fivetran_approve_certificate' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranApproveCertificate',
  'type' => 'write',
  'name' => '(Deprecated) Approve a Certificate',
  'description' => '(Deprecated) Approve a Certificate Official Fivetran endpoint: POST /v1/certificates Approves a certificate for a connection/destination, so Fivetran trusts this certificate for a source/destination database. The conn...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_group_ssh_public_key' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGroupSshPublicKey',
  'type' => 'read',
  'name' => 'Retrieve Group Public SSH Key',
  'description' => 'Retrieve Group Public SSH Key Official Fivetran endpoint: GET /v1/groups/{groupId}/public-key Returns public key from SSH key pair associated with the group.',
  'icon' => 'ph:database',
),
  'fivetran_transformation_package_metadata_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranTransformationPackageMetadataDetails',
  'type' => 'read',
  'name' => 'Retrieve a Quickstart Package Metadata Details',
  'description' => 'Retrieve a Quickstart Package Metadata Details Official Fivetran endpoint: GET /v1/transformations/package-metadata/{package_definition_id} Returns the metadata details of the Quickstart transformation package if a va...',
  'icon' => 'ph:database',
),
  'fivetran_get_proxy_agent_connections' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetProxyAgentConnections',
  'type' => 'read',
  'name' => 'List All Connections Attached to the Proxy Agent',
  'description' => 'List All Connections Attached to the Proxy Agent Official Fivetran endpoint: GET /v1/proxy/{agentId}/connections Returns all connections attached to the specified proxy agent within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_list_all_groups' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListAllGroups',
  'type' => 'read',
  'name' => 'List All Destinations within Account',
  'description' => 'List All Destinations within Account Official Fivetran endpoint: GET /v1/groups Returns a list of all groups within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_create_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateGroup',
  'type' => 'write',
  'name' => 'Create a Group',
  'description' => 'Create a Group Official Fivetran endpoint: POST /v1/groups Creates a new group in your Fivetran account. > IMPORTANT: Groups and destinations are mapped 1:1 to each other. We do this mapping using the group\'s `id` val...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_reset_hybrid_deployment_agent_credentials' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranResetHybridDeploymentAgentCredentials',
  'type' => 'write',
  'name' => 'Reset Agent Credentials',
  'description' => 'Reset Agent Credentials Official Fivetran endpoint: POST /v1/hybrid-deployment-agents/{agentId}/reset-credentials Reset credentials for a Hybrid Deployment Agent.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_run_setup_tests_log_service' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranRunSetupTestsLogService',
  'type' => 'write',
  'name' => 'Run Group Log Service Setup Tests',
  'description' => 'Run Group Log Service Setup Tests Official Fivetran endpoint: POST /v1/external-logging/{logId}/test Runs the setup tests for an existing group-level [logging service](/docs/logs/external-logs) within your Fivetran ac...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_delete_column_connection_config' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteColumnConnectionConfig',
  'type' => 'write',
  'name' => 'Drop a Blocked Column From the Destination',
  'description' => 'Drop a Blocked Column From the Destination Official Fivetran endpoint: DELETE /v1/connections/{connectionId}/schemas/{schemaName}/tables/{tableName}/columns/{columnName} Marks a blocked column for deletion from your d...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_modify_connection_column_config' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyConnectionColumnConfig',
  'type' => 'write',
  'name' => 'Update a Connection Column Config',
  'description' => 'Update a Connection Column Config Official Fivetran endpoint: PATCH /v1/connections/{connectionId}/schemas/{schemaName}/tables/{tableName}/columns/{columnName} Updates the column config within your table for an existi...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_connection_fingerprint_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetConnectionFingerprintDetails',
  'type' => 'read',
  'name' => 'Retrieve Connection Fingerprint Details',
  'description' => 'Retrieve Connection Fingerprint Details Official Fivetran endpoint: GET /v1/connections/{connectionId}/fingerprints/{hash} Returns SSH fingerprint details approved for specified connection with specified hash',
  'icon' => 'ph:database',
),
  'fivetran_revoke_connection_fingerprint' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranRevokeConnectionFingerprint',
  'type' => 'write',
  'name' => 'Revoke Connection Fingerprint',
  'description' => 'Revoke Connection Fingerprint Official Fivetran endpoint: DELETE /v1/connections/{connectionId}/fingerprints/{hash} Revokes a fingerprint, so Fivetran no longer trusts it while connecting to the source database throug...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_private_link_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetPrivateLinkDetails',
  'type' => 'read',
  'name' => 'Retrieve Private Link Details',
  'description' => 'Retrieve Private Link Details Official Fivetran endpoint: GET /v1/private-links/{privateLinkId} Returns a private link object if a valid identifier was provided.',
  'icon' => 'ph:database',
),
  'fivetran_delete_private_link' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeletePrivateLink',
  'type' => 'write',
  'name' => 'Delete a Private Link',
  'description' => 'Delete a Private Link Official Fivetran endpoint: DELETE /v1/private-links/{privateLinkId} Deletes a private link from your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_modify_private_link' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyPrivateLink',
  'type' => 'write',
  'name' => 'Update a Private Link',
  'description' => 'Update a Private Link Official Fivetran endpoint: PATCH /v1/private-links/{privateLinkId} Updates information for an existing private link within your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_system_keys' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetSystemKeys',
  'type' => 'read',
  'name' => 'List All System Keys',
  'description' => 'List All System Keys Official Fivetran endpoint: GET /v1/system-keys Returns a list of system keys within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_create_system_key' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateSystemKey',
  'type' => 'write',
  'name' => 'Create a System Key',
  'description' => 'Create a System Key Official Fivetran endpoint: POST /v1/system-keys Creates a new system key with your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_all_roles' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListAllRoles',
  'type' => 'read',
  'name' => 'List all roles',
  'description' => 'List all roles Official Fivetran endpoint: GET /v1/roles Returns a list of all predefined and custom roles within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_metadata_public_connectors' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranMetadataPublicConnectors',
  'type' => 'read',
  'name' => 'Retrieve Source Metadata Public Endpoint',
  'description' => 'Retrieve Source Metadata Public Endpoint Official Fivetran endpoint: GET /public/connector-types Returns all available source types. This endpoint provides metadata including the proper source name (‘Facebook Ads’...',
  'icon' => 'ph:database',
),
  'fivetran_get_connection_certificates_list' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetConnectionCertificatesList',
  'type' => 'read',
  'name' => 'List Certificates Approved for the Connection',
  'description' => 'List Certificates Approved for the Connection Official Fivetran endpoint: GET /v1/connections/{connectionId}/certificates Returns the list of approved certificates for the specified connection.',
  'icon' => 'ph:database',
),
  'fivetran_approve_connection_certificate' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranApproveConnectionCertificate',
  'type' => 'write',
  'name' => 'Approve a Certificate for the Connection',
  'description' => 'Approve a Certificate for the Connection Official Fivetran endpoint: POST /v1/connections/{connectionId}/certificates Approves a certificate, so Fivetran trusts this certificate for a source database connection. The c...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_destinations' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListDestinations',
  'type' => 'read',
  'name' => 'List All Destinations Within Account',
  'description' => 'List All Destinations Within Account Official Fivetran endpoint: GET /v1/destinations Returns a list of all accessible destinations within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_create_destination' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateDestination',
  'type' => 'write',
  'name' => 'Create a Destination',
  'description' => 'Create a Destination Official Fivetran endpoint: POST /v1/destinations Creates a new destination within a specified group in your Fivetran account. > IMPORTANT: Groups and destinations are mapped 1:1 to each other. We...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_user_memberships_in_connections' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetUserMembershipsInConnections',
  'type' => 'read',
  'name' => 'List All Connection Memberships',
  'description' => 'List All Connection Memberships Official Fivetran endpoint: GET /v1/users/{userId}/connections Returns all connection membership for a user within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_add_user_membership_in_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranAddUserMembershipInConnection',
  'type' => 'write',
  'name' => 'Add a Connection Membership',
  'description' => 'Add a Connection Membership Official Fivetran endpoint: POST /v1/users/{userId}/connections Adds a connection membership',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_destination_fingerprint_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetDestinationFingerprintDetails',
  'type' => 'read',
  'name' => 'Retrieve Destination Fingerprint Details',
  'description' => 'Retrieve Destination Fingerprint Details Official Fivetran endpoint: GET /v1/destinations/{destinationId}/fingerprints/{hash} Returns SSH fingerprint details approved for specified destination with specified hash',
  'icon' => 'ph:database',
),
  'fivetran_revoke_destination_fingerprint' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranRevokeDestinationFingerprint',
  'type' => 'write',
  'name' => 'Revoke Destination Fingerprint',
  'description' => 'Revoke Destination Fingerprint Official Fivetran endpoint: DELETE /v1/destinations/{destinationId}/fingerprints/{hash} Revokes a fingerprint, so Fivetran no longer trusts it while connecting to the destination databas...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_sync_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranSyncConnection',
  'type' => 'write',
  'name' => 'Sync Connection Data',
  'description' => 'Sync Connection Data Official Fivetran endpoint: POST /v1/connections/{connectionId}/sync Triggers a data sync for an existing connection within your Fivetran account without waiting for the next scheduled sync. This ...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_modify_connection_database_schema_config' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyConnectionDatabaseSchemaConfig',
  'type' => 'write',
  'name' => 'Update a Connection Database Schema Config',
  'description' => 'Update a Connection Database Schema Config Official Fivetran endpoint: PATCH /v1/connections/{connectionId}/schemas/{schemaName} Updates the database schema config for an existing connection within your Fivetran accou...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_system_key_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetSystemKeyDetails',
  'type' => 'read',
  'name' => 'Retrieve System Key Details',
  'description' => 'Retrieve System Key Details Official Fivetran endpoint: GET /v1/system-keys/{keyId} Retrieves a system key object within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_delete_system_key' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteSystemKey',
  'type' => 'write',
  'name' => 'Delete a System Key',
  'description' => 'Delete a System Key Official Fivetran endpoint: DELETE /v1/system-keys/{keyId} Deletes a system key from your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_update_system_key' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUpdateSystemKey',
  'type' => 'write',
  'name' => 'Update a System Key',
  'description' => 'Update a System Key Official Fivetran endpoint: PATCH /v1/system-keys/{keyId} Updates an existing system key within your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_resync_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranResyncConnection',
  'type' => 'write',
  'name' => 'Re-sync Connection Data (Historical Sync)',
  'description' => 'Re-sync Connection Data (Historical Sync) Official Fivetran endpoint: POST /v1/connections/{connectionId}/resync Triggers a full historical sync of a connection or multiple schema tables within a connection. If the co...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_log_service_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetLogServiceDetails',
  'type' => 'read',
  'name' => 'Retrieve Group Log Service Details',
  'description' => 'Retrieve Group Log Service Details Official Fivetran endpoint: GET /v1/external-logging/{logId} Returns a group-level [logging service](/docs/logs/external-logs) object if a valid identifier was provided.',
  'icon' => 'ph:database',
),
  'fivetran_delete_log_service' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteLogService',
  'type' => 'write',
  'name' => 'Delete a Group Log Service',
  'description' => 'Delete a Group Log Service Official Fivetran endpoint: DELETE /v1/external-logging/{logId} Deletes a group-level [logging service](/docs/logs/external-logs) from your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_update_log_service' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUpdateLogService',
  'type' => 'write',
  'name' => 'Update a Group Log Service',
  'description' => 'Update a Group Log Service Official Fivetran endpoint: PATCH /v1/external-logging/{logId} Updates information for an existing group-level [logging service](/docs/logs/external-logs) within your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_all_transformation_projects' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListAllTransformationProjects',
  'type' => 'read',
  'name' => 'List all Transformation Projects',
  'description' => 'List all Transformation Projects Official Fivetran endpoint: GET /v1/transformation-projects Returns a list of all transformation projects available via API within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_create_transformation_project' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateTransformationProject',
  'type' => 'write',
  'name' => 'Create Transformation Project',
  'description' => 'Create Transformation Project Official Fivetran endpoint: POST /v1/transformation-projects Creates a new transformation project.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_user_in_team' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetUserInTeam',
  'type' => 'read',
  'name' => 'Retrieve User Membership in a Team',
  'description' => 'Retrieve User Membership in a Team Official Fivetran endpoint: GET /v1/teams/{teamId}/users/{userId} Returns the membership details for a user in a team.',
  'icon' => 'ph:database',
),
  'fivetran_delete_user_from_team' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteUserFromTeam',
  'type' => 'write',
  'name' => 'Delete a User from a Team',
  'description' => 'Delete a User from a Team Official Fivetran endpoint: DELETE /v1/teams/{teamId}/users/{userId} Removes a user from a team.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_update_user_membership' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUpdateUserMembership',
  'type' => 'write',
  'name' => 'Update a User Membership',
  'description' => 'Update a User Membership Official Fivetran endpoint: PATCH /v1/teams/{teamId}/users/{userId} Updates a user membership in a team.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_team_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranTeamDetails',
  'type' => 'read',
  'name' => 'Retrieve Team Details',
  'description' => 'Retrieve Team Details Official Fivetran endpoint: GET /v1/teams/{teamId} Returns information for a given team within your Fivetran account',
  'icon' => 'ph:database',
),
  'fivetran_delete_team' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteTeam',
  'type' => 'write',
  'name' => 'Delete a Team',
  'description' => 'Delete a Team Official Fivetran endpoint: DELETE /v1/teams/{teamId} Deletes a team from your Fivetran account',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_modify_team' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyTeam',
  'type' => 'write',
  'name' => 'Update a Team',
  'description' => 'Update a Team Official Fivetran endpoint: PATCH /v1/teams/{teamId} Updates information for an existing team within your Fivetran account',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_transformation_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranTransformationDetails',
  'type' => 'read',
  'name' => 'Retrieve Transformation Details',
  'description' => 'Retrieve Transformation Details Official Fivetran endpoint: GET /v1/transformations/{transformationId} Returns a transformation details if a valid identifier is provided.',
  'icon' => 'ph:database',
),
  'fivetran_delete_transformation' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteTransformation',
  'type' => 'write',
  'name' => 'Delete a Transformation',
  'description' => 'Delete a Transformation Official Fivetran endpoint: DELETE /v1/transformations/{transformationId} Deletes a transformation if a valid identifier is provided.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_update_transformation' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUpdateTransformation',
  'type' => 'write',
  'name' => 'Update a Transformation',
  'description' => 'Update a Transformation Official Fivetran endpoint: PATCH /v1/transformations/{transformationId} Updates the transformation if a valid identifier is provided.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_create_account_webhook' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateAccountWebhook',
  'type' => 'write',
  'name' => 'Create an Account Webhook',
  'description' => 'Create an Account Webhook Official Fivetran endpoint: POST /v1/webhooks/account This endpoint allows you to create a new webhook for the current account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_connector_sdk_package' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetConnectorSdkPackage',
  'type' => 'read',
  'name' => 'Retrieve Connector SDK Package Details',
  'description' => 'Retrieve Connector SDK Package Details Official Fivetran endpoint: GET /v1/connector-sdk/packages/{package_id} Returns details for a specific Connector SDK package.',
  'icon' => 'ph:database',
),
  'fivetran_delete_connector_sdk_package' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteConnectorSdkPackage',
  'type' => 'write',
  'name' => 'Delete Connector SDK Package',
  'description' => 'Delete Connector SDK Package Official Fivetran endpoint: DELETE /v1/connector-sdk/packages/{package_id} Permanently deletes a Connector SDK package from your Fivetran account. > **Warning:** Packages that are associat...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_update_connector_sdk_package' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUpdateConnectorSdkPackage',
  'type' => 'write',
  'name' => 'Update Connector SDK Package',
  'description' => 'Update Connector SDK Package Official Fivetran endpoint: PATCH /v1/connector-sdk/packages/{package_id} Updates an existing Connector SDK package by uploading a new version of the connector code. All connections using ...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_account_log_service_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetAccountLogServiceDetails',
  'type' => 'read',
  'name' => 'Retrieve Account Log Service',
  'description' => 'Retrieve Account Log Service Official Fivetran endpoint: GET /v1/external-logging/account Returns the account-level [logging service](/docs/logs/external-logs) if it exists.',
  'icon' => 'ph:database',
),
  'fivetran_add_account_log_service' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranAddAccountLogService',
  'type' => 'write',
  'name' => 'Create Account Log Service',
  'description' => 'Create Account Log Service Official Fivetran endpoint: POST /v1/external-logging/account Creates an account-level [logging service](/docs/logs/external-logs).',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_delete_account_log_service' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteAccountLogService',
  'type' => 'write',
  'name' => 'Delete Account Log Service',
  'description' => 'Delete Account Log Service Official Fivetran endpoint: DELETE /v1/external-logging/account Deletes the account-level [logging service](/docs/logs/external-logs).',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_update_account_log_service' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUpdateAccountLogService',
  'type' => 'write',
  'name' => 'Update Account Log Service',
  'description' => 'Update Account Log Service Official Fivetran endpoint: PATCH /v1/external-logging/account Updates information for the account-level [logging service](/docs/logs/external-logs).',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_upgrade_transformation_package' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUpgradeTransformationPackage',
  'type' => 'write',
  'name' => 'Upgrade Transformation Package',
  'description' => 'Upgrade Transformation Package Official Fivetran endpoint: POST /v1/transformations/{transformationId}/upgrade Upgrades the Quickstart transformation package to latest version if a valid identifier is provided.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_proxy_agent_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetProxyAgentDetails',
  'type' => 'read',
  'name' => 'Retrieve Proxy Agent Details',
  'description' => 'Retrieve Proxy Agent Details Official Fivetran endpoint: GET /v1/proxy/{agentId} Retrieves the details of the specified proxy agent.',
  'icon' => 'ph:database',
),
  'fivetran_delete_proxy_agent' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteProxyAgent',
  'type' => 'write',
  'name' => 'Delete a Proxy Agent',
  'description' => 'Delete a Proxy Agent Official Fivetran endpoint: DELETE /v1/proxy/{agentId} Deletes the specified proxy agent from your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_connect_card' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranConnectCard',
  'type' => 'write',
  'name' => 'Create a Connect Card',
  'description' => 'Create a Connect Card Official Fivetran endpoint: POST /v1/connections/{connectionId}/connect-card Generates the Connect Card URI for the connection',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_all_users_in_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListAllUsersInGroup',
  'type' => 'read',
  'name' => 'List All Users within a Group',
  'description' => 'List All Users within a Group Official Fivetran endpoint: GET /v1/groups/{groupId}/users Returns a list of information about all users within a group in your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_add_user_to_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranAddUserToGroup',
  'type' => 'write',
  'name' => 'Add a User to a Group',
  'description' => 'Add a User to a Group Official Fivetran endpoint: POST /v1/groups/{groupId}/users Adds an existing user to a group in your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_user_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUserDetails',
  'type' => 'read',
  'name' => 'Retrieve a User Details',
  'description' => 'Retrieve a User Details Official Fivetran endpoint: GET /v1/users/{userId} Returns a user object if a valid identifier was provided.',
  'icon' => 'ph:database',
),
  'fivetran_modify_user' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyUser',
  'type' => 'write',
  'name' => 'Update a User',
  'description' => 'Update a User Official Fivetran endpoint: PATCH /v1/users/{userId} Updates information for an existing user within your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_all_teams' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListAllTeams',
  'type' => 'read',
  'name' => 'List All Teams',
  'description' => 'List All Teams Official Fivetran endpoint: GET /v1/teams Returns a list of all teams within your Fivetran account',
  'icon' => 'ph:database',
),
  'fivetran_create_team' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateTeam',
  'type' => 'write',
  'name' => 'Create a Team',
  'description' => 'Create a Team Official Fivetran endpoint: POST /v1/teams Creates a new team in your Fivetran account',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_log_services' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListLogServices',
  'type' => 'read',
  'name' => 'List All Log Services within Account',
  'description' => 'List All Log Services within Account Official Fivetran endpoint: GET /v1/external-logging Returns a list of all accessible [logging services](/docs/logs/external-logs) within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_add_log_service' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranAddLogService',
  'type' => 'write',
  'name' => 'Create a Group Log Service',
  'description' => 'Create a Group Log Service Official Fivetran endpoint: POST /v1/external-logging Creates a new group-level [logging service](/docs/logs/external-logs) within a specified group in your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_connection_state' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranConnectionState',
  'type' => 'read',
  'name' => 'Retrieve Connection State',
  'description' => 'Retrieve Connection State Official Fivetran endpoint: GET /v1/connections/{connectionId}/state Returns the connection state. This endpoint is only supported for Function and Connection SDK connectors.',
  'icon' => 'ph:database',
),
  'fivetran_modify_connection_state' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyConnectionState',
  'type' => 'write',
  'name' => 'Update a Connection State',
  'description' => 'Update a Connection State Official Fivetran endpoint: PATCH /v1/connections/{connectionId}/state Updates the connection state. To update the state, you should pause your connection first. To update the connection stat...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_all_users' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListAllUsers',
  'type' => 'read',
  'name' => 'List All Users',
  'description' => 'List All Users Official Fivetran endpoint: GET /v1/users Returns a list of all users within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_create_user' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateUser',
  'type' => 'write',
  'name' => 'Invite a User',
  'description' => 'Invite a User Official Fivetran endpoint: POST /v1/users Invites a new user to your Fivetran account. The invited user will have access to the account only after accepting the invitation. Invited user details are stil...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_delete_user_membership_in_account' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteUserMembershipInAccount',
  'type' => 'write',
  'name' => 'Delete Account Role',
  'description' => 'Delete Account Role Official Fivetran endpoint: DELETE /v1/users/{userId}/role Removes a user\'s role from an account, but the user remains a member of the account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_download_connector_sdk_package' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDownloadConnectorSdkPackage',
  'type' => 'read',
  'name' => 'Download Connector SDK Package',
  'description' => 'Download Connector SDK Package Official Fivetran endpoint: GET /v1/connector-sdk/packages/{package_id}/download Downloads the connector code package file (code.zip) for a specific Connector SDK package. This endpoint ...',
  'icon' => 'ph:database',
),
  'fivetran_test_webhook' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranTestWebhook',
  'type' => 'write',
  'name' => 'Test a Webhook',
  'description' => 'Test a Webhook Official Fivetran endpoint: POST /v1/webhooks/{webhookId}/test The endpoint allows you to test an existing webhook. It sends a webhook with a given identifier for a dummy connection with identifier _con...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_run_transformation' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranRunTransformation',
  'type' => 'write',
  'name' => 'Run Transformation',
  'description' => 'Run Transformation Official Fivetran endpoint: POST /v1/transformations/{transformationId}/run Runs the transformation if a valid identifier is provided.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_team_memberships_in_connections' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetTeamMembershipsInConnections',
  'type' => 'read',
  'name' => 'List All Connection Memberships',
  'description' => 'List All Connection Memberships Official Fivetran endpoint: GET /v1/teams/{teamId}/connections Returns all connections a team has membership in.',
  'icon' => 'ph:database',
),
  'fivetran_add_team_membership_in_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranAddTeamMembershipInConnection',
  'type' => 'write',
  'name' => 'Add Connection Membership',
  'description' => 'Add Connection Membership Official Fivetran endpoint: POST /v1/teams/{teamId}/connections Adds a team as a member of a connection.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_resync_tables' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranResyncTables',
  'type' => 'write',
  'name' => 'Re-sync Connection Table Data',
  'description' => 'Re-sync Connection Table Data Official Fivetran endpoint: POST /v1/connections/{connectionId}/schemas/tables/resync Triggers a historical sync of all data for multiple schema tables within a connection. This action do...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_reload_connection_schema_config' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranReloadConnectionSchemaConfig',
  'type' => 'write',
  'name' => 'Reload a Connection Schema Config',
  'description' => 'Reload a Connection Schema Config Official Fivetran endpoint: POST /v1/connections/{connectionId}/schemas/reload Reloads the connection schema config for an existing connection within your Fivetran account. > NOTE: Th...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_transformations_list' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranTransformationsList',
  'type' => 'read',
  'name' => 'List all Transformations',
  'description' => 'List all Transformations Official Fivetran endpoint: GET /v1/transformations Returns a list of all transformations within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_create_transformation' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateTransformation',
  'type' => 'write',
  'name' => 'Create a Transformation',
  'description' => 'Create a Transformation Official Fivetran endpoint: POST /v1/transformations Creates a new transformation.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_hvr_register_hub' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranHvrRegisterHub',
  'type' => 'write',
  'name' => 'Register Hub',
  'description' => 'Register Hub Official Fivetran endpoint: POST /v1/hvr/register-hub Register a new hub within your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_cancel_transformation' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCancelTransformation',
  'type' => 'write',
  'name' => 'Cancel Running Transformation',
  'description' => 'Cancel Running Transformation Official Fivetran endpoint: POST /v1/transformations/{transformationId}/cancel Cancels the execution of the transformation if a valid identifier is provided.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_transformation_project_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranTransformationProjectDetails',
  'type' => 'read',
  'name' => 'Retrieve Transformation Project Details',
  'description' => 'Retrieve Transformation Project Details Official Fivetran endpoint: GET /v1/transformation-projects/{projectId} Returns transformation project details if a valid identifier was provided.',
  'icon' => 'ph:database',
),
  'fivetran_delete_transformation_project' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteTransformationProject',
  'type' => 'write',
  'name' => 'Delete Transformation Project',
  'description' => 'Delete Transformation Project Official Fivetran endpoint: DELETE /v1/transformation-projects/{projectId} Deletes transformation project if a valid identifier was provided.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_modify_transformation_project' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyTransformationProject',
  'type' => 'write',
  'name' => 'Update Transformation Project',
  'description' => 'Update Transformation Project Official Fivetran endpoint: PATCH /v1/transformation-projects/{projectId} Updates transformation project if a valid identifier was provided.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_group_service_account' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGroupServiceAccount',
  'type' => 'read',
  'name' => 'Retrieve Group Service Account',
  'description' => 'Retrieve Group Service Account Official Fivetran endpoint: GET /v1/groups/{groupId}/service-account Returns Fivetran service account associated with the group.',
  'icon' => 'ph:database',
),
  'fivetran_webhook_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranWebhookDetails',
  'type' => 'read',
  'name' => 'Retrieve Webhook Details',
  'description' => 'Retrieve Webhook Details Official Fivetran endpoint: GET /v1/webhooks/{webhookId} This endpoint allows you to retrieve details of the existing webhook for a given identifier',
  'icon' => 'ph:database',
),
  'fivetran_delete_webhook' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteWebhook',
  'type' => 'write',
  'name' => 'Delete a Webhook',
  'description' => 'Delete a Webhook Official Fivetran endpoint: DELETE /v1/webhooks/{webhookId} This endpoint allows you to delete an existing webhook with a given identifier',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_modify_webhook' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyWebhook',
  'type' => 'write',
  'name' => 'Update a Webhook',
  'description' => 'Update a Webhook Official Fivetran endpoint: PATCH /v1/webhooks/{webhookId} The endpoint allows you to update the existing webhook with a given identifier',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_user_membership_in_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetUserMembershipInGroup',
  'type' => 'read',
  'name' => 'Retrieve Group Membership Details',
  'description' => 'Retrieve Group Membership Details Official Fivetran endpoint: GET /v1/users/{userId}/groups/{groupId} Returns details of a user membership in group.',
  'icon' => 'ph:database',
),
  'fivetran_delete_user_membership_in_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteUserMembershipInGroup',
  'type' => 'write',
  'name' => 'Delete Group Membership',
  'description' => 'Delete Group Membership Official Fivetran endpoint: DELETE /v1/users/{userId}/groups/{groupId} Removes user from a group.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_update_user_membership_in_group' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUpdateUserMembershipInGroup',
  'type' => 'write',
  'name' => 'Update Group Membership',
  'description' => 'Update Group Membership Official Fivetran endpoint: PATCH /v1/users/{userId}/groups/{groupId} Updates user group membership.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_run_setup_tests' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranRunSetupTests',
  'type' => 'write',
  'name' => 'Run Connection Setup Tests',
  'description' => 'Run Connection Setup Tests Official Fivetran endpoint: POST /v1/connections/{connectionId}/test Runs the setup tests for an existing connection within your Fivetran account. Use this parameter to test the connection w...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_hybrid_deployment_agent' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetHybridDeploymentAgent',
  'type' => 'read',
  'name' => 'Returns Hybrid Deployment Agent Details',
  'description' => 'Returns Hybrid Deployment Agent Details Official Fivetran endpoint: GET /v1/hybrid-deployment-agents/{agentId} Returns Hybrid Deployment Agent Details.',
  'icon' => 'ph:database',
),
  'fivetran_delete_hybrid_deployment_agent' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteHybridDeploymentAgent',
  'type' => 'write',
  'name' => 'Delete a Hybrid Deployment Agent',
  'description' => 'Delete a Hybrid Deployment Agent Official Fivetran endpoint: DELETE /v1/hybrid-deployment-agents/{agentId} Delete a Hybrid Deployment Agent.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_proxy_agent' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetProxyAgent',
  'type' => 'read',
  'name' => 'List all Proxy Agents',
  'description' => 'List all Proxy Agents Official Fivetran endpoint: GET /v1/proxy Returns a list of all proxy agents within your Fivetran account.',
  'icon' => 'ph:database',
),
  'fivetran_create_proxy_agent' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreateProxyAgent',
  'type' => 'write',
  'name' => 'Create a Proxy Agent',
  'description' => 'Create a Proxy Agent Official Fivetran endpoint: POST /v1/proxy Creates a new proxy agent within your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_run_destination_setup_tests' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranRunDestinationSetupTests',
  'type' => 'write',
  'name' => 'Run Destination Setup Tests',
  'description' => 'Run Destination Setup Tests Official Fivetran endpoint: POST /v1/destinations/{destinationId}/test Runs the setup tests for an existing destination within your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_private_links' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetPrivateLinks',
  'type' => 'read',
  'name' => 'List All Private Links',
  'description' => 'List All Private Links Official Fivetran endpoint: GET /v1/private-links Returns a list of all private links.',
  'icon' => 'ph:database',
),
  'fivetran_create_private_link' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranCreatePrivateLink',
  'type' => 'write',
  'name' => 'Create a Private Link',
  'description' => 'Create a Private Link Official Fivetran endpoint: POST /v1/private-links Creates a new private link in your Fivetran account. > NOTE: See the [Set Up a Connection With Private Links tutorial](/docs/rest-api/tutorials/...',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_list_users_in_team' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranListUsersInTeam',
  'type' => 'read',
  'name' => 'List All User Memberships',
  'description' => 'List All User Memberships Official Fivetran endpoint: GET /v1/teams/{teamId}/users Returns a list of users and their roles within a team in your Fivetran account',
  'icon' => 'ph:database',
),
  'fivetran_add_user_to_team' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranAddUserToTeam',
  'type' => 'write',
  'name' => 'Add a User to the Team',
  'description' => 'Add a User to the Team Official Fivetran endpoint: POST /v1/teams/{teamId}/users Assigns a role for a user in a team.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_get_user_membership_in_connections' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranGetUserMembershipInConnections',
  'type' => 'read',
  'name' => 'Retrieve Connection Membership',
  'description' => 'Retrieve Connection Membership Official Fivetran endpoint: GET /v1/users/{userId}/connections/{connectionId} Returns the details of a user\'s membership in a connection.',
  'icon' => 'ph:database',
),
  'fivetran_delete_user_membership_in_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteUserMembershipInConnection',
  'type' => 'write',
  'name' => 'Delete Connection Membership',
  'description' => 'Delete Connection Membership Official Fivetran endpoint: DELETE /v1/users/{userId}/connections/{connectionId} Removes user membership in a connection.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_update_user_membership_in_connection' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranUpdateUserMembershipInConnection',
  'type' => 'write',
  'name' => 'Update Connection Membership',
  'description' => 'Update Connection Membership Official Fivetran endpoint: PATCH /v1/users/{userId}/connections/{connectionId} Updates user membership in a connection.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_destination_details' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDestinationDetails',
  'type' => 'read',
  'name' => 'Retrieve Destination Details',
  'description' => 'Retrieve Destination Details Official Fivetran endpoint: GET /v1/destinations/{destinationId} Returns a destination object if a valid identifier was provided.',
  'icon' => 'ph:database',
),
  'fivetran_delete_destination' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteDestination',
  'type' => 'write',
  'name' => 'Delete a Destination',
  'description' => 'Delete a Destination Official Fivetran endpoint: DELETE /v1/destinations/{destinationId} Deletes a destination from your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_modify_destination' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranModifyDestination',
  'type' => 'write',
  'name' => 'Update a Destination',
  'description' => 'Update a Destination Official Fivetran endpoint: PATCH /v1/destinations/{destinationId} Updates information for an existing destination within your Fivetran account.',
  'icon' => 'ph:pencil-simple',
),
  'fivetran_metadata_connector_config' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranMetadataConnectorConfig',
  'type' => 'read',
  'name' => 'Retrieve Connector Configuration Metadata',
  'description' => 'Retrieve Connector Configuration Metadata Official Fivetran endpoint: GET /v1/metadata/connector-types/{service} Returns metadata of configuration parameters and authorization parameters for a specified connector type.',
  'icon' => 'ph:database',
),
  'fivetran_delete_team_membership_in_account' => array (
  'class' => 'OpenCompany\\Integrations\\Fivetran\\Tools\\FivetranDeleteTeamMembershipInAccount',
  'type' => 'write',
  'name' => 'Delete Team from Account',
  'description' => 'Delete Team from Account Official Fivetran endpoint: DELETE /v1/teams/{teamId}/role Removes a team from your Fivetran account',
  'icon' => 'ph:pencil-simple',
),
]; }
    public function isIntegration(): bool { return true; } public function createTool(string $class, array $context = []): Tool { return new $class($this->resolveService($context)); } public function luaDocsPath(): ?string { return __DIR__.'/../lua-docs/fivetran.md'; }
    /** @param  array<string, mixed>  $context  Optional account context from the host. */ private function resolveService(array $context = []): FivetranService { $account=$context['account']??null; if($account!==null){$creds=app(CredentialResolver::class); return new FivetranService(apiKey:$creds->get('fivetran','api_key','',$account), apiSecret:$creds->get('fivetran','api_secret','',$account), baseUrl:$creds->get('fivetran','url','https://api.fivetran.com',$account));} return app(FivetranService::class); }
}
