<?php

namespace OpenCompany\Integrations\Appwrite\Tools;

/**
 * Create an Appwrite storage bucket.
 */
class AppwriteCreateBucket extends AbstractAppwriteEndpointTool
{
    protected string $toolName = 'appwrite_create_bucket';
    protected string $toolDescription = 'Create a storage bucket with permissions and file constraints.';
    protected string $method = 'POST';
    protected string $path = '/storage/buckets';
    protected array $required = ['bucket_id', 'name'];
    protected array $bodyParams = ['bucket_id' => 'bucketId', 'name', 'permissions', 'file_security' => 'fileSecurity', 'enabled', 'maximum_file_size' => 'maximumFileSize', 'allowed_file_extensions' => 'allowedFileExtensions', 'compression', 'encryption', 'antivirus'];
    protected array $parameters = [
        'bucket_id' => ['type' => 'string', 'required' => true, 'description' => 'Bucket ID or unique() value generated by the caller.'],
        'name' => ['type' => 'string', 'required' => true, 'description' => 'Bucket name.'],
        'permissions' => ['type' => 'array', 'description' => 'Bucket permission strings.', 'items' => ['type' => 'string']],
        'file_security' => ['type' => 'boolean', 'description' => 'Enable file-level security.'],
        'enabled' => ['type' => 'boolean', 'description' => 'Whether the bucket is enabled.'],
        'maximum_file_size' => ['type' => 'integer', 'description' => 'Maximum file size in bytes.'],
        'allowed_file_extensions' => ['type' => 'array', 'description' => 'Allowed file extensions without dots.', 'items' => ['type' => 'string']],
        'compression' => ['type' => 'string', 'description' => 'Compression mode such as none, gzip, or zstd.'],
        'encryption' => ['type' => 'boolean', 'description' => 'Whether files are encrypted.'],
        'antivirus' => ['type' => 'boolean', 'description' => 'Whether antivirus scanning is enabled.'],
    ];
}
