<?php

namespace OpenCompany\Integrations\Appwrite\Tools;

/**
 * Create an Appwrite database.
 */
class AppwriteCreateDatabase extends AbstractAppwriteEndpointTool
{
    protected string $toolName = 'appwrite_create_database';
    protected string $toolDescription = 'Create a database in the current Appwrite project.';
    protected string $method = 'POST';
    protected string $path = '/databases';
    protected array $required = ['database_id', 'name'];
    protected array $bodyParams = ['database_id' => 'databaseId', 'name', 'enabled'];
    protected array $parameters = [
        'database_id' => ['type' => 'string', 'required' => true, 'description' => 'Database ID or unique() value generated by the caller.'],
        'name' => ['type' => 'string', 'required' => true, 'description' => 'Database name.'],
        'enabled' => ['type' => 'boolean', 'description' => 'Whether the database is enabled.'],
    ];
}
