<?php

namespace OpenCompany\Integrations\Appwrite\Tools;

/**
 * Create an Appwrite email message.
 */
class AppwriteCreateEmail extends AbstractAppwriteEndpointTool
{
    protected string $toolName = 'appwrite_create_email';
    protected string $toolDescription = 'Create an Appwrite email message for users, topics, or targets.';
    protected string $method = 'POST';
    protected string $path = '/messaging/messages/email';
    protected array $required = ['message_id', 'subject', 'content'];
    protected array $bodyParams = ['message_id' => 'messageId', 'subject', 'content', 'topics', 'users', 'targets', 'cc', 'bcc', 'attachments', 'draft', 'html', 'scheduled_at' => 'scheduledAt'];
    protected array $parameters = [
        'message_id' => ['type' => 'string', 'required' => true, 'description' => 'Message ID or unique() value generated by the caller.'],
        'subject' => ['type' => 'string', 'required' => true, 'description' => 'Email subject.'],
        'content' => ['type' => 'string', 'required' => true, 'description' => 'Email body content.'],
        'topics' => ['type' => 'array', 'description' => 'Topic IDs.', 'items' => ['type' => 'string']],
        'users' => ['type' => 'array', 'description' => 'User IDs.', 'items' => ['type' => 'string']],
        'targets' => ['type' => 'array', 'description' => 'Target IDs.', 'items' => ['type' => 'string']],
        'cc' => ['type' => 'array', 'description' => 'CC email addresses.', 'items' => ['type' => 'string']],
        'bcc' => ['type' => 'array', 'description' => 'BCC email addresses.', 'items' => ['type' => 'string']],
        'attachments' => ['type' => 'array', 'description' => 'Storage file attachment IDs.', 'items' => ['type' => 'string']],
        'draft' => ['type' => 'boolean', 'description' => 'Create as a draft.'],
        'html' => ['type' => 'boolean', 'description' => 'Treat content as HTML.'],
        'scheduled_at' => ['type' => 'string', 'description' => 'Optional scheduled send time.'],
    ];
}
