<?php

namespace OpenCompany\Integrations\Appwrite\Tools;

/**
 * Create an Appwrite collection.
 */
class AppwriteCreateCollection extends AbstractAppwriteEndpointTool
{
    protected string $toolName = 'appwrite_create_collection';
    protected string $toolDescription = 'Create a collection inside an Appwrite database.';
    protected string $method = 'POST';
    protected string $path = '/databases/{database_id}/collections';
    protected array $required = ['database_id', 'collection_id', 'name'];
    protected array $bodyParams = ['collection_id' => 'collectionId', 'name', 'permissions', 'document_security' => 'documentSecurity', 'enabled'];
    protected array $parameters = [
        'database_id' => ['type' => 'string', 'required' => true, 'description' => 'Database ID.'],
        'collection_id' => ['type' => 'string', 'required' => true, 'description' => 'Collection ID or unique() value generated by the caller.'],
        'name' => ['type' => 'string', 'required' => true, 'description' => 'Collection name.'],
        'permissions' => ['type' => 'array', 'description' => 'Collection permission strings.', 'items' => ['type' => 'string']],
        'document_security' => ['type' => 'boolean', 'description' => 'Enable document-level security.'],
        'enabled' => ['type' => 'boolean', 'description' => 'Whether the collection is enabled.'],
    ];
}
