<?php

namespace OpenCompany\Integrations\Appwrite\Tools;

/**
 * Create an Appwrite team.
 */
class AppwriteCreateTeam extends AbstractAppwriteEndpointTool
{
    protected string $toolName = 'appwrite_create_team';
    protected string $toolDescription = 'Create a team in the current Appwrite project.';
    protected string $method = 'POST';
    protected string $path = '/teams';
    protected array $required = ['team_id', 'name'];
    protected array $bodyParams = ['team_id' => 'teamId', 'name', 'roles'];
    protected array $parameters = [
        'team_id' => ['type' => 'string', 'required' => true, 'description' => 'Team ID or unique() value generated by the caller.'],
        'name' => ['type' => 'string', 'required' => true, 'description' => 'Team name.'],
        'roles' => ['type' => 'array', 'description' => 'Initial team roles.', 'items' => ['type' => 'string']],
    ];
}
