<?php

namespace OpenCompany\Integrations\Appwrite\Tools;

/**
 * Create an Appwrite user.
 */
class AppwriteCreateUser extends AbstractAppwriteEndpointTool
{
    protected string $toolName = 'appwrite_create_user';
    protected string $toolDescription = 'Create a new Appwrite user with email, phone, or password fields.';
    protected string $method = 'POST';
    protected string $path = '/users';
    protected array $required = ['user_id'];
    protected array $bodyParams = ['user_id' => 'userId', 'email', 'phone', 'password', 'name'];
    protected array $parameters = [
        'user_id' => ['type' => 'string', 'required' => true, 'description' => 'User ID or unique() value generated by the caller.'],
        'email' => ['type' => 'string', 'description' => 'User email address.'],
        'phone' => ['type' => 'string', 'description' => 'User phone number in E.164 format.'],
        'password' => ['type' => 'string', 'description' => 'User password.'],
        'name' => ['type' => 'string', 'description' => 'User display name.'],
    ];
}
