<?php

namespace OpenCompany\Integrations\Appwrite\Tools;

/**
 * Create an Appwrite push notification.
 */
class AppwriteCreatePush extends AbstractAppwriteEndpointTool
{
    protected string $toolName = 'appwrite_create_push';
    protected string $toolDescription = 'Create an Appwrite push notification for users, topics, or targets.';
    protected string $method = 'POST';
    protected string $path = '/messaging/messages/push';
    protected array $required = ['message_id', 'title', 'body'];
    protected array $bodyParams = ['message_id' => 'messageId', 'title', 'body', 'topics', 'users', 'targets', 'data', 'action', 'image', 'icon', 'sound', 'color', 'tag', 'badge', 'draft', 'scheduled_at' => 'scheduledAt'];
    protected array $parameters = [
        'message_id' => ['type' => 'string', 'required' => true, 'description' => 'Message ID or unique() value generated by the caller.'],
        'title' => ['type' => 'string', 'required' => true, 'description' => 'Push notification title.'],
        'body' => ['type' => 'string', 'required' => true, 'description' => 'Push notification body.'],
        'topics' => ['type' => 'array', 'description' => 'Topic IDs.', 'items' => ['type' => 'string']],
        'users' => ['type' => 'array', 'description' => 'User IDs.', 'items' => ['type' => 'string']],
        'targets' => ['type' => 'array', 'description' => 'Target IDs.', 'items' => ['type' => 'string']],
        'data' => ['type' => 'object', 'description' => 'Additional push payload data.'],
        'action' => ['type' => 'string', 'description' => 'Push action.'],
        'image' => ['type' => 'string', 'description' => 'Storage image reference.'],
        'icon' => ['type' => 'string', 'description' => 'Icon URL or reference.'],
        'sound' => ['type' => 'string', 'description' => 'Notification sound.'],
        'color' => ['type' => 'string', 'description' => 'Notification color.'],
        'tag' => ['type' => 'string', 'description' => 'Notification tag.'],
        'badge' => ['type' => 'string', 'description' => 'Badge value.'],
        'draft' => ['type' => 'boolean', 'description' => 'Create as a draft.'],
        'scheduled_at' => ['type' => 'string', 'description' => 'Optional scheduled send time.'],
    ];
}
