<?php

namespace OpenCompany\Integrations\Appwrite\Tools;

/**
 * Create an Appwrite messaging topic.
 */
class AppwriteCreateTopic extends AbstractAppwriteEndpointTool
{
    protected string $toolName = 'appwrite_create_topic';
    protected string $toolDescription = 'Create a messaging topic.';
    protected string $method = 'POST';
    protected string $path = '/messaging/topics';
    protected array $required = ['topic_id', 'name'];
    protected array $bodyParams = ['topic_id' => 'topicId', 'name', 'subscribe'];
    protected array $parameters = [
        'topic_id' => ['type' => 'string', 'required' => true, 'description' => 'Topic ID or unique() value generated by the caller.'],
        'name' => ['type' => 'string', 'required' => true, 'description' => 'Topic name.'],
        'subscribe' => ['type' => 'array', 'description' => 'Role strings allowed to subscribe.', 'items' => ['type' => 'string']],
    ];
}
