<?php

namespace OpenCompany\Integrations\Shippo\Tools;

/**
 * Connect an existing carrier account using OAuth 2.0.
 *
 * Maps to the official Shippo endpoint GET /carrier_accounts/{CarrierAccountObjectId}/signin/initiate.
 */
class ShippoInitiateOauth2Signin extends AbstractShippoTool
{
    protected const NAME = "shippo_initiate_oauth2_signin";
    protected const DESCRIPTION = "Connect an existing carrier account using OAuth 2.0\n\nOfficial Shippo endpoint: GET /carrier_accounts/{CarrierAccountObjectId}/signin/initiate.";
    protected const PARAMETERS = [
        "carrier_account_object_id" => [
            "type" => "string",
            "required" => true,
            "description" => "The carrier account ID (UUID) to start a signin process.",
        ],
        "redirect_uri" => [
            "type" => "string",
            "required" => true,
            "description" => "Callback URL. The URL that tells the authorization server where to send the user back to after they approve the request.",
        ],
        "state" => [
            "type" => "string",
            "required" => false,
            "description" => "A random string generated by the consuming application and included in the request to prevent CSRF attacks. The consuming application checks that the same value is returned after the user authorizes Shippo.",
        ],
        "shippo_api_version" => [
            "type" => "string",
            "required" => false,
            "description" => "Optional string used to pick a non-default API version to use. See our API version guide.",
        ],
    ];
    protected const METHOD = "GET";
    protected const PATH = "/carrier_accounts/{CarrierAccountObjectId}/signin/initiate";
    protected const PATH_PARAMS = [
        "CarrierAccountObjectId" => "carrier_account_object_id",
    ];
    protected const QUERY_PARAMS = [
        "redirect_uri" => "redirect_uri",
        "state" => "state",
    ];
    protected const HEADER_PARAMS = [
        "SHIPPO-API-VERSION" => "shippo_api_version",
    ];
    protected const BODY_REQUIRED = false;
}
