<?php

namespace OpenCompany\Integrations\Plaid\Tools;

/**
 * Enrich locally-held transaction data.
 *
 * Maps to the official Plaid endpoint post /transactions/enrich.
 */
class PlaidTransactionsEnrich extends AbstractPlaidTool
{
    protected const NAME = 'plaid_transactions_enrich';
    protected const DESCRIPTION = 'Enrich locally-held transaction data

Official Plaid endpoint: POST /transactions/enrich

The `/transactions/enrich` endpoint enriches raw transaction data generated by your own banking products or retrieved from other non-Plaid sources.';
    protected const PARAMETERS = array (
  'body' =>
  array (
    'type' => 'object',
    'required' => true,
    'description' => 'JSON request body matching the official Plaid OpenAPI request schema for this operation.',
  ),
);
    protected const METHOD = 'post';
    protected const PATH = '/transactions/enrich';
    protected const PATH_PARAMS = array (
);
    protected const BODY_REQUIRED = true;
}