<?php

namespace OpenCompany\Integrations\Plaid\Tools;

/**
 * Create Link Token.
 *
 * Maps to the official Plaid endpoint post /link/token/create.
 */
class PlaidLinkTokenCreate extends AbstractPlaidTool
{
    protected const NAME = 'plaid_link_token_create';
    protected const DESCRIPTION = 'Create Link Token

Official Plaid endpoint: POST /link/token/create

The `/link/token/create` endpoint creates a `link_token`, which is required as a parameter when initializing Link. Once Link has been initialized, it returns a `public_token`. For most Plaid products, the `public_token` is saved and exchanged for an `access_token` via `/item/public_token/exchange` as part of the main Link flow. For more details, see the [Link flow overview](https://plaid.com/docs/link/#link-flow-overview). A `link_token` generated by `/link/token/create` is also used to initialize other Link flows, such as the [update mode](https://plaid.com/docs/link/update-mode) flow for tokens with expired credentials, or the Identity Verification flow.';
    protected const PARAMETERS = array (
  'body' =>
  array (
    'type' => 'object',
    'required' => true,
    'description' => 'JSON request body matching the official Plaid OpenAPI request schema for this operation.',
  ),
);
    protected const METHOD = 'post';
    protected const PATH = '/link/token/create';
    protected const PATH_PARAMS = array (
);
    protected const BODY_REQUIRED = true;
}